### PR TITLE
Animated images support for GitHub

### LINKED ISSUE #18206: GIF support for GitHub content
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#Images

### What part(s) of the article would you like to see updated?

Reason and outcome: Guidance for displaying an animated image by using the HTML `` element or in combination with the `<picture>` for using with themes. These animated images supports embedding GIFs into your issues, pull requests, discussions, comments  and `.md` files.
Page section: **Images**

### Additional information

https://user-images.githubusercontent.com/48907530/170197104-c0b47665-504b-4dc1-817d-d9deb9230644.mp4

### PR DESCRIPTION
**Pull request by LRANUL**
Guidance for displaying an animated image by using the HTML `` element or in combination with the `<picture>` for using with themes. These animated images supports embedding GIFs into your issues, pull requests, discussions, comments  and `.md` files.

**Note** Retrieve the raw URL of "assets/images/help/writing/base-octocat.gif" once the asset have been merged to GitHub's original 'docs' repository and use the link to replace the forked repository's  source raw URL .

### Why:

Closes [Issue #18206](https://github.com/github/docs/issues/18206)

### What's being changed:

Changes will be made to **Images* section of the page, new addition will improve GitHub's user experience by allowing users to use animated images (GIFs).
e.g. 
For example, the following code displays an animated octo-cat with `` element:

```HTML
<img alt="This is GIF" src="https://raw.githubusercontent.com/LRANUL/docs/c2f6b7f68622266cf628b1773c98871e4d967261/assets/images/help/writing/base-octocat.gif">
```
This is GIF

###### Updates

- Added GitHub's own Octocat GIF to assets to be used with docs for showing infographics with the syntax guide.
- Added writing animated image syntax on GitHub markdowns for GIFs to be displayed on GitHub's issues, pull requests, discussions, comments  and `.md` files.

###### Notes

Retrieve the raw URL of "assets/images/help/writing/base-octocat.gif" once the asset have been merged with this pull request to GitHub's original 'docs' repository and use the link to replace the above forked repository's  source raw URL . This will remove any affiliations it has with my profile and repository, please take this action to avoid creation of broken content on GitHub docs over time as forked repositories get deleted.

##### Screenshot
image

##### Screencast
https://user-images.githubusercontent.com/48907530/170197104-c0b47665-504b-4dc1-817d-d9deb9230644.mp4

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@LRANUL Thanks so much for opening an issue and a PR! I'll get this triaged for review ⚡

**Review by japui — COMMENTED** [review]
Amei lindo 👏 🤲 🙌

**Comment by cmwilson21** [comment]
Thank you for your patience as we work through our backlog 💛

**Comment by cmwilson21** [comment]
@LRANUL Thank you again for submitting this PR. After chatting with the team, we decided to address this internally while considering certain accessibility related issues. 💛 

We'd love for you to contribute again! Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on, if you'd like.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Pull request closed without merging**
