### PR TITLE
fix:  add discussions to contribution graph

### PR DESCRIPTION
**Pull request by iam-frankqiu**
### Why:
Actually. When I created a discussion. It will be counted on my contribution graph. So, I think this is a bug.

### What's being changed:
Add discussions to the contribution graph.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by iam-frankqiu** [comment]
> Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

Thank you for your comment!

**Comment by iam-frankqiu** [comment]
> Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

Staled again?

**Comment by janiceilene** [comment]
Sorry about that @iam-frankqiu! Between GitHub Universe and the holidays, we're backed up on reviews right now 💛

**Comment by iam-frankqiu** [comment]
> Sorry about that @iam-frankqiu! Between GitHub Universe and the holidays, we're backed up on reviews right now 💛

Thank you.

**Comment by hubwriter** [comment]
Hi @iam-frankqiu - Thanks for raising this PR. Apologies for the delay reviewing it.

I just created a Discussion to check this out and it didn't show up on my contribution graph. I'm going to run this by the Discussions team to get their confirmation. I'll update this PR after I hear back from them.

In the meantime thanks again for contributing. 👍

**Comment by iam-frankqiu** [comment]
> I just created a Discussion to check this out and it didn't show up on my contribution graph. I'm going to run this by the Discussions team to get their confirmation. I'll update this PR after I hear back from them.

You are welcome! It may have a 24hours delay for the contribution graph.
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#common-reasons-that-contributions-are-not-counted

**Review by hubwriter — APPROVED** [review]
Hi @iam-frankqiu - our Discussions folks have got back to me. You're right, and your change is a good one. Many thanks.

_I had created a team discussion post, not a discussion, which is why my contribution graph didn't change._

**Comment by hubwriter** [comment]
Merging this now.

@iam-frankqiu - thanks again for contributing ... and for your patience! 😃

**Pull request merged**
