### PR TITLE
NPM/Yarn examples: Use lock file usually

### PR DESCRIPTION
**Pull request by SchulteDev**
### Why:
- Highlighting to use package-lock.json / yarn.lock for installing usually
- ~~Replacing --frozen-lockfile with its successor~~

### What's being changed:
- Example using npm
- Example using Yarn

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@SchulteMarkus Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by hubwriter — COMMENTED** [review]
@SchulteMarkus - Thank you for submitting this PR.

I've asked someone from our Actions dev team to take a look at this.

**Review by hubwriter — CHANGES_REQUESTED** [review]
@SchulteMarkus - Thanks again for this PR.

One of the Actions developers has taken a look at this and has approved the first part of the changes but said of the changes in the "Example using Yarn" section that the changes use Yarn 2 commands whereas, out of the box, GitHub hosted runners ships with Yarn 1.22.19 (https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).

To avoid problems if people haven't modified this to upgrade the Yarn version on a runner, we need to be sure that the changes you are proposing will work using Yarn 1.22.19.

Could you check this and confirm here?

**Comment by SchulteMarkus** [comment]
> One of the Actions developers has taken a look at this and has approved the first part of the changes but said of the changes in the "Example using Yarn" section that the changes use Yarn 2 commands whereas, out of the box, GitHub hosted runners ships with Yarn 1.22.19 (https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).
> 
> To avoid problems if people haven't modified this to upgrade the Yarn version on a runner, we need to be sure that the changes you are proposing will work using Yarn 1.22.19.
> 
> Could you check this and confirm here?

Ui, good that you asked!
I have added one more commit, so that the Yarn command is again Yarn 1.x compatible. I have updated the PR itself, too.
This PR changed a bit from it's indentation (not using yarn --frozen-lockfile any more) to now (using lock files as first examples). In my opinion, it's still an improvement.

**Comment by SchulteMarkus** [comment]
Failure https://github.com/github/docs/actions/runs/5621341748/job/15231953003?pr=26699 seems to be GitHub infrastructure related. @hubwriter , can you execute the build again?

**Review by hubwriter — APPROVED** [review]
@SchulteMarkus - Many thanks for the changes.

I'll get this merged/published now. Thank you for helping to keep the docs up to date. Much appreciated.

**Pull request merged**
