### PR TITLE
Fix wrong info for defaults.run

### LINKED ISSUE #23465: Wrong information in docs for `defaults.run`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Workflow syntax for `jobs.<job_id>.defaults.run`:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun

### What part(s) of the article would you like to see updated?

1. Text mentions a nonexistent key `jobs.defaults.run`.

2. Text says that "*You cannot use contexts or expressions in this keyword.*", however the [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) docs state that `jobs.<job_id>.defaults.run` should be able to access a variety of contexts. Empirically tested and the runner does in fact not fail when using the `inputs` context within a `jobs.<job_id>.defaults.run` entry.

### Additional information

I'm sending a PR with proposed changes; only reason for this issue is that PR instructions ask for creating an issue before opening a PR.

### PR DESCRIPTION
**Pull request by j1elo**
### Why:

Closes https://github.com/github/docs/issues/23465

### What's being changed (if available, include any code snippets, screenshots, or gifs):

1. Text mentioned a nonexistent key `jobs.defaults.run`.

2. Text said that "*You cannot use contexts or expressions in this keyword.*", however the [Context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability) docs state that `jobs.<job_id>.defaults.run` should be able to access a variety of contexts. Empirically tested and the runner does in fact not fail when using the `inputs` context within a `jobs.<job_id>.defaults.run` entry.

3. Removed extra repeated sentence after the link to `defaults.run`, leaving the context support of that key to be documented in that section.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by j1elo** [comment]
Only task remaining to be able to check off the requested checkboxes is to review the new contents in staging, but I do not know where I can find staging, it says to look for the "Automatically generated comment", but the only one is https://github.com/github/docs/pull/23466#issuecomment-1402332579 and it doesn't mention anything about staging so I'm a bit lost at this point.

**Comment by cmwilson21** [comment]
@j1elo Thanks for submitting a PR and linking it to your issue ✨ 

Since this is a reusable, the automatically generated comment won't trigger. You can always run your branch locally to check for changes, but no worries on that for this content change as it won't hinder the review process to leave that box unchecked. I'll get it triaged for review! ⚡

**Review by skedwards88 — COMMENTED** [review]
Thanks for this fix @j1elo ! Could you link to your workflow run logs that demonstrate that contexts and expressions can be used with these keys? That will help us review your PR. (And if you only tested contexts, should the text still mention that expressions are allowed?)

**Comment by cmwilson21** [comment]
👋 @j1elo Just wanted to check in and see if you've had a chance to link your workflow run logs as requested [here](https://github.com/github/docs/pull/23466#pullrequestreview-1288272419). Feel free to ping me when you have! ✨

**Comment by hubwriter** [comment]
I tested using a context:

```
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ${{ env.myshell }}
```

and an expression:

```
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: ${{ format('ba{0}{1}', 's', 'h') }}
```

both of these work fine.

https://github.com/codspaces/hubwriter-javascript-action/blob/main/.github/workflows/context-test.yml

On the strength of this I think we're good to merge this PR.

**Review by hubwriter — APPROVED** [review]

**Comment by hubwriter** [comment]
@j1elo - Many thanks for raising this PR, and the issue for it. 👍 

I'm going to get this merged. 🚀

**Pull request merged**
