### PR TITLE
Arguments and options for codeql database analyze with --download example

### LINKED ISSUE #19239: Arguments and options for `codeql database analyze` with `--download` example
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/configuring-codeql-cli-in-your-ci-system#basic-example-2

### What part(s) of the article would you like to see updated?

In the following example command in this article, I wonder if the order of arguments and options is correct because the repo `/codeql-dbs/example-repo` is located after `--download`.
Also `--github-auth-stdin` is needed because the token `$OCTO-ORG_ACCESS_TOKEN` is from stdin..

```sh
$ echo $OCTO-ORG_ACCESS_TOKEN | codeql database analyze --download /codeql-dbs/example-repo \
    octo-org/security-queries \
    octo-org/optional-security-queries@~1.0.1:queries/csrf.ql \
    --format=sarif-latest --output=/temp/example-repo-js.sarif
```

### Content Plan
See plan [here](https://github.com/github/docs/issues/19239#issuecomment-1212909221).

### PR DESCRIPTION
**Pull request by OlayinkaAtobiloye**
### Why:

Closes [ISSUE](https://github.com/github/docs/issues/19239)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by OlayinkaAtobiloye** [comment]
Hi @cmwilson21! I created a PR for this [issue](https://github.com/github/docs/issues/19239). Please check it out when chanced1

**Comment by cmwilson21** [comment]
@OlayinkaAtobiloye I'll get this one triaged, too! 🎉 👍

**Review by subatoi — COMMENTED** [review]
Hi @OlayinkaAtobiloye 👋 many thanks for raising this.

I noticed the existing text in the paragraph before where you've edited mentions "as in the previous example" but it's not clear what it's actually referring to and I think that might be a hangover from a previous edit.

Since the Microsoft Style Guide recommends that we not use directional language like "[above](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/above)" and "[below](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/below)" for accessibility reasons, I'd recommend expanding the scope of this a little so that it reads something like:

---

.........<EXISTING TEXT>.........When you run the {% data variables.product.prodname_codeql %} analysis, you can specify packs, versions, and paths using one of the following commands.

If you do not specify a value for the `GITHUB_TOKEN`, you can run the {% data variables.product.prodname_codeql %} analysis with the following command:

```bash
echo $OCTO-ORG_ACCESS_TOKEN | codeql pack download &lt;scope/name@version:path&gt; &lt;scope/name@version:path&gt; ...
```

If you do specify a value for `GITHUB_TOKEN`, use this modified version of the command instead:

```bash
echo $OCTO-ORG_ACCESS_TOKEN | codeql pack download &lt;scope/name@version:path&gt; &lt;scope/name@version:path&gt; echo $TOKEN --github-auth-stdin...
```

---

Feel free to write to me if you have any questions: you may have context I'm missing about this as well so not all of this suggestion may be relevant :)

**Comment by sabrowning1** [comment]
After talking with @cmwilson21 and @OlayinkaAtobiloye, we've decided to close this PR out and continue work internally. Thanks for getting us started Olayinka!

**Pull request closed without merging**
