### PR TITLE
Add additional shell script examples for the new Job output environment variables

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
### Why:
The documentation about the new Output variables for sharing data between jobs was inaccurate as it only handled the default  Ubuntu "Bash" version of the commands.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

This updates Job output variables to denote the different versions used for each shell language, kept original Bash, added Powershell and Python

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@SimonDarksideJ Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by SimonDarksideJ** [comment]
All in the day as an MVP :S

**Review by lucascosti — COMMENTED** [review]
👋 @SimonDarksideJ, thanks a lot for this PR!

🤔 This one's a bit of a tough situation. The use-case for the reusable that you've edited is to show the use of the YAML syntax for the `jobs.<job_id>.outputs` key, and not really for the scripting to set the environment variable that the key uses (we currently have that documented in  "[Workflow commands for GitHub Actions ](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)."). We currently have the Bash and powershell examples there.

I do realize that we don't explain this at all for this `jobs.<job_id>.outputs` example 😅 . Instead of repeating the examples with different scripting, how about we add a short explanation of setting the environment variable and link to the relevant section of the [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=bash#setting-an-output-parameter) article instead?

**Comment by nguyenalex836** [comment]
@SimonDarksideJ I'll be closing this PR due to inactivity - but if you would like to work on this further, we're happy to reopen this PR 💛

**Comment by SimonDarksideJ** [comment]
To be honest @nguyenalex836 I had given up on this PR as it did not seem desired, even though it was to address an issue I came across in the docs.

**Comment by nguyenalex836** [comment]
I'm sorry to hear that, @SimonDarksideJ! Let us know if you'd like to reopen this PR - we're happy to do so 💛

**Pull request closed without merging**
