### PR TITLE
Fix outdated URL for the ca-certificates package

### LINKED ISSUE #15985: Wrong URL for the Debian ca-certificates package information page
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[About commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

### What part(s) of the article would you like to see updated?

Currently, the [S/MIME commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#smime-commit-signature-verification) section contains a hyperlink that does not work as intended.
The link in question points to the Debian `ca-certificates` package information page on the [packages.debian.org](https://packages.debian.org) website.
However, when clicked, it results in an Error page from the target website (please see the attached screenshot below).
That's because the URL refers to an older/outdated Debian release ("Jessie"), for which package information is no longer available.
Additionally, the URL has a small typo in that it includes the language code for Hungarian ("hu").

I reckon this is simple to fix.
As a matter of fact I have already commited the necessary changes in my own fork of the docs repo, so expect a PR soon!

Cheers! 👍

### Additional information

GitHub_Docs_2022-03-02

### PR DESCRIPTION
**Pull request by a-roussos**
This is my attempt at a fix for the outdated URL issue I spotted while perusing the docs earlier today.

Thanks in advance for your time reviewing this! 😃

Fixes #15985

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@a-roussos 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
@a-roussos 👋🏻 - thanks for fixing this broken (and language-specific) link ✨ 
LGTM 🙂

**Comment by mchammer01** [comment]
There's a failing check. Asked someone to look into this.

**Comment by WalterMaroney** [comment]
782777

**Pull request merged**
