### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yukosgiti**
man -> main

### Why: There was a typo.

**Closes [issue link]**

### Check off the following:
- [+] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [+] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [+] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by janiceilene — APPROVED** [review]
Thanks so much for opening a PR for this fix! I'll update the branch and get this merged in once tests are passing ⚡

**Comment by goldstar611** [comment]
NO! this is not a main page, it's a man page. https://git-scm.com/docs/git-filter-branch

man, as in, manual, a guide.

**Comment by goldstar611** [comment]
https://www.kernel.org/doc/man-pages/

**Comment by goldstar611** [comment]
Excerpt from page, emphasis added using `*********`

`the fact that little educational information is provided to inform users of the ramifications of a rewrite and how to avoid mixing old and new history. For example, ********* this man page ********* discusses how users need to understand that they need to rebase their changes for all their branches on top of new history (or delete and reclone), but that’s only one of multiple concerns to consider. See the "DISCUSSION" section of the git filter-repo manual page for more details.`

**Comment by heiskr** [comment]
Thanks for the pull request. This is, as @goldstar611 mentions, a _man_ual page.

**Comment by yukosgiti** [comment]
Well, TIL!

**Comment by goldstar611** [comment]
> Well, TIL!

Sorry if I sounded offensive in my first post. It's hard to stand by and see the amount of junk P.R.s these people get without getting a little agitated.

**Pull request closed without merging**
