### PR TITLE
Fix `pull_request_target` if_merged example

### PR DESCRIPTION
**Pull request by laurelmay**
Within the workflow, the event object is still `github.event.pull_request`, so the `merged` key is at `github.event.pull_request.merged`. There _is not_ a `github.event.pull_request_target` object. This is also reflected in the table for this section in "Webhook event payload".

### Why:

Copying and pasting the code sample provided to run on merged PRs will not work; the job will always be skipped because `github.event` does not have a `pull_request_target` key on `pull_request_target` events. As documented in the "Webhook event payload" and as can be seen by dumping the event (`${{ toJSON(github.event) }}`), the key is `pull_request` instead.

### What's being changed:

The example code snippet is updated to:

```yaml
if: github.event.pull_request.merged == true
```

which should work as-is for `pull_request_target` events to run a job on a merged PR.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by kylelaker** [comment]
Quick link to the change is at https://docs-16752-751dec.preview.ghdocs.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges-1

**Comment by ramyaparimi** [comment]
@kylelaker Thanks for opening a pull request! I've triaged this issue for technical review by a subject matter expert :eyes:

**Comment by kylelaker** [comment]
Thanks! If it helps, I created a [sample repo](https://github.com/kylelaker/gha-testing) with a [`pull_request_target`-triggered workflow](https://github.com/kylelaker/gha-testing/blob/main/.github/workflows/pr-target.yml) that dumps the `github.event` object and opened a [pull request](https://github.com/kylelaker/gha-testing/pull/1) on that repo. The event details can be seen in the resulting [workflow execution](https://github.com/kylelaker/gha-testing/runs/5816385888?check_suite_focus=true#step:2:477). And in that event, there is a `pull_request` key in the object, but not a `pull_request_target`.

**Comment by ethomson** [comment]
Thanks @kylelaker - looks good to me!

**Review by mchammer01 — APPROVED** [review]
LGTM from a docs perspective!
Thanks for your contribution @kylelaker ✨

**Pull request merged**
