### PR TITLE
Update Keyboard Shortcuts to meet GitHub's new Content Style Guide

### LINKED ISSUE #13436: Update keyboard shortcuts to meet the new GitHub content style guide
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/using-github/keyboard-shortcuts

### What part(s) of the article would you like to see updated?

Keyboard shortcuts in this document are outdated. Refer to [Keyboard Shortcuts](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#keyboard-shortcuts) section in the content style guide on how to correctly present keyboard shortcuts in GitHub docs.

### Additional information

For example:

<kbd>command</kbd><kbd>k</kbd> should be <kbd>Command</kbd>+<kbd>K</kbd>
<kbd>command</kbd><kbd>shift</kbd><kbd>7</kbd> should be <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>7</kbd>

### PR DESCRIPTION
**Pull request by AnilSeervi**
### Why:

Closes #13436 

### What's being changed:
- Keyboard Shortcuts being changed to meet GitHub's new content style guide.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by AnilSeervi** [comment]
There's one more thing to do:

Add `(Mac)` and `(Windows/Linux)` for respective shortcuts, but I'm not sure for some of the shortcuts in the list, so have left it out for now.

**Comment by ramyaparimi** [comment]
@AnilSeervi 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Kimtrai2020** [comment]
[]() anilseervi:update-key-shortcuts

>

**Review by Bigg29 — COMMENTED** [review]
Connect and request

**Comment by Devarshini** [comment]
Open list of keyboard shortcuts
  	Mac 	Windows/Linux
Open keyboard shortcuts 	⌘/ 	Ctrl/
Repo actions
	Mac 	Windows/Linux
Create branch 	⌘B 	CtrlB
Fetch all 	⌘L 	CtrlL
Stage the current file 	S 	S
Stage all files 	⌘ShiftS 	CtrlShiftS
Unstage the current file 	U 	U
Unstage all files 	⌘ShiftU 	CtrlShiftU
Commit staged files with current message 	⌘Enter 	CtrlEnter
Stage all files and commit with current message 	⌘ShiftEnter 	CtrlShiftEnter
Focus commit message box 	⌘ShiftM 	CtrlShiftM
Navigation
  	Mac 	Windows/Linux
Select next commit in graph 	J or ↓ 	J or ↓
Select previous commit in graph 	K or ↑ 	K or ↑
Select next item in branch 	Shift↓
ShiftJ 	Shift↓
ShiftJ
Select previous item in branch 	Shift↑
ShiftK 	Shift↑
ShiftK
Select first commit in graph 	⌘↑ 	CtrlHOME
Select last commit in graph 	⌘↓ 	CtrlEND
Undo 	⌘Z 	CtrlZ
Redo 	⌘Y
⌘ShiftZ 	CtrlY
CtrlShiftZ
Command Palette
  	Mac 	Windows/Linux
Toggle Command Palette 	⌘P 	CtrlP
Search commits 	⌘F 	CtrlF
Open repo via Command Palette 	⌘ShiftO 	CtrlShiftO
Search file to view history and blame 	⌘ShiftH 	CtrlShiftH
Focus the left panel filter bar 	⌘OptionF 	CtrlAltF
Open current repo in terminal 	OptionT 	AltT
Open current repo in File Manager 	AltO 	AltO
Open diff or merge tool 	⌘D 	CtrlD
Close current repo 	⌘W 	CtrlW
Search within file (if file content has focus) 	⌘F 	CtrlF
UI
  	Mac 	Windows/Linux
Toggle Fullscreen Mode 	Control⌘F
	CtrlShiftF
Increase Zoom 	⌘=
⌘+ 	Ctrl=
Ctrl+
Decrease Zoom 	⌘− 	Ctrl−
Reset zoom 	⌘0 	Ctrl0
Toggle the left panel 	⌘J 	CtrlJ
Toggle the Commit Details panel 	⌘K 	CtrlK
Focus the search bar 	⌘F 	CtrlF
Focus the left panel filter bar 	⌘OptionF 	CtrlAltF
Close the current panel (if one is open) 	Esc 	Esc
Tabs
  	Mac 	Windows/Linux
New Tab 	CmdT
	CtrlT
Close Tab 	CmdW
	CtrlW
Swap to Tab #1-9 	⌘#1-9 	Ctrl#1-9
Jump to next open tab 	⌘Tab 	CtrlTab
Jump to previous open tab 	⌘ShiftTab 	CtrlShiftTab

**Review by lucascosti — APPROVED** [review]
This was a lot of work, thanks so much, @AnilSeervi! 👏 

I pushed an extra commit in https://github.com/github/docs/pull/13508/commits/0f7aaced61fbea1dd92e5b124efbae95d2dc0f54 that adds the OSs for each shortcut for when there are more than one, and also fixed a small table bug.

I'll get this merged 🚀

**Pull request merged**
