### PR TITLE
Update the `go-version` in the example as a string.

### LINKED ISSUE #24926: Update the `go-version` in the example as a string.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

file: https://github.com/github/docs/blob/main/content/actions/automating-builds-and-tests/building-and-testing-go.md
page: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

スクリーンショット 2023-04-07 17 20 40

## Summary
We should update the `go-version` in the example as a string.

|Before|After|
|-|-|
|1.15|'1.15'|

## Detail
"go-version" accepts not only strings but also numbers. However, there are some numbers that may not be interpreted correctly.
For example, "1.20" may be interpreted as "1.2". This is because the JavaScript in "actions" omits the last character "0" after the decimal point.
In the current documentation example, "1.15" is written as a number. While numbers are not prohibited, we would prefer developers to write it as a string whenever possible. By writing "1.15" as a string, we hope to implicitly guide developers in that direction.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sijysn**
### Why:

Closes: #24926 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@sijysn Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Comment by sijysn** [comment]
@cmwilson21 
I have checked!

**Comment by sijysn** [comment]
This PR resolved the issue. Thank you.
https://github.com/github/docs/pull/25146

**Comment by cmwilson21** [comment]
@sijysn Thank you for coming back and letting us know! ✨

**Pull request closed without merging**
