### PR TITLE
Use `gradle-build-action` for Gradle builds

### LINKED ISSUE #11875: Recommend `gradle/gradle-build-action` for invoking Gradle in GitHub Actions
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
- https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle

### What part(s) of the article would you like to see updated?

These 2 articles invoke Gradle directly. The Gradle team provides https://github.com/marketplace/actions/gradle-build-action which provides a better user experience. We'd like this to be the recommended way to run Gradle builds in GitHub Actions.

### Additional information

Related PRs:
https://github.com/github/docs/pull/11851
https://github.com/actions/starter-workflows/pull/1237

### PR DESCRIPTION
**Pull request by bigdaz**
The `gradle-build-action` provides enhanced execution and caching functionality for Gradle. 

Improvements over directly invoking `./gradlew` include:
- Easier to run the workflow with a particular Gradle version
- More sophisticated and more efficient caching of Gradle User Home between invocations
- Detailed reporting of cache usage and cache configuration options
- Automatic capture of Build Scan links

Related PR: https://github.com/actions/starter-workflows/pull/1237

### Why:

Closes https://github.com/github/docs/issues/11875

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@bigdaz I noticed that this PR is opened in draft version !! You can click the `Ready for review` button when you are done with making changes ✨

**Comment by bigdaz** [comment]
Thanks @ramyaparimi . Since this is a pretty major change I wasn't sure if it warranted a discussion prior to "formal" submission.  I asked on the shared Gradle/GitHub Slack channel, but didn't hear back.

**Comment by ramyaparimi** [comment]
@bigdaz Thank you so much for thinking about opening a discussion prior to a formal discussion. Like you thought, for big content changes like this, it would be helpful if an issue is opened prior to a PR. That way, our writers can take a look at it and come with a content design, which would help contributors greatly with making  their changes. Here is an [example of one such issue](https://github.com/github/docs/issues/9403).

If you would like, you can convert this PR back to draft and I can triage the issue (linked to this PR) for a writer's review :eyes:. That way, you can edit your PR with any changes they propose and open it for review again 💖 

Let me know what you think!

**Comment by bigdaz** [comment]
@ramyaparimi Thanks for the feedback. I've converted this PR back to a draft.
To confirm, you are happy to work with the issue I already opened (#11875) and are not asking me to open another issue?

**Comment by ramyaparimi** [comment]
@bigdaz 
>To confirm, you are happy to work with the issue I already opened (#11875) and are not asking me to open another issue?

Yes, that's correct! I will go ahead and triage the issue for a writer's review 👀. 

Thanks a bunch for your passion in improving the GitHub docs 💖

**Review by REDMI7AMM — COMMENTED** [review]
MIUI

**Comment by REDMI7AMM** [comment]
>

**Review by REDMI7AMM — COMMENTED** [review]
MIUI

**Comment by bigdaz** [comment]
Still hoping to have a conversation about how we can make `gradle/gradle-build-action` the official way of running Gradle from GitHub actions

**Comment by ramyaparimi** [comment]
@bigdaz Thanks so much for your patience 💖 Please convert the PR from `draft` to `ready for review` so I can 
get this triaged for review :zap:

**Review by lucascosti — APPROVED** [review]
Apologies for the time it's taken for us to review this PR.

Thanks so much for these changes, @bigdaz, and for making the equivalent changes in the starter workflows repository. 🎉 

I've made some small edits to have the articles flow a little better. I'll get these merged in when the tests pass. Thanks again!

**Pull request merged**
