### PR TITLE
switch adopt to temurin and bump to jdk17

### LINKED ISSUE #19526: Update setup-java instructions to recommend Java 17 and Temurin
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-ant
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-maven
- https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

### What part(s) of the article would you like to see updated?

The setup-java steps should recommend Java 17 as it's the latest LTS

Also switch to `temurin` as it has replaced `adopt`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gdams**
### Why:

Closes https://github.com/github/docs/issues/19526

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@gdams Thanks so much for opening a PR! I'll get this triaged for review :zap:

Our actions team may be a little slow to respond right now, so we appreciate your patience! :yellow_heart:

**Comment by gdams** [comment]
CC @maxim-lobanov (you are likely the subject matter expert here)

**Review by brcrista — APPROVED** [review]

**Review by brcrista — APPROVED** [review]
Approving from the Actions team

**Comment by gdams** [comment]
@cmwilson21 can this be merged now?

**Comment by cmwilson21** [comment]
@gdams Thanks for checking in on this! It's on the writer board now and will be reviewed soon ✨

**Review by lucascosti — APPROVED** [review]

**Pull request merged**
