### PR TITLE
şeUpdate installing-github-enterprise-server-on-aws.md

### PR DESCRIPTION
**Pull request by umutlu58**
### şlwşşEİLQWŞDLŞASd
   #@@isd4sİŞFDVFFİ5VŞÜVA5ÜAAAAAAVĞ,FDĞ5,ĞGRĞPER*EW90TREO0ORPOPTOTPRTRĞTÜT

### Why:

**Closes [issue link]**

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Alokrar** [comment]
check

**Comment by Alokrar** [comment]
ok

**Comment by hainusii** [comment]
> ### şlwşşEİLQWŞDLŞASd
> #@@isd4sİŞFDVFFİ5VŞÜVA5ÜAAAAAAVĞ,FDĞ5,ĞGRĞPER*EW90TREO0ORPOPTOTPRTRĞTÜT
> 
> ### Why:
> **Closes [issue link]**
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Comment by RadicalchAngel** [comment]
2021-03-16 15:21 UTC−07:00, Janice <.
oxx
gl>:

**Pull request closed without merging**
