### PR TITLE
Update troubleshooting-github-copilot-in-a-jetbrains-ide.md

### PR DESCRIPTION
**Pull request by burkconnor**
### Why:

There is a typo in the documentation that could mislead users.

### What's being changed (if available, include any code snippets, screenshots, or gifs):
I updated the phrase in one of the steps to match the phrase shown in Intellij IDEA verbatim. A screenshot of what is shown in Intellij IDEA is provided below.

Phrase shown in Intellij IDEA

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@burkconnor Thanks for opening a PR :+1: Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by burkconnor** [comment]
@cmwilson21 I updated the comment. Please let me know if I need to do anything else.

**Comment by cmwilson21** [comment]
@burkconnor Thank you for the update! The screenshot is super helpful, too. I'll get this up for review! ⚡

**Review by sophietheking — APPROVED** [review]
@burkconnor 👋  Thanks for opening this PR and contributing to our Docs! This looks good to me, I'll make sure tests are passing before I get this merged.

**Pull request merged**
