### PR TITLE
Applying lossless compression to unoptimized png files in images

### PR DESCRIPTION
**Pull request by Protectator**
### Why:

This PR aims to solve #298.

### What's being changed:

I optimized the size of PNGs in the `assets/images` by using **lossless compression** algorithm on them. The new size of the optimized PNGs in this PR vary between 49% and 93% of their original size. This PR reduces the total size of the images by **~2457 KB**.

### Check off the following:
- [x] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by heiskr — APPROVED** [review]
🙏🏼 Thanks!

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by Protectator** [comment]
Thanks, I'll do that. I don't really know what kind of contribution that is, though ? Is that content ? Tell me if you see somethiing more appropriate.

@all-contributors please add @Protectator for content

**Comment by Protectator** [comment]
Indeed, this ain't normal : https://github.com/github/docs/blob/main/.all-contributorsrc#L331

**Comment by Protectator** [comment]
I made a PR to repair the file first, I'll add myself after that : https://github.com/github/docs/pull/391

**Comment by Protectator** [comment]
@all-contributors please add @Protectator for content

**Pull request merged**
