### PR TITLE
Bring workflow in line with suggested usage

### PR DESCRIPTION
**Pull request by rneatherway**
To reliably give comparisons on PRs we must be analyzing
all pushes of the possible target branches (here just `main`).

### CODE REVIEW

**Comment by Supattr0712** [comment]
หียแกนสอดา

**Comment by Supattr0712** [comment]
Hdfjjcff

**Comment by Supattr0712** [comment]
Bdgjc

**Comment by Supattr0712** [comment]
Gdgh

**Comment by heiskr** [comment]
Thank you for the pull request. My understanding is the team would like to run CodeQL on pull requests in addition to `main`.

**Comment by rneatherway** [comment]
@heiskr do you mean the team would like to

a) analyse pull requests as well as analyse main, or
b) analyse pull requests against branches other than main?

If 'a', this PR achieves the desired goal. If 'b', the `branches` tags just need to be extended with the other branches, or if PRs are to be made against arbitrary branches this tag can be removed.

Either way, the `on: pull_request` trigger needs to be added or PR analysis will not work in the future.

**Comment by shannonsetzer** [comment]
What am I receiving..? I am new to this ....thx


Sent from Yahoo Mail for iPhone


On Monday, November 30, 2020, 12:32 AM, สุพัตรจันทร์แจ่มหล้า <notifications@github.com> wrote:




หียแกนสอดา

**Pull request closed without merging**
