### PR TITLE
Adding some extra detail around renaming

### PR DESCRIPTION
**Pull request by aharpole**
### Why:

**Closes https://github.com/github/docs-content/issues/3913**

### What's being changed:

In particular, defining what GitHub will do for branch renames, and what it will not do:

- added that raw file links don't get redirects
- added that PRs for forks get retargeted too
- Included that `git pull` commands have no redirects, and that users will need to update their local git environments
- added that we explain how to update your local git environment on the repo's home page

Also, this updates the GHES version this will appear on to 3.2.

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening a PR @aharpole! I'll get this triaged for review ✨

**Review by jace833 — APPROVED** [review]

**Review by jace833 — APPROVED** [review]

**Comment by lucascosti** [comment]
Thanks heaps for this PR, @aharpole!

I've made some rewording changes to mainly remove the existing future tense, and to simplify the use of the product locations. Could you have a look and let us know if the meaning is still ok?

Stage build: https://docs-4830--renaming-a-branch-u.herokuapp.com/en/github/administering-a-repository/renaming-a-branch#about-renaming-branches

**Comment by aharpole** [comment]
@lucascosti I read the doc on the link and it sounded great. :shipit:!

**Review by lucascosti — APPROVED** [review]
🚢

**Pull request merged**
