### PR TITLE
Update creating-a-composite-run-steps-action.md

### PR DESCRIPTION
**Pull request by KeisukeShima**
### Why:

I added it because there is no description about private action only in the Composite action document.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@KeisukeShima Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by KeisukeShima** [comment]
@ramyaparimi Thanks for your comment.

Let me explain this PR.
Below are links to testing Javascript Action and Docker Action.
There are Private Action and Public Action in these, and the user can choose either one.
However, the Composite Action documentation does not have this description, and **users may misunderstand that they cannot choose Private Action.**
In fact, I also read the docs and thought that Composite Action couldn't create a Private Action.
However, in reality, any Action can be tested in the same way. Therefore, the appearance of the document should be the same.

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#testing-out-your-action-in-a-workflow
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow

**Comment by KeisukeShima** [comment]
I'm not a native English speaker, so corrections are welcome.

**Comment by janiceilene** [comment]
👋 Thanks so much for this PR @KeisukeShima! There was a lot of work recently done on the composite actions docs. Let us know if the information you're looking for isn't in the new docs!

We appreciate your interest and passion in improving the GitHub docs 💖

**Pull request closed without merging**
