### PR TITLE
refer to node 16 in GitHub javascript action

### PR DESCRIPTION
**Pull request by dastrobu**
node 16 is the latest supported node version in GitHub javascript actions and is also the current LTS node version.

### Why:

Updates outdated information on nodejs version and fixes download link.

### Check off the following:

- [x ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@dastrobu 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ramyaparimi** [comment]
@dastrobu Thanks for opening this PR. This is being addressed internally in a PR to add node16 support to runner and actions (versioned for GHES), so I am going to close this PR now 💛.

Thanks so much for taking your time to contribute to the GitHub docs 💖 .

**Comment by dastrobu** [comment]
@ramyaparimi I am a bit confused. `node16` is already working in GitHub actions as far as I know. So this PR updates docs to reflect the current state. What is not supported is `node17`, which is where the current link in the docs points to. 

So current docs point to an unsupported node version (17) and recommend to use a very outdated node version (12). This is what this PR was supposed to fix.

**Comment by vgrl** [comment]
👋 @dastrobu thanks for seeking clarification. Your statement that `node16` is already available in GitHub Actions is correct for our Free, Pro, Team and Enterprise Cloud versions. However the current versions of GitHub Enterprise Server and GitHub AE only support `node12`, and we already have an internal PR open to add such versioning. As part of our internal PR, we'll also incorporate your suggested changes about updating the Node.js download URL (thank you!).

Thanks again for your work on this docs update!

**Pull request closed without merging**
