### PR TITLE
Explain what to do about bugs in translations

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

https://github.community/t/word-correction-in-documentation/192109/3

### What's being changed:

Clarify what to do about bugs in translations

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@jsoref Thanks for opening this PR. We are looking into this 👍

**Review by MaryJaneLove4 — APPROVED** [review]
Done

**Comment by jsoref** [comment]
@ramyaparimi does the bot need love?

**Comment by JoeyB26** [comment]
Everything needs love and is allowed Love

**Comment by ramyaparimi** [comment]
@jsoref I spoke with the team and we are not interested in this suggestion at the moment. This is something we have covered in our triage process and we do not want to encode it in the contributing guide at this time.

**Comment by JoeyB26** [comment]
so is this a github  program allowing users to gain acces to my device with the ability change my password and lock me out of my ow files, I need to have total access to my files?

**Pull request closed without merging**
