### PR TITLE
Citing text

### PR DESCRIPTION
**Pull request by Dinayen-Daniella**
To cite an author,  name them in parenthese  () and written in italics. For example ( | ‘- - ‘ | ) or ( | ‘ * *  ‘ | )

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@Dinayen-Daniella 
Thanks for opening a PR :+1: Could you please explain a little more about "why" and "what's being changed" in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

**Comment by Dinayen-Daniella** [comment]
Thanks for viewing. Nothing was changed , added a style of citing as a way to contribute to the project

**Review by dondondy — COMMENTED** [review]
Dellete conversation

**Comment by ramyaparimi** [comment]
@Dinayen-Daniella 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by lecoursen** [comment]
Thanks for your interest in contributing to the docs, but we won't be accepting this contribution.

**Pull request closed without merging**
