### PR TITLE
Fix error in url

### PR DESCRIPTION
**Pull request by rajbos**
### Why:
I was working with this and the url is incorrect, this fixes that.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 Hey @rajbos - Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by aiqiaoy — DISMISSED** [review]
👍🏼 from custom gate feature team

**Review by jc-clark — DISMISSED** [review]
✨ Thank you for updating this @rajbos! I suggested one minor change here just to fit our content style-guide conventions, but otherwise this looks good to me.

**Review by jc-clark — APPROVED** [review]
🚀

**Pull request merged**
