### PR TITLE
Corrected Ruff linter call example

### LINKED ISSUE #33950: Ruff call syntax has changed for Python linting
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-ruff-to-lint-code

### Additional information

PR incoming!

### PR DESCRIPTION
**Pull request by howroyd**
`ruff <path>` has been removed. Use `ruff check <path>` instead.

https://github.com/astral-sh/ruff-vscode/issues/132

### Why:

Closes: https://github.com/github/docs/issues/33950

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [X] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by howroyd** [comment]
Staging looks good, I only added one word.

I assuming all the placeholders are not my responsibility to review? e.g.

```
{% data reusables.actions.enterprise-github-hosted-runners %}
```

**Comment by nguyenalex836** [comment]
@howroyd Thanks so much for opening a PR! I'll get this triaged for review ✨ The team will have more feedback regarding the reusable upon review 💛

**Comment by Malik5703** [comment]
my8917351@gmail.com

**Comment by Malik5703** [comment]
my8917351@gmail.com

**Review by sunbrye — APPROVED** [review]

**Comment by miladnajfi** [comment]
hhj

**Comment by miladnajfi** [comment]
Namaste

**Comment by miladnajfi** [comment]
miladnajfy

**Comment by miladnajfi** [comment]
miladnajfy

**Comment by miladnajfi** [comment]
milad

**Comment by miladnajfi** [comment]
milad

**Pull request merged**
