### PR TITLE
Set all x-ratelimit-* header names to loweracse

### PR DESCRIPTION
**Pull request by alpn**
### Why:

Currently x-ratelimit-* headers are in CamelCase (in the docs), but in practice the API returns them in lower case.
Although HTTP header names are (not case sensitive)[https://www.w3.org/Protocols/rfc2616/rfc2616.html],  this could still be confusing for some, therefor I propose to change it.

Closes [issue link]

### What's being changed:

`X-RateLimit-*` => `x-ratelimit-*` (as the API returns in practice)

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@alpn 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by BigginisAlive** [comment]
ThNks

**Comment by BigginisAlive** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

Thank u

**Review by ethanpalm — APPROVED** [review]
Thanks for creating this PR, @alpn. Your changes look good and I agree that it could be confusing if the API returns different casing than the docs suggest. ✨ 

I'll get this branch up to date and merged once all the checks are passing.

Thank you for taking the time to contribute to the GitHub docs and help everyone who is using them! 🎉

**Comment by alpn** [comment]
Thank you @ramyaparimi  @BigginisAlive @ethanpalm 
I really appreciate your speedy response :)

**Pull request merged**
