### PR TITLE
fbbrute.py

### PR DESCRIPTION
**Pull request by ko602**
github.com

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by anjannair — COMMENTED** [review]
Spam

**Comment by ko602** [comment]
fbbrute.py#2345

**Comment by ko602** [comment]
pkg update && pkg upgrade

**Comment by ko602** [comment]
pkg install python

**Comment by ko602** [comment]
pkg install python

**Comment by ko602** [comment]
pkg install python2

**Comment by ko602** [comment]
pkg install git

**Comment by ko602** [comment]
pkg install pip

**Comment by ko602** [comment]
pkg install pip2

**Comment by ko602** [comment]
pip2 install requests

**Comment by ko602** [comment]
pip2 install mechanize

**Comment by ko602** [comment]
git clone https://github.com/ko602/fbbrute.py#2345

**Comment by ko602** [comment]
git clone https://github.com/ko602/fbbrute Mm

**Comment by ko602** [comment]
Tool Run

**Comment by ko602** [comment]
ls && cd fbbrute Mm && ls

**Comment by ko602** [comment]
python2 fbbrute.py

**Pull request closed without merging**
