### PR TITLE
fix: improving style guide 

### LINKED ISSUE #31686: Style guide for access, permission, role names and its usage unclear
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#permissions

### What part(s) of the article would you like to see updated?

The chapter defines role usage in caps & quoted:

> Resources (e.g., "Write" for a repository, "Admin" for a security advisory)

yet the examples below don't use any of that:

> Avoid: People with the write role can...

Trying to follow the Style guide, I'd be tempted to use: 

> Avoid: People with "Write" role can...

Is there a clear style to follow? I'd like to adhere in PRs as much as possible.

### Additional information

- In #31532 I've proposed some quotation to make the sentence more clear that it refers to "token" words as roles.
- I've followed the Style guide https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#permissions where it shows the resource role as quoted and capitalized.
- However the same style is _not_ followed in the examples right after the definition, so I'm opening this issue to clarify the usage, and eventually fix the examples or the definition to start with.

### PR DESCRIPTION
**Pull request by CBID2**
### Why:
Closes: #31686

### What's being changed (if available, include any code snippets, screenshots, or gifs):
This PR adds examples of how not to write content in GitHub's documentation to their style guide. 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
Howdy, @CBID2 👋 ! It looks like you've asked @ethanpalm for assistance on the related [issue](https://github.com/github/docs/issues/31686). I'll go ahead and leaves this PR for now while we wait for his input 💛 thank you for taking this on!

**Comment by CBID2** [comment]
> Howdy, @CBID2 👋 ! It looks like you've asked @ethanpalm for assistance on the related [issue](https://github.com/github/docs/issues/31686). I'll go ahead and leaves this PR for now while we wait for his input 💛 thank you for taking this on!

Thanks @nguyenalex836. You can give feedback too! :) I'm open to your thoughts

**Comment by nguyenalex836** [comment]
> > Howdy, @CBID2 👋 ! It looks like you've asked @ethanpalm for assistance on the related [issue](https://github.com/github/docs/issues/31686). I'll go ahead and leaves this PR for now while we wait for his input 💛 thank you for taking this on!
> 
> Thanks @nguyenalex836. You can give feedback too! :) I'm open to your thoughts

That's very kind of you! 😊 This isn't my area of expertise, and Ethan will be the superior resource - but I appreciate the kind words! 💛

**Review by ethanpalm — COMMENTED** [review]
Thanks for creating this PR, @CBID2! Adding this example is helpful since it's a pretty common mixup.

The other changes to close https://github.com/github/docs/issues/31686 would be updating lines 1482 and 1483 (unfortunately they're too far from the edited lines so I can't put the comments directly on those lines).

1482: change "Write" to write and "Admin" to admin so that the line reads (e.g. write for a repository, admin for a security advisory)
1483: remove the quotation marks so "team maintainer" becomes team maintainer

**Comment by CBID2** [comment]
> write and "Admin"

Hi @ethanpalm. I made the changes.

**Review by ethanpalm — DISMISSED** [review]
This looks great, @CBID2 😄 

I'm going to push one small change to remove the quotation marks around write and admin, then will get this published. It should be live on the Docs site soon.

Thank you for taking the time to help improve the GitHub Docs! 🚀

**Review by ethanpalm — APPROVED** [review]

**Pull request merged**
