### PR TITLE
remove mention of live share in codespace docs

### LINKED ISSUE #34390: Remove mention of Live Share from the Codespaces docs
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace

### What part(s) of the article would you like to see updated?

The following article will need to be deleted -
"[Working collaboratively in a codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace)"

as well as the references to it:

- `content/codespaces/developing-in-a-codespace/index.md`
- `content/codespaces/guides.md`
- `content/codespaces/overview.md`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
### Why:

Closes: #34390 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by gagan-bhullar-tech** [comment]
Can anyone please let me know how to setup redirects.

**Comment by nguyenalex836** [comment]
@gagan-bhullar-tech Thank you for submitting this PR! ✨ I'm going to check with our engineering team to see how to resolve that failed test regarding the redirect 👍

**Review by Saldivar003 — COMMENTED** [review]
content/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace.md

**Review by Saldivar003 — COMMENTED** [review]
34391

**Comment by nguyenalex836** [comment]
[Collaborating w/ team](https://github.slack.com/archives/C0128FB8J3H/p1724696414813239?thread_ts=1724448772.979459&cid=C0128FB8J3H) on the failed check

**Comment by gagan-bhullar-tech** [comment]
@nguyenalex836 i am unable to login to the above link. Please let me know the outcome of discussion. Thanks.

**Comment by nguyenalex836** [comment]
> We may have to leave a very short article mentioning Live Share deprecation. Please hold off on this for now. I'm talking to the developer who worked on this.
> 
> Thanks

@hubwriter Hello! 👋 Do we have an update from the developer who worked on this originally? @CBID2 recently submitted a [PR](https://github.com/github/docs/pull/34507) to address this as well, and so I've removed the `help wanted` label from the [original issue](https://github.com/github/docs/issues/34390) for the time being

**Comment by hubwriter** [comment]
Thanks @nguyenalex836 - by coincidence I finally heard back from the developer about this just last night. The changes to Live Share just affect the backend service being used. From the user point of view Live Share will still be available, so no changes are needed to the docs after all.

I'll close the new PR and the issue for this.

**Review by AhmedMostafaoo7 — COMMENTED** [review]
Nice

**Pull request closed without merging**
