### PR TITLE
Sign all tags by default

### LINKED ISSUE #35185: Command for gpg signing all tags by default
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Telling Git about your signing key

### What part(s) of the article would you like to see updated?

6. Optionally, to configure Git to sign all commits by default, enter the following command:

### Additional information

For convenience, like #21497 . I will send the PR.

### PR DESCRIPTION
**Pull request by sih4sing5hong5**
Refer: https://stackoverflow.com/a/56979390

### Why:

Closes:  #35185 35185

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Add the command for set the configure about signing tags. Like #21497 .

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by sih4sing5hong5** [comment]
The **View deployment** is not working. :cry:

**Comment by nguyenalex836** [comment]
@user Thanks so much for opening a PR! I'll get this triaged for review ✨ Additionally, viewing deployment seems to be working now! Can you check once more? 💛

**Comment by sih4sing5hong5** [comment]
> @user Thanks so much for opening a PR! I'll get this triaged for review ✨ Additionally, viewing deployment seems to be working now! Can you check once more? 💛

It is still not working...
圖片

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@sih4sing5hong5 Thank you for your patience while our SME team reviewed! They agree with your changes, and I'll get this merged now 💛 Thank you for contributing to GitHub Docs ✨ 

If you're looking for an issue to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

**Comment by Mahdi350** [comment]
در مورد اکانت ها و چک‌ها و پول های که جابجا شده چه باید بکنم چگونه حق خود را بگیرم

**Pull request merged**
