### PR TITLE
Adding inline functionality description

### PR DESCRIPTION
**Pull request by codepo8**
One of the really cool things about copilot chat is that you can use it inside your code using the CMD+i shortcut. This should be shown here as it makes the extra step of copying and pasting from the side bar unneccesary

### Why:

Closes: 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@codepo8 Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by hubwriter — CHANGES_REQUESTED** [review]
Hi @codepo8 👋 

Thank you for raising this PR. I agree that it would be good to document the inline use of Copilot Chat in these beta docs.

I've made a few suggestions to make sure the new section fits in with our style guide.

If you'd like to apply the changes then we can get this merged.

Thanks again for taking time to help improve our docs. It's much appreciated. If you spot anything else that needs changed, and is more than just a small change or correction, it's always good to raise an issue first so that we can take a look, and perhaps make suggestions, before you go ahead and work on a pull request. For more information, see "[Contributing to GitHub Docs documentation](https://docs.github.com/en/contributing)."

Thanks for your support of Copilot and the GitHub docs! 🎉

**Review by codepo8 — COMMENTED** [review]
Works for me, let's get it out there

**Comment by hubwriter** [comment]
@nguyenalex836 - Thanks for pinging me on this.

The contributor resolved all of my review comments without applying any of the changes I suggested, or making any similar changes, so we can't merge this PR.

I'm inclined to close this PR.

**Comment by nguyenalex836** [comment]
@hubwriter Thank you for the response! I saw that as well, and agree. I have a feeling given their last [comment](https://github.com/github/docs/pull/28207#pullrequestreview-1652407901), there's a slight chance this may have been an accident or misunderstanding. 

I'll close out this PR, but leave a message to the contributor letting them know we can reopen this if they would like to apply your suggestions 💛 Wanted to make sure I wasn't missing any context - thank you for helping me out!

**Comment by nguyenalex836** [comment]
@codepo8 Hello! 👋 It looks like the last batch of [suggestions](https://github.com/github/docs/pull/28207#pullrequestreview-1645929393) @hubwriter provided to you were resolved without the suggestions being applied. 

Given inactivity on this PR, I'll go ahead and close this PR - but we are happy to reopen if you would like to apply those suggestions 💛

**Pull request closed without merging**
