### PR TITLE
actions/publishing(nodejs): `id-token: write` for `npm publish` with `--provenance`

### PR DESCRIPTION
**Pull request by revi**
### Why:

NPM refuses to publish with `--provenance` unless `id-token: write` permission is supplied.

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm error code EUSAGE
npm error Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
```

I used the `{% ifversion artifact-attestations %}` as it was there in L60 (where the relevant docs were written), but not sure if this would work well... :P

See also: https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Supply `id-token: write` permission as documented by NPM.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by revi** [comment]
> Thanks for submitting a PR to the GitHub Docs project!
> 
> In order to review and merge PRs most efficiently, we require that all PRs grant maintainer edit access before we review them. For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

Well,

>> _From [the docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)_
>
> **Who can use this feature?**
>
> People with push access to the upstream repository of a fork owned by a personal account can commit to the forked branches.

This repo is owned by org, thus there is no such option. (And no, I am not going to move to my personal account just for this.) If this is really a blocker, feel free to close this and do it on your version.

**Comment by danuwih** [comment]
Please unsubscribe me from all the email from Github

Very Important

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by revi** [comment]
> Please unsubscribe me from all the email from Github
>
> Very Important

[Settings > Notifications](https://github.com/settings/notifications)

**Comment by nguyenalex836** [comment]
@revi Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by SiaraMist — APPROVED** [review]
Thanks for catching this and updating it, @revi! You did the versioning perfectly too. ✨  I'll go ahead and get this merged.

**Pull request merged**
