### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by addam13rooks**
added name to line 1

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by addam13rooks — COMMENTED** [review]
sorry just getting used to fork and pull

**Comment by addam13rooks** [comment]
Sorry taking a little longer to grasp the process

**Review by addam13rooks — COMMENTED** [review]
i think i got it

**Comment by nguyenalex836** [comment]
@addam13rooks Hello! 👋 It looks like you attempted to add your name to the public open source GitHub Docs repo. Since this is a public repo, I've marked this pull request as `invalid`. 

If this pull request was submitted by mistake, and / or you intended to do something different, I would recommend checking out our docs on [pull requests](https://docs.github.com/en/pull-requests) for assistance.

**Pull request closed without merging**
