### PR TITLE
Revert "Revert "Update issue templates""

### PR DESCRIPTION
**Pull request by janiceilene**
Reverts github/docs#3797 This is a revert of my revert 😆 

I merged in my original PR to update our templates, which removed the templates completely 🙃 I reverted the PR the get our original templates back. So, this PR is to continue working on our new issue templates.

### CODE REVIEW

**Comment by chiedo** [comment]
If we do one at a time it will be easier to trace where things broke the last time!

Here's one: https://github.com/github/docs-internal/pull/18444

**Review by RattaphonKarnsomlap — CHANGES_REQUESTED** [review]
p

**Review by RattaphonKarnsomlap — CHANGES_REQUESTED** [review]
p

**Comment by imonmobin** [comment]
Keep me updated

**Pull request closed without merging**
