### PR TITLE
[Contributing guide] Replace broken image link

### PR DESCRIPTION
**Pull request by King-of-Spades**
### Why:
I saw the link was broken, so I grabbed a valid equivalent link from the root Readme file. 

### What's being changed:
Broken (removed): ``
Replaced: ``

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by janiceilene — APPROVED** [review]
Thank so much for opening a PR with a fix @King-of-Spades! I'll update the branch and get this merged in once everything's passing 🍏

**Comment by linhzz999** [comment]
Ok

**Comment by MACHONEJ82** [comment]
Dziękuję

**Review by Alvinchong1989 — COMMENTED** [review]
Pls help

**Review by NeverLiez — COMMENTED** [review]
- [x]

**Pull request merged**
