### PR TITLE
no need of escaping inside single quotes

### PR DESCRIPTION
**Pull request by eightnoteight**
### Why:

the generated line inside the zshrc is incorrect

image

### What's being changed (if available, include any code snippets, screenshots, or gifs):

fixing escaping

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@eightnoteight Thanks so much for submitting a PR! I'll get this triaged for review :zap:

And welcome to the community! 🎉

**Review by sophietheking — DISMISSED** [review]
Hi @eightnoteight 👋 Thanks for opening this PR and fixing this! I'll make sure we merge this as soon as possible.

**Comment by farzadso** [comment]
@eightnoteight Thanks for fixing this issue. The same change needs to be made on line 106 too.

https://github.com/github/docs/blob/c705ce4010946c0e6fba12b66e692c8a2c7c7321/content/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key.md?plain=1#L106

FYI @cmwilson21

**Review by cmwilson21 — APPROVED** [review]
LGTM. Thanks for making these additional changes!

**Pull request merged**
