### PR TITLE
Add travis ci migration table

### PR DESCRIPTION
**Pull request by chewy917**
### Why:

Closes https://github.com/github/docs/issues/1862

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@chewy917 Sorry about the `stale` tag. Removing it now ✨

**Review by MRck23 — APPROVED** [review]

**Comment by janiceilene** [comment]
It looks like work has been paused on this PR, I'm going to close it now!

**Comment by Mint-6263** [comment]
:blush:

**Comment by Mint-6263** [comment]
:heart_eyes:

**Pull request closed without merging**
