### PR TITLE
Rename access-permissions-on-github.md to Update access-permissions-o…

### PR DESCRIPTION
**Pull request by SNiTEBoBy**
…n-github.md

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by hafixo** [comment]
#2693 
Merge pull requested

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Comment by jace4411** [comment]
comment@noreply.github.com

**Comment by jace4411** [comment]
reply+ASMM7YGYKMFEZDFQVVNVEP56BC7L7EVBNHHC5I3CZ4@reply.github.com

**Comment by jace4411** [comment]
hi-- 
 已通过Tutanota 安全发送，立即注册您的加密无广告邮箱！ 
 https://tutanota.com

**Pull request closed without merging**
