### PR TITLE
Add octocat-rs to Rust libraries

### LINKED ISSUE #16360: Add octocat-rs to the list of REST API libraries
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/libraries

### What part(s) of the article would you like to see updated?

This section: https://docs.github.com/en/rest/overview/libraries#rust
Repository for octocat-rs: https://github.com/octocat-rs/octocat-rs

The docs should be changed to include octocat-rs for completeness, as it's best for users to know all of the options available to them. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by proudmuslim-dev**
### Why:

Closes #16360 

### What's being changed:

Octocat-rs is being added to the table of Rust API libraries available for GitHub's REST API.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@proudmuslim-dev 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by proudmuslim-dev** [comment]
> @proudmuslim-dev Thanks so much for opening a PR! I'll get this triaged for review ⚡

No problem, thanks :)

**Review by skedwards88 — APPROVED** [review]
Thanks for this addition! We'll get this merged down for you.

**Comment by proudmuslim-dev** [comment]
Awesome, thanks!

**Pull request merged**
