### PR TITLE
Main

### PR DESCRIPTION
**Pull request by Drrr345**
repo sync

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by hfabijanic** [comment]
I am really sorry for the changed files but I don’t remember when and why I should change them.Am 21.10.2022 um 23:34 schrieb github-actions[bot] ***@***.***>:﻿
👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions. The complete list of files we can't accept are:
.devcontainer/**
.github/actions-scripts/**
.github/workflows/**
.github/CODEOWNERS
assets/fonts/**
data/graphql/**
Dockerfile*
lib/graphql/**
lib/redirects/**
lib/rest/**
lib/webhooks/**
lib/search/indexes/**
package*.json
scripts/**
translations/**
content/actions/deployment/security-hardening-your-deployments/**
You'll need to revert all of the files you changed in that list using GitHub Desktop or git checkout origin/main <file name>. Once you get those files reverted, we can continue with the review process.

**Review by ghost — COMMENTED** [review]
GPG key ID: 4AEE18F83AFDEB23

**Review by ghost — COMMENTED** [review]
- name: Approve Pull Request
    uses: juliangruber/approve-pull-request-action@v2.0.0
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      number: 1
      repo: juliangruber/approve-pull-request-action

**Review by ghost — COMMENTED** [review]
https://github.com/github/docs/pull/21538#issue-1418881419

**Comment by D461081B** [comment]
@cmwilson21

**Comment by D461081B** [comment]
@greatness99

**Review by Genniefrmbx — COMMENTED** [review]
I have no idea what I'm doing

**Pull request closed without merging**
