### PR TITLE
Update ignore section of with example for github-actions : configuration-options-for-the-dependabot.yml-file.md

### PR DESCRIPTION
**Pull request by osarobo**
Include ignore example for `github-action` package-echo system. Ref: https://github.zendesk.com/agent/tickets/2318990 

```
- package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'actions/checkout'
        versions: '>= 3'
```

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@osarobo Hello! 👋 Would you be able to respond to this [issue](https://github.com/github/docs-content/issues/14037) when you have a chance?

**Comment by nguyenalex836** [comment]
@osarobo Thank you for responding to that internal issue! I'll get this triaged for review ✨

**Review by vgrl — DISMISSED** [review]
Thanks @osarobo! I am going to apply a small change, then I'll double check on preview and merge if all looks good! ⚡

**Review by vgrl — APPROVED** [review]
👍 Looks good on preview.

**Pull request merged**
