### PR TITLE
#32401 Minor typo: missing > in docs

### PR DESCRIPTION
**Pull request by conorheffron**
| **Source** | **Preview** | **Production** | **What Changed** |
|:----------- |:----------- |:----------- |:----------- |
| [`actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform.md`](https://github.com/github/docs/blob/c6e2c821902be9f42b051b9d191412d333d14b4d/content%2Factions%2Fdeployment%2Fsecurity-hardening-your-deployments%2Fconfiguring-openid-connect-in-google-cloud-platform.md) | [fpt](https://docs-32414-2ce5fd.preview.ghdocs.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)<br>[ghec](https://docs-32414-2ce5fd.preview.ghdocs.com/enterprise-cloud@latest/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)<br>ghes@ [3.12](https://docs-32414-2ce5fd.preview.ghdocs.com/enterprise-server@3.12/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.11](https://docs-32414-2ce5fd.preview.ghdocs.com/enterprise-server@3.11/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.10](https://docs-32414-2ce5fd.preview.ghdocs.com/enterprise-server@3.10/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.9](https://docs-32414-2ce5fd.preview.ghdocs.com/enterprise-server@3.9/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) <br> | [fpt](https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)<br>[ghec](https://docs.github.com/enterprise-cloud@latest/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform)<br>ghes@ [3.12](https://docs.github.com/enterprise-server@3.12/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.11](https://docs.github.com/enterprise-server@3.11/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.10](https://docs.github.com/enterprise-server@3.10/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) [3.9](https://docs.github.com/enterprise-server@3.9/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) <br> |  Typo fix |

### Why:
- Minor typo: missing > in docs [actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token](https://docs-32414-2ce5fd.preview.ghdocs.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token)
- What: Update configuring-openid-connect-in-google-cloud-platform.md

### Closes: 
#32401

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by conorheffron** [comment]
[Check unallowed file changes](https://github.com/github/docs/actions/workflows/triage-unallowed-contributions.yml)

**Comment by conorheffron** [comment]
[Check unallowed file changes](https://github.com/github/docs/actions/workflows/triage-unallowed-contributions.yml)

https://docs-32414-2ce5fd.preview.ghdocs.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token

**Comment by conorheffron** [comment]
> [Check unallowed file changes](https://github.com/github/docs/actions/workflows/triage-unallowed-contributions.yml)

https://docs-32414-2ce5fd.preview.ghdocs.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token

**Comment by nguyenalex836** [comment]
@conorheffron Thank you for opening this PR! ✨ Apologies - unfortunately, it looks like this is one of the few files we do not allow contributions toward. I'll file an issue to fix this internally. Thank you again for submitting a fix 💛

**Pull request closed without merging**
