### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by LakshmanPalli**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by LakshmanPalli** [comment]
Just a practice to learn pull requests, thaught to make a change in the content, that I think fits the context.

Thank you 👍

**Comment by LakshmanPalli** [comment]
Just in a practice of learning pull requests, made a change in the content, that I think fits the contest. 

Thank you 👍

**Comment by Mexicool** [comment]
> ### Por qué:
> Cierra [enlace del problema]
> 
> ### Lo que se está cambiando:
> ### Marque lo siguiente:
> * [ ] He revisado mis cambios en la puesta en escena (busque el último evento de implementación en la línea de tiempo de su solicitud de extracción y luego haga clic en **Ver implementación**).
> * [ ] Para los cambios de contenido, he completado la [lista de verificación de auto-revisión](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).
> 
> ### Impacto del escritor (Esta sección es solo para miembros del personal de GitHub):
> * [ ] Esta solicitud de extracción afecta a la experiencia de contribución
>   * [ ] He añadido la etiqueta "impacto del escritor"
>   * [ ] He añadido una descripción y/o una demostración en vídeo de los cambios a continuación (por ejemplo, un "vídeo antes y después")

#7958

**Comment by Mexicool** [comment]
diff --git a/content/github/setting-up-and-managing-your-github-profile/index.md b/content/github/setting-up-and-managing-your-github-profile/index.md
index 503052faa574..97402939081c 100644
--- a/content/github/setting-up-and-managing-your-github-profile/index.md
+++ b/content/github/setting-up-and-managing-your-github-profile/index.md
@@ -10,6 +10,7 @@ versions:
   ghae: '*'
 topics:
   - Profiles
+  - Contribution
 children:
   - /customizing-your-profile
   - /managing-contribution-graphs-on-your-profile

**Comment by ramyaparimi** [comment]
@LakshmanPalli Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ramyaparimi** [comment]
@LakshmanPalli I talked to the team and they pointed out that 'contribution' does not come under the allowed topic list. For more information please checkout this [docs](https://github.com/github/docs/blob/main/data/allowed-topics.js)  ⚡ 
Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

**Pull request closed without merging**
