### PR TITLE
Fix link in creating-personal-access-token (#25030)

### PR DESCRIPTION
**Pull request by ghost**
### Why: 
There are some grammatical mistakes you need to fix. Also the headings were glitching too.

Closes: 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Asteriod0 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for fixing this! We'll get it merged for you.

**Comment by cmwilson21** [comment]
Closing and reopening this PR to get it merged

**Comment by Nzerich** [comment]
Great

**Review by Apetree100122 — COMMENTED** [review]
Thank

**Pull request closed without merging**
