### PR TITLE
Document npm run build step

### PR DESCRIPTION
**Pull request by sarahs**
See https://github.com/github/docs/pull/940#issuecomment-719849872.

This PR documents how to run the `npm run build` step to create static assets locally.

### CODE REVIEW

**Review by hubwriter — APPROVED** [review]
Changes LGTM. Thanks for adding this information. 👍

**Review by chiedo — APPROVED** [review]

**Review by JasonEtco — APPROVED** [review]
Nice addition, thanks @sarahs!

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Pull request merged**
