### PR TITLE
Update working-with-the-npm-registry.md

### PR DESCRIPTION
**Pull request by heliosalesjr**
### Why:

Adds a space to an example here - https://docs.github.com/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by heliosalesjr** [comment]
it wasn't too much, I'd just added a space somewhere it was missing one.

**Comment by cmwilson21** [comment]
@heliosalesjr Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by vgrl — COMMENTED** [review]
LGTM, @heliosalesjr while we're working in this article can you also update line 145 with the same change?

**Comment by cmwilson21** [comment]
@heliosalesjr 👋 Just checking in. Are you able to make the same change in line 145 as mentioned above? ☝️

**Comment by heliosalesjr** [comment]
> @heliosalesjr 👋 Just checking in. Are you able to make the same change in line 145 as mentioned above? ☝️

I've tried to but I'm getting confused and I'm afraid I'll do something wrong. I'm reading all the instructions and I'll try again as soon as I figure this out, ok? If you think I'm missing something very obvious, I'd like to hear from you. Thank you!

**Comment by cmwilson21** [comment]
@heliosalesjr No prob! If you go to your file [here](https://github.com/heliosalesjr/docs/blob/patch-1/content/packages/working-with-a-github-packages-registry/working-with-the-npm-registry.md) and click the edit button in the top right bar, you can then scroll down to line 145 and add the missing space between `"registry":"https` there, too. Then commit your change again. 

Hope that is the information you were asking for! 💖

**Comment by heliosalesjr** [comment]
> @heliosalesjr No prob! If you go to your file [here](https://github.com/heliosalesjr/docs/blob/patch-1/content/packages/working-with-a-github-packages-registry/working-with-the-npm-registry.md) and click the edit button in the top right bar, you can then scroll down to line 145 and add the missing space between `"registry":"https` there, too. Then commit your change again.
> 
> Hope that is the information you were asking for! 💖

Thank you so much for your help! I think it's done now! :-)

**Comment by cmwilson21** [comment]
@heliosalesjr You're welcome! Thanks for providing this fix. I'll get this merged down once all the checks are passing ✅

**Review by cmwilson21 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
