### PR TITLE
Update electron hyperlink

### PR DESCRIPTION
**Pull request by devcutler**
## Why:

Previous URL may have been 'https://electronjs.org/docs' but currently returns 404, intended page is now at 'https://electronjs.org/docs/latest'. This PR updates that hyperlink to the correct URL.

Former URL:
```
https://electronjs.org/docs
```
Current URL leading to the documentation for the latest version:
```
https://electronjs.org/docs/latest
```

### CODE REVIEW

**Comment by arynthernium** [comment]
Updated tests and translated pages to match, updating tests is disallowed so commit isn't passing checks.

**Comment by heiskr** [comment]
If you reset the translations changes; the test change should work just fine. Our translation pipeline is a separate process, and currently any changes to translations get overwritten when the pipeline runs each day.

**Comment by heiskr** [comment]
Change looks great! I don't know if locally you're able to run `npm ci && npm run prettier` but that should be all that's needed to merge :) Thanks!

**Comment by cmwilson21** [comment]
@arynthernium 👋 Just checking in here. Have you had a chance to apply the changes in the [comment above](https://github.com/github/docs/pull/22098#issuecomment-1320443661)?

**Comment by cmwilson21** [comment]
@arynthernium No problem at all! Thanks for making the update. There's several of our team out this week, but it'll be reviewed soon. ⚡ 

Thanks for your help in the upkeep for the docs! 💖

**Review by peterbe — APPROVED** [review]

**Comment by aless864** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by Aqeebrao** [comment]
#22945

**Comment by AAmrullah** [comment]
arynthernium:patch-1

**Pull request merged**
