### PR TITLE
remove unneeded quotes

### PR DESCRIPTION
**Pull request by remyleone**
### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@remyleone 
Thanks for opening a PR :+1: Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

**Comment by remyleone** [comment]
done

**Comment by ramyaparimi** [comment]
@remyleone 
Thanks so much for filling out the PR template! I'll get this triaged for review :zap:

**Comment by lee-dohm** [comment]
@remyleone Thanks again for your submission!

In the future, please fill out the _entire_ PR template including the "Why" and "What's being changed" sections. This gives us valuable insight into the motivation behind the change which helps us get everyone's submissions reviewed and handled more quickly.

While it is not currently listed in the Style Guide, there is a reason for the double quotes around each of the links in this page (and many, many other pages besides). Double quotes signify that it is an internal link, as opposed to a link to a resource on another site. Since each of the links you modified here are internal links, they should remain double quoted. Because of this, I'm closing the PR.

Thanks again for your passion and interest in improving the GitHub Docs!

**Comment by remyleone** [comment]
It was absolutely not obvious to me that having double quotes meant internal links. I haven't seen that anywhere else.

**Pull request closed without merging**
