### PR TITLE
Update aws-actions/configure-aws-credentials version

### LINKED ISSUE #24520: Update aws-actions/configure-aws-credentials version to v2
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#requesting-the-access-token

### What part(s) of the article would you like to see updated?

Update GitHub action snippet to use `aws-actions/configure-aws-credentials@v2` instead of `aws-actions/configure-aws-credentials@v1`

### Additional information

I opened a PR for this, but it's on a page, that doesn't allow contributions:
https://github.com/github/docs/pull/24518

### PR DESCRIPTION
**Pull request by matthiasgubler**
Use v2 instead of v1

### Why:

The action suggests to use the latests version `v2`: https://github.com/aws-actions/configure-aws-credentials#recent-updates

Closes: #24520

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by matthiasgubler** [comment]
Hi @cmwilson21 
I had to create a new PR because I deleted my branch and fork and, therefore couldn't reopen it.

**Comment by cmwilson21** [comment]
@matthiasgubler thanks for submitting another PR! I'll get this triaged for review ⚡

**Comment by mchammer01** [comment]
@matthiasgubler 👋🏻 - thanks for improving our docs ✨ 
Unfortunately, it appears that you are modifying a file for which we don't accept external contributions (see the [bottom item in the list](https://github.com/github/docs/pull/24555#issuecomment-1476812226) of the message from the bot: `content/actions/deployment/security-hardening-your-deployments/**`).
I will discuss this with the GitHub Actions team and we may have to make these updates manually as there is at least another article impacted by this change.
I'll keep you updated. Thanks for your patience.

**Comment by jc-clark** [comment]
Thanks for the lookout @matthiasgubler! ✨

We have made the changes internally and [the article](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#requesting-the-access-token) is up to date in production.

**Comment by matteocontrini** [comment]
@jc-clark the article is outdated again and the action version should be changed to v3. v2 currently produces a deprecation warning of the underlying AWS SDK. Thanks!

**Comment by matteocontrini** [comment]
Well, since Node.js 16 is now EOL, the action should be now upgraded to v4.

**Pull request closed without merging**
