### PR TITLE
Update hello-world.md

### PR DESCRIPTION
**Pull request by nkimson1**
changed . to , after "Reviewers"

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by nkimson1 — COMMENTED** [review]
changed "." to ","

**Comment by cmwilson21** [comment]
@nkimson1 Thanks so much for submitting a PR! Great catch. I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
LGTM, thanks for fixing the typo ✨

**Comment by Mayurachat2021** [comment]
Hello World. Getting started.
Last updated 2022-10-13.

This tutorial walks you through the steps to set up a Qiskit Runtime service instance, log in to your service instance, and run your first job on a quantum computer.

If you are an administrator who needs to set up Qiskit Runtime for your organization, refer to [Plan Qiskit Runtime for an organization](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-quickstart-org) for instructions to set up a service instance and work with users.

Step 1: Create a service instance

If you already created a Qiskit Runtime service instance or were invited to one by an administrator, skip to the next step. To determine whether you already have access to an instance, check your [IBM Cloud Instances page](https://cloud.ibm.com/quantum/instances). If you have one or more instances shown, you can skip ahead to [Install Qiskit packages](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-get-started#install-packages).

From the [Qiskit Runtime Provisioning page](https://cloud.ibm.com/catalog/services/quantum-computing), choose the appropriate service plan, depending on what you need access to. For more information about these plans, see the [Qiskit Runtime plans](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-plans) topic.

Lite: Free simulators-only plan to help you get started with Qiskit Runtime. Learn to use Qiskit Runtime by following our examples and tutorials for one of the pre-built programs available for running circuits efficiently.
Standard: A pay-as-you-go model for accessing IBM Quantum systems and simulators. Build your own programs and leverage all the benefits of Qiskit Runtime by running on real quantum hardware, while maintaining access to all of the systems available to the Lite plan.
Because this is not a free plan, it is important to understand how to best manage your costs. See [Manage the cost](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-cost) for tips to limit your cost, how to set up spending notifications, and more.

Complete the required information, then click Create.
Step 2: Install or update Qiskit packages

Install or update the following packages in your development environment. They let you create circuits and work with primitive programs with Qiskit Runtime. For detailed instructions, refer to the [Qiskit install and setup topic](https://docs.quantum-computing.ibm.com/start/install). Periodically check the [Qiskit release notes](https://qiskit.org/documentation/release_notes.html) (or rerun these commands) so that you always have the latest version.

# Installs the latest version of the Qiskit meta-package for circuit creation.
pip install qiskit -U

# Installs the latest version of the Qiskit Runtime package, which is needed to interact with the Qiskit Runtime primitives on IBM Cloud.
pip install qiskit-ibm-runtime -U


To authenticate to the service, call QiskitRuntimeService with your IBM Cloud API key and the CRN:

from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(channel="ibm_cloud", token="<IBM Cloud API key>", instance="<IBM Cloud CRN>")

Find your API key. From the [API keys page](https://cloud.ibm.com/iam/apikeys), view or create your API key, then copy it to a secure location so you can use it for authentication.
Find your Cloud Resource Name (CRN). Open the [Instances page](https://cloud.ibm.com/quantum/instances) and click your instance. In the page that opens, click the icon to copy your CRN. Save it in a secure location so you can use it for authentication.
Step 4: Optionally save your credentials to disk

Optionally save your credentials to disk (in the $HOME/.qiskit/qiskit-ibm.json file). If you don't save your credentials to disk, you must specify your credentials every time you start a new session.

If you save your credentials to disk, you can use QiskitRuntimeService() in the future to initialize your account.

from qiskit_ibm_runtime import QiskitRuntimeService

# Save account to disk.
QiskitRuntimeService.save_account(channel="ibm_cloud", token="<IBM Cloud API key>", instance="<IBM Cloud CRN>", name="account-name")

# Load the saved credentials 
service = QiskitRuntimeService(name="account-name")

If you need to update your saved credentials, run save_account again, passing in overwrite=True and the updated credentials. For more information about managing your account, see the [account management topic](https://docs.quantum-computing.ibm.com/run/account-management).

For instructions to use the cloud Quantum Qiskit API, see the [authentication](https://cloud.ibm.com/apidocs/quantum-computing#authentication) section in the API documentation.

Test your setup

Run a simple circuit using Sampler to ensure that your environment is set up properly:

from qiskit.test.reference_circuits import ReferenceCircuits
    from qiskit_ibm_runtime import QiskitRuntimeService, Sampler

    job = Sampler("ibmq_qasm_simulator").run(ReferenceCircuits.bell())

    print(f"job id: {job.job_id()}")
    result = job.result()
    print(result)

Step 5: Run a program

Qiskit Runtime uses [primitive programs](https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-overview#primitive-programs) to interface with quantum computers. The following programs are publicly available.

Sampler:
Allows a user to specify a circuit as an input and then generate quasiprobabilities. This enables users to more efficiently evaluate the possibility of multiple relevant data points in the context of destructive interference.
Estimator:
Allows a user to specify a list of circuits and observables and selectively group between the lists to efficiently evaluate expectation values and variances for a given parameter input. It is designed to enable users to efficiently calculate and interpret expectation values of quantum operators that are required for many algorithms.
This example uses the Sampler primitive:

# Prepare the input circuit.
from qiskit import QuantumCircuit

bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
bell.measure_all()

# Execute the circuit
from qiskit_ibm_runtime import Sampler

backend = service.backend("ibmq_qasm_simulator")
sampler = Sampler(backend)
job = sampler.run(circuits=bell)
print(job.result())

**Pull request merged**
