### PR TITLE
Copy (to eventually Rename) typod files

### LINKED ISSUE #30824: Typos in file names in github/docs
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

* content/apps/oauth-apps/maintaining-oauth-apps/troubleshooting-oauth-app-access-token-request-errors.md
* content/copilot/configuring-github-copilot/configuring-github-copilot-in-your-environment.md
* content/copilot/using-github-copilot/getting-started-with-github-copilot.md
 

### What part(s) of the article would you like to see updated?

References to misspelled files (pictures and reusables) should be corrected

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes: #30824

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by jsoref** [comment]
Is the preference to just live with the misspelled assets, to make a copy, or to let a github employee do the fix internally and let docbot copy over the fix later?

**Comment by nguyenalex836** [comment]
@jsoref  Thanks so much for opening a PR! I'll get this triaged for review ✨

> Is the preference to just live with the misspelled assets, to make a copy, or to let a github employee do the fix internally and let docbot copy over the fix later?

Great question - I will need to let the team speak to this during their review 💛

**Review by subatoi — APPROVED** [review]
Edit: see below

**Review by subatoi — CHANGES_REQUESTED** [review]
Ah, in hindsight, it would be prudent to create new files for the assets and reference them correctly, as you've done, and leave the old files intact. Then the bots will take care of cleaning them up. This is because, as noted in the failing test, they might not otherwise appear in translated content correctly.

**Comment by subatoi** [comment]
Thanks for that! The new files are below [the 144 ppi requirement](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#technical-specifications) (I realise that's quite hard to find). 

To reduce frustration on your part, I'll fix this for you by pushing to this branch in the new year, and then we can get this merged 👍

**Review by subatoi — APPROVED** [review]
I didn't realise the two files that are below the PPI requirement are already in place as such, so this'll be tracked separately and I'm happy to merge this now 👍 

Thanks again!

**Pull request merged**
