### PR TITLE
Update apply-to-github-education-as-a-student.md

### LINKED ISSUE #35073: Instruction is out-dated
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/159ac36116fdeb3eaef6c8572861fc8908ae0b1f/content/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-education-for-students/apply-to-github-education-as-a-student.md?plain=1#L48

### What part(s) of the article would you like to see updated?

The Expiration and Renewals section

### Additional information

This instruction is out-dated. There is no longer "Reverify your academic affiliation" in the drop down menu.

### PR DESCRIPTION
**Pull request by Dusch4593**
### Why:

It looks like there was a UI update to the profile menu on the GitHub Education page. In addition to the textual changes, I am also going to include a new screenshot image with the updated menu option.

Closes: https://github.com/github/docs/issues/35073

### Check off the following:

- [ ] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [ ] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [ ] All CI checks are passing.

### CODE REVIEW

**Comment by Dusch4593** [comment]
I created a private Imgur link for the updated screenshot image: https://imgur.com/9sEclaY

**Review by nguyenalex836 — DISMISSED** [review]

**Comment by nguyenalex836** [comment]
@Dusch4593 Thanks so much for opening a PR with this update! I'll update the branch and get this merged once tests are passing 🍏

**Comment by nguyenalex836** [comment]
@Dusch4593 Thank you so much for opening a PR with this update! Changes look perfect 💛 Once the screenshot has been updated, let me know and I'll get this merged!

**Comment by Dusch4593** [comment]
@nguyenalex836 

I'll be able to make that change by tomorrow AM 😌

**Review by nguyenalex836 — APPROVED** [review]

**Pull request merged**
