### PR TITLE
Add info on where posts are published to

### LINKED ISSUE #1933: Difficulty finding a post I just published from my Github Page
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/adding-content-to-your-github-pages-site-using-jekyll

### What part(s) of the article would you like to see updated?

In the step by step instructions to create a post, it would be helpful to describe *where* the post gets published to. I found the publishing URL to be a bit unintuitive.

### Additional information

I opened https://github.com/github/docs/pull/1931 to address this.

### PR DESCRIPTION
**Pull request by szunami**
When following this tutorial, I found it very difficult to actually view the post I just created.

The default behavior is documented here: https://jekyllrb.com/docs/front-matter/#predefined-global-variables

### Why:

When creating my first post, I found it very difficult to view the post on my published site. I imagine this is a pain point for others.

I opened https://github.com/github/docs/issues/1933 to discuss this.

### What's being changed:

This PR adds a reference URL where posts are published to.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@szunami Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by szunami** [comment]
Posting to ward off the stale bot

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by szunami** [comment]
:)

**Comment by szunami** [comment]
(:

**Comment by szunami** [comment]
@janiceilene whoops I missed a loop; I don't think I have the perms to remove the stale label. Can you help me out here? ty

**Review by felicitymay — APPROVED** [review]
Hi @szunami - thank you so much for your patience. It's great to have your contribution as it'll save other users getting stuck at the last part of the instructions.

Your changes look good to me.

**Pull request merged**
