### PR TITLE
Update about-git.md

### PR DESCRIPTION
**Pull request by Archit-Jain-Github**
Updated basic Git commands; added essential commands for daily development workflow.

### Why:
Enhanced Git command documentation to provide a comprehensive reference for daily development tasks, improving clarity and efficiency in version control workflows.

Closes: 
NA

### What's being changed (if available, include any code snippets, screenshots, or gifs):
```git
#### Version Control

- `git --version`: Check the git version

#### Staging Changes

- `git add [file]`: Stage changes of a particular file
- `git add .`: Stage all files

#### Branch Management

- `git branch`: Display the current working branch
- `git branch [branch-name]`: Create a new branch
- `git branch -M [branch-new-name]`: Rename the current branch
- `git branch -b [new-branch-name]`: Create and switch to a new branch
- `git branch -d [branch-name]`: Delete a branch
- `git branch -D [branch-name]`: Delete a branch forcefully
- `git push origin --delete [deleted-branch-name]`: Delete branch from the remote repository

#### Branch Navigation

- `git checkout`: Navigate between branches
- `git checkout [branch-name]`: Switch to a specific branch

#### File and Directory Management

- `git clean`: Remove untracked files from the working directory

#### Repository Cloning

- `git clone`: Create a copy of an existing repository

#### Committing Changes

- `git commit`: Commit changes with a detailed message
- `git commit -m "message"`: Commit changes with a brief message
- `git commit --amend`: Modify the recent commit

#### Viewing Changes

- `git show [commit]`: Output metadata and content changes of a specific commit

#### Configuration Settings

- `git config`: Set configuration options for your git installation
- `git config --global user.name "[name]"`: Set your name for commit transactions
- `git config --global user.email "[email-address]"`: Set your email for commit transactions
- `git config --global color.ui auto`: Enable helpful colorization of command line output
- `git config --list`: Check user config details

#### Retrieving Changes

- `git fetch`: Retrieve changes from the remote repository without merging

#### Repository Initialization

- `git init`: Turn an existing directory into a git repository
- `git branch -M main`: Rename the current branch to main (after initializing)

#### Viewing Revision History

- `git log`: Explore previous revisions of the project
- `git log --follow [file]`: List version history for a file, including renames

#### Merging Changes

- `git merge`: Integrate changes in divergent branches
- `git merge [branch]`: Combine the specified branch’s history into the current branch

#### Pulling Changes

- `git pull`: Download and merge changes from the remote repository
- `git pull origin main`: Pull changes from the remote main branch
- `git pull origin [branch-name]`: Pull changes from a specific remote branch

#### Pushing Changes

- `git push`: Push changes to the remote repository
- `git push origin main`: Push changes to the remote main branch
- `git push origin [branch-name]`: Push changes to a specific remote branch
- `git push -u origin main`: Push changes to the upstream, for seamless future pushes

#### Comparing Changes

- `git diff [branch-name]`: Compare the current branch with a specific branch
- `git diff [first-branch]...[second-branch]`: Show content difference between two branches

#### Rebasing Changes

- `git rebase`: Incorporate changes from one branch onto another
- `git rebase -i`: Interactive rebasing session

#### Reference Log

- `git reflog`: Display a history of reference updates, providing a safety net to recover lost commits or branches

#### Remote Repository

- `git remote`: Administer remote connections
- `git remote add origin [link]`: Transfer origin from the local system to a remote repository
- `git remote -v`: Verify remote git

#### Undoing Changes

- `git reset`: Undo changes to files in the working directory
- `git reset [filename]`: Undo changes to a particular file
- `git reset HEAD~1`: Undo a single commit and remove the current change
- `git reset [hash]`: Move multiple commits back
- `git reset --hard [hash]`: Move multiple commits back (in the code editor)

#### Status

- `git status`: Display the state of the working directory and the staged snapshot

#### Reverting Changes

- `git revert`: Create a new commit that undoes changes from a previous commit without removing any data
- `git status`: Display the state of the working directory and the staged snapshot

```

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@Archit-Jain-Github Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by Archit-Jain-Github** [comment]
> @Archit-Jain-Github Thanks so much for opening a PR! I'll get this triaged for review ✨

Thanks!!

**Comment by am-stead** [comment]
hi @Archit-Jain-Github, 

Thanks so much for this submission, and for taking the time to write this up in detail.💛

The proposal contains a brilliantly structured and detailed overview of useful Git commands, but I'm afraid, in this case, we won't be accepting the proposed change.  

The general aim of the existing article is to introduce just a few of the most common and basic Git commands, linking out to more comprehensive content at the bottom of the page.

Finding the right balance for this content is difficult, but since Git is well documented in so many places online, we didn’t think it would be appropriate to document this too thoroughly in our own content.

Thank you again for contributing to our docs.💛 It may help in future to first open an issue for this kind of proposed change, so that we can provide any feedback in advance, but in any case thank you again for your submission and do please also feel free to take a look at our "[Help wanted](https://github.com/github/docs/labels/help%20wanted)" board!✨

**Pull request closed without merging**
