### PR TITLE
Add creating a branch as contribution count

### PR DESCRIPTION
**Pull request by lambdakilo**
### Why:

'What counts as a contribution' list is missing one activity type: creating a branch. Here's a reference of the Discussion: https://github.com/github/docs/discussions/24985#discussioncomment-5645578

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Before:
image
After:
image

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by PieniiSienii — COMMENTED** [review]
Looks perfect!!!

**Review by PieniiSienii — COMMENTED** [review]
Amazing!!

**Comment by cmwilson21** [comment]
@akirataguchi115 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for updating the docs with what you learned! We'll get this merged for you.

**Pull request merged**
