### PR TITLE
doc: include a tip on how to get your Github ID

### PR DESCRIPTION
**Pull request by CodeLeom**
### Why:
The existing content tells the reader the `GitHub no-reply` email format but did not tell the readers how to get their `Github ID`. My PR added a tip on how the reader can get their `Github ID` and be able to formulate their `no-reply` email as explained in the content.

Closes: 
N/A

### What's being changed (if available, include any code snippets, screenshots, or gifs):
I included the tip, immediately after the `Note`.

Note

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@CodeLeom Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by abdolla4** [comment]
چرا ادغام مسدودشده است

**Comment by abdolla4** [comment]
Screenshot_۲۰۲۴-۱۰-۰۳-۱۹-۰۹-۲۲-۰۲۷_com facebook katana
سلام ممنون ازشما عزیزان من نمیتونم دارایی‌های خود رابه کیف تراس والت هدایت کنم ممنون میشم کمکم کنید

**Comment by subatoi** [comment]
@CodeLeom 👋 Thanks for raising this—I don't necessarily think this is a bad addition, but it's hard to know how many people this would actually help. This is one of the reasons we ask contributors to raise issues before going ahead and raising PRs—that way everyone, and most importantly you as the contributor, has a better experience. In this case, it would have allowed us to establish beforehand whether this change is worth making. Since not everybody will use the API and it's far easier to get the ID in this context by navigating to https://github.com/settings/emails, as the documentation notes, I'm going to close this out. Don't be discouraged from looking at our issues marked `help wanted` and thank you for your interest in the GitHub Docs

**Pull request closed without merging**
