### PR TITLE
Guide to use branches instead of tags for serviceable releases

### PR DESCRIPTION
**Pull request by AArnott**
Git tags are not safe to redefine. An existing git clone *does not download tags that are already known* because git assumes that *tags will never be redefined*. 
As it stood, this doc sounded like it advocated *moving tags*, which can cause lots of confusion in a team with many git clones.
With this change, I revise the use of tag/branch terms to make it clear that branches should move and tags should remain static.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@AArnott Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by AArnott** [comment]
@janiceilene How long before triage looks at this?

**Comment by peterchyke** [comment]
What's new?Sent from my Galaxy
-------- Original message --------From: Andrew Arnott <notifications@github.com> Date: 27/11/20  06:00  (GMT-11:00) To: github/docs <docs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [github/docs] Guide to use branches instead of tags for serviceable releases (#1413) 
@janiceilene How long before triage looks at this?

**Comment by janiceilene** [comment]
@AArnott It's triaged and waiting for the team. Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by AArnott** [comment]
Thanks, @janiceilene. I got nervous when the bot threatened to close the issue.

**Comment by martin389** [comment]
👋 Thank you for this contribution! I'm just checking these proposed changes with our support folks.

**Comment by AArnott** [comment]
Thanks, @martin389. One question/concern I have is whether the GitHub Marketplace will list *branches* as "versions" that can be selected the way it does for tags. If it doesn't, that seems like a hole to fill.

**Comment by martin389** [comment]
Clearing `stale` status. :hourglass_flowing_sand:

**Comment by martin389** [comment]
Status update: Checking with reviewers ❤️

**Comment by martin389** [comment]
Status update: Followed up with reviewers

**Comment by martin389** [comment]
Following up on this 👍

**Comment by martin389** [comment]
Clearing stale status. ⏳

**Comment by martin389** [comment]
Clearing stale status. ⏳

**Comment by martin389** [comment]
Following up on this review 👀

**Comment by janiceilene** [comment]
👋 @AArnott The devs and product management have gotten back to us, and they would like to keep the existing guidance in place for now, since they are currently looking at additional options on how to improve things in this space. 

So sorry that we aren’t able to merge this PR, we really appreciate your interest in helping improve the Actions docs! 💛

**Pull request closed without merging**
