### PR TITLE
Remove duplicated line on self-hosted-runners

### LINKED ISSUE #16443: Duplicated lines on about-self-hosted-runners
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

### What part(s) of the article would you like to see updated?

> Your [runner](https://github.com/actions/runner) machine connects to GitHub using the GitHub Actions self-hosted runner application. The GitHub Actions runner application is open source. You can contribute and file issues in the runner repository. When a new version is released, the runner application automatically updates itself when a job is assigned to the runner, or within a week of release if the runner hasn't been assigned any jobs.

Above lines appear twice.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uny**
### Why:

Closes https://github.com/github/docs/issues/16443

### What's being changed:

It seems that [this line](https://github.com/github/docs/blame/main/content/actions/hosting-your-own-runners/about-self-hosted-runners.md#L24) was added later.
So I remove this line.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@uny 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Cryptobinarytradeoptionx — COMMENTED** [review]
Thanks

**Comment by pjlogan39** [comment]
> ### Why:
> 
> #16443
> ### What's being changed:
> 
> It seems that [this line](https://github.com/github/docs/blame/main/content/actions/hosting-your-own-runners/about-self-hosted-runners.md#L24) was added later. So I remove this line.
> ### Check off the following:
> 
>     * [x]  I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> 
>     * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> 
> ### Writer impact (This section is for GitHub staff members only):
> 
>     * [ ]  This pull request impacts the contribution experience
>       
>       * [ ]  I have added the 'writer impact' label
>       * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

No

**Review by martin389 — COMMENTED** [review]
Thanks for noticing this! Fix looks good in local staging.

**Review by martin389 — APPROVED** [review]

**Comment by arslan-raza-143** [comment]
@ramyaparimi

**Pull request merged**
