### PR TITLE
pull_request_target: clarify avoid

### LINKED ISSUE #26535: pull_request_target avoid clarification
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

Clarify `pull_request_target` avoid:

> Avoid using this event if you need to build or run code from the pull request.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kevingentile**
### Why:
The phasing here is ambiguous. The underlying "code" _can_ be modified (ex. `actions/checkout@v3` checking out the PR's head ref). However any workflow changes will not execute from a PR until they land on the target branch. 

Closes: #26535

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Documentation on `pull_request_target` event.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@kevingentile Thanks for submitting a PR with your issue! I've edited your post slightly to [link your PR to your issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). 👍 

I'll get this triaged for review! :zap:

**Comment by Chrislann1974** [comment]
Ju

**Comment by SiaraMist** [comment]
Hey @kevingentile, thank you so much for opening this PR to update the docs! ⚡ 

I was hoping you could provide some further clarification on the changes you are making? As far as I understand, the line you are updating advises people not to use `pull-request-target` as a trigger with an explicit PR checkout because it could be a security risk, as [this Security Lab article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) explains much better than I can. The warning in the red box a little further down on the page you updated also describes this further. Please let me know if I'm misunderstanding your update, and we can work together to make this section more clear.

Thanks again for contributing to the docs! ✨

**Comment by kevingentile** [comment]
Hi @SiaraMist, thank you for reaching out for clarification.

There has been much confusion on my end over the years regarding secure usage of `pull_request_target` vs `pull_request` events. After re-reading the security document you linked I'm motivated to close this issue with no action.

My suggestions were motivated by a need to access secrets during the build phase which would not be widely applicable for users interacting with public repos or forks as the secret(s) would be necessary for local builds and thus no longer secret.

As an aside, a consequence of the recommended approach is any auto-generated dependabot PRs will always fail to execute a build workflow if a secret is required as part of a build (ex. GITHUB_TOKEN for registry access to dependencies). This is likely the intended behavior but a minor annoyance as my current workaround is to push an empty commit to each dependabot PR to trigger a privileged workflow.

**Comment by SiaraMist** [comment]
Hey @kevingentile, thank you for explaining your thought process! 💛 Based on what you said and how I read this, I'm going to just close out this PR. For the odd Dependabot behavior you are seeing, you may want to leave feedback in the [GitHub Community](https://github.com/orgs/community/discussions). Thanks again for contributing to the docs!

**Pull request closed without merging**
