### PR TITLE
Removed broken/low quality/dead/archived PHP libraries

### PR DESCRIPTION
**Pull request by GrahamCampbell**
### Why:

The list of packages here should be a list of decent quality packages that are compatible with the latest version of PHP. I've removed those that are not that, either because they don't work on PHP 7.4/8.0 (or any version anymore!) and/or are poor quality and/or have been marked as archived some years ago with no direct replacement.

### What's being changed:

The list of recommended community PHP GitHub API clients.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by SickZauer — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by GrahamCampbell** [comment]
@janiceilene Whoops, sorry about that! I've updated the OP for you. :)

**Comment by janiceilene** [comment]
Thanks so much for filling that out @GrahamCampbell 💖 I've triaged this for review ✨

**Review by lecoursen — APPROVED** [review]
Thanks so much for cleaning this up! I'll merge now. ⚡

**Pull request merged**
