### PR TITLE
Update workflow-commands-for-github-actions.md

### LINKED ISSUE #21529: Clarify how multiline output values can be set via `GITHUB_OUTPUT`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

### What part(s) of the article would you like to see updated?

Due to recent changes, I had to switch our codeflows from using `set-output` to the method described in the section on "Setting an output parameter", by appending to (the file with the name in the variable) `$GITHUB_OUTPUT`.

This is very similar to how `$GITHUB_ENV` works in the previous section.

I had need to post a multiline output, and so decided to just try the technique described for "Environment files" (the preceding section). That is, I used the pattern
```
{name}<<{delimiter}
{value}
{delimiter}
```
and ended up with code looking like this:
```yaml
steps:
  - name: Set the output in bash
    id: step_one
    run: |
      echo 'JSON_RESPONSE<<EOF' >> $GITHUB_OUTPUT
      curl https://example.lab >> $GITHUB_OUTPUT
      echo 'EOF' >> $GITHUB_OUTPUT
```

And as far as I can tell, this worked great (and is much simpler than what I had to do before).

I think it would be beneficial if this possibility was pointed out by the documentation. Simply saying something akin to "multi-line output values can be set with the same technique used in the previous section to define multi-line environment variables" would already help a lot.

### Additional information

_No response_

---
edited by maintainer

### Content plan [here](https://github.com/github/docs/issues/21529#issuecomment-1289693089)

### PR DESCRIPTION
**Pull request by ujjwal-shekhar**
### Why:

Closes #21529

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Added a `Note` at the end of the `Multiline Strings` section that clarifies it's use cases.

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by ujjwal-shekhar** [comment]
> @ujjwal-shekhar Thanks so much for opening a PR! I edited your post slightly to [link it to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). 🔗
> 
> I'll get this triaged for review ⚡

**Comment by ujjwal-shekhar** [comment]
The repo seems to be frozen, could you look in it. :)

**Comment by cmwilson21** [comment]
@ujjwal-shekhar We had a freeze while we merged some larger files. It's thawed now. Your PR is waiting for review. A writer will take a look at it soon 👀

**Comment by cmwilson21** [comment]
👋 @ujjwal-shekhar - After checking into this a bit further, could you update the PR to reflect the [comment here](https://github.com/github/docs/issues/21529#issuecomment-1289693089)? Meaning, add a link to the [setting an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) section, pointing people to the [multi-line strings section](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings) section. 

Check out our style guide's section on [links](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links) for additional information.

We really appreciate your interest in improving the docs! 💖

**Comment by cmwilson21** [comment]
@ujjwal-shekhar 👋 Checking in again, are you able to make the requested changes in the comment above? 💖

**Comment by lecoursen** [comment]
I'm going to close this PR for now. If you decide to update it as described by @cmwilson21 in https://github.com/github/docs/pull/21599#issuecomment-1292564504, feel free to reopen!

**Pull request closed without merging**
