### PR TITLE
chore: non-content typo cleanup

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

Typo fixes from #733 that were split out because they require engineering review rather than content reviews.

### What's being changed:

- Various typo fixes
- Probably product changes required upstream for the changes in `data/graphql/` rather than in this PR that might need to be rebased out

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by runleonarun** [comment]
Hey @nschonni I meant to call out previously that the `/lib/graphql` and `/data/graphql/` content is autogenerated from other code so these change will be overwritten. Can you remove changes to those directories?

The rest looks great to me but I'm sure Engineering will want to approve it.

**Comment by nschonni** [comment]
@runleonarun yup, I self commented on the last PR around this one myself https://github.com/github/docs/pull/733#discussion_r512247341 😄 
I just left them in here so the right folks can create the internal bugs to they're addressed in the upstream code

**Review by heiskr — APPROVED** [review]
I think this looks great. Even if it does cause a merge conflict with some automated tooling, I think these are actually the kinds of conflicts we want lol.

**Comment by chiedo** [comment]
@rachmari could you give this a final review and merge if you think it's good.

Specifically, this file `lib/graphql/static/prerendered-objects.json`

**Comment by chiedo** [comment]
@nschonni thanks for catching these! These are generated via automation so we’ve taken note of these typos and are going to fix them upstream. Closing this PR and when we fix the issues upstream they’ll be fixed in the repo!

**Comment by nschonni** [comment]
@chiedo not all of these are from generated content

**Pull request closed without merging**
