### PR TITLE
Tweaks for managing disruptive comments

### LINKED ISSUE #16446: Managing disruptive comments is overly prescriptive
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md

### What part(s) of the article would you like to see updated?

This content:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L53

... feels more like instructions for how a specific project should operate, as opposed to the world at large. If it's the world at large, then it should be integrated into the tooling.

This should really have its own anchor, for `redacting` information:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L59

https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L64-L65

The content should also include a note that it's merely a suggestion.

https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L80

It's a bit late in the chronology to make this suggestion. I'd suggest it precede the information about deleting a comment (i.e. before `Deleting a comment is your last resort as a moderator.`). But, I want to be careful to not be too prescriptive (the current content suffers from this...).

There should be an anchor for the steps:
https://github.com/github/docs/blob/ed48eab88d1cbbe2a99aa02885140155029910d1/content/communities/moderating-comments-and-conversations/managing-disruptive-comments.md?plain=1#L88

### Additional information

Fwiw, while this information is interesting, it is definitely not complete.

I found this page because I was researching a behavior I noticed today which does not appear to be documented.

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes #16446

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by hubwriter** [comment]
I've reached out to our Communities folks for a review of this.

**Review by robertnopickle — APPROVED** [review]
Looks good and makes sense to me ❤️  👍🏻  👍🏻

**Comment by hubwriter** [comment]
@jsoref - Many thanks for making this improvement to the docs.

I'll get this merged/published now.
🚀

**Review by hubwriter — APPROVED** [review]

**Pull request merged**
