### PR TITLE
Add Octocrab to third party libraries

### PR DESCRIPTION
**Pull request by XAMPPRocky**
### Why:

Developers writing their GitHub integrations in Rust, might be interested in using the octocrab library.

### What's being changed:

Adds the octocrab library to list of third party libraries.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Matthew123465 — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by XAMPPRocky** [comment]
I'm not sure how this would be stale on my end when it's pending review.

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by XAMPPRocky** [comment]
@janiceilene I understand that, however it's pretty bad experience as a contributor to get a comment that a PR will be closed where's there's nothing I can do other than comment on it, it's generated unneeded noise for both contributors and the team. It would be nice if there was a label such as `waiting on review` that disabled the stale bot for PRs with that label while team works through their backlog.

**Comment by janiceilene** [comment]
I appreciate that perspective and that's a great suggestion! I'll bring that up with the team.

**Comment by XAMPPRocky** [comment]
:)

**Review by skedwards88 — APPROVED** [review]
🚀 Thanks for making this addition! I'll get this merged down for you.

**Pull request merged**
