### PR TITLE
Removes the mention of "internal repositories" in GitHub actions docs for FPT customers

### LINKED ISSUE #33225: [Improvement]: Actions article mentions internal repos in the FPT version of the docs
### Is this issue for a product update or release that is not yet available to customers?

No? Then please continue. Thank you!

### Describe the desired documentation updates and the problem they solve for customers.

This article mentions internal repos in the FPT version of the docs:

"[Sharing actions and workflows with your organization](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization)"

Apply versioning to avoid this.

### Which existing articles, if any, are affected?

"[Sharing actions and workflows with your organization](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization)"

### Who does this affect?

FPT customers

### What is the user or business need for these changes?

It's confusing for customers on Free/Pro/Team plans to see references to internal repos when they don't have such things.

### We welcome contributions, are you able to help?

Anyone can raise a PR to fix this

### PR DESCRIPTION
**Pull request by Haimantika**
### Why:

Closes: https://github.com/github/docs/issues/33225

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removes the mention of `internal repositories` in [Sharing actions and workflows with your organization](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization) docs for FPT customers.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by Haimantika** [comment]
> @Haimantika Thank you so much for opening this PR! ✨
> 
> I looked at the preview environmment, and it looks like there is an issue with some of the text rendering. Just wanted to let you know in case you'd like to fix this yourself - but if you need any assistance, please let us know! 💛
> 
> image

My guess - it is because of the {%endif%} liquid tag. Have pushed a change, hope the resolves.

**Comment by Haimantika** [comment]
The issue is solved, but we also need to change the wording in `Warning` not sure how to do that 👀

**Comment by nguyenalex836** [comment]
> The issue is solved, but we also need to change the wording in `Warning` not sure how to do that 👀

@Haimantika That's awesome - glad that liquid tag issue is fixed! ✨ I've linked the location for the content in that warning below 💛 

image

- https://github.com/github/docs/blob/main/data/reusables/actions/outside-collaborators-actions.md
- https://github.com/github/docs/blob/main/data/reusables/actions/scoped-token-note.md

Happy to provide any assistance if needed - just let me know! ✨

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@Haimantika Thanks so much for taking care of these fixes! I'll update the branch and get this merged once tests are passing 🍏

**Pull request merged**
