### PR TITLE
Update example to use "actions/setup-node@v2"

### PR DESCRIPTION
**Pull request by erikvold**
### Why:

Using the newer `actions/setup-node@v2`

To match https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

### What's being changed:

Code in a example to use `actions/setup-node@v2` instead of `actions/setup-node@v1`

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@erikvold Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by lecoursen — APPROVED** [review]
Thanks! This looks good so I'll merge now. ⚡

**Comment by lecoursen** [comment]
Actually @erikvold, I'm not able to merge because your branch is out of date with main, and I can't update your branch. Can you please select the "Allow edits from maintainers" checkbox in the right sidebar? Thanks!

**Comment by erikvold** [comment]
@lecoursen ok, done.

**Pull request merged**
