### PR TITLE
Adds missing `{% raw %}` tags to caching page

### LINKED ISSUE #22864: Missing `{% raw %}` tags on caching page
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

### What part(s) of the article would you like to see updated?

markdown is rendered incorrectly due to missing raw tags - in particular, GitHub Action expressions are not rendered: instead of `${{ ... }}` there's only `$` displayed in the last example on that page - likely because LiquidJS templating engine thinks those are output tags that it can't parse.

### Additional information

PR to follow

### PR DESCRIPTION
**Pull request by anno1985**
### Why:

Closes https://github.com/github/docs/issues/22864

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Adds missing `{% raw %}` and `{% endraw %}` tags around three places with rendering issues in the last example on the caching page.

These tags are currently missing, apparently causing the LiquidJS templating engine to attempt to parse GitHub Action expressions from that example and to render them as output. As the expressions aren't LiquidJS output tags, parsing fails, and nothing is rendered.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] ~~For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).~~ **N/A: added tags only**

### CODE REVIEW

**Comment by anno1985** [comment]
Unfortunately, the example is actually re-using a code snippet that is embedded via LiquidJS tags, so disabling them wholesale is not the solution.

**Comment by anno1985** [comment]
Looks good to me; however, the section in question (which uses https://github.com/actions/gh-actions-cache/) shows up for ghes 3.7, when it probably shouldn't:

> Note: This extension currently supports github.com only, GitHub Enterprise Server is not supported currently.

However, that seems to be an unrelated issue with a variable used in an `ifversion` tag on lines 317/366:
```
{% ifversion actions-cache-list-delete-apis %}
```

**Comment by cmwilson21** [comment]
@anno1985 Thank you for opening a PR and linking it to your issue! ✨ 

We appreciate all the info provided. 💖 I'll get this triaged for review ⚡

We appreciate your patience during the holiday season 💖

**Comment by SiaraMist** [comment]
Hey @anno1985, thank you so much for opening this PR! Your updates look great. I'll go ahead and get this merged. 🚀

**Review by SiaraMist — APPROVED** [review]

**Pull request merged**
