### PR TITLE
rest: Fix broken shell commands for REST Auth examples

### PR DESCRIPTION
**Pull request by 5HT2**
### Why:

See: #24920 (fixes some of the problems mentioned here)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Lack of `\` in shell command after some commands.
### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by skedwards88 — APPROVED** [review]
Thanks for fixing this! We'll get this merged down for you.

**Comment by cmwilson21** [comment]
@5HT2 - Looks like there are some conflicts on this branch. Can you ping me after they've been resolved? We can get this merged then 💖

**Comment by 5HT2** [comment]
@cmwilson21 should be good to go?

**Comment by cmwilson21** [comment]
@5HT2 perfect! Thanks for the update and the ping. Will get this merged! ✨ 

If you'd like to contribute another PR, please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Pull request merged**
