### PR TITLE
Minor spelling corrections

### PR DESCRIPTION
**Pull request by lucalves**
### Why:

Just fixes minor misspellings.

### What's being changed:

Wrong words.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by dreamer820 — COMMENTED** [review]
not sure if it was what was truly sent since these mac codes and dirty IPs don't add up right.

**Comment by lucalves** [comment]
> not sure if it was what was truly sent since these mac codes and dirty IPs don't add up right.

Sorry, I really don't understand what you tried to say.

**Review by flawhoodlum1 — APPROVED** [review]

**Review by flawhoodlum1 — APPROVED** [review]

**Comment by flawhoodlum1** [comment]
Approved

**Review by flawhoodlum1 — APPROVED** [review]

**Review by Ray-hu — APPROVED** [review]
#content/developers/github-marketplace/viewing-transactions-for-your-listing.mdB-)

**Review by SMAKSS — APPROVED** [review]

**Comment by janiceilene** [comment]
@lucalves Thank you so much for opening a PR to fix these typos! I can't believe we had "automagically" in the docs 😆 I'll get the branch updated and merge it once tests are passing 🍏

**Review by janiceilene — APPROVED** [review]

**Pull request merged**
