### PR TITLE
chore: Remove locales from docs.microsoft.com urls

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

Microsoft links automatically direct to the users locale when it is removed from the URLs. This is also done for the docs.microsoft.com content in order to improve localization of content. There were changes to the translated content in the cleanup, but it wasn't committed here, so it would flow through the regular translation flow.

### What's being changed:

Ran the cleanup from https://github.com/microsoft/vscode-docs-authoring/ to strip locales from MS urls

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — APPROVED** [review]
Well, I tried this with some different languages by changing the browser language and it is working as expected.

**Review by heiskr — APPROVED** [review]
Awesome, nice catch

**Comment by janiceilene** [comment]
Thanks @nschonni! I'll triage this for a content review, as well.

**Review by rachmari — APPROVED** [review]
@nschonni thank you! This looks great! I'll get this merged right away. 🚀

**Pull request merged**
