### PR TITLE
Update and rename content/actions/managing-workflow-runs/approving-wo…

### PR DESCRIPTION
**Pull request by ivan0117**
…rkflow-runs-from-public-forks.md to 內容/行動/管理工作流運行/approving-workflow-runs-from-public-forks.md

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ivan0117 — COMMENTED** [review]
p

**Comment by ivan0117** [comment]
p

**Review by ivan0117 — COMMENTED** [review]
內容/行動/管理工作流運行/approving-workflow-runs-from-public-forks.md

**Comment by ivan0117** [comment]
diff --git a/content/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.md "b/\345\205\247\345\256\271/\350\241\ 214\345\213\225/\347\256\241\347\220\206\345\267\245\344\275\234\346\265\201\351\201\213\350\241 /approving-workflow-runs-from-public-forks.md"
相似指數 97%
從 content/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.md 重命名
重命名為“\345\205\247\345\256\271/\350\241\214\345\213\225/\347\256\241\347\220\206\345\267\245\344\ 275\234\346\265\201\351\201\213\350\241\214/approving-workflow-runs-from-public-forks.md"
索引 28d83bb82f42..e9def281b4e1 100644
--- a/content/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.md
+++ "b/\345\205\247\345\256\271/\350\241\214\345\213\225/\347\256\241\347\220\206\345\267\245 \344\275\234\346\265\201\351\201\213\350\241\214/approving-workflow-runs-from-public-forks.md"
@@ -6,7 +6,7 @@ 版本：
   fpt: '*'
 shortTitle：批准公共分叉運行
 ---
——
+approving-workflow-runs-from-public-forks.md
 ## 關於從公共分叉運行的工作流
 
 {% data reusables.actions.workflow-run-approve-public-fork %} 但是，您可以為 [repository](/github/administering-a-repository/managing-repository-settings/disabling-or-限制-github-actions-for-a-repository#configuring-required-approval-for-workflows-from-public-forks), [organization](/organizations/managing-organization-settings/disabling-or-limiting-github- actions-for-your-organization#configuring-required-approval-for-workflows-from-public-forks) 或 [enterprise](/github/setting-up-and-managing-your-enterprise/setting-policies-for -organizations-in-your-enterprise-account/enforcing-github-actions-policies-in-your-enterprise-account#configuring-required-approval-for-workflows-from-public-forks）。

**Comment by ivan0117** [comment]
$去環境
設置 GO111MODULE=
設置 GOARCH=amd64
設置 GOBIN=
設置 GOCACHE=C:\Users\holmed2\AppData\Local\go-build
設置 GOENV=C:\Users\holmed2\AppData\Roaming\go\env
設置 GOEXE=.exe
設置GOFLAGS=
設置 GOHOSTARCH=amd64
設置 GOHOSTOS=windows
設置 GOINSECURE=
設置GONOPROXY=
設置 GONOSUMDB=
設置 GOOS=windows
設置 GOPATH=C:\Users\holmed2\go
設置 GOPRIVATE=
設置 GOPROXY=https://proxy.golang.org,direct
設置 GOROOT=C:\Go
設置 GOSUMDB=sum.golang.org
設置 GOTMPDIR=
設置 GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
設置 GCCGO=gccgo
設置 AR=ar
設置 CC=gcc
設置 CXX=g++
設置 CGO_ENABLED=1
設置GOMOD=
設置 CGO_CFLAGS=-g -O2
設置 CGO_CPPFLAGS=
設置 CGO_CXXFLAGS=-g -O2
設置 CGO_FFLAGS=-g -O2
設置 CGO_LDFLAGS=-g -O2
設置 PKG_CONFIG=pkg-config
設置 GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\holmed2\AppData\Local\Temp\go-build226326482=/tmp/ go-build -gno-record-gcc-switches
你做了什麼？
將“C:\Windows\System32\whoami.exe”作為“systeminfo.exe”複製到以下程序的目錄中，然後運行該程序：

包主

進口 （
      “fmt”
      “操作系統”
      “操作系統/執行”
)

功能主（）{
      os.Setenv("PATH", `C:\Windows\System32`)

      cmd := exec.Command("systeminfo.exe")
      出，錯誤：= cmd.CombinedOutput()
      如果錯誤！= nil {
            恐慌（錯誤）
      }
      fmt.Println(string(out))
}
你期待看到什麼？

**Review by RaplotBigdwag — APPROVED** [review]

**Pull request closed without merging**
