### PR TITLE
Fix links to community discussions

### PR DESCRIPTION
**Pull request by nickserv**
### What's being changed (if available, include any code snippets, screenshots, or gifs):

Community discussions have moved. This broke some links, so I fixed them.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by nickmccurdy** [comment]
It seems like the links in feature preview are also broken.

**Comment by cmwilson21** [comment]
@nickmccurdy Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by rsese — DISMISSED** [review]
Thank you!  JS changes look good, I manually tested too and things work as expected with the new URLs 👍

**Comment by nickmccurdy** [comment]
Can someone also please file an issue for internal links like in feature preview, or should I contact support?

**Review by warmachine028 — COMMENTED** [review]
Changes look good to me

**Review by sophietheking — DISMISSED** [review]
Hi @nickmccurdy 👋 thanks for opening this issue and fixing these links. Looks good to me!

I'll get this merged for you. 🚀

**Comment by nickmccurdy** [comment]
I noticed the repository got renamed. I'd like to update the links again before this is merged.

**Comment by cmwilson21** [comment]
@nickmccurdy Great catch on the rename! Thanks for bringing that up. This hasn't been merged yet, so if you want to go in and make those changes, feel free to do so. We would really appreciate it! 💛

**Comment by nickmccurdy** [comment]
Do I need to update the translations too? I noticed they're ignored in VSCode.

**Comment by cmwilson21** [comment]
Unfortunately, we are not able to accept changes for translated content. Our translation process involves an integration with an external service, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we’re not there yet.

See https://github.com/github/docs/blob/main/contributing/types-of-contributions.md#earth_asia-translations.

**Comment by cmwilson21** [comment]
Thank you so much for making these other updates! 💖 

I'll get these merged down once the tests have been completed. 🍏

**Review by cmwilson21 — APPROVED** [review]
LGTM. Thank you for taking the time to update this!

**Comment by nickmccurdy** [comment]
I've noticed some newer docs are linking to https://github.com/orgs/community/discussions. Is there a difference? Should I update these to be more consistent?

**Comment by cmwilson21** [comment]
👋 Hey again @nickmccurdy. I spoke with the team and you are right. There's been several recent changes but the **/orgs** is the correct URL. Another great catch on your end. If you are still up for it, we would appreciate the update.

**Pull request merged**
