### PR TITLE
Update workflow-syntax-for-github-actions.md

### PR DESCRIPTION
**Pull request by RubenGamarrarodriguez-tomtom**
Use a consistent naming, for user defined keys in the workflow examples

### Why:

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

References to user defined keys in yaml

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@RUBenGAMArrarodRiguEZ-ToMtOm Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by jc-clark** [comment]
👋 Hey @RUBenGAMArrarodRiguEZ-ToMtOm! Thanks for helping out here. Can you help us understand these changes a bit more? Where are the names inconsistent? And is there an issue that this PR closes?

**Review by skedwards88 — COMMENTED** [review]
Thanks for this PR! It looks like there are still come cases of underscore instead of dashes (e.g. `my_first_job` instead of `my-first-job`). (You can see the preview of your PR [here](https://docs-31515-3bd47a.preview.ghdocs.com/en/actions/using-workflows/workflow-syntax-for-github-actions).) Since either syntax works and since this PR's goal was to add consistency, we'll leave this PR unmerged pending future changes. Once the changes are made, our maintainer should re-triage this PR for review.

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Hi @jc-clark,
one can see the other examples and code in the page, I am not able to find consistency in the job naming conventions when reading through the page.

Is about consistency and, arguably, readability for user defined keys in the yml snippets of workflow examples in the markdown file.

The changes done is to have all the ids of the jobs with the same naming conventions hypencase. With the changes proposed some the few job names which unexpectedly had underscore casing have not hyphen case. Like the rest.

This are some examples already in the file following a hyphencase convention.
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L103
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L174
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L184
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L184
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L368
1. https://github.com/github/docs/blob/ad9e7061b9b26354f4969653d4679378c7fa804e/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L1096

**Pull request closed without merging**
