### PR TITLE
Fix example for the `toJSON` function

### PR DESCRIPTION
**Pull request by matthieuprat**
### Why

The example of the `toJSON` function is slightly misleading. It can make you think that the `status` value of the `job` context is capitalized while it's actually lowercased.

I think the example should reflect that.

### Checklist

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by onsd101** [comment]
94a9f11628d2f1557abd42cbe5c1fd65faa34652

**Comment by cmwilson21** [comment]
@matthieuprat Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for improving this! We'll get this merged down for you.

**Review by Ed023 — COMMENTED** [review]
Nice

**Pull request merged**
