### PR TITLE
Trim pre- and post-amble in the CC-BY license text

### LINKED ISSUE #275: new LICENSE file incorrect, and would not be detected by github
### What article on docs.github.com is affected?

None

### What part(s) of the article would you like to see updated?

None

### Additional information

Not a problem of displayed content, but of a file in the repo:

The LICENSE file (recently promoted via #204) is an overly-complete paste from Creative Commons.  It includes the preamble (with a bit missing) and afterword, which are intended as instructions to users, and are not part of the license text itself. Lines 1-56 and lines 367-end can (should?) be dropped - search for the ===== delimiters.

In addition, if you select this license, github does not recognize the license when it presents summary information the way it usually does for the project as a whole, and if you click on a LICENSE file (independently tested on a fresh repo since this one is "incorrect" as noded).  That's not an error of the docs repo itself, of course, but at least can make the team aware of it.

### PR DESCRIPTION
**Pull request by jeffmcaffer**
### Why:
The CC-BY license file has extra text that is not intended to be part of the license itself. 
See #275 

closes #275
### What's being changed:

Trim the extraneous text with guidance from the legal team.

### CODE REVIEW

**Comment by jeffmcaffer** [comment]
Need to validate that the new text is properly detected by licensee. Hold off merging until validated.

**Review by zeke — APPROVED** [review]
Looks good. Thanks for working on this 👍🏼

**Comment by jeffmcaffer** [comment]
Turns out that licensee does NOT detect this new text correctly. I chatted briefly with @benbalter and opened https://github.com/licensee/licensee/issues/464. Two choices here:

1. merge this now. The user experience will *likely* be the same in that they should still see View license and should still be guided to the LICENSE file.
2. wait for the licensee fix. 
3. close this as won't fix. The text is not invalid, it's just "overly complete"

I have no preference one way or another.

**Comment by mlinksva** [comment]
The repo UI isn't going to state a specific license regardless of what happens with this PR due to #204 (`LICENSE-CODE` is intelligible to humans, but licensee conservatively sees that and `LICENSE` and doesn't assert anything for the repo overall).

I would not recommend merging this. Most of the text cut is [recognized to be optional](https://spdx.org/licenses/CC-BY-4.0.html), but is in the canonical version [provided by CC](https://creativecommons.org/licenses/by/4.0/legalcode.txt), and in general I'd discourage fiddling with license texts merely to save a few bytes.

**Comment by jeffmcaffer** [comment]
I was intending on proposing some updates to the GitHub UI that would add support for showing multiple licenses. in that case, the licensee output (having found both LICENSE and LICENSE-CODE) could be rendered usefully. The overall outcome is NOASSERTION but there is a list of high confidence licenses that could be rendered.

In any event, since currently licensee does not recognize the trimmed down text, I suggest not merging this. Once licensee does, we can reconsider.

**Pull request closed without merging**
