### PR TITLE
add responsive to footer

### PR DESCRIPTION
**Pull request by Arhell**
### Why:
fix this issue https://github.com/github/docs/issues/1267

### What's being changed:
add responsive to footer

If you have any comments, write
**review page:**
https://docs-1268--fix-footer.herokuapp.com/en
**after fix:**

### CODE REVIEW

**Comment by Arhell** [comment]
cc @janiceilene
cc @heiskr

**Comment by janiceilene** [comment]
@Arhell Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by chiedo** [comment]
@simpsoka this looks good to me! You cool with it?

**Review by simpsoka — APPROVED** [review]
Looks good to me! cc @chiedo

**Review by heiskr — APPROVED** [review]

**Pull request merged**
