### PR TITLE
Added Keeper where LastPass and 1Password are referenced as password …

### LINKED ISSUE #23825: Include Keeper in references to password managers
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/organizations/managing-saml-single-sign-on-for-your-organization/accessing-your-organization-if-your-identity-provider-is-unavailable.md
content/organizations/managing-saml-single-sign-on-for-your-organization/downloading-your-organizations-saml-single-sign-on-recovery-codes.md
content/admin/user-management/managing-users-in-your-enterprise/best-practices-for-user-security.md
content/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication-recovery-methods.md
content/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication.md
content/authentication/keeping-your-account-and-data-secure/updating-your-github-access-credentials.md
content/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token.md
content/authentication/keeping-your-account-and-data-secure/creating-a-strong-password.md
content/rest/quickstart.md
content/rest/quickstart.md
content/rest/guides/getting-started-with-the-rest-api.md
content/rest/guides/getting-started-with-the-rest-api.md
content/rest/guides/scripting-with-the-rest-api-and-javascript.md
content/rest/overview/other-authentication-methods.md

### What part(s) of the article would you like to see updated?

Include link to Keeper (https://keepersecurity.com) when 1Password or LastPass is mentioned

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by craiglurey**
…managers and secret managers. Keeper is a secure enterprise password management platform with millions of users and thousands of enterprise customers. Keeper is SOC2 Certified, FedRAMP Authorized, audited by 3rd party penetration testers and maintains a public vulnerability disclosure program. Keeper's APIs and SDKs are open source published on Github at https://github.com/Keeper-Security/

Closes https://github.com/github/docs/issues/23825

### Why:

Keeper is an enterprise password management platform which is SOC2 Certified, FedRAMP Authorized, audited by 3rd party penetration testers and maintains a public vulnerability disclosure program. Since 1Password and LastPass are mentioned, we would like to make sure that we're also included.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added reference to Keeper where 1Password and LastPass are mentioned as a password manager or TOTP device.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@craiglurey Thanks for submitting a PR with your issue! I've edited it slightly so it links to your issues 👍 

I'll get this triaged for review! :zap:

**Comment by cmwilson21** [comment]
@craiglurey Thanks again for the PR ✨ 

After chatting with the team, we are not going to accept this change at this time. 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by craigdemo** [comment]
Are you going to remove all 3rd party references then?

**Comment by cmwilson21** [comment]
👋 @craiglurey - Thanks for reaching back out. This is a definitely an area of the docs we take seriously. We have an internal vetting process and are working with our security team to update these references. We did have Keeper at one time and it was removed per [this comment](https://github.com/github/docs/pull/9114#issuecomment-902141015). It will be reviewed again, along with others, as we update these docs. 

I hope that provides a bit more clarity on our internal work. 💛

**Pull request closed without merging**
