### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dvcastillo**
Change "ony" to "only".

### Why: "ony" is not a [word](https://www.merriam-webster.com/dictionary/ony). I believe the original author meant "only".

Closes ISSUE

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@dvcastillo Great catch! Thanks for opening a PR with this fix. I'll get this merged down once the tests have all passed. ⚡

**Review by cmwilson21 — APPROVED** [review]
Great catch! 🚀

**Comment by Daniel7427** [comment]
73937615

**Comment by Daniel7427** [comment]
Now

**Pull request merged**
