### PR TITLE
fix-spelling-canceled

### LINKED ISSUE #22624: [Improvement]: Consistency for spelling of "canceled" in non-API docs
### Is this issue for a product update or release that is not yet available to customers?

No? Then please continue. Thank you!

### What article(s) is affected?

The following files (corresponding to articles on docs.github.com and including REST content that's in Markdown) seem to use the word "cancelled" in prose:

```
actions/learn-github-actions/contexts.md
actions/learn-github-actions/expressions.md
authentication/keeping-your-account-and-data-secure/reviewing-your-security-log.md
codespaces/troubleshooting/troubleshooting-creation-and-deletion-of-codespaces.md
communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization.md
communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account.md
developers/github-marketplace/selling-your-app-on-github-marketplace/pricing-plans-for-github-marketplace-apps.md
developers/github-marketplace/using-the-github-marketplace-api-in-your-app/testing-your-app.md
developers/github-marketplace/using-the-github-marketplace-api-in-your-app/webhook-events-for-the-github-marketplace-api.md
developers/github-marketplace/using-the-github-marketplace-api-in-your-app/handling-plan-cancellations.md
developers/github-marketplace/creating-apps-for-github-marketplace/viewing-metrics-for-your-listing.md
developers/github-marketplace/creating-apps-for-github-marketplace/viewing-transactions-for-your-listing.md
developers/apps/guides/creating-ci-tests-with-the-checks-api.md
organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization.md
organizations/managing-membership-in-your-organization/removing-a-member-from-your-organization.md
site-policy/github-terms/github-corporate-terms-of-service.md
site-policy/github-terms/github-terms-of-service.md
sponsors/receiving-sponsorships-through-github-sponsors/managing-your-sponsorship-tiers.md
```

There's a lot of use of "cancelled" in the REST API docs but a quick and dirty grep similar to the one above shows that all of it is related to products (ie it's canned in API requests/responses and we shouldn't change it/can't change it)

### Describe the desired docs changes and the problem they solve for customers.

We should be using the word `canceled` (US English, described by MS Style guide) where appropriate in the documentation prose. 

Some of the instances of `cancelled` are in referential material like "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts)," or status check functions like in "[Expressions](https://docs.github.com/en/actions/learn-github-actions/expressions#cancelled)". Since these refer to GitHub Actions contexts or special functions, we shouldn't change them.

### Who does this affect?

Readers of docs

### What is the impact to users?

Minimal impact, but there is a impression/reputation/consistency factor

### Are you willing to open a PR to make this fix? If not, do you know anyone (Hubber or not, we're open source!) who's willing to help write this documentation?

Opening this for an OS contribution ✨

### PR DESCRIPTION
**Pull request by technoph1le**
### Why:

Closes #22624 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The word "cancelled" is changed to "canceled". However, the word inside the specific blocks, such as ``cancelled`` and `<code>cancelled</code>` has NOT been changed since they refer to GitHub Actions contexts or special functions.

The following files have been inspected and corrected according to the issue #22624 

a list of changed files

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@dostonnabotov Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by hubwriter — COMMENTED** [review]
These changes all look good to me. Thanks for raising this PR @dostonnabotov 👍 

It's unfortunate that we use `cancelled` for actions, events, and as a status. However, when not referring to these directly, we should use the more common US English spelling of "canceled."

I'm holding off approving this for merging as we need to get the changes to the two site policy articles:
https://github.com/github/docs/pull/22692/files#diff-f47dd12027f2466c4965712e8121d44f6811d1c67cc5a6e169652c91de9a85f5
and 
https://github.com/github/docs/pull/22692/files#diff-ffa23917e1ff7b5a569ab12289674191f4e21f65f1db6dcb4887f693e99a9835

reviewed and approved by someone from @github/site-policy-admins as these are legal documents and this spelling variant may be significant.

**Comment by hubwriter** [comment]
Awaiting review & approval by https://github.com/orgs/github/teams/site-policy-admins for these spelling changes:

* https://github.com/github/docs/pull/22692/files#diff-f47dd12027f2466c4965712e8121d44f6811d1c67cc5a6e169652c91de9a85f5

  In this article: https://docs.github.com/en/site-policy/github-terms/github-corporate-terms-of-service

* https://github.com/github/docs/pull/22692/files#diff-ffa23917e1ff7b5a569ab12289674191f4e21f65f1db6dcb4887f693e99a9835

  In this article: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

**Review by literarytea — APPROVED** [review]
👍

**Comment by dostonnabotov** [comment]
Hi, @cmwilson21, @hubwriter.

Can I delete the branch `fix-spelling-of-canceled-docs`? Even though it shows that it has been merged, but the pull request is still open.

**Comment by hubwriter** [comment]
@dostonnabotov - Thanks for your patience.
Yes, you can delete that branch now.
👍

**Pull request merged**
