### PR TITLE
Add gidgethub to the list of Third Party Python Libraries

### PR DESCRIPTION
**Pull request by Mariatta**
### Why:

It would be great to include gidgethub to the list of third party Python libraries.

Gidgethub is an async Python library for interacting with GitHub APIs. It has support to receive webhooks, making REST API calls and graphQL, GitHub App and GitHub Actions.

Documentation: https://gidgethub.readthedocs.io/en/latest/

### What's being changed:

This is a one-line change, I added gidgethub to the list of third party Python libraries.
### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening a PR @Mariatta! I'll get this triaged for review ⚡

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by Mariatta** [comment]
Let me know if you have any questions or concerns about this library. Thanks.

**Review by runleonarun — APPROVED** [review]
Thank you for contributing! I checked with the Ecosystem API team and they are 👍 

I love the history of the name! Very thoughtful ❤️

**Pull request merged**
