### PR TITLE
Update managing-multiple-accounts.md

### PR DESCRIPTION
**Pull request by nodescout**
Updating the Windows shell command "credential-manager erase" to "credential-manager-core erase". On Windows, the former returns "git: 'credential-manager' is not a git command."

### Why:

The current command to clear the credential manager store is incorrect for Windows. It produces an error `git: 'credential-manager' is not a git command. See 'git --help'.`

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Changing the following:
echo "protocol=https`nhost=github.com" | git credential-manager erase

-to-

echo "protocol=https`nhost=github.com" | git credential-manager-core erase

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Valecia2023** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

**Comment by meowius** [comment]
@nodescout Thanks so much for flagging this and taking the time to open a PR. I have a clarification for you from our Git team that requires a small edit to this PR if you're willing.

Context: the correct command depends on which version of Git and Git Credential Manager you have installed. 

That means making a different edit to "[Managing multiple accounts](https://docs-28447-33dfd4.preview.ghdocs.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/managing-multiple-accounts)."

Leave the resuable you edited as is (i.e., leave it as `git credential-manager erase` and do not update to `git credential-manager-core erase`).

Instead, update the bullet _preceding_ the reusable from this, as it reads currently:

> If the output is `manager-core`, you're using Git Credential Manager. To clear the credentials, run the following command.

to this, as it should read:

> If the output is `manager` (or `manager-core` in previous versions), you’re using Git Credential Manager.

Let us know if you'd be willing to update this PR to reflect this. Thank you!

**Comment by nodescout** [comment]
Hi @meowius,

I have made the requested updates to address the feedback regarding the Git Credential Manager usage. Instead of modifying the `managing-multiple-accounts.md` file directly, I updated the reusable component that contains the relevant information. The changes can be seen in commit [7f1eabd](https://github.com/nodescout/docs/commit/7f1eabd4e4d8e7f98d67fe379bf4b4ce704562ad). Additionally, I reverted the original changes made to `managing-multiple-accounts.md` as they are no longer necessary with the updated reusable component.

Please review the updates at your convenience and let me know if there are any further changes needed. Thank you for your feedback and guidance on this!

**Comment by meowius** [comment]
Brilliant @nodescout, thanks so much for catching that this was part of a reusable and making the update. I"ll get this merged. Really appreciate your making the docs better for everyone! ⚡

**Review by meowius — APPROVED** [review]
:shipit:

**Pull request merged**
