### PR TITLE
Update basic-writing-and-formatting-syntax.md

### LINKED ISSUE #25588: Markdown Snippets in "Lists" Section of basic-writing-and-formatting-syntax.md Incorrect
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Basic writing and formatting synatx](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

### What part(s) of the article would you like to see updated?

The "markdown" snippet in the Lists section under "Nested Lists" is incorrect. When copy and pasted the results are in consistent with images and description.

### Additional information

The list item number does not match the images showing the rendered code.

### PR DESCRIPTION
**Pull request by nobedee**
### Why: 

Corrected markdown and description in Lists section so as to have it produce expected results.
Three areas where this occurred.
1. Markdown snippets did not output correctly or as described when copied and pasted into a document. 
2. Description did not output intended results.
3. Markdown snippets did not output correctly or as described when copied and pasted into a document.  

Closes:  [#25588](https://github.com/github/docs/issues/25588)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

CHANGE ONE - lines 235:236 <br>
Edited "...markdown" on lines 235 to 236 so as to have it copy and paste and produce the same results as example image.

CHANGE TWO - line 241 <br>
Changed the text at the end of line 241, changing text from "seven spaces" to "nine spaces"; as prior text did not seem to produce the results from the example image.

CHANGE THREE - lines 244:246 <br>
Edited "...markdown" on lines 244 to 246 so as to have it copy and paste and produce the same results as example image.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by nobedee — COMMENTED** [review]
Lines 234 to 236 pasted from editor that produced expected results.

Description change on line 241 matches comment, and will produce expected results when used.

Lines 244 to 246 pasted from editor that produced expected results.

**Comment by nanis94** [comment]
Nobedee:yama-1 master

**Comment by cmwilson21** [comment]
@nobedee Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Review by sophietheking — APPROVED** [review]
@nobedee 👋  Thanks for contributing to our Docs! ✨  This looks good to me, so I'll make sure tests are passing, before merging your PR.

**Pull request merged**
