### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by chiedo**

### CODE REVIEW

**Review by janiceilene — APPROVED** [review]
LGTM :shipit:

**Review by Rimaq53 — COMMENTED** [review]
Screenshot_20210201-234416_Chrome

**Comment by king40or** [comment]
@chiedo hey I apologize if this isn't a good place to ask a question.  I've got some issues that I really don't know where to start to know if I'm looking at the correct answer or not,  I can't really get into exactly what is happening because it would take up a couple of pages, and when I send support questions I get flagged as spam.

**Comment by janiceilene** [comment]
:wave @king40or You can take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions ✨

**Pull request merged**
