### PR TITLE
Update Index.md

### PR DESCRIPTION
**Pull request by katelynnashley95icloudcom**
All my accounts

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by IMANUEL27** [comment]
give me support

Pada tanggal Rab, 9 Jun 2021 17.23, Ashley Bayes ***@***.***>
menulis:

**Comment by Ihsan-K** [comment]
Thanks

**Review by katelynnashley95icloudcom — COMMENTED** [review]
@bassa846 @BachaTyler @brideypatterson @bruce @katelynnashley95icloudcom @mtodd @bruce @technicalpickles 

> [x](https://ashleybayes95.icloud.kikcom) 

#7214 #7214 #7211 #7210 #7212 #

**Review by katelynnashley95icloudcom — COMMENTED** [review]
@katelynnashley95icloudcom 
@Jonathanm[Gmail ](https://github.com/github/docs/pull/7247) 
#7238 #7247 #7246 #7247 #7188 #
>

**Comment by datuplambik** [comment]
.amz_inline_image{
                max-width: 100%
            }
         
        body{
            font-family: -apple-system-font, HelveticaNeue, LucidaGrande;
        }

**Comment by datuplambik** [comment]
---------- Diteruskan ----------
Pengirim: samsudin samsudin ***@***.***>
Tanggal: 15 Sep 2021 6:59 AM
Subjek: 
Penerima: 
CC: 

>
>
> https://apps.apple.com/my/app/macos-big-sur/id1526878132?mt=12

**Pull request closed without merging**
