### PR TITLE
docs: update how to disable unathenticated sign-ups

### PR DESCRIPTION
**Pull request by balcsok**
### Why: Docs out of date

Closes: n/a

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Since the **Enable sign-up** button is no longer present in the Management Console UI, I propose to change the wording of the doc to say "Make sure to select **Private mode**"
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@balcsok Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by maxgtr992 — COMMENTED** [review]
Ok

**Review by maxgtr992 — COMMENTED** [review]
Ok

**Comment by sophietheking** [comment]
@balcsok 👋 Thanks for opening this PR and contributing to our docs, we really appreciate it!

The **Enable sign-up** option is visible on my GHES 3.14 instance (if you scroll down a little):

Screenshot of the Management Console of a GHES instance

What version of GHES are you on? 😄

**Comment by sophietheking** [comment]
@balcsok Ahh, right. From the article, it looks like you can only disable authenticated sign-ups if you're using built-in authentication for your GHES instance, so that would explain the missing option in your Management Console. 😸

**Comment by nguyenalex836** [comment]
@sophietheking Thank you for reviewing here! ✨ 

@balcsok Given the conversation above, I'll go ahead and close this issue 💛 

If by chance you're looking for issues to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

**Pull request closed without merging**
