### PR TITLE
Update Copilot Chat images to be more obvious

### LINKED ISSUE #26952: Update Copilot Chat images to be more obvious
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/copilot/github-copilot-chat/using-github-copilot-chat?tool=vscode

### What part(s) of the article would you like to see updated?

The existing images for VSCode show a generic search tab and only have a small non-obvious rectangle to indicate what the user should click. We had multiple people confused by the docs as we ran through onboarding.
image
image

I have a PR here to update the images: https://github.com/github/docs/pull/26949

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mdeeks**
### Why:
The existing images show a generic search tab and only have a small non-obvious rectangle to indicate what the user should click. We had multiple people confused by the docs as we ran through onboarding.

Closes: #26952 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updated the images with a larger square and arrow. Also made sure the panel shows the actual page of the selected icon rather than the search page.

| Before | After |
|--------|--------|
| image | image | 
| image | image |

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by mdeeks** [comment]
The github action failed with a 502 but it does in fact work and I verified here: https://docs-26949-45a775.preview.ghdocs.com/en/copilot/github-copilot-chat/using-github-copilot-chat

**Comment by cmwilson21** [comment]
@mdeeks Thank you for opening a PR and linking it to your issue! ✨ 

Thanks for providing the side by side screenshot comparison. That's really helpful 👍 

I'll get this on the board for review. In the mean time, check out our [contributing guide for screenshots](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots) if you have any questions.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by lecoursen** [comment]
Thanks for your interest in contributing to GitHub Docs! ✨ These screenshots follows our guidelines as is, so we won't be able to accept this change.

>Updated the images with a larger square and arrow. 

This violates our guidelines for highlighting images, which you can read in "[Creating screenshots](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#highlighting-elements-in-screenshots)."

>Also made sure the panel shows the actual page of the selected icon rather than the search page.

This was done intentionally. When we instruct the user to click on that icon, we want the screenshot to reflect what the user is seeing at the time we ask them to complete the step, not after they've completed it.

**Comment by imanpat908s-ship-it** [comment]
> Thanks for your interest in contributing to GitHub Docs! ✨ These screenshots follows our guidelines as is, so we won't be able to accept this change.
> 
> >Updated the images with a larger square and arrow. 
> 
> This violates our guidelines for highlighting images, which you can read in "[Creating screenshots](https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#highlighting-elements-in-screenshots)."
> 
> >Also made sure the panel shows the actual page of the selected icon rather than the search page.
> 
> This was done intentionally. When we instruct the user to click on that icon, we want the screenshot to reflect what the user is seeing at the time we ask them to complete the step, not after they've completed it.~~````

````~~
> Comment @iman908s-ship-it

**Pull request closed without merging**
