### PR TITLE
Add about gitignore global default config at ignoring-files.md (#21863)

### LINKED ISSUE #21863: Recommend default global gitignore file
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

### What part(s) of the article would you like to see updated?

The article recommends setting `core.excludesfile` and adding an ignore file to the user’s home directory.

This is unnecessary since [this change](https://github.com/git/git/commit/dc79687e0b70805894d1b4432cef7164ae86e033) in Git 1.7.12 (August 2012), which made Git default to reading the file `$HOME/.config/git/ignore`. Using this file is preferable as it avoids configuraiton and it’s the standard location for config, reducing bloat in the home directory.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aokabin**
### Why:

Closes: #21863

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Code snippet:
image

Preview Changes:
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Ruffledfeatherz** [comment]
Hmmm

**Review by rhino701 — COMMENTED** [review]
👍

**Comment by cmwilson21** [comment]
@aokabin Thanks so much for submitting a PR! We appreciate the screenshots, too.

I'll get this triaged for review :zap:

And welcome to the community! If you are looking for more ways to contribute, please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

**Review by jhosman — APPROVED** [review]
Thanks for opening a PR with this fix @aokabin! ❤️ 

I’ve made a few additional commits to expand the first paragraph to include an example, and to remove all mentions of the `~/.gitignore_global` file. (Since `~/.config/git/ignore` has been the Git default for quite a while now, it should be safe to only recommend this single method going forward.) 

While I was in there, I also updated the formatting of all filenames in the article to use backticks instead of italic format, per the [style guide](https://docs.github.com/en/contributing/writing-for-github-docs/style-guide#file-and-directory-names).

We'll go ahead and get this merged for you once tests are passing! Thanks so much! :rocket: ✨

**Review by rhino701 — COMMENTED** [review]
👍

**Pull request merged**
