### PR TITLE
Fix example code snippets

### LINKED ISSUE #6211: Ruby example for Securing your Webhook contain errors
### What article on docs.github.com is affected?
[Securing your Webhooks](https://docs-6209--patch-1.herokuapp.com/en/developers/webhooks-and-events/securing-your-webhooks)

### What part(s) of the article would you like to see updated?

Both of the Ruby code snippets on this page should get the payload from `request.body` instead of `params[:payload]`

### Additional information

_Not required._

### PR DESCRIPTION
**Pull request by raccube**
### Why:

I noticed that the example code snippet in the "Securing your webhooks" page would not run.

**Closes #6211**

### What's being changed:

The JSON payload being parsed is now being retrieved from the request body rather than a `payload` parameter.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@raccube Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by sayyaf69** [comment]
#6237 #6218 #6235

**Review by S69y — APPROVED** [review]
[moderator removed content]

**Review by hubwriter — APPROVED** [review]
@raccube - Good spot. Many thanks for this fix. 
Your help is much appreciated. 👍

**Pull request merged**
