### PR TITLE
Fix inconsistent alerts by using the markdown notation

### LINKED ISSUE #35195: Inconsistent labeling of Note/Warning blocks
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Reading the GitHub Actions documentation I have noticed that the labeling of `Note/Warning` blocks is inconsistent through the documentation. Is that intentional or can be this seen as a `bug`?

```
>[!NOTE]
```
note_1

```
**Note:** or **Notes:**
```
note_2

note_3

```
>[!WARNING]
```
warning_1

```
**Warning:**
```
warning_2

### What part(s) of the article would you like to see updated?

My first search in the repository indicates that it affects other docs as well. It would be nice if the docs would have a consistent way to display the blocks (preferably the `>[!NOTE] / >[!WARNING]` notation), and not have different kinds even in same article.

### Additional information

If whished I could provide a PR to fix this issue.

### PR DESCRIPTION
**Pull request by akordowski**
### Why:

As described in the issue #35195 the display of alerts is inconsistent across the documentation. The following PR provides changes to all alerts according to the docs [guidelines](https://docs.github.com/en/contributing/writing-for-github-docs/using-markdown-and-liquid-in-github-docs#alerts) using the Markdown notation.

Closes: #35195

### What's being changed (if available, include any code snippets, screenshots, or gifs):

All alerts for `note`, `tip`, `important` and `warning` have been changed and unified from the following notation to the Markdown notation according to the docs guidelines.

```
{% note %}
text
{% endnote %}

> [!NOTE]
> Text
```

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by akordowski** [comment]
Is there a way to go around the following lint error?

```
__ running gh pr diff __
could not find pull request diff: HTTP 406: Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locally cloning the repository instead. (https://api.github.com/repos/github/docs/pulls/35216)
PullRequest.diff too_large
```

**Comment by nguyenalex836** [comment]
@akordowski Thank you so much for the time and effort put into this PR! ✨ 🚀 We didn't expect a PR to change every inconsistency, and are greatly appreciative of the energy put into improve our docs 🙇 

> Is there a way to go around the following lint error?

Unfortunately there isn't - would you be alright with breaking up your PR into multiple PRs smaller than the max files limit (300)? 💛

**Comment by akordowski** [comment]
@nguyenalex836 

> We didn't expect a PR to change every inconsistency, and are greatly appreciative of the energy put into improve our docs 🙇

You're very welcome! :relaxed:

> would you be alright with breaking up your PR into multiple PRs smaller than the max files limit (300)?

That was also my idea. Maybe a PR for each seaction? (Actions, Copilot, ...) That would propably also make it easier to review. What do you think?

Should I also create an new issue for each PR or reference to the existing one?

**Comment by nguyenalex836** [comment]
@akordowski 

> That was also my idea. Maybe a PR for each seaction? (Actions, Copilot, ...) That would propably also make it easier to review. 

This sounds like an excellent plan! 💛 

> Should I also create an new issue for each PR or reference to the existing one?

Feel free to just have each PR reference the existing issue! Thank you!

**Comment by akordowski** [comment]
@nguyenalex836 Ok, will do. Thank you!

**Comment by akordowski** [comment]
As this PR exceeds the linter limit of 300 files, this PR is splited into 4 new ones, see [here](https://github.com/github/docs/issues/35195#issuecomment-2462998778). This PR will be closed.

**Pull request closed without merging**
