### PR TITLE
Update configuring-github-copilot-in-your-environment.md

### PR DESCRIPTION
**Pull request by SumaiyaTarannumNoor**
### Why: Some grammatical and syntax errors have been corrected.

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 Thank you so much. 😊😊

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 Hello, can you merge this pull request please?

**Comment by nguyenalex836** [comment]
Hi @SumaiyaTarannumNoor 👋 this PR will need to be reviewed by a team member before it can be merged. We appreciate your patience! 💛

**Pull request closed without merging**
