### PR TITLE
Change capitalization

### LINKED ISSUE #21591: [Improvement]:
### What article(s) is affected?

These reusables:

- data/reusables/secret-scanning/partner-secret-list-private-repo.md
- data/reusables/secret-scanning/partner-secret-list-public-repo.md
- data/reusables/secret-scanning/secret-list-private-push-protection.md

### Describe the desired docs changes and the problem they solve for customers.

We should update the capitalization in the reusables listed above to be consistent with the style guide. Product names (e.g. `Atlassian`) and abbreviations (e.g. `API`) should remain capitalized, but other things (e.g. `Refresh Token`) should be lower case. For example,`DevCycle Client API Key` becomes `DevCycle client API key`.

examples:
`DevCycle Client API Key` becomes `DevCycle client API key`
`Ionic Refresh Token` becomes `Ionic refresh token`
`GitHub OAuth Access Token` becomes `GitHub OAuth access token`

### PR DESCRIPTION
**Pull request by ishuen**
### Why:

Closes #21591 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Capitalisation is changed.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @ishuen Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by mchammer01** [comment]
I'll review this tomorrow.

**Review by mchammer01 — COMMENTED** [review]
@ishuen 👋🏻 - thanks for your contribution ✨ 
I understand your reasoning for changing the capitalization, but we worked on these strings with our partners, and also that's how they appear in the UI.
As a result, we cannot accept this contribution. Thanks for your understanding ❤️

**Review by Nuttapon43 — COMMENTED** [review]
@ishuen

**Pull request closed without merging**
