### PR TITLE
Auto merge doc fix

### LINKED ISSUE #32303: Unclear about auto merge option location
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository

image

### What changes are you suggesting?

add a screenshot or give the exact path.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ktauchathuranga**
### Why: its because I was searching for how to enable auto-merge in my repo, I found the documentation but it was unclear and I search trough settings like 15 min before I found it

Closes: https://github.com/github/docs/issues/32303

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I added a screenshot of the location of the option and cleared out the exact path in the text section.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@ktauchathuranga Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by nguyenalex836 — DISMISSED** [review]

**Comment by nguyenalex836** [comment]
@ktauchathuranga Thanks so much for opening a PR with this update! I made a few minor edits to make this update more closely align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide) 💛  I'll update the branch and get this merged once tests are passing 🍏

**Review by nguyenalex836 — APPROVED** [review]

**Comment by ktauchathuranga** [comment]
> @ktauchathuranga Thanks so much for opening a PR with this update! I made a few minor edits to make this update more closely align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide) 💛 I'll update the branch and get this merged once tests are passing 🍏

yeaah.... i am sorry for the oversight. but you fixed it. thank you... 😇

**Comment by nguyenalex836** [comment]
It was no problem at all - thank you for your contribution! 💛 ✨ 

If you're up for tackling another issue, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on 😄

**Pull request merged**
