### PR TITLE
Update URLs for Ubuntu image for Actions runner

### LINKED ISSUE #13388: Deadlinks in Hosted runner in Actions
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Some links are dead in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

### What changes are you suggesting?

All links should be valid in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software

### Additional information

actions/virtual-environments#4794

### PR DESCRIPTION
**Pull request by tnir**
https://github.com/actions/virtual-environments/pull/4794

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### Why:

Closes #13388

### What's being changed:

This PR follows what actions/virtual-environments#4794 changed.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Xirad-06** [comment]
tnir:actions/runner-linux-readme

**Comment by oddstr13** [comment]
Duplicate of #13319

**Comment by ramyaparimi** [comment]
@tnir Thank you for opening this PR. This is a duplicate of [this PR](https://github.com/github/docs/pull/13319) so I am going to close this now 💛.

Thanks so much for your passion in contributing to the GitHub docs 💖

**Comment by tnir** [comment]
Thanks for triaging this external improvement.

**Pull request closed without merging**
