### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saptarsi96**
Fixed the defects to remove the duplicate contributors as per issue #389

### Why:

This change is to fix issue #389.

### What's being changed:

Readme.md File.
Before: 
image
After:
image

### Check off the following:
- [X] All of the tests are passing.
- [X] I have reviewed my changes in staging.
- [X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by saptarsi96 — COMMENTED** [review]
@Ruth-ikegah, Can you please review this change? I guess this fixes your issue #389.

**Comment by janiceilene** [comment]
Thanks so much for fixing this @saptarsi96! I'll update the branch and get it merged once the tests are passing 🍏

**Review by janiceilene — APPROVED** [review]

**Comment by Ruth-ikegah** [comment]
Nice work @saptarsi96

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by saptarsi96** [comment]
@all-contributors please add @saptarsi96 for code

**Comment by saptarsi96** [comment]
@janiceilene I think there is some issue with the @all-contributors bot.

**Comment by saptarsi96** [comment]
@all-contributors please add @saptarsi96 for design.

**Comment by Rsamudra19236** [comment]
I don't have internet data to do the teaching

Pada tanggal Rab, 14 Okt 2020 12.22 allcontributors[bot] <
notifications@github.com menulis:

**Comment by Rsamudra19236** [comment]
I don't have internet data to do the teaching

Pada tanggal Rab, 14 Okt 2020 12.25 Saptarsi Saha <notifications@github.com
menulis:

**Pull request merged**
