### PR TITLE
do not use migrator to transfer GHES between hypervisors

### LINKED ISSUE #23450: do not use migrator to transfer GHES between hypervisors
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[content/admin/user-management/migrating-data-to-and-from-your-enterprise/about-migrations.md](https://docs.github.com/en/enterprise-server@3.7/admin/user-management/migrating-data-to-and-from-your-enterprise/about-migrations)

### What part(s) of the article would you like to see updated?

The intro blurb leads our GHES customers to think that using `ghe-migrator` is the preferred method of transferring a GHES instance between hypervisors. This isn't the case.

Enterprise Support recommends using either:

1. Backup and restore onto the new location using [GitHub Enterprise Server Backup Utils](https://github.com/github/backup-utils) OR
2. "[Creating a high availability replica](/enterprise/admin/guides/installation/creating-a-high-availability-replica/)" and "[Initiating a failover to your replica appliance](/admin/enterprise-management/initiating-a-failover-to-your-replica-appliance)." 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Fuzzwah**
### Why:

Closes #23450

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removing the final sentence of the `intro`, adding a `Note:` box to inform customers of the supported method of re-homing a GHES instance

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

/cc @pnsk

### CODE REVIEW

**Comment by pnsk** [comment]
Thanks @Fuzzwah for opening this issue.

I agree to this update ❤️

**Comment by cmwilson21** [comment]
👋 @Fuzzwah Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Review by vgrl — COMMENTED** [review]
Thanks @Fuzzwah! I am going to apply a few small changes, then I'll double check on preview and merge if all looks good! ⚡

**Review by vgrl — APPROVED** [review]
Looks good on [preview](https://docs-23451-44b085.preview.ghdocs.com/en/enterprise-server@3.7/admin/user-management/migrating-data-to-and-from-your-enterprise/about-migrations).

**Pull request merged**
