### PR TITLE
Change usage of "container" to "container registry"

### PR DESCRIPTION
**Pull request by jcansdale**
### Why:

Users are potentially confused by references to "container support". For example:

> Ok, I'll check it out. I didn't do it because GitHub Container Registry is a term which lead me to think is for storing containers instead of images.

https://github.zendesk.com/agent/tickets/980826

### What's being changed:

- Change "Container guides for GitHub Packages" to "Guides for GitHub Container Registry"

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@jcansdale Thanks for opening a PR! I see this is still in draft mode. Feel free to ping me when you're ready for a writer review and I'll get this triaged ⚡

**Comment by REGI220** [comment]
SEJAN BEM VINDOS NO MYSPACE

**Review by lokera07 — APPROVED** [review]

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening 💛

**Comment by jeremyepling** [comment]
We should close this PR or adapt it to use the updated naming scheme - https://docs.google.com/document/d/1BhHuQ7PhPf_ZTOjk2LYi4c-xUBrr9RUowmgkVeU_rXA/edit#

**Comment by jcansdale** [comment]
@jeremyepling 👋🏻  I like @clarkbw's `Container registry guide` suggestion here:
https://github.slack.com/archives/CM82WM3LY/p1614117030013700?thread_ts=1614075029.012500&cid=CM82WM3LY

I'm going to close this PR and defer to the updated naming scheme. 😄

**Comment by MichaelFoundation** [comment]
> ### Why:
> Users are potentially confused by references to "container support". For example:
> 
> > Ok, I'll check it out. I didn't do it because GitHub Container Registry is a term which lead me to think is for storing containers instead of images.
> 
> https://github.zendesk.com/agent/tickets/980826
> 
> ### What's being changed:
> * Change "Container guides for GitHub Packages" to "Guides for GitHub Container Registry"
> 
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**38html file for docs-style can’t be found narrow end for protection guarantee, to if and when pivot 65md5, are always file for configure without seen by owner registry of licensed. Js.console/   **

**Comment by MichaelFoundation** [comment]
```
steps:
      - uses: actions/checkout@v2
      - name: Dhennis Linganay  @gustavobini 
        uses: actions/setup-python@v2
        with: CS/HH
          python-version: ${{334.012}}
[www.com](https:/http:/) 

>  #![E2BB5CB0-19AD-4902-8742-7B91D122BCD0](https://user- JS
images.githubusercontent.com/69623706/120094112-07110600-c151-11eb-8b52-41acce0c0c51.png)

```

> ``

**Pull request closed without merging**
