### PR TITLE
Update generating-a-json-web-token-jwt-for-a-github-app.md

### LINKED ISSUE #33324: Unable to generate valid JWT using Bash example
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server@3.10/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt

### What part(s) of the article would you like to see updated?

The Bash example for generating a JWT does not seem to work.

I'm working with a GitHub Enterprise server version `3.10.12`.

##  Current behavior

Using some censored values here, but to illustrate what the current behavior is when I run it:

```console
$ ./generate-jwt.sh Iv1.c0ffeec0ffeec0ff ./my-app.2024-06-03.private-key.pem
JWT: ewogICAgInR5cCI6IkpXVCIsCiAgICAiYWxnIjoiUlMyNTYiCn0.ewogICAgImlhdCI6MTcxNzUwMTk2MCwKICAgICJleHAiOjE3MTc1MDI2MjAsCiAgICAiaXNzIjpJdjEuYzBmZmVlYzBmZmVlYzBmZgp9.YoShUxrZ-fIwyKm6nXrgluU6jXnElLjijQTvUZOk9eeHb5prP64oAJvFYr7ZCNwHYHRGJnrSLNyw2c8LmAo6IGg9bdi_mrE5qzMZO1ZWLqJP6EMqJ1TCvgPS4zHk8dH6GB5JTp_QJsp6n5Q8Kgloqb-oqSbqxt87Sn1nkxyVsVFiZ_8r-wHemCg1mTEub1Vyz3PZHxfrdh_x-r6YwQ8qD8m-uWhBovZLsNDfIxcVhLtSu6msAPiF3oB4_DhcvSuZaROhHGs7umHMWnLP6sWp0unfy_LUFkEPoWx7pDaU--9yqA75cdxDps7LMDehmg1VESc8llvBtsrVQP-8b-gzqw

$ curl -L -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${JWT:?}" -H 'X-GitHub-Api-Version: 2022-11-28' 'https://github.example.com/api/v3/app'
{
  "message": "A JSON web token could not be decoded",
  "documentation_url": "https://docs.github.com/enterprise-server@3.10/rest"
}
```

## Some notes

One thing that immediately sticks out to me is that the JWT does not start with `eyJ0` like I'm used to seeing, but instead `ewog`. Turns out that's because the script keeps some newlines in the JSON:

```console
$ echo -n '{"typ":"JWT","alg":"RS256"}' | base64
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9

$ echo -en '{\n    "typ":"JWT",\n    "alg":"RS256"\n}' | base64
ewogICAgInR5cCI6IkpXVCIsCiAgICAiYWxnIjoiUlMyNTYiCn0=
```

I'm not sure if that is legal. Maybe it is.

### Additional information

If we can change the script to output `eyJhbGci[…]` instead of `JWT: eyJhbGci[…]`, I think that would be very useful. Makes it much easier to use that in a script when a JWT is required.

There are also some warnings from ShellCheck that we may want to fix while we're at it:

```console
$ shellcheck generate-jwt.sh

In generate-jwt.sh line 7:
pem=$( cat $2 ) # file path of the private key as second argument
           ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
pem=$( cat "$2" ) # file path of the private key as second argument


In generate-jwt.sh line 10:
iat=$((${now} - 60)) # Issues 60 seconds in the past
       ^----^ SC2004 (style): $/${} is unnecessary on arithmetic variables.


In generate-jwt.sh line 11:
exp=$((${now} + 600)) # Expires 10 minutes in the future
       ^----^ SC2004 (style): $/${} is unnecessary on arithmetic variables.

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
  https://www.shellcheck.net/wiki/SC2004 -- $/${} is unnecessary on arithmeti...
```

### LINKED ISSUE #33989: bash instructions for creating jwt for github app do not work with client id but work with app id
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt

### What part(s) of the article would you like to see updated?

Running the script with the client id results in a token which when used throws the following error:

```
{
  "message": "A JSON web token could not be decoded",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

Running the script with the app id results in a valid token.

### PR DESCRIPTION
**Pull request by mark-mxwl**
### Why:

Closes: #33324 
Closes: #33989

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updated formatting for payload JSON to return top-level JSON when decoded, as the previous version was throwing an error for some users. Header JSON moved to single line to match payload. Also removed "JWT: " from print line to avoid scripting conflicts.

### Check off the following:

- [X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [X] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by lindhe** [comment]
Thanks for fixing this! Great job!

There seem to be some shellcheck warnings left:

```console
$ shellcheck bash.sh

In bash.sh line 5:
pem=$( cat $2 ) # file path of the private key as second argument
           ^-- SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
pem=$( cat "$2" ) # file path of the private key as second argument


In bash.sh line 8:
iat=$((${now} - 60)) # Issues 60 seconds in the past
       ^----^ SC2004 (style): $/${} is unnecessary on arithmetic variables.


In bash.sh line 9:
exp=$((${now} + 600)) # Expires 10 minutes in the future
       ^----^ SC2004 (style): $/${} is unnecessary on arithmetic variables.


In bash.sh line 30:
printf '%s\n' $JWT
              ^--^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
printf '%s\n' "$JWT"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
  https://www.shellcheck.net/wiki/SC2004 -- $/${} is unnecessary on arithmeti...
```

Maybe let's fix them also.

**Comment by nguyenalex836** [comment]
@mark-mxwl Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by mark-mxwl** [comment]
Thx for the ShellCheck output @lindhe! While those are all valid warnings, we don't really have to worry about globbing (wildcards)/splitting (tab, space, newline) on our positional parameters, due to the type of data we're passing through. The curly braces on the expressions are optional--I kept them there for the sake of consistency and readability.

**Comment by brakel** [comment]
Hi, thanks for the update. I ran the updated script, removing the templating, and there still seems to be an issue with the `iat` claim being a string:

```
{
  "message": "'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

Removing the quotes in the script solves the issue for me.

Interestingly, the same validation is not applied to the `exp` claim and will work as either a string or int.

**Comment by mark-mxwl** [comment]
Thanks for catching that @brakel. Interesting re: the behavior with `exp`. I adjusted the script so that `iat` and `exp` values are both integers, which hopefully will resolve this.

**Comment by Githubant123** [comment]
Hi

**Comment by Githubant123** [comment]
Hi it ok

**Review by Githubant123 — COMMENTED** [review]
Hi,its ok

**Review by Clydonight — COMMENTED** [review]
It's good for me to generate all this information and to be able to understand all your instructions thx

**Comment by Jaga416381** [comment]
Im sorry if i dit something. Im a beginner at this. Sorry. But my
graphenoseOS pixel 6a is still hacked.
Os it any step that can remove graphenos on my pixel?

Regards

Den fre 23 aug. 2024 19:11github-actions[bot] ***@***.***>
skrev:

**Comment by nguyenalex836** [comment]
@mark-mxwl Apologies for the delay! We recently merged a [PR](https://github.com/github/docs/pull/33859) that I believe resolves the issue this PR is attempting to fix. Many apologies for not being able to get to this sooner 💛 

I'll go ahead and close out this PR, but please feel free to reopen / ping if needed!

**Comment by mark-mxwl** [comment]
Np @nguyenalex836! Glad it got sorted. Appreciate the heads-up! 🙏

**Pull request closed without merging**
