### PR TITLE
Remove redundant word (since/so)

### PR DESCRIPTION
**Pull request by timmc-edx**
### Why:

This sentence has a redundant "since" and "so"; one of the two needs to be removed.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Just a word removal.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@timmc-edx Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by cmwilson21 — APPROVED** [review]
LGTM, thanks for this fix! 🚢

**Comment by cmwilson21** [comment]
@timmc-edx Thanks for update! I'll get this merged down once all the checks have passed ✅

**Comment by Erctas** [comment]
Yes

**Pull request merged**
