### PR TITLE
Update viewing-all-of-your-issues-and-pull-requests.md

### PR DESCRIPTION
**Pull request by cgthayer**
Calling out the properly permalink to list one's own open PRs, because the UI modifies the URL in the browser bar.

### Why:

It's unclear what the link should be since the UI modifies the URL in the browser bar quite a bit. Also 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Adding info

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@cgthayer Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by jangiann09** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Comment by Hadi83mars402402** [comment]
مشطووووووور

**Comment by Hadi83mars402402** [comment]
شكرا

**Comment by cmwilson21** [comment]
@cgthayer Thanks so much for opening a PR and for your interest in improving the docs. I spoke with our team, and we are not going to accept this change 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍 

Thanks again for your passion in improving GitHub docs! 💖

**Pull request closed without merging**
