### PR TITLE
Update about-your-personal-dashboard.md

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
### Why:

 I am trying to add what you can do in GitHub if you when to the right hand side of the dashboard. I know it is in the code, but they did not include what I was trying to say.

### What's being changed:

Adding more that you can do on a GitHub dashboard page.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by venusFT** [comment]
Merge
53487554+venusFT@users.noreply.github.com

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by SmashedFrenzy16** [comment]
ok

**Comment by SmashedFrenzy16** [comment]
I have

**Comment by SmashedFrenzy16** [comment]
I have done it now

**Comment by janiceilene** [comment]
@SmashedFrenzy16 Please fill out the **Why** and **What's being changed** questions in the top comment.

**Comment by SmashedFrenzy16** [comment]
@janiceilene I am trying to add what you can do in GitHub if you when to the right hand side of the dashboard. I know it is in the code, but they did not include what I was trying to say.

**Comment by janiceilene** [comment]
@SmashedFrenzy16 Thanks for that additional context! I've triaged this for review ✨

**Comment by SmashedFrenzy16** [comment]
Thanks @janiceilene !

**Comment by megbird** [comment]
:wave: hi! I've checked in with other members of my team and I've confirmed that this isn't a general use case. If you want to include a screenshot and reopen this PR please do so, but for now since it's now the standard dashboard configuration I'll close this out 💛

**Pull request closed without merging**
