### PR TITLE
Update generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

### PR DESCRIPTION
**Pull request by bobbyaxe74**
Some Linux (ubuntu 20.04) users encounter issues with executing `eval "$(ssh-agent -s)" ` they get "eval: command not found" and the fix is that they need to execute it as superuser but this not covered in the documentation hence my modification.

### Why: To ensure that the existing ssh keys generation and configuration for Linux works across the board for various environments

**Closes [issue link]**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@bobbyaxe61 Thanks for opening a PR 👍 Please fill out the **Why** and **What's being changed** in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by bobbyaxe61** [comment]
@janiceilene Thanks for your guidance I have made the modifications.

**Comment by janiceilene** [comment]
@bobbyaxe61 Thanks so much for that helpful context! I've triaged this for review ✨

**Review by felicitymay — DISMISSED** [review]
Thanks for flagging the need for root permissions in some environments and for updating the docs. This looks like a change that will help other users 💖 

I'm going to apply a change to fix the formatting issue and then this should be good to merge ✨

**Review by felicitymay — APPROVED** [review]
The formatting now looks as expected.

**Pull request merged**
