### PR TITLE
On the code-nav page, link to Tree-sitter instead of Semantic

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
### Why:

Currently, the Code Navigation documentation says that the feature uses the [Semantic](https://github.com/github/semantic) Haskell library. This is no longer true; the feature now uses the [Tree-sitter](https://github.com/tree-sitter/tree-sitter) C library directly.

It's important to inform users correctly about this, so that they know which repository to visit in order to report bugs in our code navigation, request features, or submit contributions.

### What's being changed:

This is a one-sentence change at the beginning of the code navigation page.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@maxbrunsfeld Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by maxbrunsfeld** [comment]
The page that I updated has been translated to quite a few languages. I'm not sure if it's worth updating the link in those translated documents, or if there's any existing process for porting updates to the translated versions.

Because it's just a link (and a repo name), in most cases, I could probably make the appropriate change myself. Let me know if that would be helpful.

translations/es-XL/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/es-ES/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/de-DE/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/ru-RU/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/ja-JP/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/zh-CN/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/ko-KR/content/github/managing-files-in-a-repository/navigating-code-on-github.md
translations/pt-BR/content/github/managing-files-in-a-repository/navigating-code-on-github.md

**Comment by Dopeboyco** [comment]
> ### Why:
> Currently, the Code Navigation documentation says that the feature uses the [Semantic](https://github.com/github/semantic) Haskell library. This is no longer true; the feature now uses the [Tree-sitter](https://github.com/tree-sitter/tree-sitter) C library directly.
> 
> It's important to inform users correctly about this, so that they know which repository to visit in order to report bugs in our code navigation, request features, or submit contributions.
> 
> ### What's being changed:
> This is a one-sentence change at the beginning of the code navigation page.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Comment by janiceilene** [comment]
Thanks for the offer @maxbrunsfeld, but we don't update any of the translated files here. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens.

**Review by shati-patel — APPROVED** [review]
Thank you for the update, @maxbrunsfeld! I'll merge this shortly 😃 

(There's a failing PR check which is unrelated to your change. I'll check with the docs-engineering team to get this fixed!)

**Pull request merged**
