### PR TITLE
Update configuring-a-publishing-source-for-your-github-pages-site.md

### PR DESCRIPTION
**Pull request by thebarshablog**
The current documentation consisted of a bunch of unclickable links adding no value to the user experience while reading.

### CODE REVIEW

**Comment by thebarshablog** [comment]
Has this issue been assigned to someone?

If not, I'd like to take care and be part of the changes.

**Comment by Carlexos765** [comment]
> The current documentation consisted of a bunch of unclickable links adding no value to the user experience while reading.

**Comment by thebarshablog** [comment]
@Carlexos765 Hi, I'm not able to read the comment you dropped in because I'd closed the pull request way before. Please comment down if you would like to say something.

**Comment by cmwilson21** [comment]
@thebarshablog Thanks for checking in! 👋

I'm wondering if perhaps it was the .md file you may have been viewing vs the document in production. I checked the article [here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) and everything appeared to be rendering correctly. The .md file builds the production page and utilizes many reusables and formatting tools that render in production.

I hope that information is help 💛

**Comment by thebarshablog** [comment]
@cmwilson21, thank you for the response ☺️

**Pull request closed without merging**
