### PR TITLE
Fix broken link on liquid helpers

### PR DESCRIPTION
**Pull request by WilliamChang80**
## Why:
I get 404 when open liquid helpers page from contributing.md

### What's being changed:
Fix path for liquid helpers

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much @WilliamChang80! I'll update the branch and get this merged as soon as tests are green 🍏

**Review by janiceilene — APPROVED** [review]

**Comment by WilliamChang80** [comment]
Is there any problem with the CI? It takes too long for caching node_modules

**Comment by nschonni** [comment]
@WilliamChang80 hitting the branch update button may unstick it

**Comment by WilliamChang80** [comment]
@janiceilene ready to merge

**Pull request merged**
