### PR TITLE
Fix port number in the docs

### PR DESCRIPTION
**Pull request by mehran-prs**
=

### Why:

To Fix a single-word typo.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The port number in bookmarklet docs changed from `400` to `4000` because I think it was a typo. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by BINSAAD2030** [comment]
Thankswww.ziljah.com-------- الرسالة الأصلية --------من:‏ "welcome[bot]" ***@***.***>التاريخ:‏ الجمعة، 23 ديسمبر، 2022 11:12 صإلى:‏ github/docs ***@***.***>نسخة إلى:‏ Subscribed ***@***.***>الموضوع:‏ Re: [github/docs] Fix port number in the docs (PR #22831)
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.

**Comment by mehran-prs** [comment]
Hi @cmwilson21 
Could you tell me the reason of marking this PR as spam please?
I think the port number should be `4000` really, am I wrong?

**Comment by cmwilson21** [comment]
@mehran-prs Thanks for reaching back out. This PR was not marked as spam or closed by us, but a different comment was. This PR showed that it was self closed on Dec. 23rd, so it did not make it to the triage process. 

This appears to have been a mistake so I'm happy to reopen this and get it triaged for review ✨

**Review by cmwilson21 — APPROVED** [review]
Great catch! 🚢

**Comment by cmwilson21** [comment]
Great catch, thanks for the update on localhost:4000! I'll get this merged once all the checks have passed ✅

**Review by lecoursen — APPROVED** [review]

**Pull request merged**
