### PR TITLE
Added a note about the limitation for the event_type value of the repository_dispatch event

### LINKED ISSUE #16409: Document limitations for the `event_type` length of the `repository_dispatch` event
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

1. [Events that trigger workflows: `repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)
1. [Create a repository dispatch event: Parameters](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event--parameters)

### What part(s) of the article would you like to see updated?

Add a note to both articles telling that the `event_type` value is limited to 100 characters.

**I can fix the docs on my own**. However, I need guidance on how to add the note to the second page (Create a repository dispatch event: Parameters). It seems like API reference is generated automatically, as I can see only pre-made JSONs like, for example, `api.github.com.json` in the `lib/rest/static/decorated`

----

There is a related issue #15710 - I can fix it as well. Please assign it to me.

### Additional information

```
{
    "message": "Invalid request.\n\nOnly 100 characters are allowed; 101 were supplied.",
    "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-dispatch-event"
}
```

Related issue: #15710

### PR DESCRIPTION
**Pull request by bandantonio**
### Why:

Closes #16409 

### What's being changed:

* added a note about the limitation for the `event_type` value of the `repository_dispatch` event

event_type-limitation

### Check off the following:

- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@bandantonio please leave a comment when this PR is converted to "Ready for review" so I can get notified 💖

**Comment by bandantonio** [comment]
@ramyaparimi This PR is ready review

**Comment by ramyaparimi** [comment]
@bandantonio 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by lucascosti — APPROVED** [review]
Thanks for this clarification, @bandantonio!

**Pull request merged**
