### PR TITLE
Update getting-started-with-github-copilot.md

### PR DESCRIPTION
**Pull request by kahlan88**
Add extra info to the authorization in VSCode - in case the auth pop up doesn't show automatically.

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Cmcxxx** [comment]
Thank you for making this

**Review by Cmcxxx — COMMENTED** [review]
Thank u

**Comment by cmwilson21** [comment]
@kahlan88 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by sophietheking** [comment]
@kahlan88 Thanks for opening a PR! I think it would be a good to add a screenshot, I created one:

vscode-bell-icon

Could you add it? 😄

**Comment by kahlan88** [comment]
> @kahlan88 Thanks for opening a PR! I think it would be a good to add a screenshot, I created one:
> 
> vscode-bell-icon
> Could you add it? 😄 You can add the image to `/assets/images/help/copilot/`.

I think it's done now 😸

**Comment by kahlan88** [comment]
There's a failing check on this PR, not sure if I can do anything to resolve it.

```
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/@primer%2freact: aborted
npm ERR! network This is a problem related to network connectivity.
```

I just updated checklist and got the branch up to date, so apart from that, it's ready to go :-)

**Comment by kahlan88** [comment]
Is there anything else you need from me to complete this?

**Review by sophietheking — APPROVED** [review]
@kahlan88 Apologies for not getting back to you sooner, I missed the notification. I updated the sentence slightly for clarity and made sure all tests are passing. Let's get this merged! 🚀

**Pull request merged**
