### PR TITLE
Fix broken internal link

### PR DESCRIPTION
**Pull request by TyMick**
I'll mark this "ready to review" once I have time to fill out the below template. It should be ready to go, I just want to respect the process.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @TyMick Thanks for opening a PR and letting me know about the draft. We really appreciate you taking the time to fill in the info! 💖

**Comment by aitemour79** [comment]
Bouddi OK tomorrow

**Review by PIYUSH-MISHRA-00 — COMMENTED** [review]
wrong link directive corrected

**Comment by cmwilson21** [comment]
👋 @TyMick Just checking in to see if this PR is ready for review? 👀

**Comment by PIYUSH-MISHRA-00** [comment]
> wave @TyMick Just checking in to see if this PR is ready for review? eyes

all the checks have been passed must have been merged till now...

**Review by PIYUSH-MISHRA-00 — COMMENTED** [review]
Link directive is corrected.

**Pull request closed without merging**
