### PR TITLE
Actions: Add examples for shells other than Bash

### PR DESCRIPTION
**Pull request by Simran-B**
### Why:

#253

### What's being changed:

- Add examples for PowerShell Core, Windows `cmd` and Python
- Unify headlines of existing examples
  - bash = Bash
  - pwsh = PowerShell Core
  - cmd = Windows `cmd`
  - python = Python
- Minor markup improvements

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Simran-B** [comment]
Note to self: need to test YAML examples in `content\actions\reference\workflow-commands-for-github-actions.md` with different shells.

**Comment by janiceilene** [comment]
@Simran-B Let me know when you're ready for reviews ✨

**Comment by janiceilene** [comment]
@Simran-B I'm going to toss a `never-stale` label on this one, then you can ping me when you're ready for review without getting stale pings while you're working on it ⚡

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by janiceilene** [comment]
😭 Stop it stalebot!

**Comment by Simran-B** [comment]
Having a headline above each example for every shell type is pretty messy. My idea was to use tabs, but that's apparently not going anywhere (https://github.com/github/docs/pull/1606#issuecomment-813382840). I'm waiting for an alternative.

**Review by roythearsonist — APPROVED** [review]
Looks good

**Review by SirJosh1987 — APPROVED** [review]

**Review by SirJosh1987 — APPROVED** [review]

**Review by ivan0117 — APPROVED** [review]
P

**Review by ivan0117 — APPROVED** [review]
P

**Review by DoctorSky1967 — APPROVED** [review]

**Review by SirJosh1987 — APPROVED** [review]

**Comment by ramyaparimi** [comment]
@Simran-B Just checking to see if you have any update on this PR 😄

**Comment by DoctorSky1967** [comment]
You're wellcome

 Dr.Sky

**Review by SirJosh1987 — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks so much for working on this PR! It looks like work is paused, so I'm going to close the PR to remove it from our actively tracked backlog. If you'd like to continue work on it at anytime please let us know and we'll be happy to reopen it!

**Review by faxfoxbaxbox — COMMENTED** [review]
#12073 #12077 #12075 #11851 #12076

**Review by faxfoxbaxbox — COMMENTED** [review]
# # #12076 #11851 #12075 #12077

**Pull request closed without merging**
