### PR TITLE
Added quotation marks

### PR DESCRIPTION
**Pull request by OfficialMuffin**
When signing commits with git commit. User needs to specify the commit message within quotation marks.

### What's being changed:

Small typo error

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by BIOSTYMA — COMMENTED** [review]
G. Job

**Review by BIOSTYMA — COMMENTED** [review]
Jjjj

**Review by BIOSTYMA — COMMENTED** [review]
Ggg

**Review by BIOSTYMA — COMMENTED** [review]
Geeg

**Comment by ramyaparimi** [comment]
@OfficialMuffin 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by OfficialMuffin** [comment]
Only a little fix :3

**Review by ramyaparimi — APPROVED** [review]
@OfficialMuffin 
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by tebibu654** [comment]
?

**Pull request merged**
