### PR TITLE
updated the section links

### PR DESCRIPTION
**Pull request by wonntann**
Wanted to add png from the blog https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/ but uploads are disabled in the images folder.
It would be beneficial to have this note regarding the Table of Contents.

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@wonntann 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by felicitymay** [comment]
@wonntann - Thanks for adding this information to the docs. Great call. 💖 

After looking at this, I suggest that we add this new content as a new section "Table of contents" and put it after "Headings", since it's determined by the number of headings you add. I'll edit the PR accordingly and see if I can add an image of the button.

**Comment by felicitymay** [comment]
@wonntann - it looks as if I don't have access to edit your PR. Can you enable the checkbox to allow maintainer edits? Then I'll be able to update your PR and get it ready to merge. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by wonntann** [comment]
Thank you for looking into this matter, I will try to get to it this afternoon!

**Comment by wonntann** [comment]
Hi there, thank you for your patience. I was unable to access that pull request again, and since I do not have permission to push a branch, I created a new repo https://github.com/wonntann/add-headings-toc-image with the title that you were recommending. Please let me know if you need anything further from me.

**Comment by felicitymay** [comment]
@wonntann - thanks for your patience too. It looks as your fork of this repository, that you used to create this pull request, was deleted on GitHub somehow:

image

I think this explains why you weren't able to access the pull request or push to the branch 😞

**Comment by felicitymay** [comment]
Thanks so much for your time and patience in contributing to GitHub docs. Seems like your repository for this PR was deleted somehow. Because of that, we won't be able  to merge or make any changes to this PR. I can see that we have two options now:

1. You can make changes in a new fork of this repository and open a new PR.
2. One of the maintainers can close this PR and make the changes you suggest internally.

If you would like to open a new PR with the changes, please post the link here. Let us know how you would like to proceed with the changes.

**Comment by ihantoh** [comment]
Done

**Comment by wonntann** [comment]
Hi @felicitymay I put in a new pull request to the respective area within the docs. Here is the pr https://github.com/github/docs/pull/15218
I didn't add the image within the folder, since I do not have permission to edit the folders, I added the image via the link from the gh blog post.
Thanks!

**Comment by felicitymay** [comment]
Hi @wonntann - thank you so much for the second PR. I've reviewed the new PR and it will be ready to merge once we've sorted out the image 💖 

Closing this PR in favor of: https://github.com/github/docs/pull/15218.

**Pull request closed without merging**
