### PR TITLE
Avoid linting issues with Super-Linter

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
### Why:

Copying and pasting this command will make Super-Linter complain like:
```
  2024-09-19 08:35:15 [INFO]   Command output for GITHUB_ACTIONS:
  ------
  .github/workflows/deploy.yaml:27:9: shellcheck reported issue in this script: SC2086:info:11:16: Double quote to prevent globbing and word splitting [shellcheck]
     |
  27 |         run: |
     |         ^~~~
```

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Enclosing the `GITHUB_PATH` between double quotes.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@sebastian-luna-valero Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by Wayo965op** [comment]
> ### Why:
> Copying and pasting this command will make Super-Linter complain like:
> 
> ```
>   2024-09-19 08:35:15 [INFO]   Command output for GITHUB_ACTIONS:
>   ------
>   .github/workflows/deploy.yaml:27:9: shellcheck reported issue in this script: SC2086:info:11:16: Double quote to prevent globbing and word splitting [shellcheck]
>      |
>   27 |         run: |
>      |         ^~~~
> ```
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Enclosing the `GITHUB_PATH` between double quotes.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
sebastian-luna-valero:patch-1

**Review by Rina485 — COMMENTED** [review]
#34690

**Comment by nguyenalex836** [comment]
@sebastian-luna-valero Thank you so much for your patience while our SME team reviewed! They've approved of your changes, and I'll get this merged shortly 💛

**Review by nguyenalex836 — APPROVED** [review]

**Pull request merged**
