### PR TITLE
Correct CRE terminology for GitHub Premium Support

### LINKED ISSUE #7973: Correct Premium Support role name
### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-server/admin/enterprise-support/overview/about-github-enterprise-support#about-github-enterprise-support

### What part(s) of the article would you like to see updated?

GitHub Premium Support does not include Technical Account Managers (TAM), but rather offers a Customer Reliability Engineer (CRE) to work with customers entitled for GitHub Premium Plus Support.

### Additional information

This adds alignment with other documentation outlining the GitHub Premium Support offerings.

### PR DESCRIPTION
**Pull request by maclarel**
### Why:

This corrects the naming of one of the deliverables in the GitHub Premium Support programs.

Fixes https://github.com/github/docs/issues/7973.

### What's being changed:

GitHub Premium Support does not include Technical Account Managers (TAM), but rather offers a Customer Reliability Engineer (CRE) to work with customers entitled for GitHub Premium Plus Support.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@maclarel Thanks so much for opening this PR! I will triage it for review ⚡

**Review by systemespectr — APPROVED** [review]

**Review by jmarlena — APPROVED** [review]
@maclarel Thanks for your patience. This PR looks ready to ship! 🚢

**Comment by hoantrieu-code** [comment]
Hay

**Comment by 09115522240** [comment]
در تاریخ جمعه ۲۰ ژانویهٔ ۲۰۲۳،‏ ۰۱:۴۶ hoantrieu-code <
***@***.***> نوشت:

**Comment by hoantrieu-code** [comment]
Hay

**Pull request merged**
