### PR TITLE
Create my-first-branch

### PR DESCRIPTION
**Pull request by Bashirsaba**
I have created a new branch, created a file, and made a commit!

### Why:

Closes:

### Check off the following:

- [x] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [x] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [x] All CI checks are passing.

### CODE REVIEW

**Comment by Bashirsaba** [comment]
PROFILE.md

**Comment by Bashirsaba** [comment]
PROFILE.md

**Review by lalithaar — COMMENTED** [review]
Congratulations on creating a branch, for practising the GitHub skills - you can create a original repo where you can modify and practise writing in markdown, pull requests etc 

A pull request to the GitHub docs might be rejected because it's not relevant to it.

All the very best

**Review by forthegood1515 — COMMENTED** [review]
Submit The review.

**Pull request closed without merging**
