### PR TITLE
Remove example from `workflow-dispatch-inputs` reusable

### LINKED ISSUE #24501: Unnecessary and duplicate `workflow-dispatch-inputs-example.md` file
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows

### What part(s) of the article would you like to see updated?

Going through the docs, I noticed that the example used to define inputs for manually triggered workflows is duplicate and serves no extra purpose.

Looking at the docs this extra example comes from file [`workflow-dispatch-inputs-example.md`](https://github.com/github/docs/blob/main/data/reusables/actions/workflow-dispatch-inputs-example.md) and was just added [last month](https://github.com/github/docs/commits/main/data/reusables/actions/workflow-dispatch-inputs-example.md) for some reason.

### Additional information

If you look at the video, except spacing of `options` values, both are same example

https://user-images.githubusercontent.com/46301285/225749771-16ed2877-aa99-4f63-a211-c0b31100f15b.mp4

### PR DESCRIPTION
**Pull request by Drarig29**
### Why:

Closes: https://github.com/github/docs/issues/24501

### What's being changed (if available, include any code snippets, screenshots, or gifs):

If you look at [where this reusable is used](https://github.com/search?q=repo%3Agithub%2Fdocs+workflow-dispatch-inputs&type=code), it's always followed by the `workflow-dispatch-inputs-example` reusable.

In one place though, we have a `#### Example` between `workflow-dispatch-inputs` and `workflow-dispatch-inputs-example`, so it's not possible to just remove `workflow-dispatch-inputs-example` and keep `workflow-dispatch-inputs` **with the example inside**.

https://github.com/github/docs/blob/30d6875223e9030de33ebbe8d37b6ebc3355c706/content/actions/using-workflows/workflow-syntax-for-github-actions.md?plain=1#L203-L209

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Drarig29** [comment]
cc. @cmwilson21 😄

**Comment by cmwilson21** [comment]
@Drarig29 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by SiaraMist — APPROVED** [review]
This looks great to me, thank you for making this fix @Drarig29! ⚡ I'll go ahead and get this merged.

**Comment by Koms22** [comment]
جيد

**Pull request merged**
