### PR TITLE
Actions: Various fixes for migration pages

### PR DESCRIPTION
**Pull request by Simran-B**
### Why:

Some of the code examples on [Migrating from Jenkins to GitHub Actions
](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-jenkins-to-github-actions#examples-of-common-tasks) have wrong indentation and there are issues with the styling of code blocks in tables:

image

### What's being changed:

- Improve and fix indentation of code examples
- Remove unnecessary whitespace
- Replace erroneous curly brace with parenthesis in Jenkins example (I'm not sure if the closing parenthesis can actually be placed on a new line, but I would be surprised if not)
- Override the `.markdown-body table code` SCSS style so that for `.markdown-body table pre > code` no padding and background-color is applied, which leads to a slightly indented first code line and a dark gray background even though there is a light gray background already. There is a related style in [primer](https://github.com/primer/css/blob/4d128a79418a03f4d6d1d1f85ebdf17a22a14b6e/src/markdown/code.scss#L20-L34), but I don't think that it can/should be used here.
- Improve Markdown table markup (whitespace)

image

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much @Simran-B! I'll get this triaged for review 🎉

**Comment by Simran-B** [comment]
What's the status on this PR? Was it rejected?

**Comment by janiceilene** [comment]
Sorry about that @Simran-B! That was my miss and stalebot closed it 💛 We're updating stalebot so that it's less noisy and doesn't close things that are waiting on review 😅

**Review by lucascosti — APPROVED** [review]
Thanks sooo much for these fixes, @Simran-B! ❤️ 

The content changes look great 👍 .

The CSS fix also looks good to me, but I'll get someone from the @github/docs-engineering to have a 👀 too to approve that change before we merge this.

**Review by JasonEtco — APPROVED** [review]
CSS change looks great to me, thanks for that fix!

**Pull request merged**
