### PR TITLE
Added missing step to auto-merge to ensure auto-merge is enabled in settings

### PR DESCRIPTION
**Pull request by samsmithnz**
### Why:

Auto-merge documentation is incomplete. It doesn't explain you need to enable auto-merging in settings to use.

(no open issue currently)

### What's being changed:

Additional step to docs to enable auto-merge in settings. Note: open to feedback here. It might make sense for this to be a separate "note: ensure this is enabled in settings" section, instead of being part of the 1,2,3

Note that a screenshot to the settings artifact already existed, so I linked to this in my content updates too: 
[Enable auto-merge](https://github.com/github/docs/blob/main/assets/images/help/pull_requests/allow-auto-merge-checkbox.png)

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
  - [direct link to new docs](https://docs-3623--patch-1.herokuapp.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request#enabling-auto-merge)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@samsmithnz Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by ADIK171191** [comment]
request

**Review by ghost — APPROVED** [review]
req

**Review by ghost — CHANGES_REQUESTED** [review]
request

**Review by Rafael69f — APPROVED** [review]

**Comment by lucascosti** [comment]
👋 @samsmithnz, thanks a lot for this PR!

We already have a separate article that shows setting up auto-merge on a repository: "[Managing auto-merge for pull requests in your repository](https://docs.github.com/en/github/administering-a-repository/managing-auto-merge-for-pull-requests-in-your-repository).", and we mention the requirement of enabling it first on the repo and link to that at just a little higher on the page:

image

I think this probably covers things, but thanks a lot for your interest in helping improve our docs!

**Comment by samsmithnz** [comment]
Thanks, happy for this to be closed, looks like I missed that link. Thank you!

**Pull request closed without merging**
