### PR TITLE
add section for creating projects using api

### LINKED ISSUE #19096: add section for "creating projects" using api
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Under the heading [`using the API to manage projects (beta)`](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects), add a sub-section with an example demonstrating "creating projects (using APIs)," because there are mutation apis available for ProjectV2 for creating a new project, [`mutations#createprojectv2`](https://docs.github.com/en/graphql/reference/mutations#createprojectv2), and having an example for its usage would be helpful.

Screenshot 2022-07-18 at 3 18 30 PM

### What changes are you suggesting?

Add a section with an example to create GitHub Project Beta using api

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Priyankasaggu11929**
### Why:

Closes https://github.com/github/docs/issues/19096

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The PR add a sub-section with an example demonstrating "creating projects (using APIs), under the heading [`using the API to manage projects (beta)`](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects),  as there are mutation apis available for ProjectV2 for creating a new project, [mutations#createprojectv2](https://docs.github.com/en/graphql/reference/mutations#createprojectv2), and having an example for its usage would be helpful.

The output (obtained from staging preview) looks as follows:

#### GitHub CLI section

Screenshot 2022-07-19 at 10 38 29 AM

#### Curl section

Screenshot 2022-07-19 at 10 38 12 AM

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Priyankasaggu11929 Thanks so much for opening a PR and linking it to your issue! ✨

I'll get this triaged for review :zap:

**Comment by stevecat** [comment]
Hey @Priyankasaggu11929, thanks so much for adding information about creating projects! ✨ 

Can you enable the checkbox to allow maintainer edits? We've rearranged the category recently so there's a few conflicts to fix and things to tweak before I can get this merged. Thank you! 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Priyankasaggu11929** [comment]
Hello @stevecat, apologies for the late response. I was traveling for past days. :)

I just verified that the checkbox for maintainers edit is already checked. Please point me if there's something I should do to help move the PR forward. Thank you!


Screenshot 2022-09-20 at 10 13 37 PM

**Comment by stevecat** [comment]
Hey @Priyankasaggu11929, my apologies, you're absolutely correct! There was an unrelated issue on my end stopping me from pushing to your branch 😄 

I've fixed the conflict by moving your changes to the new article's new location (`content/issues/planning-and-tracking-with-projects/automating-your-project/`) and I've made a few tweaks. I've also moved your work into a new "Managing projects" section that we might expand upon and I've added some instructions for organization owners too; the /users endpoint will return the node ID for organizations *and* users so it was just a small change.

Thanks again for your contribution! I'll get this approved and merged in shortly ✨ :tada:

**Review by guntrip — APPROVED** [review]

**Pull request merged**
