### PR TITLE
Typo in the example code

### PR DESCRIPTION
**Pull request by ariG23498**
A small typo in the comments.

### Why:
I am suggesting this change becuase I have found a small `typo` in the code. The `latest ubuntu` did not have the `t` in place. 

### What's being changed:
A spelling mistake is being taken care of. In the github actions quickstart guide, the spelling of `latest` has a missing `t`.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@ariG23498 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janiceilene** [comment]
Thanks for your patience @ariG23498! Our small team is working our way through all the amazing contributions ✨

**Comment by ariG23498** [comment]
Thank you for the reply. I am eager to getting this PR merged :smile:

**Review by shati-patel — APPROVED** [review]
Thank you for fixing the typo, @ariG23498! We really appreciate all these contributions to help improve our docs 😊 

I'll get this merged shortly!

**Pull request merged**
