### PR TITLE
Fix typo: `sponsoring-an-open-source-contributor.md`

### PR DESCRIPTION
**Pull request by omarcostahamido**
- fix typo.

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@omarcostahamido Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by sophietheking — APPROVED** [review]
@omarcostahamido Thanks for opening this PR and contributing to our Docs, we really appreciate it! 🎉  This change looks good to me, so I'll go ahead and get this merged.

**Comment by omarcostahamido** [comment]
Dear @cmwilson21 and @sophietheking thank you very much for accepting my contribution to the docs.
I was carefully reading through it as I was also trying to finally set up `github sponsorships` for my github profile.
Fingers crossed it'll be approved:

Screen Shot 2023-08-15 at 12 51 20 PM

I'm still not entirely sure how to configure the tiers (in terms of $$ and perks). So I've left them unpublished before submitting for review. I hope that will not be a negative point. When I click the `preview profile` it looks like this:

Screen Shot 2023-08-15 at 12 55 25 PM

Best,
OCH

**Comment by cmwilson21** [comment]
@omarcostahamido Thanks again for the PR updating the docs! If you haven't yet, check out the docs around [sponsorship and tiers](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account#creating-sponsorship-tiers). If you run into any additional problems, please reach out to our awesome [support team](https://support.github.com/request) 👍

**Pull request merged**
