### PR TITLE
Update managing-environments-for-deployment.md to clear wording ambiguity

### PR DESCRIPTION
**Pull request by KennanHunter**
### Why:

The previous wording made it sound like the only way to make an environment secret in a public repo was to be on the GitHub free plan. While minor, my sleep deprived eyes took an extra few seconds to parse it correctly.

Closes:

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Just a wording change.

### Check off the following:

- [ ] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [ ] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [ ] All CI checks are passing.

### CODE REVIEW

**Comment by Sultan0901** [comment]
[Add docs-internal PRs to the docs-content FR project v2](https://github.com/github/docs/actions/workflows/first-responder-v2-prs-collect.yml)

**Comment by Sultan0901** [comment]
[Add docs-internal PRs to the docs-content FR project v2](https://github.com/github/docs/actions/workflows/first-responder-v2-prs-collect.yml)

**Comment by Sultan0901** [comment]
[Add docs-internal PRs to the docs-content FR project v2](https://github.com/github/docs/actions/workflows/first-responder-v2-prs-collect.yml)

**Comment by Sultan0901** [comment]
[Add docs-internal PRs to the docs-content FR project v2](https://github.com/github/docs/actions/workflows/first-responder-v2-prs-collect.yml)

**Comment by Sultan0901** [comment]
KennanHunter:patch-1

**Comment by nguyenalex836** [comment]
@KennanHunter Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by subatoi — APPROVED** [review]
Many thanks @KennanHunter — I agree this is clearer so I'll get this merged for you now 👍

**Pull request merged**
