### PR TITLE
Update generating-a-new-gpg-key.md

### PR DESCRIPTION
**Pull request by frankely**
Removes $ from the code blocks.

When copying a code block from this section, the "$" is copied as the first character, which makes the copy feature less useful.

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by GodAlmighty777** [comment]
> Removes $ from the code blocks.
> 
> When copying a code block from this section, the "$" is copied as the first character, which makes the copy feature less useful.
> 
> 
> 
> ### Why:
> 
> Closes [issue link]
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> 
> 
> ### Check off the following:
> 
> - [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> - [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> 
> - [ ] This pull request impacts the contribution experience
>   - [ ] I have added the 'writer impact' label
>   - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")
> 
> 
> 
>

**Comment by cmwilson21** [comment]
@frankely Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by frankely** [comment]
@cmwilson21 sounds good! Thank you for reviewing this.

**Comment by tranthithoa0803** [comment]
Ok

**Comment by subatoi** [comment]
Thanks so much for opening an issue @frankely! I'm opening an internal issue right now to look at this.

Thank you for your interest and passion in improving the GitHub Docs :sparkling_heart:

**Pull request closed without merging**
