### PR TITLE
Update creating-redis-service-containers.md

### LINKED ISSUE #22661: Client.js does not match the current version of redis npm module
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

https://github.com/github/docs/blob/803715b128d5adf4f15e8e13bff2b0cfb86c66c1/content/actions/using-containerized-services/creating-redis-service-containers.md?plain=1#L279

### What part(s) of the article would you like to see updated?

Client.js, the example code for testing Redis service container, does not match the current version of  [redis](https://www.npmjs.com/package/redis) npm module. 

Currently, running `npm install redis` through terminal installs version 4.x(4.5.1) of redis by default. However, the Client.js code appears to have been written prior to redis v4.x. Comparing redis v4 and v3, the syntax and internal operation are completely different, as if creating a new package. For example, The redis v4 has been changed to operate asynchronously based on a promise object by default rather than based on a callback. More details can be found in the [v3 to v4 Migration Guide](https://github.com/redis/node-redis/blob/HEAD/docs/v3-to-v4.md).

Therefore, when the Client.js is executed on redis v4.x, the attached error occurs first, and other errors occur even if the legacy mode is applied like `createClient({ legacyMode: true })`. 

### Additional information

스크린샷 2022-12-13 오전 2 45 59

### PR DESCRIPTION
**Pull request by ChoHadam**
### Why:

Closes #22661 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I wanted the _client.js_ code to work with the current version(4.x) of [redis](https://www.npmjs.com/package/redis) npm module. So I modified it by the following steps.

**Step1** 
Modify _client.js_ code to operate while maintaining v3 syntax in v4 using legacy mode.
**Step2** 
Fix some comments in _client.js_ code.
**Step 3** 
Modify _client.js_ code to promise-based async code using ES6 and disable legacy mode.

Before creating this pull request, I followed the [guide](https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers) and created a Redis client in my workflow to make sure that the modified code works. You can see the results in the following Redis runner example.

[Redis runner example](https://github.com/ChoHadam/Copied.A.fume.Server/actions/workflows/Redis%20runner%20example.yml)
스크린샷 2022-12-13 오후 5 49 21

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by lilmac82** [comment]
Stop

**Review by n6wbb6 — COMMENTED** [review]
Appove

**Review by hubwriter — APPROVED** [review]
This looks like a good update to me. 👍 
Many thanks for doing this @ChoHadam. 
Apologies it has taken so long to get this reviewed.

**Comment by ChoHadam** [comment]
Hi @hubwriter , I'm hadam.👋🏻  I'm one of the favorite readers of github docs.
Thank you for merging this PR! I have some questions about your review.

Can you please let me know why it took so long for this PR to get reviewed?
I just wonder if  there wasn't enough time to review, or if there was difficulty to understand my PR (e.g. poor readability, lack of my English skills). 

And I'm also curious why my PR was able to be merged all at once without much feedback.

This is my first open source contribution, so I think your comments will help me make better contributions in the future. 😊

**Comment by hubwriter** [comment]
Hi there @ChoHadam 👋 

Apologies again that this PR went un-reviewed for so long. We usually review open-source contributions a lot quicker. Unfortunately, this one sat in our review backlog for a long time. There was no particular reason for this - just that we're a little under-staffed in the internal Docs team that reviews all PRs in this repo.

Because you provided great information about the reason for the change, in the issue you raised, and evidence of testing your work, I was able to merge this PR without asking for further work. This doesn't always happen but I was glad that, after leaving this in the backlog for so long, I was able just to go ahead and merge it.

I hope this doesn't put you off making further contributions to the GitHub docs in future. We really appreciate your work helping to keep the docs up to date. 🙇‍♂️

**Comment by ChoHadam** [comment]
Thank you for your reply @hubwriter .
It was nice talking with you. It means a lot to me 😊  
Have a nice day ☀️

**Pull request merged**
