### PR TITLE
Add content - configure subdomain for github pages site that was built using actions workflow

### LINKED ISSUE #26014: Configuring custom domain for github pages site that was built remotely
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

### Details
- When deploying to github-pages environment using a GitHub Actions workflow, current docs do not describe a way to authenticate the **subdomain**
- Current docs method (point 8) creates a CNAME file, it only covers use case of deploying GitHub Pages from a branch

### Supported use case
- Using a static site generator and GitHub Actions workflow to build and remotely publish to github-pages environment for GitHub Pages

### Outcome
- After testing, I got it to work by authenticating just the subdomain in user settings as stated here https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-user-site
- To build and deploy files with GitHub Actions workflow, create cname record with dns provider, then authenticate subdomain in user settings 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brianwaithaka**
### Why:
Current docs do not cover use case where using a static generator and a custom GitHub Actions workflow builds and publishes directly to github-pages environment

Since workflow builds and deploys directly, adding a cname file only covers use case of deploying GitHub Pages from a branch

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

Closes: #26014 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

- Changing this doc by adding a new entry under point 8
- Adding a reusables.pages.build-remotely-verify-subdomain file with the actual text

Screenshot 2023-06-15 at 10 19 52

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@brianwaithaka Thanks so much for opening a PR! We appreciate the extra context and screenshot! ✨ 

I'll get this triaged for review :zap:

In the meantime, if you're looking for other contributions, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍

**Comment by cmwilson21** [comment]
@brianwaithaka Checked in with the team on this one, this is a good point but the PR is somewhat incorrect. Point 8 in the doc page linked above does not apply to sites built with a custom workflow. Instead of storing the domain in a CNAME file, it needs to be done in the Pages settings. Linking to the domain verification doc is a good general call out but it does not describe how to associate a custom domain with a site, only how to verify a domain. 

Can you update the PR to reflect the team feedback?

**Comment by cmwilson21** [comment]
👋 Forgot to mention, ping me here in the issue when the updates have been made and I'll get the review process started on it again ✨

**Comment by brianwaithaka** [comment]
Well noted, I will update accordingly

**Comment by brianwaithaka** [comment]
Hi @cmwilson21 , sorry for the delay. Just some clarification needed please. 

So issue was that when building the site and publishing directly to gh-pages env + setting up the subdomain in pages settings, i still could not get it to work. 
Docs only suggest cname file method which applies to deploying from a branch 

Therefore,  by verifying the subdomain under account settings, after setting it up in pages settings for the repo, it worked. Do you suggest this info be provided as a note or additional point under 8 in the #configuring-a-subdomain section ? [on this site](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)

Please guide since team feedback suggests scraping the point from here altogether and/or perhaps placing it under the [troubleshooting page](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#cname-errors)

**Comment by cmwilson21** [comment]
@brianwaithaka Thanks for following up with this! I think making it a note will do. The reviewer may have other thoughts but by committing that update, we can get it on the review board again 👀

**Comment by brianwaithaka** [comment]
Hello, @cmwilson21 , updates made. Please review

**Pull request closed without merging**
