### PR TITLE
Clarify GH password requirements

### LINKED ISSUE #1396: Password requirements are misleading
### What article on docs.github.com is affected?

[Creating a strong password](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-strong-password)

### What part(s) of the article would you like to see updated?

The password requirements are missing the phrase "at least". Without this phrase, it seems like the password requirements **must** be exactly eight or 16 characters long.

### PR DESCRIPTION
**Pull request by hongshaoyang**
### Why:

Closes #1396 .

### What's being changed:

The password requirements are missing the phrase "at least". Without this phrase, it seems like the password requirements must be exactly eight or 16 characters long.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@hongshaoyang Thanks so much for opening a PR! I'll get this triaged for review 🌟

**Comment by hongshaoyang** [comment]
@janiceilene any updates on this PR?

**Comment by janiceilene** [comment]
@hongshaoyang Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Review by shati-patel — APPROVED** [review]
Thank you very much for your change, @hongshaoyang! We really appreciate all the community contributions to help improve our docs 😊 

I'll get this merged shortly!

**Comment by hongshaoyang** [comment]
thanks @shati-patel

**Pull request merged**
