### PR TITLE
Closes Issue(31721): Added the link to What are your cookie choices and controls?

### LINKED ISSUE #31721: Typo in privacy policy
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[github-general-privacy-statement.md](https://github.com/github/docs/blob/6415c00c11eb55bf199ab319e0ce4568969aea4d/content/site-policy/privacy-policies/github-general-privacy-statement.md)

### What part(s) of the article would you like to see updated?

See

https://github.com/github/docs/blob/6415c00c11eb55bf199ab319e0ce4568969aea4d/content/site-policy/privacy-policies/github-general-privacy-statement.md?plain=1#L61

I'm pretty sure "this" should be a link to "What are your cookie choices and controls?"

### Additional information

These documents are great, thank you for making them available under a permissive license.

### PR DESCRIPTION
**Pull request by code-Gambler**
### Why:
The link to What are your cookie choices and controls? was missing, so added the link in the `content/site-policy/privacy-policies/github-general-privacy-statement.md` file
Closes: 
[31721](https://github.com/github/docs/issues/31721)

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Only a link to [this page](https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement#what-are-your-cookie-choices-and-controls) is being added

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@code-Gambler Thanks so much for opening a PR! Looks great to me - I'm going to ask our Site Policy team to review ✨ 

Internal: asked [here](https://github.slack.com/archives/C5EE6U8UV/p1708455966883359)

**Review by khxu — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@code-Gambler Thanks again for opening this PR! I'll update the branch and get this merged once tests are passing 🍏

**Comment by code-Gambler** [comment]
> Why have you included the full URL, not just the fragment?

I looked at other links, they had the whole URL, so I included the whole URL
Now when I checked back, I realized they were all leading to `github.com` due to which they had the full URL.
I should have included the fragment!

What do you guys suggest? Should I make a new PR with the fragments?

**Comment by samuelcolvin** [comment]
Should definitely just be the fragment as it's in the same file.

**Comment by code-Gambler** [comment]
> samuelcolvin

Submitted a new [pr](https://github.com/github/docs/pull/31767) with only the fragment!

**Pull request merged**
