### PR TITLE
Update detaching-a-fork.md

### PR DESCRIPTION
**Pull request by jkopczyn**
Clarify what to do with an error message about refusing to delete branches.

### Why:

Got a somewhat scary message when the repository was old enough to use `master` and the new copy used `main`. Add a warning about this for future reference.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Deleting a fork instructions; add a warning.

### Check off the following:

- [X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [X] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by Saminkamoje2810** [comment]
jkopczyn:patch-1

**Comment by jkopczyn** [comment]
I'm unclear on the linter's objection so I'll leave this for someone more familiar with the style guidelines to fix.

**Comment by nguyenalex836** [comment]
@jkopczyn Let me see if just updating the branch resolves 🤞 if not, one of our other team members can assist with the linter error upon reviewing this contribution 💛

**Comment by nguyenalex836** [comment]
@jkopczyn Thank you for your patience while the team reviewed! 
 
After review, we believe the issue may be caused by initializing the new repository (creating a README) rather than an empty one. 

If you can reach out to wonderful our [support team](https://support.github.com/request) to confirm this is correct and also a common problem, please let us know and we can work on making the "Create a repo" step clearer! ✨ 

For now, I'll close this issue - but feel free to reopen this whenever you have an update 💛 Thank you!

**Pull request closed without merging**
