### PR TITLE
Update review-template.md

### PR DESCRIPTION
**Pull request by kandeldeepak46**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by venomOZ431** [comment]
Adam Harden liked your email

**Comment by Joryt85** [comment]
On Sun, 6 Nov 2022 at 9:06 AM venomOZ431 ***@***.***> wrote:
Adam Harden liked your email


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- 90079955

**Comment by cmwilson21** [comment]
@kandeldeepak46 Thanks for opening this PR! However, we are not going to accept these changes. 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by Joryt85** [comment]
Sent from Outlook for Android<https://aka.ms/AAb9ysg>

**Pull request closed without merging**
