### PR TITLE
Use correct `standard` peer dependencies

### PR DESCRIPTION
**Pull request by voxpelli**
### Why:

dependabot can not help with updating from unmaintained modules to maintained forks, that needs manual intervention. This replaces the unmaintained (and for [`eslint-config-standard` incorrect](https://github.com/standard/eslint-config-standard/blob/e8e4738214273ef0870a04bd810a85e9d9aee497/package.json#L71)) [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) with the [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n) fork that's maintained by the [official ESLint Community org](https://github.com/eslint-community).

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Replace `eslint-plugin-node` with the now used official fork `eslint-plugin-n`.

Also update to latest version of `eslint-config-standard` and its peer dependencies.

Since it can be hard for users of `eslint-plugin-node` to find out that there's a maintained fork from the official [ESLint Community project](https://github.com/eslint-community) I'm doing a drive where I'm making PR:s to some projects to raise awareness.

See: https://github.com/eslint-community/eslint-plugin-n/issues/100

Disclaimer: I'm a co-maintainer of both `standard` and `eslint-plugin-n`

### Check off the following:

_Not applicable for this_

- [x] ~~I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.~~

  - ~~For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.~~
- [x] ~~For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).~~

### CODE REVIEW

**Review by Wdtwsm777 — COMMENTED** [review]
#698

**Review by Wdtwsm777 — COMMENTED** [review]
#27425

**Comment by peterbe** [comment]
Hej hej @voxpelli Thanks for the PR. 

The public `github/docs` repo is a copy of the private `github/docs-internal` repo which is where we do code changes. We do this for the sake of security. This way PR contributions to this public repo needs to be about *content* changes. But every now and then excellent OSS citizens like yourself come along and help out. Super appreciate it!
I'll copy this PR to our private repo and make sure it gets tested there first. Then it'll trickle in to this public repo. 

Tack för hjälpen!

**Comment by voxpelli** [comment]
@peterbe Makes sense, tack!

**Comment by cmwilson21** [comment]
@voxpelli Thanks for submitting this PR! Looks like the PR @peterbe submitted internally has been merged and the changes are now live in the repo. So I'm going to go ahead and close this out ✨ 

Thank you again for raising this! We appreciate your contribution to the docs!

**Pull request closed without merging**
