### PR TITLE
Add 'converted_to_draft' action to the pull request webhook payload documentation

### PR DESCRIPTION
**Pull request by recurser**
### Why:

See https://github.com/github/docs/issues/2416

> There is an `action` called `converted_to_draft` that is not documented here:
>
>> Can be one of `opened`, `edited`, `closed`, `assigned`, `unassigned`, `review_requested`, `review_request_removed`, `ready_for_review`, `labeled`, `unlabeled`, `synchronize`, `locked`, `unlocked`, or `reopened`.
>
> This is the reverse of the `ready_for_review` action that is already documented - triggered when a pull request is converted back to a draft.
>
> This has a follow-on effect in the [octokit/webhooks.js](https://github.com/octokit/webhooks.js/pull/399) library since the Typescript types are generated from Github documentation.

103186705-e07e4300-4904-11eb-9b5c-8c411d07b167

### What's being changed:

The `converted_to_draft` action has been added to the list of actions, in the base documentation ~~and existing translations~~.

Edit: I reverted the changes to the translations as [requested by the bot](https://github.com/github/docs/pull/2417#pullrequestreview-559386947).

See the updated documentation on the [Heroku review app here](https://docs-2417--add-converted-to-dr.herokuapp.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-31).

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Vargas11484 — APPROVED** [review]

**Comment by janiceilene** [comment]
@recurser Thanks so much for following the trail and opening an issue and PR 💖 I'll get this triaged for review!

**Comment by wolfy1339** [comment]
This isn't stale. Waiting on review from the required person/team

**Comment by wolfy1339** [comment]
This isn't stale. Waiting on review from the required person/team

**Comment by wolfy1339** [comment]
This isn't stale. Waiting on review from the required person/team

**Review by skedwards88 — APPROVED** [review]
🚀 Thank you for making this change and thank you for your patience while we work through reviews! I'll get this merged down for you.

**Comment by skedwards88** [comment]
Closes https://github.com/github/docs/issues/2416

**Pull request merged**
