### PR TITLE
Add GitHub Pages Action

### PR DESCRIPTION
**Pull request by peaceiris**
Pull-request for Issue #1303

### Why:

Add the [GitHub Pages Action] which is listed at the [Actions topic].

- [GitHub Pages Action]: peaceiris/actions-gh-pages - GitHub Actions for GitHub Pages: Deploy static files and publish your site easily. Static-Site-Generators-friendly.
- Actions topic: https://github.com/topics/actions

[GitHub Pages Action]: https://github.com/peaceiris/actions-gh-pages 
[Actions topic]: https://github.com/topics/actions

### What's being changed:

N/A

### Check off the following:

- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@peaceiris Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by RobertEmmettJones — APPROVED** [review]

**Comment by nitishgoukonde** [comment]
Why:
Add the GitHub Pages Action which is listed at the Actions topic.

GitHub Pages Action: peaceiris/actions-gh-pages - GitHub Actions for GitHub Pages: Deploy static files and publish your site easily. Static-Site-Generators-friendly.
Actions topic: https://github.com/topics/actions
What's being changed:
N/A

Check off the following:
 All of the tests are passing.
 I have reviewed my changes in staging.
 For content changes, I have reviewed the localization checklist
 For content changes, I have reviewed the Content style guide for GitHub Docs.

**Comment by peaceiris** [comment]
Updated!

**Comment by chiedo** [comment]
@simpsoka let us know what you think!

**Review by simpsoka — APPROVED** [review]
This looks great! Thanks for the add @peaceiris! :shipit:

**Comment by FREELANCEGITIT** [comment]
Am i this person? Lol
    On Thursday, December 10, 2020, 06:28:07 AM PST, Chiedo John <notifications@github.com> wrote:  
 
 


@simpsoka let us know what you think!

**Comment by simpsoka** [comment]
> Am i this person? Lol 

hahaha nope that's me :) 

just had a chance to review and I love it! gonna get this merged in

**Pull request merged**
