### PR TITLE
download an artifact from the same workflow run

### LINKED ISSUE #10269: essential-features-of-github-actions.md should explain how to download an artifact from the same workflow run
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

### What part(s) of the article would you like to see updated?

Missing these details

>To download an artifact from the same workflow run, your download job should specify `needs: upload-job-name` so it doesn't start until the upload job finishes.

### Additional information

Related to https://github.com/github/docs/pull/10268

### PR DESCRIPTION
**Pull request by achekery**
essential-features-of-github-actions.md should explain how to download an artifact from the same workflow run

### Why:

Closes https://github.com/github/docs/issues/10269

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@achekerylla 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by achekerylla** [comment]
My changes in staging look good to me. https://docs-10268--patch-2.herokuapp.com/en/actions/learn-github-actions/essential-features-of-github-actions

**Comment by achekerylla** [comment]
### Self review

You should always review your own PR first.

For content changes, make sure that you:

- [ ] Confirm that the changes meet the user experience and goals outlined in the content design plan (if there is one).
- [ ] Compare your pull request's source changes to staging to confirm that the output matches the source and that everything is rendering as expected. This helps spot issues like typos, content that doesn't follow the style guide, or content that isn't rendering due to versioning problems. Remember that lists and tables can be tricky.
- [ ] Review the content for technical accuracy.
- [ ] Review the entire pull request using the [localization checklist](contributing/localization-checklist.md).
- [ ] Copy-edit the changes for grammar, spelling, and adherence to the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).
- [ ] Check new or updated Liquid statements to confirm that versioning is correct.
- [ ] If there are any failing checks in your PR, troubleshoot them until they're all passing.

**Comment by achekerylla** [comment]
Localization checklist found here. Link from self review directions needs updating.

https://github.com/github/docs/blob/main/contributing/localization-checklist.md

**Comment by achekerylla** [comment]
Unintentionally changed name of this PR. Restored to original name.

**Review by Boradeus — COMMENTED** [review]
achekerylla:patch-2

**Review by Marksmith1987 — APPROVED** [review]

**Review by HarryBO881 — APPROVED** [review]

**Comment by achekerylla** [comment]
>Merging is blocked

Anything that I can do to help?  @myoazwan95, @Marksmith1987 , @HarryBO881

**Comment by ramyaparimi** [comment]
@achekerylla An acceptable review comes from a member of the docs team and it says **member** on their profile 🐬  A green check mark appears only when a PR is approved by a docs team member ✅ Until then, you can ignore any comments and/or approvals from anyone else 💖

**Review by lucascosti — APPROVED** [review]
Thanks, @achekerylla! I'll get this merged in 🚢

**Review by Rkabako — COMMENTED** [review]
Good

**Review by Rkabako — COMMENTED** [review]
G234

**Review by Darius917 — COMMENTED** [review]
Improve existing content

**Comment by dr-suhadalishaheed** [comment]
Hi 
https://github.com/github/docs/pull/10268#

**Pull request merged**
