### PR TITLE
GitHub context fix

### LINKED ISSUE #10017: github.action description is wrong
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)

### What part(s) of the article would you like to see updated?

github.action description to match my [GitHub Action execution results](https://github.com/alvinseville7cf/GitHubContextTest/runs/3585538956?check_suite_focus=true).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
- script names fixed

### Why:

Closes #10017 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@alvinseville7cf 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by NizamShah7 — APPROVED** [review]

**Review by NizamShah7 — APPROVED** [review]

**Review by NizamShah7 — APPROVED** [review]
alvinseville7cf:patch-2

**Review by Luimoll — APPROVED** [review]

**Comment by emilyseville7cf** [comment]
I don't understand what I have to do now. Nothing? :)

**Comment by ramyaparimi** [comment]
@emilyseville7cf Yep!! Those workflows are waiting for an approval, so everything should run once the changes are reviewed and approved 👍 🐬 Thanks a bunch for your patience 💖

**Review by skedwards88 — APPROVED** [review]
🎉 Thanks for this correction! I'll get this merged down for you.

**Comment by ramyaparimi** [comment]
@emilyseville7cf It looks like I don't have permission to resolve the merge conflict. I think if you enable the checkbox to allow maintainer edits, then I will be able to resolve this. (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork ) Alternatively, could you resolve the merge conflict?

**Review by NizamShah7 — APPROVED** [review]

**Comment by ramyaparimi** [comment]
@emilyseville7cf The PR has some unresolved conflicts which is blocking the merge process 💛  Could you please try resolving the conflict by merging into your working branch from main? Once the conflicts are resolved, I will be able to merge this PR ✨ 

Thanks so much for your time in contributing to the GitHub docs 💖

**Review by Lakho145 — APPROVED** [review]

**Comment by emilyseville7cfg** [comment]
> Could you please try resolving the conflict by merging into your working branch from main?

Yeah, I can. I will to it as soon as possible.

**Review by Lakho145 — APPROVED** [review]

**Comment by emilyseville7cfg** [comment]
@ramyaparimi, everything is ready.

**Comment by ramyaparimi** [comment]
@emilyseville7cfg 
Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks so much for your patience 💖

**Comment by emilyseville7cfg** [comment]
@ramyaparimi, this checkbox (`Allow edits and access to secrets by maintainers`) is already enabled.

**Pull request merged**
