### PR TITLE
Update libraries.md to include python client for GitHub's REST API that uses the OpenAPI Spec

### PR DESCRIPTION
**Pull request by hamelsmu**
### Why:

Including a new python client that is using GitHub's newly published open api spec!

### What's being changed:  

Adding a new python client to the docs

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

cc: @jph00

### CODE REVIEW

**Review by dartie1987 — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks @hamelsmu! I'll get this triaged for review ⚡

**Review by Pakphum100 — COMMENTED** [review]
`[https://globalpts.playtimes.com/windows/index.php?exchangeRate=&dateTimeZone=&token=2a1cbf4919eafd2b187ddef594218a3be990ef83&bankId=itp&playerId=UFAKKAH5008&gameId=00601001005](https://globalpts.playtimes.com/windows/index.php?exchangeRate=&dateTimeZone=&token=2a1cbf4919eafd2b187ddef594218a3be990ef83&bankId=itp&playerId=UFAKKAH5008&gameId=00601001005) `

**Review by skedwards88 — APPROVED** [review]
Thanks for adding this @hamelsmu ! I'll get it merged.

**Review by Highaboveus2 — COMMENTED** [review]
Thanks

**Pull request merged**
