### PR TITLE
fix: remove duplicate step in getting started guide

### PR DESCRIPTION
**Pull request by vladdoster**
### Why:

Confusing for user to read.

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

GitHub copilot installation guide for Neovim.

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by vladdoster** [comment]
IMG_0445

**Comment by Ismaelkadir** [comment]
> 
> 
> ### Why:
> 
> Confusing for user to read.
> 
> Closes: 
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> GitHub copilot installation guide for Neovim.
> 
> 
> 
> ### Check off the following:
> 
> - [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> - [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 

😜

**Comment by Rhenzzo** [comment]
😉👌🙄🤫

**Review by atifnimran — COMMENTED** [review]
Ok thanks

**Review by steveward — APPROVED** [review]
Good catch @vladdoster, and thanks for the PR! I'll get this merged.

**Pull request merged**
