### PR TITLE
Remove 'your key must use RSA' for generating new GPG key

### LINKED ISSUE #20379: GPG supported key algorithms
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

### What part(s) of the article would you like to see updated?

#generating-a-gpg-key

In the `supported-gpg-key-algorithms` section, it shows Github supports a list of algorithms including RSA. 

However in the `generating-a-gpg-key` section, it says 'Your key must use RSA', which suggests it is RSA only,  and contradicts with `supported-gpg-key-algorithms` section.

I didn't test the real behaviors, so not sure which one is outdated. But I expect to see them aligned or provided some context on why we must use 'RSA'.

### Additional information

Screen Shot 2022-09-03 at 12 14 53

### PR DESCRIPTION
**Pull request by Zhong-z**
### Why:
In the `reusables.gpg.supported-gpg-key-algorithms` section, it shows Github support more than `RSA`. However when generating a new key, we 'must' use RSA, which seems contradicts each other.

The purposed change assumes `reusables.gpg.supported-gpg-key-algorithms` is the source of truth. 

Closes #20379

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removed `Your key must use RSA` sentence.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Zhong-z Thanks for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review ⚡

**Comment by Ameralkashaan** [comment]
في الخميس، ٢٧ أكتوبر ٢٠٢٢, ٠٤:٥٣ chupapimunyanyl ***@***.***>
كتب:

**Comment by arthha** [comment]
> ### Why:
> In the `reusables.gpg.supported-gpg-key-algorithms` section, it shows Github support more than `RSA`. However when generating a new key, we 'must' use RSA, which seems contradicts each other.
> 
> The purposed change assumes `reusables.gpg.supported-gpg-key-algorithms` is the source of truth.
> 
> Closes #20379
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Removed `Your key must use RSA` sentence.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Comment by japui-coder** [comment]
Remove 'your key must use RSA' for generating new GPG key #20380

**Comment by japui-coder** [comment]
This pull request impacts the contribution experience

**Review by rmjspaz — COMMENTED** [review]
#content/github/administering-a-repository/finding-information-in-a-repository/filtering-issues-and-pull-requests-by-assignees.md #

**Comment by Rt6812** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).
>

**Comment by isaacmbrown** [comment]
Hi @Zhong-z, you are right that this appears to be a contradiction in the article. I suspect the fix may need to be slightly more complex in the context of the procedure; we also say that `Your key must be at least 4096 bits.`, but, at least with the GPG software I was using, only the RSA algorithm could generate a key of this length. We'll need to clarify our requirements and recommendations here, so I'll reach out to someone internally and get back to your when I hear back.

**Comment by akingatwork** [comment]
Needs help with me

**Comment by Zhong-z** [comment]
@isaacmbrown Thanks for getting back me 😃. Deleted the key length sentence, please have another look. 👨🏼‍💻

**Review by isaacmbrown — APPROVED** [review]
Thanks for this @Zhong-z! Looks good to merge to me 🚀

**Pull request merged**
