### PR TITLE
Fix `at lease` instead of `at least` typo

### LINKED ISSUE #2020: Typo `at lease` instead of `at least`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#check_suite

### What part(s) of the article would you like to see updated?

`at lease` to `at least`

### Additional information

I tried making a PR with the required modifications but it seems we are not allowed to make a PR with those modified json files: https://github.com/github/docs/pull/22952/files

### PR DESCRIPTION
**Pull request by Greesb**
### Why:

There are multiple typos

Closes github/rest-api-description#2020 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Changed all occurrence of `at lease` to `at least`

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by ProKashif — COMMENTED** [review]
LGTM

**Review by w455e — COMMENTED** [review]
what

**Comment by cmwilson21** [comment]
@Greesb - Thanks for opening an PR! I've made a slight edit to your post to link it to your issue. For more information on how to do that, see "[Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)". 👍 

I'll get this triaged for review! :zap:

**Comment by Zia4511** [comment]
(PR#22952)

**Comment by felicitymay** [comment]
Hi @Greesb 👋🏻 

Many thanks for identifying this typo in the REST API docs 🙇🏻‍♀️ 

Our docs for the REST API articles are generated automatically from an OpenAPI schema, which is why your pull request triggered [the warning above](https://github.com/github/docs/pull/22952#issuecomment-1368847486). Having autogenerated docs makes it easier to ensure that they are updated whenever the API is updated, but does have the side effect that we'll need to fix this typo internally.

I'll trigger a workflow that will open an internal issue to fix this error.

**Comment by felicitymay** [comment]
Closing because this needs to be fixed in a different repository.

**Pull request closed without merging**
