### PR TITLE
Fix workflow in Actions 'Introductions' article

### LINKED ISSUE #7866: Following Github Actions tutorial but getting an npm EACCES error
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow

### Additional information

https://github.com/jsoref/188088/runs/2965080849?check_suite_focus=true

I followed the instructions:
1. I created a repository https://github.com/jsoref/188088
2. I went to https://github.com/jsoref/188088/new/main?filename=.github%2Fworkflows%2Fblank.yml&workflow_template=blank
3. I copy and pasted the filename and the contents from the help page
4. I clicked start commit
5. I pasted the url into the commit
6. I waited for the action to run and checked the results

It fails:
https://github.com/jsoref/188088/runs/2965080849?check_suite_focus=true

Precisely as reported here:
https://github.community/t/following-github-actions-tutorial-but-getting-an-npm-eacces-error/188088/1

Yes. I know how to do this right, but I should be able to follow the instructions (as @seddonr faithfully attempted) and get a working product.

### PR DESCRIPTION
**Pull request by lucascosti**
### Why:

Closes https://github.com/github/docs/issues/7866

### What's being changed:

Updates the workflow on the Actions 'Introduction' article to get it working again. This issue is seemed to be caused by the recent update of actions/setup-node to v2, which now prefers a `node-version` to be specified.

Tests:
Workflow: https://github.com/lucascosti/actions-public-playground/blob/85f97785dc883e5007634bd3e9c529a4a2d5fe03/.github/workflows/intro_article_test.yml
Workflow run: https://github.com/lucascosti/actions-public-playground/runs/3053584138?check_suite_focus=true

I also updated the workflow syntax article example to use checkout instead of setup-node, because the one-liner `checkout` is a better example as it doesn't require any inputs.

Stage links:

* https://docs-8141--lucascostifix-intro.herokuapp.com/en/actions/learn-github-actions/introduction-to-github-actions
* https://docs-8141--lucascostifix-intro.herokuapp.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Artek199 — APPROVED** [review]

**Comment by jsoref** [comment]
https://docs-8141--lucascostifix-intro.herokuapp.com/assets/images/help/images/overview-actions-result-updated-2.png

Shows `@v1`. And apparently this is using `@v2`.

**Review by 123MwanjeMike — APPROVED** [review]

**Review by martin389 — APPROVED** [review]
Looks good to me! 🎊

**Comment by lucascosti** [comment]
> https://docs-8141--lucascostifix-intro.herokuapp.com/assets/images/help/images/overview-actions-result-updated-2.png
> 
> Shows `@v1`. And apparently this is using `@v2`.

@jsoref Thanks for noticing; we don't always update minor details in screenshots if they're not crucial to understanding what we're documenting.

**Comment by jsoref** [comment]
@lucascosti: if `@v2` caused issues here, then I claim it's moderately important.

I understand not wanting to do random busywork, but if it's actually a key cause of a problem, then it might deserve an update.

**Comment by gsteele178** [comment]
I'll take a look at it

**Comment by lucascosti** [comment]
> @lucascosti: if `@v2` caused issues here, then I claim it's moderately important.
> 
> I understand not wanting to do random busywork, but if it's actually a key cause of a problem, then it might deserve an update.

@jsoref I understand your point, but I don't think people will be authoring the workflow based on the contents of that screenshot, so I don't think it's much of a risk. Feel free to retake the screenshot and submit and PR if you'd like 🙂

**Comment by gsteele178** [comment]
Echo user keystrokes!

**Comment by gsteele178** [comment]
A wise man once said play the fool, don't be the fool. For it will allow
you to fool

**Comment by gsteele178** [comment]
Tracking climate data has been UNREAL , it opened everything up

**Pull request merged**
