### PR TITLE
Update creating-a-pull-request-from-a-fork.md

### LINKED ISSUE #29279: In Creating-a-pull-request-using-fork.md file a particular statement needs an example to understand  for beginners.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Link to the article affected](https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork.md)

### What part(s) of the article would you like to see updated?

The Statement **If your pull request compares your topic branch with a branch in the upstream repository as the base branch, then your topic branch is also called the compare branch of the pull request** is a bit confusing to comprehend all in one read. Hence, to make it easy to understand a simple example below it would help. 
The example would help beginners more easily understand what is **topic branch, upstream repository, base branch, compare branch**.

### Additional information

I can work on this issue and create a **self-reviewed pull request**

### PR DESCRIPTION
**Pull request by Aviace**
Added a simple example below to easily comprehend the statement "If your pull request compares your topic branch with a branch in the upstream repository as the base branch, then your topic branch is also called the compare branch of the pull request".

### Why: The example would help beginners more easily understand what is "topic branch, upstream repository, base branch, compare branch".

Closes: [Issue-29279](https://github.com/github/docs/issues/29279)

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Screenshot 2023-10-20 023540

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Aviace** [comment]
> @Aviace Thank you for opening an issue and linking it to your PR! ✨
> 
> I'll get this triaged for review! ⚡
> 
> In the mean time, would you mind removing the `*` from the PR? Check out our style guide to see how we handle [branch names](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#branch-names) 👍

sure I will read the style guide and follow accordingly

**Comment by Aviace** [comment]
@cmwilson21 I have removed * from the PR.

**Comment by Aviace** [comment]
> > @Aviace Thank you for opening an issue and linking it to your PR! ✨
> > I'll get this triaged for review! ⚡
> > In the mean time, would you mind removing the `*` from the PR? Check out our style guide to see how we handle [branch names](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#branch-names) 👍
> 
> sure I will read the style guide and follow accordingly

@cmwilson21 I have done the necessary changes(removing * from PR). Do I have to create a new PR?

**Comment by Aviace** [comment]
I have created a new [PR] (https://github.com/github/docs/pull/29316) that passes all 43 checks and skips 4.

**Comment by sophietheking** [comment]
@Aviace 👋 I'll close this PR in favour of https://github.com/github/docs/pull/29316. For next time, feel free to make any edits directly in your existing PR, this way you don't have to open a new one. 😸

**Pull request closed without merging**
