### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Singh-csm**
### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Singh-csm** [comment]
update

**Comment by Njbabyyyy** [comment]
- - [ ] > @zeke []()

**Comment by Njbabyyyy** [comment]
> 
> 
> ### Why:
> 
> Closes: 
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> 
> 
> ### Check off the following:
> 
> - [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.
> 
>   - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> - [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
>

**Comment by Singh-csm** [comment]
close

**Pull request closed without merging**
