### PR TITLE
fix typo: `pull_request_target` vs. `pull_request`

### PR DESCRIPTION
**Pull request by staabm**
### Why:

I guess its copy/pasted mistake which just need to be fixed.

**Closes [issue link]**

### What's being changed:

a typo

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @staabm I'm not familiar with this article, can you explain why you believe it's a mistake? Thank you!

**Comment by staabm** [comment]
The section in which this table details are printed is about `pull_request_target`.

i concluded that the text is a typo, because it seems the table was copy pasted from within the same page section which describes `pull_request`

**Comment by janiceilene** [comment]
Thanks for that additional context @staabm, it'll help our reviewers! I'll triage this for review ⚡

**Review by ethanpalm — APPROVED** [review]
👋🏼  Hi @staabm, thanks for catching this typo! The change looks great and I'll get it merged as soon as all checks are passing ✨

Thanks for your contribution and helping to improve the GitHub docs!

**Pull request merged**
