### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Haleshot**
Added the image for the README toggle list.

### Why:
The Toggle list in the README of the Contributing Markdown file doesn't load; added the image of the Toggle list in the README.

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Added the image given below:
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Haleshot Thanks for the PR! However, I'm seeing the table of contents icon in the contributing file. Are you still seeing a broken image? If so, could you let us know the browser you are using? 

Thanks! ✨

**Comment by Haleshot** [comment]
> @Haleshot Thanks for the PR! However, I'm seeing the table of contents icon in the contributing file. Are you still seeing a broken image? If so, could you let us know the browser you are using?
> 
> Thanks! ✨

I'm using Edge and yes I'm still seeing a broken image.
Image - 
image

Shifted to Light mode, refreshed the browser multiple times to check if it was an issue from my side.

**Comment by Haleshot** [comment]
> @Haleshot Thanks for the PR! However, I'm seeing the table of contents icon in the contributing file. Are you still seeing a broken image? If so, could you let us know the browser you are using?
> 
> Thanks! ✨

Does it seem to be an issue that persists only from my end? I have tried multiple browsers, multiple devices and the image for the README toggle list is shown in none.

**Comment by Haleshot** [comment]
> @Haleshot This is super interesting, I did the same, even downloading and using Edge to check it. Is your browser updated to the latest release? Would you mind sharing your operating system with us?

No issues. I'm using Windows 11 (Acer Nitro 5 Laptop), Edge browser on a standard Wi-Fi connection (well over 100+ Mbps). No VPN connected as well.

**Comment by cmwilson21** [comment]
@Haleshot Thanks! I'm gonna check with the team and see if anyone else is experiencing the broken image. 👍

**Comment by Haleshot** [comment]
> @Haleshot Thanks! I'm gonna check with the team and see if anyone else is experiencing the broken image. 👍

Thanks for the update!

**Comment by peterbe** [comment]
@stevecat Can you help out here. I'm still working on understanding why it would render differently under different browsers. 
But can you validate the validity of the change. Is this `CONTRIBUTING.md` file going to be weaved into the main content and cease to just be a `.md` file you view in the GitHub web UI?

**Comment by peterbe** [comment]
In terms of the image not working, I can't see that. 

Screenshot 2023-05-30 at 1 33 22 PM-with-shadow

I suspect the image depends on cookie perhaps.

**Comment by Haleshot** [comment]
@peterbe Hi, I have been looking into this for a while now. Tried with different devices (Linux laptop, windows laptop, mobile - both iOS and Android), Wi-Fi networks (switched to Cellular Data) and browsers as I stated above. Tried with my friend's mac for the first time and it seems to render in that; the browser I used for viewing the file was Safari. Not sure what the issue is...

**Comment by peterbe** [comment]
@Haleshot How strange! And frustrating. 
I think it might be a mistake to rely on a dynamic URL for the image. After all, even when it works it looks a bit strange because you get an image that is meant for dark mode when viewing the Markdown in light mode. 

The old image works. Too. For me :)

Screenshot 2023-05-31 at 8 41 28 AM-with-shadow

Did that one not work either for you when you view https://github.com/github/docs/blob/main/CONTRIBUTING.md

**Comment by Haleshot** [comment]
> @Haleshot How strange! And frustrating. I think it might be a mistake to rely on a dynamic URL for the image. After all, even when it works it looks a bit strange because you get an image that is meant for dark mode when viewing the Markdown in light mode.
> 
> The old image works. Too. For me :)
> 
> Screenshot 2023-05-31 at 8 41 28 AM-with-shadow
> Did that one not work either for you when you view https://github.com/github/docs/blob/main/CONTRIBUTING.md

No that doesn't seem to be working for me either 😅 
image

Ahh, now it seems it just fails to render for some reason... 

Alright, tested my same laptop at a friend's house, works now. Guess there is an issue with my ISP. Mayble certain part is getting blocked out 🤔

**Pull request closed without merging**
