### PR TITLE
Add vertical bars("|") to the missing points

### PR DESCRIPTION
**Pull request by hong9lol**
### Why:
 - It is better to add vertical bars("|") although it doesn't affect to view

### What's being changed:
- Just added three vertical bars. 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@hong9lol 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ethomson** [comment]
Sure, this seems reasonable.  It's nice to be consistent with the rest of the other lines.

**Review by vgrl — APPROVED** [review]
Thanks for your contribution! These changes look good in preview: https://docs-preview-15841-22acad.eastus.azurecontainer.io/en/actions/learn-github-actions/contexts#github-context

**Comment by shanajhwhy** [comment]
[]()

**Pull request merged**
