### PR TITLE
Fix use of "structured" vs "unstructured"

### PR DESCRIPTION
**Pull request by jimrazmus**
The guidance and description are inconsistent. This change corrects that inconsistency.

### Why:

The inconsistency between the guidance and its description is confusing. 

### What's being changed:
 
The inconsistency between the guidance and its description.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR @jimrazmus! Changing the first word from "structured" to "unstructured" changes the meaning of this section of the article, so I'm going to close this PR.

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by jimrazmus** [comment]
The title of the section reads "Never use structured data as a secret" but then goes on to talk about unstructured data leading to redaction failures. So what I take away is to never use structured or unstructured data in secrets. It that the intent of the section? The examples call out JSON, XML, and YAML. Are those examples meant to speak to the title of the section in regards to structured data or the preceding sentence regarding unstructured data?

**Comment by janiceilene** [comment]
You were totally right about this change @jimrazmus and closing this PR was my mistake. I'm sorry about that! It ended up being fixed in another PR with some additional context in this comment https://github.com/github/docs/pull/1036#discussion_r517607393.

Thank you for following up with a helpful and kind explanation of why your suggestion was important!

**Comment by jimrazmus** [comment]
@all-contributors please add @jimrazmus for documentation

**Pull request closed without merging**
