### PR TITLE
Update adding-a-file-to-a-repository.md

### LINKED ISSUE #19002: Add git lfs link or description to "Adding a file to a repository" page
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository

### What part(s) of the article would you like to see updated?

Adding a link to the top of the page that takes the user to this page: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github 
This would be helpful because it provides easier access to the git LFS documentation in case users want to upload files greater than 100 MB in size. 
Right now the "managing large files" section is a tab on the left sidebar, but it may not be intuitive for people to look their if they are wondering how to add files greater than 100mb to Github

### Additional information

Screen Shot 2022-07-13 at 3 40 19 PM
Screen Shot 2022-07-13 at 3 41 27 PM

### PR DESCRIPTION
**Pull request by nayasinghania**
### Why:

Closes issue [19002](https://github.com/github/docs/issues/19002) 

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Add git lfs description sentence to "Adding a file to a repository" page

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@vedantsinghania05 Thanks for opening this PR! I made a slight edit to link it to the issue. 

I'll triage this for the team to take a look! 👀

**Review by nitishmalang — COMMENTED** [review]
Its good & improved

**Comment by nitishmalang** [comment]
contribution specific files are good

**Review by sophietheking — APPROVED** [review]
Hi @vedantsinghania05 👋  Thanks for opening this PR and adding this information, we really appreciate it. 💖 

I added another variable (`{% data variables.product.product_name %}`) instead of GitHub in the linked article name, and I removed the domain name from the url. Tests are passing now! 🍏 I'll get this merged for you.

**Pull request merged**
