### PR TITLE
Insights: add the `read:issues` permission

### PR DESCRIPTION
**Pull request by c-brooks**
### Why:

cc/ https://github.com/github/insights/issues/2024
cc/ @github/insights 

There was recently a change to Insights so the GitHub App needs additional permissions, and we need to update the Docs so that customers know to add the `read:issues` permissions to their apps.

### What's being changed:

1. Adds instructions to add the `read:issues` permissions to the initial GH App creation:
Screen Shot 2021-01-15 at 10 57 44 AM

2. Adds a section to upgrade from Insights v1.5.0-alpha.1
Screen Shot 2021-01-15 at 11 26 26 AM

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks @c-brooks! I'll get this triaged for the team to review ⚡

**Review by levindixon — APPROVED** [review]

**Comment by ndikumasabo** [comment]
I'm NEW COM ON GITHUB BUT I'M VERY INTERESTED TO LEARN AND USE GITHUB

**Comment by c-brooks** [comment]
@janiceilene Is it possible to get this reviewed today? We’d like to put it out today with our release. thanks!

**Review by vanobig — APPROVED** [review]
🐑  it

**Comment by lecoursen** [comment]
👋🏻 @c-brooks, can you open an issue about this in the private repo? This update will require a bit more discussion. Thanks!

**Comment by janiceilene** [comment]
It looks like this was moved to an internal issue, so I'm going to close this up ⚡

**Pull request closed without merging**
