### PR TITLE
Document ghe-config command to enable/disable Code Scanning

### PR DESCRIPTION
**Pull request by mario-campos**
As the industry heads to a config-as-code/infrastructure-as-code world, we will likely encounter companies/individuals that would like to automate and script the deployment of GHES, including the enabling/disabling of GHAS.

### Why:

See above.

### What's being changed:

I added the `ghe-config` command to run in order to do the same thing in this guide. I think it'll be useful to some to see another, more-scriptable way to execute the same thing.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by mario-campos** [comment]
@mattpollard, do you need anything from me to merge this?

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Review by mattpollard — APPROVED** [review]
👋🏻 Thanks for this contribution, @mario-campos! Appreciate your patience while we got to reviewing this 😄

I've revised your instructions a bit to keep existing procedures straightforward and provide a dedicated section with conceptual information to introduce the more advanced instructions you've detailed.

I'll merge this shortly, and the changes will be live within an hour or two. Thanks again 🙇🏻

**Comment by mattpollard** [comment]
And that ordered list is certainly interesting 🙃 Fortunately, this'll be rendered properly either way 😄

**Pull request merged**
