### PR TITLE
Update supported Terraform versions

### LINKED ISSUE #18491: Update Dependabot Supported Versions of Terraform
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

### What part(s) of the article would you like to see updated?

The supported version of terraform appear to be out of date, [at the bottom of this table](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems).

[The line in GitHub is here](https://github.com/github/docs/blob/4f7efa2b90f4d09bb6303ed2755c1b08f26ae4b0/data/reusables/dependabot/supported-package-managers.md?plain=1#L27).

I saw some merged PRs for dependabot that show newer versions of Terraform are supported. 
[Bump Terraform from 1.0.11 to 1.1.6](https://github.com/dependabot/dependabot-core/pull/4748)
[Bump Terraform from 1.0.16 to 1.2.0](https://github.com/dependabot/dependabot-core/pull/5170)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #18491 

### What's being changed:

Updated the max supported Terraform version to `1.2.x`

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by japui** [comment]
Atualizar versões compatíveis do Terraform

**Comment by janiceilene** [comment]
@thispsj Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by felicitymay — COMMENTED** [review]
@thispsj - your change looks good. I'm just going to verify with the Dependabot team whether we can update this version number for GitHub Enterprise Server users too.

Then we'll either merge this PR as-is, or add a condition so that enterprise server users see the correct information.

**Comment by mchammer01** [comment]
@thispsj - thanks for making this update ✨ 
Just checking with the Dependabot team whether we need to leave `<= 1.0` for older GHES versions.
Will report back once I've heard from them.

**Comment by mchammer01** [comment]
I am going to merge this shortly.  Our intent is that users will be able to pull in updated Dependabot actions in older GHES versions to get the latest Terraform versions.

**Review by mchammer01 — APPROVED** [review]
LGTM 💖

**Pull request merged**
