### PR TITLE
Spelling `e.g.` means `exempli gratia`

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

e.g. should be spelled as such, in https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy

#### Before
https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#learn-more-and-speak-up
image

#### After
https://docs-31981-8420cc.preview.ghdocs.com/en/site-policy/content-removal-policies/dmca-takedown-policy#learn-more-and-speak-up
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@jsoref Hello! 👋 Let us know once this PR is ready for review

**Comment by jsoref** [comment]
@nguyenalex836 this is ready

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@jsoref Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by nguyenalex836** [comment]
@jsoref Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing, and our Site Policy team gives their approval 🍏

**Comment by nguyenalex836** [comment]
Internal: requested review from Site Policy team [here](https://github.slack.com/archives/C5EE6U8UV/p1709915577883779)

**Review by khxu — APPROVED** [review]
t.y.! 😄

**Pull request merged**
