### PR TITLE
Remove note that is contradicted in the subsequent paragraph

### PR DESCRIPTION
**Pull request by jmandel**
### Why: remove contradictory information

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Remove a note stating that security reports cannot be made to repositories that do not opt into receiving them

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

---

The paragraph following the deleted line says that reports can be made to public repositories even if they have not turned on this feature.

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@jmandel Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by enyart1 — COMMENTED** [review]
Omg IDK really don't know

**Comment by mchammer01** [comment]
Thanks for your contribution @jmandel ✨ 
We will review this PR this week!

**Comment by 2chiefk** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).
>

**Comment by mchammer01** [comment]
@jmandel -I am not sure that there is a contradiction between both the note and the paragraph, but I agree that you've highlighted confusing content, that we should improve on. Thanks you so much for that 💖 ✨ 
We will fix this internally as I need to discuss with the team in charge how they'd like to proceed with this.
As a result, I will close this issue.

**Comment by jmandel** [comment]
Thanks! It sounds like I misunderstood the content. Here are some suggestions for how to make it clearer. 


>If you do not have admin or security permissions for a public repository, you can still privately report a security vulnerability

If I understand correctly, this could be rewritten more clearly as something like 

> If a public repository has enabled "Private vulnerability reporting," anyone can report an issue by clicking "Security" ...

**Pull request closed without merging**
