### PR TITLE
Add SQL Server codespaces code examples

### LINKED ISSUE #21581: Codespaces Samples - Add SQL Sample
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces

### What part(s) of the article would you like to see updated?

Update the Code examples section with SQL examples.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cmaneu**
### Why:

Closes #21581

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Add a new SQL sample in the **Code examples** section of [Codespaces docs landing page](https://docs.github.com/en/codespaces)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmaneu** [comment]
I don't have the staging address, however I've reviewed https://docs-21580-ec9634.preview.ghdocs.com/en

**Review by NostalgicGareth — COMMENTED** [review]
- [ ]

**Comment by cmaneu** [comment]
Hi @NostalgicGareth, 
I think there is an issue with your comment :)

**Comment by cmwilson21** [comment]
@cmaneu Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review ⚡

**Review by NostalgicGareth — COMMENTED** [review]
Yes

**Review by skedwards88 — APPROVED** [review]
Thanks for this addition! We'll get this merged down for you.

**Pull request merged**
