### PR TITLE
Delete content/github/finding-talent-with-github-jobs directory

### PR DESCRIPTION
**Pull request by jccwm**
### Why:

With the deprecation of GitHub Jobs this should likely be removed.

### What's being changed:

Deleting this entry/ directory

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

 

Removes user facing content about a deprecated service.

### CODE REVIEW

**Comment by janiceilene** [comment]
@jccwm Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by Scopetta197** [comment]
Ok

**Comment by Scopetta197** [comment]
Va bene

**Review by lecoursen — APPROVED** [review]
Looks good to me! I fixed the merge conflicts and failing tests and will merge now. 🎉

**Comment by legranchionew** [comment]
332-339

**Comment by legranchionew** [comment]
file .eslintrc.js 29 lines (29 sloc)  change from 18 to 18

**Pull request merged**
