### PR TITLE
The git commands here seems outdated.

### PR DESCRIPTION
**Pull request by amhrn**
### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@mhrn77 Thanks so much for opening a PR! I'll get this triaged for review 🌟

**Comment by mhrn77** [comment]
Hope this minor change gets reviewed soon. Thanks.

**Comment by felicitymay** [comment]
👋🏻 Hi @mhrn77 

Thank you for telling us that you ran into trouble with the steps in this topic and for raising a PR to help other people avoid having the same problem.

Fairly recently we updated our topics to use `main` as the name for the default branch in line with our decision to use [inclusive language](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#inclusive-language). 

I've just run through the steps in this topic and successfully added a dummy repository with a default branch of `main`. It seems as if my computer's set up differently from yours. I know it was a week or so ago that you had the problem, but do you have any information that would help us work out if there are any extra steps that some people need to use?

**Comment by mhrn77** [comment]
Hello @felicitymay,

Thanks for clearing that up. Sorry for the trouble.

**Comment by felicitymay** [comment]
Hi @mhrn77 - no trouble.

Please continue to let us know where you find problems or room for improvement in the docs.

**Pull request closed without merging**
