### PR TITLE
Add remote repository to git push commands

### LINKED ISSUE #15577: git push --force-with-lease example-branch without repository fails
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

### What part(s) of the article would you like to see updated?

The issue: 
On the document page, there are 2 `git push` commands mentioned as `git push --force-with-lease example-branch` and `git push --force example-branch`. But neither of them will not be successful without a repository name before a branch name. 

What is the expected outcome?
these `git push` commands should be `git push --force-with-lease origin example-branch` and `git push --force origin example-branch` respectively.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tsuyo**
### Why:

Closes https://github.com/github/docs/issues/15577

### What's being changed:

Two `git push` commands on [this page](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) should be `git push --force-with-lease origin example-branch` and `git push --force origin example-branch` respectively.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@tsuyo 
Thanks for opening a PR :+1: Please fill out "why" and "what's being changed" in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

**Comment by ramyaparimi** [comment]
@tsuyo 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by vgrl — COMMENTED** [review]
Thanks for making these improvements @tsuyo!

👍 this is great! Just a style change and the PR is good to go. 🎉 

I'll commit the changes and get this PR merged.

**Review by vgrl — APPROVED** [review]
Changes look good in preview: https://docs-preview-15535-58e064.eastus.azurecontainer.io/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Pull request merged**
