### PR TITLE
working-with-the-docker-registry.md

### PR DESCRIPTION
**Pull request by m-star5**
@15MariamS [Diana navarro cola y e](working-with-the-docker-registry.md) When you can find amazing great content that will make you

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by 11997777** [comment]
Stop

**Comment by emem-crypto** [comment]
> @15MariamS [Diana navarro cola y e](working-with-the-docker-registry.md) When you can find amazing great content that will make you
> 
> ### Why:
> Closes [issue link]
> 
> ### What's being changed:
> ### Check off the following:
> * [x]  I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [x]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Review by emem-crypto — COMMENTED** [review]
App

**Comment by thiwatx33** [comment]
m-star5:patch-9

**Pull request closed without merging**
