### PR TITLE
Update broken link on '/rest/overview/other-authentication-methods'

### LINKED ISSUE #10839: The href for a link points to a non-existent ID
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

On the https://docs.github.com/en/rest/overview/other-authentication-methods#working-with-two-factor-authentication page, there is a link "[authenticate using OAuth token](https://docs.github.com/en/rest#authentication)" links to the id `#authentication` which doesn't exist on the `/en/rest` page.

Screen Shot 2021-10-06 at 7 38 00 PM

Browser: Chrome 93

### What changes are you suggesting?

I was expecting the link to direct me to the element on `/en/rest` with the id "authentication" but that element and corresponding element don't exist leaving the user at the top of the page.

I'm not entirely sure where the element with `id="authentication"` is now to correct this link but since it was originally on `/en/rest` at some point in time its hopefully not moved too far to track down.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannerdolby**
### Why:

Closes #10839

### What's being changed:
Changing link definition for `[oauth-auth]: /rest#authentication` to `[oath-auth]: /rest/guides/basics-of-authentication`

Since the original link `/rest#authentication` linked to a non-existent ID, I wasn't entirely sure where this was intended to go but I thought [/rest/guides/basics-of-authentication](https://docs.github.com/en/rest/guides/basics-of-authentication) seemed like a good fit. Let me know if there is a more preferred URL to use.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by faythforever11** [comment]
Thank you

**Comment by faythforever11** [comment]
#Thx so very much!

**Comment by ramyaparimi** [comment]
@tannerdolby 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by guntrip — COMMENTED** [review]
Thanks for raising the issue and opening this PR, @tannerdolby! ✨ 

`/rest/guides/basics-of-authentication` is a guide for implementing authentication with an OAuth application but because the "Working with two-factor authentication" section we're updating is discussing how to authenticate with a personal access token, I think the [Authentication section in "Resources in the REST API"](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#authentication) is a better fit.

I'll make that change (using a suggested change which I'll apply myself) and then get this merged. Thanks again for spotting this and contributing to our docs!

**Review by guntrip — APPROVED** [review]

**Pull request merged**
