### PR TITLE
Explain how to view security alerts

### LINKED ISSUE #4760: Provide instructions for how to allow non admins to see dependabot security alerts
### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/supply-chain-security/viewing-and-updating-vulnerable-dependencies-in-your-repository

### What part(s) of the article would you like to see updated?

`Viewing and updating vulnerable dependencies`

Doesn't explain how a non admin can view security alerts, it appears to assume that everyone is an admin of all repositories.

There is no documentation for an admin explaining how to let non admins see the security alerts.

This leads to two problems:
1. Admins see alerts and don't understand why others can't see them
2. Others get urls that don't work and don't understand what to do

### Additional information

The current public facing information for this is here:
https://github.community/t/cant-see-the-access-to-alerts-for-dependabot-settings/157526

It does not include pictures, it isn't maintained, and it is not discoverable.

---

### Content design plan

1. Change to the [Viewing and updating vulnerable dependencies in your repository](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/viewing-and-updating-vulnerable-dependencies-in-your-repository) article:

    - In the metadata at the top of the file, update the `permissions` statement. It should mention users with explicit access to security alerts.

2. Change to the reusable that defines step 3 of the procedure.
    - After the text, before the `{% ifversion ftp %}` condition, add a brief sentence explaining that if the option is missing, they should ask for access to security alerts. Then add a "For more information..." link to [Managing security and analysis settings for your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository#granting-access-to-security-alerts)

### PR DESCRIPTION
**Pull request by jsoref**
https://github.community/t/cant-see-the-access-to-alerts-for-dependabot-settings/157526

### Why:

It's incredibly frustrating to developers being asked to fix things they can't see.
It's incredibly frustrating to admins not knowing how to let developers see things that admins can already see.

**Closes #4760**

### What's being changed:

Add text to `Viewing and updating vulnerable dependencies in your repository` to help developers and administrators navigate the security bits.

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks again @jsoref! I'll get this triaged for review ⚡

**Comment by jsoref** [comment]
Again, there's no obvious reason for the user hat I'm wearing to know that that page is the right further reading to read. This is the page the user is going to land on.

**Comment by linhzz999** [comment]
Ok

**Comment by linhzz999** [comment]
Ok

**Comment by jsoref** [comment]
I'm not saying my PR text is the right text. It isn't. It's to invite discussion about the right text in this place.

**Pull request closed without merging**
