### PR TITLE
Content Corrections

### PR DESCRIPTION
**Pull request by SumaiyaTarannumNoor**
### Why: Some grammatical corrections have been made.

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 Thank you, I really appreciate this. 😊 😊

**Comment by hubwriter** [comment]
@SumaiyaTarannumNoor - Thank you for raising this. However, I'm going to close this as these changes are mainly personal preferences on how to phrase something, rather than corrections or improvements.

If you'd like to make changes I'd recommend raising an improvement issue [here](https://github.com/github/docs/issues/new/choose), then someone from the team can take a look at your proposal before you go ahead. 

For more information about contributing, and our house style, see https://docs.github.com/en/contributing.

**Comment by SumaiyaTarannumNoor** [comment]
@hubwriter I understand your point of view; however, there is always a better way to phrase anything, and there is nothing "personal" about it. Also, I do think you haven't checked it all.

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Hello! 👋 Just wanted to step in to say how much we appreciate your contributions in the past 💛 While I would advise listening to @hubwriter's guidance here regarding improvement issues / house style, please do not let the closing of this PR discourage you! 

Your engagement in this community is valued, and we would love to see additional contributions from you after you've referenced the contributing docs @hubwriter provided ✨ thank you!

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 I appreciate it a lot. I am willing to contribute more in the future. Thank you. 😊 😊

**Pull request closed without merging**
