### PR TITLE
chore: Format json files with Prettier

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

EditorConfig was added in a previous PR. This does a one time cleanup so the next changes to the files are a simpiler diff that won't have to include any of the whitespace cleanups

### What's being changed:

Probably easiest to view in the "whitespace ignored view" https://github.com/github/docs/pull/1177/files?diff=unified&w=1
Ran https://github.com/caarlos0/jsonfmt as a quick why to consistently apply the whitespace as a on-off instead of trying to introduce something with a lot of opinons like Prettier:
- Match indenting in EditorConfig of 2 spaces
- Add missing EOF
- Collapse empty arrays and objects

### Check off the following:
- [ ] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by heiskr — APPROVED** [review]
Makes sense to me. 🙏🏼 Thanks!

**Comment by chiedo** [comment]
I connected with @sarahs and most of these files are generated automatically by scripts... it wouldn't hurt anything to merge this, but the files will just get overwritten with the old whitespace at some point.

So I'm not clear what the benefit to merging this would be.

**Comment by nschonni** [comment]
@chiedo now that the Prettier for Yaml PR landed, would it make sense to add that for the JSON files too or just ignore a particular pattern of generated files?

**Comment by chiedo** [comment]
> just ignore a particular pattern of generated files

My opinion is this!

**Comment by nschonni** [comment]
@chiedo if you provide a pattern I can add it to the `.prettierignore`. Flip side is that now that this is automated and linted, it's easier to re-apply to the generated files as they land, even if they tool produces something slightly different natively

**Comment by chiedo** [comment]
Thanks @nschonni! I'll follow back up in a few weeks. We're going to start reviewing all open source PRs on Mondays (starting after Thanksgiving) as a team. We've had a few workflow changes break internal processes over the past week so we're going to start looping everyone in to get sign off.

**Review by tashaemery — APPROVED** [review]

**Comment by nschonni** [comment]
@rachmari I took your approach for the Yaml files in `update-files.js` and added the `json` extension 😄

**Comment by chiedo** [comment]
@nschonni sorry on the delay here! Most of these JSON files are generated via automation so we don’t see a pressing reason to merge this PR as they’ll get overwritten. So we’re going to close this PR for the time being. Moving forward can you start by opening an issue rather than a PR so we can make sure we can commit to the issue before you start working on it?

**Comment by nschonni** [comment]
@chiedo this hooks into the script like the Yaml files for the generated content

**Pull request closed without merging**
