### PR TITLE
Document runner.debug

### PR DESCRIPTION
**Pull request by JustinGrote**
### Why:

Document the runner.debug property, which exists and is useful for triggering actions only when "Enable Debug Logging" is enabled on a job re-run.

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Add an entry to the table to describe the runner.debug attribute and when it is useful.

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
Thanks for opening a PR :+1: Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by cmwilson21** [comment]
@JustinGrote thanks for filling in the template! I'll get this triaged for review.

Our actions team may be a little slow to respond right now, so we appreciate your patience! :yellow_heart:

**Comment by lucascosti** [comment]
Thanks for this, @JustinGrote! I made a few edits for clarity:

* There is also an equivalent environment variable set in the runner OS. 
* Mentioned that it is only set when debug logging is enabled (e.g. the context/envar does not exist when it isn't enabled.).

**Review by martin389 — APPROVED** [review]
Looks good in staging: https://docs-19404-ff7336.preview.ghdocs.com/en/actions/learn-github-actions/contexts#runner-context 👍

**Comment by JustinGrote** [comment]
> Thanks for this, @JustinGrote! I made a few edits for clarity:
> 
> * There is also an equivalent environment variable set in the runner OS. 
> * Mentioned that it is only set when debug logging is enabled (e.g. the context/envar does not exist when it isn't enabled.). 

Hi Lucas,

Thanks! Also important to note that the variable isn't referenceable by the env. syntax in an Action, that tripped me up for a while.

**Comment by lucascosti** [comment]
> Also important to note that the variable isn't referenceable by the env. syntax in an Action, that tripped me up for a while.

Yep, when to use environment variables vs. contexts is a bit confusing. We have advice [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#using-contexts-to-access-environment-variable-values) and [here](https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts) that hopefully explains why/when environment variables can't be used in a workflow file.

**Pull request merged**
