### PR TITLE
Update telling-git-about-your-signing-key.md

### PR DESCRIPTION
**Pull request by alexmazaltov**
add alternative command for fish shell

### Why: cause it is not obvious how to deal with gpg signature using fish shell

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@alexmazaltov Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by alexmazaltov** [comment]
@nguyenalex836 thank you for your time

**Comment by alexmazaltov** [comment]
@nguyenalex836 please review

**Comment by subatoi** [comment]
Hi @alexmazaltov, and thanks for your submission and interest in the docs—

As a rule, we target Bash. I think we can make that fact clearer in our contributing documentation and I'll discuss that internally. There are potentially many more places other than this one where we could add examples that are specific to other shells, and unless there's a very specific reason to call one out in particular, we wouldn't make an exception, so for that reason I'm afraid we won't be accepting this submission right now.

I'd recommend opening an issue in future first for a better experience all round, just so we can offer feedback on how worthwhile a change or addition is before you go ahead and raise a PR. Alternatively, you can take one of the issues that are already marked as help wanted.

Thank you again!

**Review by SonuG56 — COMMENTED** [review]
SonuG56

**Pull request closed without merging**
