### PR TITLE
Update responses for current format

### LINKED ISSUE #8015: Update response content in tutorial
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

### What part(s) of the article would you like to see updated?

Update returned responses from curl  https://api.github.com/users/defunkt
 to match current state

### Additional information
Suggested fix in pull request

### PR DESCRIPTION
**Pull request by bkmgit**
### Why:

Closes https://github.com/github/docs/issues/8015

### What's being changed:

Example output from curl command

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@bkmgit Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Review by Artek199 — APPROVED** [review]

**Comment by gsteele178** [comment]
What is this

**Review by kaldrako1 — COMMENTED** [review]
No I did not authorized

**Review by felicitymay — APPROVED** [review]
Hi @bkmgit 

Thanks for updating the responses in this getting started guide: https://docs-8016--patch-2.herokuapp.com/en/rest/guides/getting-started-with-the-rest-api. I think it will help new users ✨ 

I'll update our branch from `main` and merge these changes 🚀

**Pull request merged**
