### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bl-ue**
### Why:

Fixed typos found with [codespell](https://github.com/codespell-project/codespell) & [cSpell](https://github.com/streetsidesoftware/cspell).

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

---

A few notes here.

- Some of the file names had typos in, so I renamed them and updated all references to them that I could fine (edace80 & 4d699c3).  I'll check on the staging site to see if they're ok

- For consistency, I updated some of the legal docs (agreements, data protection, etc.) to use American English all over, because for `authorized` and `organizational` they were using mixed

- Your contributing guidelines say not to contribute translations here which I totally understand, but I was wondering if I could submit these translation changes that I did since they're identical across all translations, and I'd almost classify them as syntactical rather than normal translations.

- I changed `reenable` to `re-enable`

- A few trailing newlines were trimmed at the ends of some files

### CODE REVIEW

**Comment by bl-ue** [comment]
Hehe, a bit strange to see a bot requesting changes, but I concede.  I'll try to fix those.

**Comment by bl-ue** [comment]
So it looks like `translations/**` is the only bad guy 😞. Just to confirm (@janiceilene, ...?), I should definitely undo those changes?  They're just references to files in `` images.

**Comment by bl-ue** [comment]
ping @heiskr @skedwards88 @janiceilene? What should I do about [this](https://github.com/github/docs/pull/7451#issuecomment-862767672)?

**Comment by janiceilene** [comment]
@bl-ue Please refrain from pinging individuals who are not involved in the PR or issue you're working in.

Thanks for opening a PR with these fixes! I believe the only official problem was the `translation` files, but we also have a lot of autogenerated content in our REST and GraphQL that we need to change internally. I'll chat with the team and figure out the best solution here.

**Comment by bl-ue** [comment]
>Please refrain from pinging individuals who are not involved in the PR or issue you're working in.

I'm sorry @janiceilene — I just wanted to make sure that I wasn't being ignored because you saw that changes were requested.  I'll keep that in mind.

>but we also have a lot of autogenerated content in our REST and GraphQL that we need to change internally.

Ah, great point.

>I'll chat with the team and figure out the best solution here.

Thank you! :)

**Comment by janiceilene** [comment]
👋 @bl-ue Can you remove the translated files from this PR? Let me know when that's done and I'll get this up for review.

**Comment by bl-ue** [comment]
Done.  I saved the old branch locally in case we need it.

**Review by mchammer01 — APPROVED** [review]
LGTM, thanks for fixing these typos 😉

**Pull request merged**
