### PR TITLE
Add AWS pricing and IAM links

### PR DESCRIPTION
**Pull request by imjohnbo**
### Why:

Pricing and IAM links were missing.

### What's being changed:

<p align="center">

</p>

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by imjohnbo** [comment]
Seeking a quick 👍 from @jpadams: https://docs-3606--update-aws-ghes.herokuapp.com/en/enterprise-server@3.0/admin/installation/installing-github-enterprise-server-on-aws#prerequisites

**Comment by myarb** [comment]
Thanks for opening this PR @imjohnbo ! ✨ Can you ping `@github/docs-content` when you're ready for a content review and ready for us to merge this? That'll get it on the first responder's radar to request a review ⚡

**Comment by janiceilene** [comment]
Thanks so much for opening a PR @imjohnbo! I'll get this triaged for review ⚡

**Review by jpadams — APPROVED** [review]
LGTM!

**Review by skedwards88 — APPROVED** [review]
🚀 LGTM! Thanks for improving the docs! I'll get this merged down for you.

**Pull request merged**
