### PR TITLE
Rename CONTRIBUTING.md to CONTRIBUTING.md11139988

### PR DESCRIPTION
**Pull request by Tamtam778**
11139988

### Why:

Closes ISSUE

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Tamtam778** [comment]
11139988

**Comment by Tamtam778** [comment]
Tamtam778

**Comment by Tamtam778** [comment]
11139988

**Comment by Tamtam778** [comment]
11139988

**Comment by Tamtam778** [comment]
11139988

**Review by Tamtam778 — COMMENTED** [review]
Duplicate of #

**Comment by Tamtam778** [comment]
5CONTRIBUTING.md to

**Comment by Tamtam778** [comment]
CONTRIBUTING.md to11139988#22854

**Comment by Tamtam778** [comment]
CONTRIBUTING.md to

**Comment by Tamtam778** [comment]
CONTRIBUTING.md11139988 #22854
 Closed
[Tamtam778](https://github.com/Tamtam778) wants to merge 1 commit

**Comment by Tamtam778** [comment]
CONTRIBUTING.md11139988 #22854
 Closed
[Tamtam778](https://github.com/Tamtam778) wants to merge 1 commit

**Comment by Carlexos765** [comment]
Leave  a comme

**Comment by Carlexos765** [comment]
Leave reviw

**Pull request closed without merging**
