### PR TITLE
Clarify that `always()` has a side effect

### PR DESCRIPTION
**Pull request by CyberShadow**
One straight-forward interpretation of the previous wording was that the function simply always returns `true`, with no other side effects. A reasonable conclusion would then be that, in an `if` expression, `&& always()` is redundant, and can be omitted. However, this in incorrect, as the function does have the side effect of forcing the step to be executed in addition to returning `true`.

### Why:

(This is a relatively minor change, does it need an issue?)

### What's being changed:

Just the description of the `always()` function.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@CyberShadow Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Adriamo132 — APPROVED** [review]

**Review by ivan0117 — APPROVED** [review]
p

**Review by ivan0117 — CHANGES_REQUESTED** [review]
p

**Review by ivan0117 — COMMENTED** [review]
p

**Comment by DoctorSky1967** [comment]
Help reset pls.

**Review by skedwards88 — APPROVED** [review]
🚀 Thanks for this addition! I'll get this merged down for you.

**Pull request merged**
