### PR TITLE
Update outdated images

### LINKED ISSUE #5134: Update images on the "Transferring a repository" page
### What article on docs.github.com is affected?
[Transferring a repository](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository)

### What part(s) of the article would you like to see updated?
The screenshots in steps 5 and 6 of [Transferring a repository owned by your user account](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) and steps 6 and 7 of [Transferring a repository owned by your organization](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-organization) are outdated.

### Additional information

**This is the image from the docs:**
Screen Shot 2021-04-07 at 8 15 44 AM

**This is what it actually looks like:**
Screen Shot 2021-04-07 at 8 15 44 AM

### PR DESCRIPTION
**Pull request by lucalves**
### Why:

Because some images in the "Transferring a repository" section are out of date.

**Closes #5134**.

### What's being changed:

I included two new images, according to what is presented today when transferring a repository. Are they:

repo-transfer-free-plan-warnings

Note that in this image, I replaced the real name of the repository with the phrase "the name of the repository":

repo-transfer-complete

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Alvinchong1989 — APPROVED** [review]

**Comment by janiceilene** [comment]
@lucalves Thanks so much for opening a PR with the new images! I'll get this triaged for review 🎉

**Review by Afsaneh1361 — CHANGES_REQUESTED** [review]
The ad will solve one of these two problems, so...  Delete one

**Comment by mesca216** [comment]
#5311

**Comment by lucalves** [comment]
Someone to review this PR?

**Comment by janiceilene** [comment]
I just got a chance to review this @lucalves and it looks great 🎉 I'll update the branch and get this merged ✨ Thanks again for taking the time to update these screenshots!

**Review by janiceilene — APPROVED** [review]

**Pull request merged**
