### PR TITLE
feat: add explicit `gh auth setup-git` step

### LINKED ISSUE #13011: Step missing in `gh auth login` credential caching flow: `gh auth setup-git`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

### What part(s) of the article would you like to see updated?

Step 3 here is missing: https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git

`gh auth setup-git` is necessary to configure git to use the cached credentials. I had to guess this command, it's nowhere mentioned.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by corneliusroemer**
### Why:

Closes #13011 

### What's being changed:

Make a necessary step explicit: `gh auth setup-git`

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@corneliusroemer 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by HLA95** [comment]
> @bruce

**Review by mislav — COMMENTED** [review]
Thank you for the contribution, but `gh auth login` interactive mode already includes the setup that `gh auth setup-git` would do. If during `auth login` you get asked “would like to authenticate to Git …” and answer “Yes” to it, that sets up gh as a git credential helper. So you see, calling `gh auth setup-git` manually just after `gh auth login` shouldn't be necessary.

**Comment by skedwards88** [comment]
Thanks for weighing in @mislav! @corneliusroemer , I am going to close out this PR and corresponding issue, but we'd love to see more contributions from you in the future!

**Pull request closed without merging**
