### PR TITLE
Update using-ssh-over-the-https-port.md

### PR DESCRIPTION
**Pull request by bon77**
The user for connecting must be "git"

### Why:

Improve documentation

### What's being changed:

doc

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ X ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by imnetcat — APPROVED** [review]

**Comment by janiceilene** [comment]
@bon77 Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by ajsirota — APPROVED** [review]
LGTM! :+1:

**Review by goatdawg — CHANGES_REQUESTED** [review]
> 

> ``

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Review by shati-patel — APPROVED** [review]
Thank you for the update @bon77! Much appreciated 😃 

I'll get this merged shortly.

**Pull request merged**
