### PR TITLE
fixing gh-21736

### LINKED ISSUE #21736: Adding '+'  for creating unordered lists
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

### What part(s) of the article would you like to see updated?

the lists part where creation of unordered list is explained with `-` `*` but not with `+` . So it should be added with it's examples 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ramvikrams**
### Why:

Closes [gh-21736]
Closes #21736 

### Check off the following:

- [x]  I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@ramvikrams Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by sophietheking — APPROVED** [review]
Hi @ramvikrams 👋  Thanks for opening this PR and contributing to our Docs, we really appreciate it! ✨  I made one small change (https://github.com/github/docs/pull/21741/commits/5178f52b51909818da0794c48734714d46e5722f). I will approve your PR and get it merged! 🚀

**Comment by cmwilson21** [comment]
Testing closing and reopening this to rerun the preview deploy.

**Review by cmwilson21 — APPROVED** [review]
Approving review after close/reopen

**Comment by ramvikrams** [comment]
> Approving review after close/reopen

Thanks

**Comment by cmwilson21** [comment]
@ramvikrams Sorry for the delay! I ran into some technical difficulties while getting this merged. Thanks for the contribution!

**Comment by ramvikrams** [comment]
> @ramvikrams Sorry for the delay! I ran into some technical difficulties while getting this merged. Thanks for the contribution!

No problem mam, thanks your help.

**Pull request merged**
