### PR TITLE
Update securing-your-webhooks.md

### PR DESCRIPTION
**Pull request by kristianjaeger**
For example in C# you may need to use Encoding.UTF8.GetBytes(payload) instead of Encoding.ASCII.GetBytes(payload). Thanks. Cheers.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by NaYGAmE7890** [comment]
Free

**Review by The-Pharoah — CHANGES_REQUESTED** [review]
Thx

**Review by The-Pharoah — CHANGES_REQUESTED** [review]
Help secure?

**Comment by kristianjaeger** [comment]
@The-Pharoah Yes, this is related to securing the web hook. For someone to properly validate the web hook they need to treat the payload as unicode.  Otherwise if there's a unicode character in the webhook JSON the signature will not be validated properly. A few examples of how this can happen are 1) if there's a long merge commit title GitHub automatically puts a "..." unicode character in the message field of the JSON, 2) if someone's name has unicode characters, or 3) if someone uses unicode characters in their pull request title. Cheers.

**Comment by janiceilene** [comment]
@kristianjaeger Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by kristianjaeger** [comment]
Thanks, @janiceilene !

**Review by lucascosti — APPROVED** [review]
Thanks a lot for this contribution, @kristianjaeger! 🙇‍♂️ 

I've reworded the new encoding note and separated it into a separate block closer to the complete code example.

I'll get this merged in! 🎉

**Comment by kristianjaeger** [comment]
Thanks so much, @lucascosti and @janiceilene ! Cheers.

**Pull request merged**
