### PR TITLE
Updated the Set Up Git file

### PR DESCRIPTION
**Pull request by NikNikovsky**
If you find any errors, please point them out.

### Why:
I am hoping for a better user experience and maybe building trust among GitHub users.

### What's being changed (if available, include any code snippets, screenshots, or gifs):
I am making this look more appealing to the end user using Grammarly to fix the language in the documents

### Check off the following:

- [v] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [v] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@NikNikovsky Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by NikNikovsky** [comment]
> Thanks so much for opening a PR! I'll get this triaged for review ⚡
Thank you.
I shall continue improving GitHub when i have time.

**Review by BTCLaravel — COMMENTED** [review]
gh pr checkout 24107

**Comment by NikNikovsky** [comment]
> gh pr checkout 24107

What does that mean?
Just wondering

**Review by mchammer01 — APPROVED** [review]
@NikNikovsky 👋🏻 - thanks for improving our docs 🎉

**Comment by Botino888** [comment]
sorry maybe I'm wrong, useless

Tải xuống Outlook dành cho Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NikNikovsky** [comment]
> @NikNikovsky 👋🏻 - thanks for improving our docs 🎉

You're welcome.

**Pull request merged**
