### PR TITLE
fix action buttons on mobile

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/github/docs/issues/1468

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://docs-1476--fix-btn.herokuapp.com/en/free-pro-team@latest/actions
after fix

**Comment by janiceilene** [comment]
@Arhell I see this is currently a draft PR, let me know when you're ready for review from the docs team and I'll get it triaged 💖

**Comment by Arhell** [comment]
@janiceilene ready for review

**Comment by chiedo** [comment]
It looks good! 🙏🏿  Can you update the branch so it's not out-of-date with the base branch?

**Review by chiedo — APPROVED** [review]

**Comment by Arhell** [comment]
Done

**Comment by chiedo** [comment]
Thanks for your help @Arhell !

**Pull request merged**
