### PR TITLE
Dependabot: update supported terraform versions

### PR DESCRIPTION
**Pull request by gmile**
Bump supported terraform versions to 1.3.x

### Why

There's evidence folks are using terraform 1.3.x with dependabot, see: https://github.com/dependabot/dependabot-core/issues/6316. At the same time current documentation indicates only 1.2.x versions of terraform are supported, which may be misleading to some.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Supported version of Terraform is being bumped to 1.3.x family of versions.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Notes

* Prior version bump can be seen here https://github.com/github/docs/pull/18646

### CODE REVIEW

**Comment by Natsoye** [comment]
gmile:patch-1

**Comment by cmwilson21** [comment]
@gmile Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by jurre — APPROVED** [review]
Yep, that's correct! https://github.com/dependabot/dependabot-core/blob/67583efda736a3391632d268c681d54819d49efa/Dockerfile#L258

**Review by mchammer01 — APPROVED** [review]
@gmile - LGTM, thanks for fixing this inaccuracy in our docs ✨

**Pull request merged**
