### PR TITLE
https://github.com/npm/npm/bsc1780/447afc8316536405dc3fc3a682edad5294…

### PR DESCRIPTION
**Pull request by Branscott1780**
…3c6c0e/.mailmap

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

I was removed from contribution contributes for my profile @branscott1780. Should be added to npm/npm and all other should be removed and therefore, any contribution made to force the removed . even so while being blocked from contribution but did any way should be exposed and reported and delt with by the security of this sight I ask the npm be paused till further notice. @branscott1789

### CODE REVIEW

**Review by Branscott1780 — COMMENTED** [review]
I was removed from contribution contributes for my profile @Branscott1780. Should be added to npm/npm and all other should be removed and therefore, any contribution made to force the removed . even so while being blocked from contribution but did any way should be exposed and reported and delt with by the security of this sight I ask the npm be paused till further notice. @branscott1789

> ``

**Comment by Branscott1780** [comment]
# @bsc1780 missing

**Comment by Branscott1780** [comment]
#ffffff overlay

**Review by ghost — COMMENTED** [review]
@mtodd 
https://circleci.com/docs/2.0/docker-to-machine/#pre-installed-software

**Pull request closed without merging**
