### PR TITLE
Explicitly call out that Dependabot only updates direct dependencies by default

### PR DESCRIPTION
**Pull request by LingMan**
Dependabot does not update indirect dependencies by default. This has caused confusion for some users in the past (yours truly included), so mention it explicitly in higher level documentation new Dependabot users are likely to read.

Original discussion: https://github.com/dependabot/dependabot-core/issues/5437

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by tranthithoa0803 — COMMENTED** [review]
Ok

**Review by tranthithoa0803 — COMMENTED** [review]
Ok

**Comment by cmwilson21** [comment]
@LingMan Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by jules-p — APPROVED** [review]
Hey @LingMan 👋🏻 Thank you so much for opening this PR. I've made a minor change to align with our style guide, but this looks great and ready to merge now. 🚀 ✨ 💖

**Pull request merged**
