### PR TITLE
Add server_url to github context

### PR DESCRIPTION
**Pull request by bwhaley**
I found that `server_url` works in the `github` context. Perhaps all of the `GITHUB*` environment variables work in the `github` context? Not sure, haven't tested them all.

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@bwhaley 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
🚀 Thanks for this addition! I'll get this merged down for you.

**Comment by ramyaparimi** [comment]
@bwhaley It looks like I don't have permission to resolve the merge conflict. I think if you enable the checkbox to allow maintainer edits, then I will be able to resolve this. (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork ) Alternatively, could you resolve the merge conflict?

**Comment by bwhaley** [comment]
Merged from main! How does it look now?

**Comment by ramyaparimi** [comment]
> Merged from main! How does it look now?

Awesome!!!!! Thanks so much. Updating branch and merging now ✨

**Comment by bwhaley** [comment]
Thanks for maintaining the docs!

**Pull request merged**
