### PR TITLE
Add Secret Scanning validation sample in JavaScript

### PR DESCRIPTION
**Pull request by Piccirello**
### Why:

This PR adds a JavaScript code sample for verifying the Secret Scanning payload signature.

### What's being changed:

Added code sample.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by nenehulc — COMMENTED** [review]
Good

**Comment by janiceilene** [comment]
👋 @Piccirello Can you explain a little about why you think this code sample is an important addition? Thank you!

**Comment by greysteil** [comment]
@janiceilene - I can do the explaining on this one, I asked @Piccirello to submit this!

Verifying the requests that GitHub secret scanning makes to partner endpoints is a fiddle. It can take partners hours to get their verifications working, and we want to help them as much as possible. Code snippets like this one (we also have them for Go and Ruby) are a great shortcut, and this code is pretty evergreen - it's not going to go out of date anytime quickly.

In an ideal world we'd have a nice experience where folks can click between different languages, to see the implementation in the one that's relevant to them. I don't think we have any precedent for that yet though, unless I'm mistaken?

Thanks for the pull request @Piccirello!

**Review by shati-patel — APPROVED** [review]
Thank you so much for the pull request, @Piccirello! 😃 

Given the extra context from @greysteil (thank you!) this looks good to merge 🎉

**Pull request merged**
