### PR TITLE
Update deploying-runner-scale-sets-with-actions-runner-controller.md

### LINKED ISSUE #27791: Remove repeated word, "setting"
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Configuring Kubernetes mode](https://docs.github.com/en/enterprise-server@3.9/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#configuring-kubernetes-mode)

### What part(s) of the article would you like to see updated?

There's a word repeated in the block,

> In order to allow jobs without a job container to run, you need to instruct the runner to disable this check. You can do that by **setting setting** ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER to false on your runner container

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aaronkjones**
Remove repeated word, "setting"

### Why:

There is a repeated word.

Closes: [#27791](https://github.com/github/docs/issues/27791)

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Tarsuslummmm** [comment]
Sa

**Comment by Tarsuslummmm** [comment]
Gel

**Comment by Tarsuslummmm** [comment]
Zz

**Comment by cmwilson21** [comment]
@aaronkjones Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! And welcome to the community! 🎉

**Review by mchammer01 — APPROVED** [review]
@aaronkjones 👋🏻 - thanks for fixing this typo ✨ 
LGTM :shipit:

**Pull request merged**
