### PR TITLE
Add a couple of inline links for convenience to close #2732

### LINKED ISSUE #2732: Add a couple of inline links to the Reusables and variables section of content-style-guide.md
### What article on docs.github.com is affected?
This issue actually isn't in relation to an issue with docs.github.com. I'd like to improve [the "Reusables and variables" section of `contributing/content-style-guide.md`](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#reusables-and-variables) by adding a couple of inline links for convenience.

### What part(s) of the article would you like to see updated?
I would like to change the final sentence of the section I just mentioned, 

> For more information, see the data directory in the github/docs repository and the “Product names” section of this document.

so that "data directory" and "Product names" have links to the appropriate sections for faster access.

### Additional information
I think this would make it easier for first-time contributors to this repository to find the information they need. I may have a fix for this.

### PR DESCRIPTION
**Pull request by hirehamir**
Closes #2732.

### Why:
I think adding inline links will increase the productivity of people wanting to contribute, especially first-time contributors.

### What's being changed:
I changed the last sentence of [the "Reusables and variables" section of `contributing/content-style-guide.md`](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#reusables-and-variables), which is
> For more information, see the data directory in the github/docs repository and the “Product names” section of this document.

to use a couple of relative links to access the appropriate sections, since I think this makes navigation easier and more convenient.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@hamirmahal Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by emilyistoofunky — APPROVED** [review]
Thanks @hamirmahal! ✨  We'll get this merged soon.

**Comment by rifatwoclan** [comment]
Listo

**Comment by hamirmahal** [comment]
@emilyistoofunky @janiceilene You're welcome! Thank you for approving and merging.

**Pull request merged**
