### PR TITLE
Fix typo avaiable in about-github-copilot-chat-in-githubcom.md

### PR DESCRIPTION
**Pull request by lastlevelbus**
### Why:

avaiable should be available? 🤔

### What's being changed (if available, include any code snippets, screenshots, or gifs):

avaiable changed to available

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by lastlevelbus** [comment]
No idea how `content/copilot/github-copilot-enterprise/copilot-chat-in-github/about-github-copilot-chat-in-githubcom.md` has matched any of the "unallowed file changes" 🤔

**Comment by lastlevelbus** [comment]
Preview looks good!

**Comment by nguyenalex836** [comment]
@lastlevelbus Thank you for submitting this PR! ✨ I'm going to check with the team why our "spelunker" message is triggering for the updates made to `about-github-copilot-chat-in-githubcom.md`. 

I'll return once I have more information 💛

**Comment by nguyenalex836** [comment]
@lastlevelbus Howdy 👋 ! After discussing with the team, it looks like that file is a `rai` file, which we cannot accept contributions toward - 

> We also can't accept contributions to files in the content directory with frontmatter `type: rai`

Apologies, I missed this during my initial investigation! I'll file an issue internally to have this typo fixed, and will close out this issue. Thank you again for raising a flag on this typo! 💛 

If you're looking for another issue to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

**Pull request closed without merging**
