### PR TITLE
Update section related to downloading/uploading GHES license file

### PR DESCRIPTION
**Pull request by stacycarter**
### What's being changed:

"How to download the license file" is often a top concern and I'm proposing that we reflect this in the section header.

**Current section header:**

"Uploading a new license to GitHub Enterprise Server"

**Proposed new section header:**

"Downloading a new license file and uploading it to GitHub Enterprise Server"

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@stacycarter Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by mchammer01 — DISMISSED** [review]
@stacycarter - this change LGTM and clarifies things for our customers 💖 
However this anchor is being used in 2 other locations in the docs, and need updating as a result:

- /admin/advanced-security/enabling-github-advanced-security-for-your-enterprise
- /admin/overview/managing-your-github-enterprise-license

where `/admin/overview/managing-your-github-enterprise-license#uploading-a-new-license-to-github-enterprise-server` should now be `/admin/overview/managing-your-github-enterprise-license#downloading-a-new-license-and-uploading-it-to-github-enterprise-server`

Any chance you could update these two anchors in these two files?
I can try and push a commit to your branch too (but I need to investigate if I have enough permissions to do that).

**Comment by mchammer01** [comment]
I managed to get your branch and made the changes myself 🙂

**Review by mchammer01 — APPROVED** [review]
LGTM 💖

**Pull request merged**
