### PR TITLE
Update point 2 of Creating your first workflow

### PR DESCRIPTION
**Pull request by shreeya-sengupta**
On reading point 2 of Creating your first workflow section it is not clear that the commit should not be done immediately on the same branch (point 2) and the user should go to point 3 before committing. Adding an extra line in point 2 to inculcate this clarity.

### Why:
 Improvement in the "Github Action - Quickstart" document, section "Creating your first workflow". To the best of my understanding issue need not be created for a document updation and only a PR request should suffice.

### What's being changed:

image
On reading point 2 of Creating your first workflow section it is not clear that the commit should not be done immediately on the same branch (point 2) and the user should go to point 3 before committing. Adding an extra line in point 2 to inculcate this clarity.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@shreeya-sengupta Thanks so much for opening a PR! I'll get this triaged for review 🌟

**Comment by shreeya-sengupta** [comment]
@janiceilene : Hi, thanks for adding it to the docs team reviews. Any further updates? Thanks

**Comment by janiceilene** [comment]
@shreeya-sengupta Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by lecoursen** [comment]
Thanks so much for opening this PR! We're not currently planning to change this right now.

**Pull request closed without merging**
