### PR TITLE
Fixing Azure DevOps NuGet Dependabot config examples

### PR DESCRIPTION
**Pull request by joshjohanning**
### Why:

The documentation as is doesn't work with using `token: ${{secrets.MY_AZURE_DEVOPS_TOKEN}}`

You receive a 401 error in the [Dependabot logs](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/troubleshooting-dependabot-errors#investigating-errors-with-dependabot-version-updates), as shown below: 

```
{:source=>"https://pkgs.dev.azure.com/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json"}
updater | INFO <job_312553835> Checking if Microsoft.Extensions.Logging.Abstractions 2.0.0 needs updating
  proxy | 2022/03/09 22:42:52 [046] GET https://pkgs.dev.azure.com:443/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json
  proxy | 2022/03/09 22:42:52 [046] * authenticating nuget feed request (host: pkgs.dev.azure.com, bearer auth)
  proxy | 2022/03/09 22:42:52 [046] 401 https://pkgs.dev.azure.com:443/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json
updater | INFO <job_312553835> Handled error whilst updating Microsoft.Extensions.Logging.Abstractions: private_source_authentication_failure 
```

Others have had this issue, mentioned here: https://github.com/dependabot/dependabot-core/issues/3555

One of the solutions as to add a `:` somewhere in the `token` to force it to use basic auth, like this:

```yml
registries:
  nuget-azure-artifacts:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json
    token: '${{ secrets.AZURE_DEVOPS_PAT }}:'
```

But instead, `username` and `password` is a cleaner and more consistent solution since that what the other examples right above it are using:

```yml
registries:
  nuget-azure-artifacts:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/jjohanning0798/PartsUnlimited/_packaging/nuget-example/nuget/v3/index.json
    username: octocat@example.com
    password: ${{ secrets.AZURE_DEVOPS_PAT }}
```

For tracking purposes, I mistakenly created this as a PR in my repo in March, but I have verified that this is still an issue today. https://github.com/joshjohanning/docs/pull/53

### What's being changed:

On the [Dependabot version updates configuration page](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#nuget-feed), changing the Azure DevOps examples to use `username` and `password` instead of `token`.

There are two instances of an Azure DevOps Artifact feed being used, and in both cases, it uses the `token` property to authenticate. However, that doesn't work. In lieu of the `token` property being fixed to not have to manually include a `:` somewhere in the token property for it to use basic auth to be able to connect, we should just use `username` and `password` using the personal access token, like shown in the screenshots below.

Changing this:
image

To:
image

We are still saying that it can use a username and password OR token, though.  If we still wanted to show an example of using a token, I suggest we do that for the regular nuget feed url ( `https://nuget.example.com/v3/index.json` ) and not the Azure DevOps artifact feed url since that doesn't work. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by joshjohanning** [comment]
If we still wanted to show a `username and password` example and a `token` example, I would envision something like this (flipping the two examples around) :




```
    ### `nuget-feed`
    
    The `nuget-feed` type supports username and password, or token.
    
    {% raw %}
    ```yaml
    registries:
      nuget-azure-devops:
        type: nuget-feed
        url: https://pkgs.dev.azure.com/.../_packaging/My_Feed/nuget/v3/index.json
        username: octocat@example.com
        password: ${{secrets.MY_AZURE_DEVOPS_PAT}}
    ```
    {% endraw %}
    
    {% raw %}
    ```yaml
    registries:
      nuget-example:
        type: nuget-feed
        url: https://nuget.example.com/v3/index.json
        password: ${{secrets.MY_NUGET_TOKEN}}
    ```
    {% endraw %}

    ### `python-index`
    
    The `python-index` type supports username and password, or token.
    
    {% raw %}
    ```yaml
    registries:
      python-azure:
        type: python-index
        url: https://pkgs.dev.azure.com/octocat/_packaging/my-feed/pypi/example
        username: octocat@example.com
        password: ${{secrets.MY_AZURE_DEVOPS_PAT}}
        replaces-base: true
    ```
    {% endraw %}

    {% raw %}
    ```yaml
    registries:
      python-example:
        type: python-index
        url: https://example.com/_packaging/my-feed/pypi/example
        token: ${{secrets.MY_PYPI_TOKEN}}
        replaces-base: true
    ```
    {% endraw %}
```

**Comment by cmwilson21** [comment]
👋 @joshjohanning Thanks for opening a PR! I'll get it triaged! ⚡

**Comment by jeffwidman** [comment]
We may want to see how hard it is to simply get the underlying issue fixed, IMO that'd be better from a security perspective than switching away from tokens:
* https://github.com/dependabot/dependabot-core/issues/3555

Not sure how hard that is though, I'll take a look...

**Comment by joshjohanning** [comment]
I agree that the _best_ solution is probably to have that bug fixed...

But I'm not sure if it makes any difference from a security perspective, at least in the Azure DevOps example, since Azure DevOps is going to be a Personal Access Token regardless of whether we're able to use `token` or `username and password` - it's a PAT that's going to be used for authentication either way. 

FWIW, [msft docs reference](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops#publish-packages-from-external-sources) using a username and password to auth to Azure Artifacts, for example, which uses a PAT for the password (and coincidentally, the username field can be anything). 

But right now us showing Azure DevOps examples that don't work is not ideal.

**Review by felicitymay — APPROVED** [review]
Thanks for the update

**Comment by jeffwidman** [comment]
Sorry for the slow response @joshjohanning, I looked into this more and what you say makes complete sense.

Especially:
> But I'm not sure if it makes any difference from a security perspective, at least in the Azure DevOps example, since Azure DevOps is going to be a Personal Access Token regardless of whether we're able to use token or username and password - it's a PAT that's going to be used for authentication either way.

I didn't realize they accepted the PAT either way.

Thanks again for this!

**Comment by joshjohanning** [comment]
Woot woot! Thanks @jeffwidman

**Pull request merged**
