### PR TITLE
docs: properly quote wildcard character for `dependency-name`

### LINKED ISSUE #7646: Missing quotes on `*` wildcard for `dependency-name`
### What article on docs.github.com is affected?
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore

Incorrectly references `dependency-name: *` which if copied and used within a `dependabot.yml` file cannot be parsed. The `*` should be quoted.

### PR DESCRIPTION
**Pull request by sjungling**
### Why:

Currently, the documentation contains an inline example that when copied directly and used in a `dependabot.yml` config causes Dependabot to be unable to parse the config and breaks Dependabot.

closes #7646

### What's being changed:

Quote the `*` in the inline text.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Hbutlercapone — APPROVED** [review]

**Review by Hbutlercapone — APPROVED** [review]

**Comment by janiceilene** [comment]
👋 @sjungling Please fill out the **Why** and **What's being changed** part of the pull request template in the top comment to help us triage your issue to the best folks. Let me know when that's done and I'll get this up for review 💛

**Comment by sjungling** [comment]
> 👋 @sjungling Please fill out the **Why** and **What's being changed** part of the pull request template in the top comment to help us triage your issue to the best folks. Let me know when that's done and I'll get this up for review 💛

Hi @janiceilene updated the PR template and created an associated issue per instructions

**Review by felicitymay — APPROVED** [review]
@sjungling - many thanks for reporting this omission in the docs and fixing it 💖 

Your change looks great. I'll need to update your branch from `main` and then we can merge the PR.

**Comment by Daytonshaver140** [comment]
yep.

**Pull request merged**
