### PR TITLE
Add documentation for markdown's note/warning syntax

### LINKED ISSUE #25237: Add Documentation about warning and Note markdown syntax
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

The Github Markdown: [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

### What part(s) of the article would you like to see updated?

The [Quoting Text](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-text) section.

This section doesn't mention the syntax to generate the following markdown:
```md
> **Note**
> Info text

> **Warning**
> warning text
```
> **Note**
> Info text

> **Warning**
> warning text

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vinalti**
### Why:

By chance I discovered the Note and Warning markdown syntax to make :
> **Note** A note in markdown

> **Warning** Or a warning in markdown

```markdown
> **Note** A note in markdown

> **Warning** Or a warning in markdown
```

I couldn't find it referenced in the documentation.

Closes: #25237 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added a section under `Quoted Text` for `Special Quoted Text` including the  `> **Note**`  and `> **Warning**` Syntax

> **Note**
> I think that this syntax should be updated according to [received comments](https://github.com/orgs/community/discussions/16925).
> In particular due to the lack of flexibility for the title and the lack of compatibility with the HTML standard.  
> The future changes being able to break the current behavior the current PR may not be implemented as is.

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Vinalti** [comment]
First mentioned [here](https://github.com/orgs/community/discussions/16925)

**Comment by pboling** [comment]
As explained at length by many people, quite eloquently in some cases, this feature needs to be killed before it gets any more entrenched.

See: https://github.com/orgs/community/discussions/16925

**Comment by Vinalti** [comment]
Thank you for your answer, I hope developers will come up with a replacement solution then.

**Comment by cmwilson21** [comment]
Throwing in the comment from https://github.com/github/docs/issues/25237#issuecomment-1531736368 as reference to this closing 💛

**Pull request closed without merging**
