### PR TITLE
Update community exchange requirements

### PR DESCRIPTION
**Pull request by plskz**
### Why:

There's a new requirement for submitting a repository in community exchange

### What's being changed (if available, include any code snippets, screenshots, or gifs):

image

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@plskz Thanks so much for opening a PR! We appreciate the added details. I'll get this triaged for review :zap:

**Review by ghost — COMMENTED** [review]
630607d0d42cff9731a9f54a79cb9bd660253b6b

**Review by ghost — COMMENTED** [review]
4AEE18F83AFDEB23

**Review by nutty323 — COMMENTED** [review]
[automerge](https://github.com/github/docs/actions/workflows/automerge.yml)

**Review by nutty323 — COMMENTED** [review]
Update community change requirements

**Review by nutty323 — COMMENTED** [review]
Update community change requirements

**Review by sophietheking — APPROVED** [review]
@plskz thank you so much for opening a PR and contributing to our Docs! ✨ 🚀  I've approved your PR and will get it merged.

**Pull request merged**
