### PR TITLE
Fix invalid syntax for pull_request_target example

### LINKED ISSUE #1891: Invalid syntax for workflow pull_request_target event example
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

[`pull_request_target` example](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target) has a YAML syntax error due to a missing colon.

#### Docs: :point_down: 
<kbd>
 pull_request_target docs
</kbd>

#### Syntax Error: :point_down: 
<kbd>
  invalid yaml
</kbd>

### Additional information

PR: #1890

### PR DESCRIPTION
**Pull request by tomjschuster**
### Why:

fixes #1891

Example for `pull_request_target` is missing a colon after the `pull_request_target` key, resulting in a YAML syntax error.

#### Docs: :point_down: 
<kbd>
  pull_request_target docs
</kbd>

#### Syntax Error: :point_down:
<kbd>
  invalid yaml
</kbd>

### What's being changed:

Add colon after `pull_request_target` key and move to new line:

#### Docs: :point_down: 
<kbd>
  pull_request_target docs fixed
</kbd>

#### Valid YAML: :point_down:
<kbd>
  valid yaml
</kbd>

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — APPROVED** [review]

**Comment by janiceilene** [comment]
@tomjschuster Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by tomjschuster** [comment]
Just commenting to keep this open.

**Comment by janiceilene** [comment]
@tomjschuster Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by tomjschuster** [comment]
Just commenting to keep this open. Hope everyone is enjoying their holidays.

**Comment by DozerKatDC10** [comment]
Having hard time signing from pc lot of redirects

**Comment by DozerKatDC10** [comment]
{' why redirects trying to sign in/{

**Comment by skedwards88** [comment]
LGTM! Thank you for opening this issue and making a fix! I'll get it merged down for you.

**Review by skedwards88 — APPROVED** [review]
LGTM! Thank you for opening this issue and making a fix! I'll get it merged down for you.

**Comment by jace4511** [comment]
> LGTM! Thank you for opening this issue and making a fix! I'll get it merged down for you.

**Pull request merged**
