### PR TITLE
Updates REST API examples to HTTP/2

### LINKED ISSUE #5992: [Improvement]: Update REST API examples to use HTTP/2 instead of HTTP/1.1
### What feature or product is affected?

REST API

### What is the new or expected behavior?

use HTTP/2 instead of HTTP/1.1

### How is the old or inaccurate behavior currently documented?

The REST API examples should use HTTP/2 instead of HTTP/1.1

For example, in [this code snippet](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#schema),

```
> HTTP/1.1 200 OK
```

would change to

```
> HTTP/2 200
```

Note: To compare HTTP2 vs HTTP1.1 responses, you can pass the `-v` option to curl: `curl -i https://api.github.com -v --http1.1`

### Who does this affect?

users of the REST API

### What is the impact to users?

confusion about differences between the API responses that the user sees and what the docs show

### PR DESCRIPTION
**Pull request by lucalves**
### Why:

Hello everyone, everything good?

According to Issue #5992, generated by @docs-bot, it is recommended to use HTTP/2 instead of HTTP/1.1, as 2 is faster for responses.

**Closes #5992**.

### What's being changed:

I made the change from HTTP/1.1 to HTTP/2 in the documentation.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Aytac998** [comment]
> ### Neden:
> Herkese merhaba, her şey yolunda mı?
> 
> @ Docs-bot tarafından oluşturulan Sayı [# 5992'ye göre](https://github.com/github/docs/issues/5992) , yanıtlar için 2 daha hızlı olduğundan HTTP / 1.1 yerine HTTP / 2 kullanılması önerilir.
> 
> **Kapatır [# 5992](https://github.com/github/docs/issues/5992)** .
> 
> ### Neler değişiyor:
> Dokümantasyonda HTTP / 1.1'den HTTP / 2'ye değişikliği yaptım.
> 
> ### Aşağıdakileri kontrol edin:
> * [x] Sahnelemedeki değişiklikleri inceledim. ( Çekme isteğinizde **heroku'ya dağıtma** bağlantısını bulun, ardından **Dağıtımı görüntüle'yi** tıklayın )
> * [x] İçerik değişiklikleri için [yerelleştirme kontrol listesini](https://github.com/github/docs/blob/main/contributing/localization-checklist.md) inceledim[](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x] İçerik değişiklikleri [için GitHub Docs için İçerik stili kılavuzunu](https://github.com/github/docs/blob/main/contributing/content-style-guide.md) inceledim .

A

**Review by Ice991 — COMMENTED** [review]
Updates REST API examples to HTTP/2

**Comment by janiceilene** [comment]
Thanks for picking up this work so quickly @lucalves! I'll get this triaged for review ⚡

**Review by skedwards88 — COMMENTED** [review]
✨ Thank you for opening this PR! I have one nit comment that [HTTP/2 does not support status messages](https://fetch.spec.whatwg.org/#concept-response-status-message) (i.e., it returns `200` instead of `200 OK`). Are you willing to also make this change to the PR?

**Comment by lucalves** [comment]
> ✨ Thank you for opening this PR! I have one nit comment that [HTTP/2 does not support status messages](https://fetch.spec.whatwg.org/#concept-response-status-message) (i.e., it returns `200` instead of `200 OK`). Are you willing to also make this change to the PR?

Yes, I make the change and I will commit soon.

**Review by skedwards88 — COMMENTED** [review]
Close! I believe all of the status messages should be removed. (e.g. `404 Not Found` -> `404`, `201 Created` -> `201`, etc.)

**Comment by lucalves** [comment]
Hello, @skedwards88, I think it's ok now! You can verify?

**Review by skedwards88 — APPROVED** [review]
🎉 Yay this looks great! I'll get it merged down for you.

**Pull request merged**
