### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Arifan998**
Optional extended

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Arifan998** [comment]
Optional extended



### Why:

Closes [issue link]



### What's being changed:



### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Comment by Arifan998** [comment]
range

**Review by Romansss2 — APPROVED** [review]

**Review by Romansss2 — APPROVED** [review]

**Comment by octocat69** [comment]
U going to be smiling silent now 😂

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 25, 2021 at 6:38 PM, Smile ***@***.***> wrote:   


range

**Comment by Romansss2** [comment]
~~~~

**Pull request closed without merging**
