### PR TITLE
Update broken command in docs to add an existing project to GitHub using the command line

### LINKED ISSUE #11030: Command in article to pull latest changes from branch of newly made repo is broken
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Adding an existing project to GitHub using the command line](https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line)

Browser: Brave Browser Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)

Screen Shot 2021-10-10 at 7 10 58 PM

Screen Shot 2021-10-10 at 7 11 07 PM

### What changes are you suggesting?

A possible fix: I am expecting that this command pulls the latest changes from the remote repository. So, I found that simply omitting --set-upstream also achieves that. The fixed command can simply be `$ git pull origin main`.

The docs should be changed to allow the user to copy and paste the command, and observe the expected result stated in the doc. Use case: Anytime someone wants to add an existing project to GitHub using the command line, this command may be used from the docs.

Expected outcome: The fixed command works as expected in the docs and helps user pull latest changes from the remote repo.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Kartikeya1012**
Here is the output I get with the original command

```
$ git pull --set-upstream origin main
error: unknown option `set-upstream'
usage: git pull [<options>] [<repository> [<refspec>...]]
...
```

Just executing `$ git pull origin main` does the trick here.

### Why:

Closes #11030

### What's being changed:

Changing the command from `$ git pull --set-upstream origin main` to `$ git pull origin main` in the documentation file. This fixes the broken command mentioned in the issue, helps increase clarity of what the command is expected to do.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Jassi10000-zz — COMMENTED** [review]
@Kartikeya1012 
Buddy , the original command 
<code> git pull --set-upstream origin main </code>
is perfectly written , issue is you are not able to undestand what its actually saying

If you look closely in the error, It says:

```
error: unknown option `set-upstream'
usage: git pull [<options>] [<repository> [<refspec>...]]
```
The second line here means you have to first provide the link of the repository from which you have made the pull or from which you want to pull new changes 

To undestand the upstream concept  read this 

### When you push to a remote and you use the --set-upstream flag git sets the branch you are pushing to as the remote tracking branch of the branch you are pushing. Adding a remote tracking branch means that git then knows what you want to do when you git fetch , git pull or git push in future

If you have any doubts , just google first or ask someone in the community 
I hope you understood a lil 

All the best for ur further contributions

**Comment by Kmk2368** [comment]
content/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line.md

**Comment by Kartikeya1012** [comment]
@Jassi10000

Thanks for the comment. Unfortunately, I am unable to understand what you are trying to convey. While I understand what `--set-upstream` does, I am not sure if it is a flag for `git pull` as of today. I think the error does not recognize this flag, but it seems maybe the error is not that.

Could you please write the command to pull changes from a newly made repository, that is, to achieve the expected result of [step 5 of this article](https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line)? I would love to learn more from you! Thanks!

**Review by Kmk2368 — COMMENTED** [review]
content/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line.md #11288

**Pull request closed without merging**
