### PR TITLE
Update authorizing-an-ssh-key-for-use-with-saml-single-sign-on.md

### PR DESCRIPTION
**Pull request by nneul**
Note about ssh revocation.

### Why:

Doc doesn't make clear the scope of impact of revoking an SSH key. 

### What's being changed:

Trivial documentation update to clarify the scope of impact of revoking the key.

### Check off the following:
- [X ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by LEBATRUNG** [comment]
Tkanh

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by nneul** [comment]
@janiceilene

**Comment by janiceilene** [comment]
@nneul Could you fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by nneul** [comment]
updated.

**Comment by janiceilene** [comment]
Thanks so much @nneul! I'll get this triaged for review 🌟

**Comment by ethanpalm** [comment]
Hi @nneul, thanks for opening a PR! Since the scope of this article deals with authorizing an SSH key with one organization, the note is correct and I'm going to close this PR.

Thanks for your passion and taking the time to contribute to the GitHub docs!

**Pull request closed without merging**
