### PR TITLE
spelling error in intro paragraph

### LINKED ISSUE #22598: Small spelling mistake in creating webhooks page.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks

### What part(s) of the article would you like to see updated?

You'll first need to set up what events  __you__ webhook should listen to. 

The you should be "your" :)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by clxmente**
### Why:

Closes [#22598](https://github.com/github/docs/issues/22598)

### What's being changed (if available, include any code snippets, screenshots, or gifs):
image

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by anandfresh — COMMENTED** [review]
Approved

**Comment by cmwilson21** [comment]
@clxmente Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Comment by cmwilson21** [comment]
@clxmente Great catch! I'll get this merged down once all the checks have passed ✅ 

Thanks for the PR! ⚡

**Review by cmwilson21 — APPROVED** [review]
LGTM 👍

**Pull request merged**
