### PR TITLE
Searching on blank string fix

### PR DESCRIPTION
**Pull request by ChiragKr04**
### Why:

https://github.com/github/docs/issues/3154

### What's being changed:

./javascripts/search.js

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by ChiragKr04** [comment]
#3154

**Comment by ChiragKr04** [comment]
#3154

**Comment by ChiragKr04** [comment]
#3154

**Review by heiskr — COMMENTED** [review]
Hi @ChiragKr04 :wave:

Thanks for opening this PR.

I think we still want the `toggleStandaloneSearch` and emptying/rerendering bits to happen if there's no query, in case some types a query and then deletes it.

**Comment by ChiragKr04** [comment]
> Hi @ChiragKr04 :wave:
> 
> Thanks for opening this PR.
> 
> I think we still want the `toggleStandaloneSearch` and emptying/rerendering bits to happen if there's no query, in case some types a query and then deletes it.

Ahh yes! I got your point.

**Comment by heiskr** [comment]
Hi @ChiragKr04 we've integrated this work separately, thank you for your help 💖

**Review by danielchaney187 — APPROVED** [review]

**Pull request closed without merging**
