### PR TITLE
Update automatically-merging-a-pull-request.md

### PR DESCRIPTION
**Pull request by KnapSac**
### Why:
The sentence was grammatically incorrect.

### What's being changed:
Added missing 'with' to create a correct sentence.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@KnapSac Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by Vahid0024sohel0024monavar0024** [comment]
سلام به خوبا

**Comment by afsaneh92117** [comment]
با سلام بی صبرانه منتظر چنین روزی بودم

در تاریخ سه‌شنبه ۲۶ ژانویهٔ ۲۰۲۱،‏ ۱۲:۵۸ ب.ظ Casper Verhaar <
notifications@github.com> نوشت:

**Comment by afsaneh92117** [comment]
Komakam konid khasteh shodam  khodaro shokr mikonam ye hamzabon peyda
kardam

در تاریخ پنجشنبه ۲۸ ژانویهٔ ۲۰۲۱،‏ ۳:۳۵ ق.ظ Afsaneh Heydari <
afsanh3108@gmail.com> نوشت:

**Comment by ethanpalm** [comment]
👋  Thanks for opening a PR. This doc is accurate as its currently written, so I'm closing this.

You can check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label if you want to see other issues ready for PRs. :sparkles:

**Pull request closed without merging**
