### PR TITLE
Issue forms: set the "body" field as required

### PR DESCRIPTION
**Pull request by tomrav**
### Why:

Found a mistake in the docs.

### What's being changed:

In the documentation for the new "Issue Forms" the `body` field is marked as `optional`, it should be `required`.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@tomrav Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ivan0117** [comment]
https://github.com/github/docs/pull/8430/files

**Review by ivan0117 — COMMENTED** [review]
p

**Review by ivan0117 — CHANGES_REQUESTED** [review]
p

**Review by hubwriter — APPROVED** [review]
@tomrav - Many thanks for fixing this. Much appreciated. 👍

**Pull request merged**
