### PR TITLE
Fix Actions branch glob documentation.

### PR DESCRIPTION
**Pull request by chrisgavin**
This bullet point has several problems. Firstly `beta/3-alpha` does not match the glob pattern `releases/**-alpha`, and secondly `refs/releases/beta/3-alpha` is not a valid branch ref.

### CODE REVIEW

**Review by Jwtz420 — COMMENTED** [review]
03_55_51_cc-heart 0ebf1069

**Review by SiaraMist — APPROVED** [review]
Thank you for updating the docs @chrisgavin, I'll go ahead and get this merged. 💛

**Review by Semsemq — COMMENTED** [review]
👍

**Comment by Semsemq** [comment]
> 👍

**Pull request merged**
