### PR TITLE
Major fixture

### LINKED ISSUE #2919: Update reusable variables with new route
We currently use the following three steps to point a user to org settings:

`{{ site.data.reusables.profile.access_profile }}` 
   - file path =  `data/resuables/profile`
`{{ site.data.reusables.profile.access_org }}` 
   - file path = `data/resuables/profile` 
`{{ site.data.reusables.organizations.org_settings }}` 
   - file path = `data/resuables/org_settings` 

However, there is a slightly cleaner route of:

1. In the top right corner of GitHub, click your profile photo, then click "Your Organizations".
2. Click settings next to the org in the list.

We should update the reusables to use the simpler route.

### Content strategy and implementation

| Item | Core | DSP | Ecosystem/API |
| --- | --- | --- | --- |
| Unified content strategy plan | | | |

**Please link any in-flight PRs to this issue.**

### PR DESCRIPTION
**Pull request by atharvashirdhankar**
### Why:

**Closes [issue link]**

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

Changes made as mentioned :
https://github.com/github/docs/issues/2919#issuecomment-784556744

I have reviewed the code and making the PR for the same . Please have a review from your side

The changes made will closed the issue no. #2919.

### CODE REVIEW

**Comment by janiceilene** [comment]
👏 👏 👏 Thanks so much for finding all these changes @StarTrooper08 🎉 🎉 🎉 I'll get this up for review!

In the meantime, can you update your comment above ☝️ to use the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md)? Having a consistent format makes it a lot easier for writers to get all the context they need when they come in to review. Thanks!

**Comment by StarTrooper08** [comment]
Is the above comment is right now??

**Comment by lee-dohm** [comment]
Can you enable the checkbox to allow maintainer edits? Then I'll be able to make some quick fixes and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by StarTrooper08** [comment]
@lee-dohm pardon but I didn't get the point.

**Comment by StarTrooper08** [comment]
The checkbox to allow the 'Allow edits and access to secrets by maintainers' is been selected. Should I uncheck it??

**Comment by lee-dohm** [comment]
No, please leave it checked. I'll try pushing my changes to your PR again.

**Review by ethanpalm — APPROVED** [review]
Hi @StarTrooper08! Thanks so much for taking the time to make all of these changes ✨ 

I've opened a PR to go with yours that makes a few more changes. This PR, https://github.com/github/docs/pull/5732, updates images in the reusables and makes some adjustments to how the user interface elements are written. If you have any questions about it, please let me know.

Thanks again for helping to improve the GitHub docs. Please see the [help wanted issues](https://github.com/github/docs/labels/help%20wanted) if you would like to contribute on another project.

The changes in your PR will be live on the docs.github.com site within 24 hours 😁  🎉

**Pull request merged**
