### PR TITLE
Actions: promote jobs steps title to h3 to appear in sidebar

### PR DESCRIPTION
**Pull request by dr-js**
### Why:

It seems `h3` and up title will appear in sidebar.
Currently most common-used job config is hidden with it's `h4` title.

### What's being changed:

This commit changed the following title from `h4` to `h3` and also promoted sub-titles:
- `jobs.<job_id>.steps.*`
- `jobs.<job_id>.strategy.*`
- `jobs.<job_id>.container.*`
- `jobs.<job_id>.services.<service_id>.*`

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by dr-js** [comment]
Side note: after some more digging, it seems like setting `miniTocMaxHeadingLevel: 4` like: [content/actions/reference/events-that-trigger-workflows.md#L5](https://github.com/github/docs/blame/main/content/actions/reference/events-that-trigger-workflows.md#L5) should also work.
Changing this way should result in a much smaller commit, if this is preferred then I can redo current commit.

**Comment by janiceilene** [comment]
Thanks @dr-js! I'll triage this for review ⚡

**Comment by dr-js** [comment]
ping

**Comment by janiceilene** [comment]
Thanks for your patience @dr-js! Our team is still working out way through the amazing contributions we got during Hacktoberfest 🎃

**Comment by dr-js** [comment]
Just realized that, too. Thank you all for keeping up the good work! 🎃
And if this needs any change, let me know!

**Comment by dr-js** [comment]
ping

**Review by shati-patel — APPROVED** [review]
Thank you for the updates @dr-js! Your changes look good, and are consistent with the rest of the `jobs.<job_id>.*` headers 😃 

 I'll get this merged soon!

**Pull request merged**
