### PR TITLE
Add Amazon ECS / Azure App Service deployment guides

### PR DESCRIPTION
**Pull request by swinton**
### Why:

Building on #2085, adds deployment guides for Amazon ECS / Azure App Service as part of a group of select partner deployment guides. 

/cc @runleonarun, @imjohnbo, @jpadams 👋 

### What's being changed:

* Adds a new "deployment guide" for Amazon ECS and Azure App Service based on the existing starter workflows:
    * https://github.com/actions/starter-workflows/blob/master/ci/aws.yml.
    * https://github.com/actions/starter-workflows/blob/master/ci/azure.yml.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by imjohnbo** [comment]
@swinton, I think you might also need to add links to these guides in [this list](https://github.com/github/docs/pull/2085/files#diff-e8e40b4be0e0384203d634d0a090a031d04ac00dcbb15532ad437f258890e438)

**Comment by jpadams** [comment]
@swinton I don't see the Guides linked in the [preview enviro deploy](https://docs-2088--deployment-guidesad.herokuapp.com/en/free-pro-team@latest/actions/guides) like I do in the one @imjohnbo deployed. 

https://github.com/github/docs/pull/2085#issuecomment-745532945

**Comment by swinton** [comment]
> @swinton, I think you might also need to add links to these guides in [this list](https://github.com/github/docs/pull/2085/files#diff-e8e40b4be0e0384203d634d0a090a031d04ac00dcbb15532ad437f258890e438)



> @swinton I don't see the Guides linked in the [preview enviro deploy](https://docs-2088--deployment-guidesad.herokuapp.com/en/free-pro-team@latest/actions/guides) like I do in the one @imjohnbo deployed.

Thanks both. I think we should close this PR and I'll add my commits to @imjohnbo's PR directly, so we don't have any merge conflicts in that file. That :cool: with you, @imjohnbo?

**Comment by swinton** [comment]
Should be [there](https://docs-2088--deployment-guidesad.herokuapp.com/en/free-pro-team@latest/actions/guides) now:

image

**Comment by swinton** [comment]
> I'll add my commits to @imjohnbo's PR directly, so we don't have any merge conflicts in that file. That 🆒 with you, @imjohnbo?

Continuing this work under a single PR: #2085

See you there 👋

**Pull request closed without merging**
