### PR TITLE
Update about-self-hosted-runners.md

### PR DESCRIPTION
**Pull request by pholleran**
### Why:

https://github.com/github/docs-content/issues/3188

### What's being changed:

`codeload.github.com` is being added to the DNS entries that need to be open for self-hosted runners to work. Several actions, when downloaded to the runner, need to load content from codeload.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Suya159357** [comment]
https://github.com/github/docs/pull/930/files

**Comment by Suya159357** [comment]
.

**Comment by janiceilene** [comment]
Thanks for opening a PR @pholleran! I'll get this triaged for review.

**Review by rachmari — APPROVED** [review]
@pholleran thanks for the update! I'll get this merged right away. 🚢

**Comment by iwaki710** [comment]
希望

**Pull request merged**
