### PR TITLE
Update configuring-dependabot-security-updates.md

### PR DESCRIPTION
**Pull request by raineorshine**
### Why:

Dependabot continues giving updates even after being disabled if a `dependabot.yml` file is present. Deleting `dependabot.yml` is a necessary step for disabling dependabot completely.

This was perplexing me for months, but I found the solution here: https://github.community/t/disable-dependabot/143425/5

### What's being changed:

A missing step is being added to the instructions for disabling dependabot.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@raineorshine 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by mchammer01** [comment]
I'll review this tomorrow!

**Comment by mchammer01** [comment]
@raineorshine 👋🏻 - thanks for contributing to our docs ✨ 
I'd like some clarification on your update as I am slightly confused. 

- Dependabot _security_ updates are usually enabled and disabled via the UI ("Enable/Disable" button as shown in one of the screenshots in the GitHub Community post). An engineer from the Dependabot team told me that we do sometimes recommend users to check in a config file for security updates and set the allowed open pull requests to 0. You disable Dependabot security updates via the UI. For more information, see [here](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#enabling-or-disabling-dependabot-security-updates-for-an-individual-repository). When you do so, you shouldn't get any more Dependabot PRs.

- Dependabot _version_ updates are configured via the dependabot.yml file. To disable Dependabot version updates, you delete the dependabot.yml file file from your repo. You shouldn't get any more Dependabot PRs. You can also tweak that config file if you want to disable updates temporarily for one or more dependencies, or package managers. For more information, see [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates).

Could you let me know if you're referring to Dependabot version updates or Dependabot security updates? Or if you're not sure. That'll enable me to help you with this PR. Thank you so much 🙏🏻 🙂

**Comment by mchammer01** [comment]
I'm so sorry to hear that the docs are confusing in this respect 😢 
Your suggestion seems like a great one. Let me talk to the Dependabot Updates team to see what we can do to avoid further confusion. Thank you very much for highlighting this pain point, and sorry about that.

**Comment by raineorshine** [comment]
Great, thanks for your follow through.

**Pull request closed without merging**
