### PR TITLE
Add Supported Color Models to Basic Writing Syntax

### LINKED ISSUE #17312: Document markdown color rendering
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

One of the following:

- [Basic writing and formatting syntax](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
   - Under the "Quoting code" section OR
   - Under its own section
- [Working with advanced formatting](https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting) having its own page?

### What part(s) of the article would you like to see updated?

I have noticed recently that wrapping color in markdown code syntax renders the color. I'm not sure if this is new behavior, but either way, I don't believe this is documented anywhere. I thought it was cool, and it would be nice to have this documented. 

I'm not entirely sure the best location to put this. You can see my suggestions above, but I don't think this is extensive enough to have its own page? I wouldn't mind writing and opening a PR documenting this, but I first would love some feedback as to where this would be best placed. Thanks!

### Additional information

Below you can see an example list that shows colors being rendered when wrapped in markdown code syntax. Note that keeping a list of supported colors doesn't have to be in the documentation. I just wanted to list them all out to see what was working. 

#### Supported
- HEX `#3fb950`
- RGB `rgb(255, 233, 0)`
- HSL `hsl(128, 49%, 49%)`

#### Unsupported
- HSV `hsv(128, 66%, 73%)`
- CMYK `cmyk(66%, 0%, 57%, 27%)`
- HSB `hsb(128, 49%, 49%)`
- HSI `hsi(128, 42%, 43%)`
- HWB `hwb(128, 25%, 27%)`
- NCol `G14, 25%, 27%`
- CIELAB `CIELab(66.77, -55.25, 42.98)`
- CIEXYZ `xyz(20.8459, 36.3325, 13.504)`
- VEC4 `(0.25f, 0.73f, 0.31f, 1f)`

### PR DESCRIPTION
**Pull request by aisgbnok**
### Why:

Closes #17312

### What's being changed (if available, include any code snippets, screenshots, or gifs):

> **Note**
> I decided to put the section directly under **Quoting code** because it follows similar syntax and is related; however, feel free to move this section if you believe there is a better place.

Added documentation for the three supported color models (HEX, RGB, HSL) in a table similar to the ["Styling text" table.](https://docs.github.com/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text)

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by aisgbnok** [comment]
Are `SVGs` not supported in GitHub Documentation? 

On my local development server the `SVGs` render properly and are prepended with some sort of ID. `cb-xxx`
image
image

However, in the Azure deployment they don't render properly. 
https://docs-18478-9eab09.preview.ghdocs.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#supported-color-models

Not sure if my syntax is wrong, the deployment is wrong, or `SVGs` are not supported. If so, let me know and I'll replace them with PNGs.

**Comment by aisgbnok** [comment]
I based my syntax on the [World Wide Web Consortium's CSS Color Module Level 3](https://www.w3.org/TR/css-color-3/).

- [RGB (HEX and RGB)](https://www.w3.org/wiki/CSS3/Color/RGB)
- [HSL](https://www.w3.org/wiki/CSS3/Color/HSL)

While those links may be helpful, I decided against linking them because I don't think GitHub Docs needs to explain how web colors work. It could also be further confusing because the GitHub supported color models don't support the 3 hex `#RGB` format, as listed in W3C.

**Comment by janiceilene** [comment]
@aisgbnok Thanks so much for including all of this helpful information into the decisions you made 😍 

We don't support `.svg`, if you could update these to be `.png` that would be super helpful. Thanks again!

**Comment by aisgbnok** [comment]
Thanks, @janiceilene, I have replaced the `.svg` files with `.png` files. Let me know if there is anything else I can do!

**Review by hubwriter — CHANGES_REQUESTED** [review]
Hi @aisgbnok - This looks really good. Thanks.

However, when I tried this out for myself in a readme it didn't work. I used the markdown you give as an example and it rendered like this:

image

I was expecting it to render as shown in your new section:

image

You can see this here: https://github.com/hubwriter/hubwriter-test/blob/master/README.md

I tried this in Chrome, Firefox, and Safari but the colored circle you show didn't show up.

Could you clarify how/where you get this markdown to render as shown in your images? Thanks

**Comment by aisgbnok** [comment]
@hubwriter, unfortunately, it seems like it only renders in Issue/PR descriptions or comments. I should have tested in a readme as well. 

| Color | Syntax | Example | Output |
| --- | --- | --- | --- |
| HEX | <code>\`#RRGGBB\`</code> | <code>\`#0969DA\`</code> | `#0969DA` |
| RGB | <code>\`rgb(R,G,B)\`</code> | <code>\`rgb(9, 105, 218)\`</code> | `rgb(9, 105, 218)` |
| HSL | <code>\`hsl(H,S,L)\`</code> | <code>\`hsl(212, 92%, 45%)\`</code> | `hsl(212, 92%, 45%)` |

Should we scratch the whole section or add a warning note that it does not work in markdown files but will work elsewhere? Apologies for this oversight, thanks!

**Comment by aisgbnok** [comment]
The background color should be `#ffffff` for light mode and `#0d1117` for dark mode.

**Comment by hubwriter** [comment]
@aisgbnok - Ah, that makes sense. Thanks.

I think it would be a shame to lose this entirely.

I'd suggest making a couple of changes.

Change:

> You can call out color within a sentence with single backticks. A supported color model within backticks will display a visualization of the color.

to:

> In issues, pull requests, and discussions, you can call out colors within a sentence by using backticks. A supported color model within backticks will display a visualization of the color.

And also change:

> **Note:** A supported color model cannot have any leading or trailing spaces within the backticks.

to:

> **Notes**:
> 
> * A supported color model cannot have any leading or trailing spaces within the backticks.
> * The visualization of the color is only supported in issues, pull requests, and discussions.

**Comment by aisgbnok** [comment]
@hubwriter, thanks, I committed your suggestions.

**Review by hubwriter — APPROVED** [review]

**Comment by hubwriter** [comment]
@aisgbnok - That's great. Many thanks for your help. 🎖️ 

I've approved this to be merged. We have a merge freeze on the repo until 11 July but we'll get this merged/published after that. 🚀

**Pull request merged**
