### PR TITLE
Update working-with-the-npm-registry.md

### PR DESCRIPTION
**Pull request by SumaiyaTarannumNoor**
Some grammatical corrections have been done.

### Why: For some small grammatical corrections.

Closes: 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by nguyenalex836 — DISMISSED** [review]

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thank you for opening this PR! ✨ Per the automated message above, in order to review and merge PRs most efficiently, we require that all PRs grant maintainer edit access before we review them. 

For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

Once you haven completed the above, I'll update the branch and get this merged once tests are passing 🍏

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thank you for opening this PR! ✨ Per the automated message above, in order to review and merge PRs most efficiently, we require that all PRs grant maintainer edit access before we review them.

For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

Once you have completed the above, I'll update the branch and get this merged once tests are passing 🍏

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 Thanks for the review. I have updated it to "Allow edits by maintainers." Would you merge it now?

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thank you! It looks like two of our automated checks failed when I tried to update the branch. 

To resolve one of them, can you please remove the blank lines you added in your PR (lines 149 and 150)?

I am working with our team on the second failed check, and will return when I have more information 💛

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 I have removed line no. 149 and 150.

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@SumaiyaTarannumNoor Thank you! I've just added this PR to our merge queue, and this should be merged shortly ✨ We appreciate your willingness to contribute to GitHub Docs! 

If you're looking for another issue to work on, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues 💛

**Comment by SumaiyaTarannumNoor** [comment]
@nguyenalex836 I really appreciate it. Thank you. 😊

**Pull request merged**
