### PR TITLE
docs: show current topic in bold

### LINKED ISSUE #4922: Current topic not shown
### What article on docs.github.com is affected?

"[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"

### What part(s) of the article would you like to see updated?

The topic list doesn't show the current topic in bold.

[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)

image

### Additional information

These current topics can be seen in bold on [Set up Git](https://docs.github.com/en/github/getting-started-with-github/set-up-git), [Create a repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo) or [Be social](https://docs.github.com/en/github/getting-started-with-github/be-social).

image

### PR DESCRIPTION
**Pull request by ghost**
### Why:

**Closes #4922**

### What's being changed:

```diff
  - "[Set up Git](/articles/set-up-git)"
  - "[Create a repository](/articles/create-a-repo)"
+ - **Fork a repository**
  - "[Be social](/articles/be-social)"
```

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — COMMENTED** [review]
Hi, thanks for the PR, but I guess this change is unnecessary here.

**Comment by janiceilene** [comment]
@harshcut Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by tartarza112244** [comment]
> ### Why:
> **Closes #4922**
> 
> ### What's being changed:
> ```diff
>   - "[Set up Git](/articles/set-up-git)"
>   - "[Create a repository](/articles/create-a-repo)"
> + - **Fork a repository**
>   - "[Be social](/articles/be-social)"
> ```
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Comment by tartarza112244** [comment]
> ### Why:
> **Closes #4922**
> 
> ### What's being changed:
> ```diff
>   - "[Set up Git](/articles/set-up-git)"
>   - "[Create a repository](/articles/create-a-repo)"
> + - **Fork a repository**
>   - "[Be social](/articles/be-social)"
> ```
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Review by tartarza112244 — DISMISSED** [review]

**Review by Alvinchong1989 — COMMENTED** [review]
I don’t understand what you want

**Comment by Alvinchong1989** [comment]
> I don’t understand what you want

**Review by lucascosti — APPROVED** [review]
Thanks for this, @harshcut! It looks like you're correct 👍 

I also added some more changes to `be-social.md` to make all the articles consistent for that section in the quickstart series.

**Pull request merged**
