### PR TITLE
Update workflow-commands-for-github-actions.md

### PR DESCRIPTION
**Pull request by paulyhedral**
While a meter for delis would be incredibly useful for determining the best sandwich shop, a delimiter is better for dividing multiline strings.

### Why:

Correcting misspelling in text.

### What's being changed:

Spelling changed from `delimeter` to `delimiter`.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening this up @paulyhedral 🥪 Could you fill out the pull request template and then I'll get this up for review!

**Comment by paulyhedral** [comment]
Filled in remainder of pull request template.

**Comment by janiceilene** [comment]
Thanks @paulyhedral 💛 I'll let the @github/docs-content-ecosystem team know this is ready for review!

**Review by rachmari — APPROVED** [review]
@paulyhedral Deli meter 😆 👏 I did laugh out loud when reading this so thank you for that, but also thank you for finding this one and fixing it up! 💚 :octocat: 

I'll get this merged!! 🚢 🚀

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by paulyhedral** [comment]
@all-contributors please add @paulyhedral for content

**Pull request merged**
