### PR TITLE
Clarification in trust-relationship policy example

### PR DESCRIPTION
**Pull request by conradt-paf**
I've tested a wide variety of cases and compared to Cloudtrail Events.

only `sub` is currently sent to and compared in AWS open-id connector for GitHub.
`aud` will *always* be sts.amazonaws.com, making the `aud` string used in the example obsolete (and possibly misleading)

So, the IAM trust relationship policy (GitHub OIDC -> AWS) for the role-to-be-assumed should perform conditional checks on `sub` which (currently only) contain this information:

`"token.actions.githubusercontent.com:sub": "repo:organization-name/repository-name:ref:refs/heads/branch-name"`

If the conditional StringLike is used, wildcard can be used for `branch-name`

There might be other things to touch up on in this README.md to reflect this information

### Why:

fix some confusion

### What's being changed:

IAM policy example will correctly check for `aud` and `sub` claim that AWS openid-connector uses.
`sub` claim inherently contains organization claim already.

We also use `ForAllValues` to correctly perform an AND operation (instead of OR)

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@conradt-paf 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by conradt-paf** [comment]
```
"Condition": {
  "ForAllValues:StringEquals": {
    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}
```

```
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
  }
}
```

Using `StringLike`
```
"Condition": {
  "StringLike": {
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/*"
  }
}
```

**Comment by conradt-paf** [comment]
Tested and working, that was the final commit. You may push to this fork/branch if possible

**Comment by conradt-paf** [comment]
> @conradt-paf Thanks so much for opening a PR! I'll get this triaged for review ⚡

Thank you, I added even more clarification after rigorous testing and trying to find out how this works

**Comment by martin389** [comment]
Status update: I've asked for tech review of these proposed changes 👍

**Comment by martin389** [comment]
Tech reviewer has confirmed they're happy with these changes 🎊 I'll work on fixing the merge conflict next.

**Comment by redova87** [comment]
- > ### 

- [ ] 

> _**``**_

**Comment by Benzgood77** [comment]
FB_IMG_1644759892410
Kittipong Thassajan ได้ร่าง

**Comment by Benzgood77** [comment]
กิตติพงศ์ ทัศจันทร์ 13/02/1987

ในวันที่ จ. 14 ก.พ. 2022 05:27 น. Benzgood77 ***@***.***>
เขียนว่า:

**Comment by martin389** [comment]
Status update: confirming tech review

**Review by martin389 — APPROVED** [review]
PM has approved this change 👍

**Comment by martin389** [comment]
Looks good in staging: https://docs-preview-12137-db0886.eastus.azurecontainer.io/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy

**Pull request merged**
