### PR TITLE
Correct link for reviewing dependency changes in a pull request

### PR DESCRIPTION
**Pull request by mahmoudhossam**
### What's being changed:

Fixed a link that went to a different part of the documentation than what was expected.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Perfect

**Review by ghost — COMMENTED** [review]
#9369

**Comment by ramyaparimi** [comment]
@mahmoudhossam 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
LGTM ✨ 
Thanks for fixing the link!

**Comment by Nattugglan** [comment]
Great!!

Sent from ProtonMail for iOS

På mån, mars 7, 2022 vid 18:04, mc ***@***.***> skrev:

**Pull request merged**
