### PR TITLE
Add proper markdown to 'main'

### PR DESCRIPTION
**Pull request by a2br**
### What:
I have changed **"main"** to **`main`**.
### Why:
Below the 'main' section, in the 'master' section, `master` is used, not "master".

### CODE REVIEW

**Comment by janiceilene** [comment]
@a2br Thanks so much for opening a PR! I'll get this triaged for review 💖

**Comment by a2br** [comment]
Still waiting for review.

**Comment by janiceilene** [comment]
@a2br Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Review by felicitymay — COMMENTED** [review]
Hi @a2br 👋🏻 

Thanks for your patience. Your change to the `data/glossaries/external.yml` file looks good 😄 

I'm less sure about the changes to the translated files. On the whole, we don't accept changes to those files but maybe formatting changes are safe. I'll check with our localization team and let you know how we can get your changes merged.

**Comment by a2br** [comment]
Ok! I can still revert the commits on the translation files.

**Comment by felicitymay** [comment]
> Ok! I can still revert the commits on the translation files.

I hadn't noticed that they were in separate commits. That would be great. Many thanks.

**Comment by a2br** [comment]
Done! ✅

**Review by felicitymay — APPROVED** [review]
💖 Many thanks for reverting those commits. This looks ready to merge now 🚢

**Comment by felicitymay** [comment]
@a2br 👋🏻 Bonjour 😄 

Since I merged your pull request, I've been getting email notifications about Actions workflow failures in your fork. This puzzled me. I looked into it. 

I think you enabled **Actions** in the settings for your fork. The failing workflow synchronizes the `docs` repository with our internal systems. It uses a token that your fork does not have access to. To avoid using up your Actions minutes, you should turn off actions in your fork of the `docs` repo ([Disabling or limiting GitHub Actions for a repository](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#managing-github-actions-permissions-for-your-repository)).

I raised this with the docs engineering team and they will update the synchronization workflow so that it does not run on forks.  The work is not scheduled yet, so it would be good to turn off actions for this repository.

**Comment by a2br** [comment]
Actions are now disabled in my fork ☑️

**Comment by felicitymay** [comment]
💐 Thank you. I hope that this hasn't cause problems for you in your fork.

We usually create a [feature branch](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-branches) from `main` with the changes we want to merge into the `main` branch of the `docs` repository. This would also help avoid problems like this in any future changes you propose to the `docs` repository.

**Comment by a2br** [comment]
Yes, that's what I usually do. Since the change here was very small, I thought i'd just delete my fork and re-fork if needed in the future. Thanks for the reminder though.

**Comment by felicitymay** [comment]
That makes sense. Some of the contributors to this repository are just starting out with git and GitHub, so I thought I should mention it. It's great to hear that you already knew.

Have a great weekend 👋🏻

**Pull request merged**
