### PR TITLE
Fix typo in action step name

### PR DESCRIPTION
**Pull request by ajsirota**
### Why:

Fix a typo

### What's being changed:

`Run brower-test` --> `Run browser-test`

### Check off the following:

- [N/A] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by ajs256** [comment]
This doesn't actually change the workflows in any way. I'm assuming the bot can be overridden by its overlords.

**Review by janiceilene — APPROVED** [review]
Thanks so much @ajs256!

**Comment by janiceilene** [comment]
It looks like we're having some trouble with our staging checks. I'll come back to get this merged next week! Sorry about the delay 💛

**Comment by ajs256** [comment]
No problem.

**Pull request merged**
