### PR TITLE
[GitHub Packages registry] "Using a published package" with Gradle registry

### LINKED ISSUE #7885: [GitHub Packages registry] Deprecated plugin in Gradle Registry guideline
### What article on docs.github.com is affected?

* Working with a GitHub Packages registry
  * [Working with the Gradle registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry)  

### What part(s) of the article would you like to see updated?

If I follow the guideline with latest Gradle version (`7.1`), this error raises when trying to run `mvn install`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Plugin [id: 'maven'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see 
  https://docs.gradle.org/7.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

Legacy Maven Plugin (**maven** plugin) is not included on the list of core plugins from Gradle 7.x:

* https://docs.gradle.org/7.0/userguide/plugin_reference.html
* https://docs.gradle.org/7.1/userguide/plugin_reference.html

If I try this link of **maven** plugin https://docs.gradle.org/7.1/userguide/maven_plugin.html redirects to **maven-publish** plugin https://docs.gradle.org/7.1/userguide/publishing_maven.html. However, **maven-publish** doesn't provide a task with the same behavior:

* `install` task from **maven** plugin publishes both the package under development and all the dependencies in the local Maven repository (`~/.m2/repository`).
* `publishToMavenLocal` from **mave-publish** plugin only publishes the package under development in the local Maven repository (`~/.m2/repository`).

### Additional information

I created #7142 and #7143 before. So sorry for the inconveniences, I was wrong! I made a mistake after using Gradle for a long time and forgetting the real behavior of `mvn install` command (I was thinking about the behavior of `publishToMavenLocal` task) :pray: 

I made the tests in [this repository](https://github.com/rachelcarmena/test-gh-packages). The results can be seen in [this console output](https://github.com/rachelcarmena/test-gh-packages/runs/2971927430).

GitHub Packages Registry workes like a charm, congrats and thank you so much!! :raised_hands:

### PR DESCRIPTION
**Pull request by rachelcarmena**
### Why:

Closes #7885 . Please, find the reason of this pull request in that issue.

### What's being changed:

Replace "Installing a package" section by "Using a published package" section on:

  * [Working with the Gradle registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry)  

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@rachelcarmena Thank you so much for the detailed issue and a PR with the fix! I'll get this triaged for review ⚡ 

Just a heads up, the team is out for the next two weeks, so we'll be very slow to respond 💛

**Review by mahdiamer — APPROVED** [review]
Good

**Review by SirJosh1987 — APPROVED** [review]

**Review by SirJosh1987 — DISMISSED** [review]

**Review by Artek199 — DISMISSED** [review]

**Review by hubwriter — DISMISSED** [review]
@rachelcarmena - This change looks good.
Many thanks for contributing. 👍

**Comment by rachelcarmena** [comment]
> @rachelcarmena - This change looks good.
> Many thanks for contributing. +1

Thanks to you! :tada: 
I pushed another commit to solve [the failed linting test](https://github.com/github/docs/pull/7886/checks?check_run_id=3192467620).

**Review by hubwriter — APPROVED** [review]

**Comment by rachelcarmena** [comment]
Thanks to you!!! :tada:

**Pull request merged**
