### PR TITLE
updated reusable variables

### PR DESCRIPTION
**Pull request by atharvashirdhankar**
changes made for issue no #2919

### Why:

**Closes [issue link]**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by theerapong2425** [comment]
@theerapong2425

**Comment by StarTrooper08** [comment]
@janiceilene where I will get those 
Instance .Can I get one example .I m not getting those instances for 3 fix

**Comment by lee-dohm** [comment]
@StarTrooper08 You can find an example of the three of them together here:

https://github.com/github/docs/blame/main/content/developers/github-marketplace/applying-for-publisher-verification-for-your-organization.md#L18-L20

What we need for you to do is to find all instances of this pattern in the entire project and change it to the second pattern as described in [this comment](https://github.com/github/docs/issues/2919#issuecomment-800556264). The most efficient way to do that is to make the changes with a text editor on your local computer rather than through the GitHub website. If you're unfamiliar with how to perform this task in your text editor, you'l have to consult your editor's documentation, specifically "Find in Files" or "Find in Project" is what the feature is typically called in most editors.

I hope that helps!

**Comment by StarTrooper08** [comment]
Thanks ,I should start working on it now.

**Comment by StarTrooper08** [comment]
@janiceilene I have done with few changes for instances mentioned. Work is in progress.
I will have pr in few days

**Comment by janiceilene** [comment]
Awesome @StarTrooper08! Thanks for the update 🎉

**Comment by StarTrooper08** [comment]
So far I have done with this much work.


And I have one question only were the 3 instances that are as follows : 
​```
{% data reusables.profile.access_profile %}
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```

​Should be replaced with this right : 

```
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```

And if I get something like this should I replace those 3 from here too??

![githubchanges.PNG](https://user-images.githubusercontent.com/72031540/114489613-0f5cc280-9c31-11eb-8bb3-5b22051198c5.PNG)

**Comment by janiceilene** [comment]
@StarTrooper08 That's exactly right! If you get a big list that starts with the three reusables 

```
{% data reusables.profile.access_profile %}
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```

you should replace the three reusables with the two updated ones

```
{% data reusables.profile.access_org %}
{% data reusables.organizations.org_settings %}
```

and leave everything else in the list as it is. Thank you for continuing to work on this PR 🎉

**Comment by StarTrooper08** [comment]
Okay👍

**Comment by 06Den** [comment]
> changes made for issue no #2919
> ### Why:
> 
> **Closes [issue link]**
> ### What's being changed:
> ### Check off the following:
> 
>     * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> 
>     * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> 
>     * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

denistschaikovski@gmail.com

**Comment by 06Den** [comment]
>

**Comment by lee-dohm** [comment]
It looks like this was made obsolete by #5538, so I'm going to close it. If I've misunderstood, please let me know!

**Pull request closed without merging**
