### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ghost**
code align

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by ahamdesigner** [comment]
I havnt  touched the content but aligned it so it looks more beautiful

thanks

**Comment by MohamadRardieyy** [comment]
#317

**Comment by MohamadRardieyy** [comment]
https://github.com/github/docs/issues/745

**Comment by MohamadRardieyy** [comment]
Mohamad

**Pull request closed without merging**
