### PR TITLE
Fix alerts

### LINKED ISSUE #35445: Alerts without header
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Multiple articles.

### What part(s) of the article would you like to see updated?

There are still alerts in the documentation which are using the following notation:

```
{% note %}
Text
{% endnote %}

// same for tip and warning
```

These alerts don#t have any header (Note, Tip, Warning) and are rendered just with the colored strip.

Examples:
- [Note](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-environments-to-manually-trigger-workflow-jobs)
- [Tip](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authenticating-to-the-rest-api-with-an-oauth-app)
- [Warning](https://docs.github.com/en/apps/github-marketplace/using-the-github-marketplace-api-in-your-app/handling-new-purchases-and-free-trials)

### Additional information

Maybe some are ment to be that way. If not I could provide a PR with fixes.

### PR DESCRIPTION
**Pull request by akordowski**
### Why:

There are occurrences of alerts without a header using the liquid and not the markdown notation.

Closes: #35445

### What's being changed (if available, include any code snippets, screenshots, or gifs):

This PR fixes the alerts by using the markdown notation.

### Check off the following:

- [ ] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [x] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [x] All CI checks are passing.

### CODE REVIEW

**Comment by akordowski** [comment]
@nguyenalex836 And here some mismatches between alert header and the content.

This tip should be rather a warning:

see [here](https://docs-35468-433e6c.preview.ghdocs.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port)
grafik

And the following tips sould be rather notes:

see [here](https://docs-35468-433e6c.preview.ghdocs.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/importing-an-external-git-repository-using-the-command-line)
grafik

see [here](https://docs-35468-433e6c.preview.ghdocs.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#commit-has-not-been-pushed-online) (scroll down)
grafik

see [here](https://docs-35468-433e6c.preview.ghdocs.com/en/site-policy/site-policy-deprecated/amendment-to-github-terms-of-service-applicable-to-us-federal-government-users)
grafik

What do you think?

**Review by mlinksva — DISMISSED** [review]

**Comment by nguyenalex836** [comment]
@akordowski Thank you for another batch of fixes! ✨ 

> So, should we keep the new version or should I revert the changes?

Let's keep the new version - I agree with the new formatting, and these changes align more closely with our style guide 💛 

> And here some mismatches between alert header and the content.

Agree with you updating those tips to warning / notes 👍 feel free to update the PR! I'll review the current changes in the meantime

**Review by nguyenalex836 — DISMISSED** [review]

**Comment by akordowski** [comment]
@nguyenalex836 I updated the alerts as described. You can take a look. Thank you!

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@akordowski Changes look perfect ✨ We'll need one more review from our Site Policy team given the updates!

@mlinksva Howdy! Would you mind giving one final review for this PR? Some minor updates were recently made - thank you! 💛

**Comment by Sultan0901** [comment]
https://github.com/github/docs/actions/workflows/no-response.yaml/badge.svg

**Comment by akordowski** [comment]
@mlinksva Any chance to review this PR?

cc @nguyenalex836

**Comment by nguyenalex836** [comment]
@akordowski I've pinged the greater Site Policy team for a re-review just in case! This wonderful team can get very busy 💛

**Comment by akordowski** [comment]
@nguyenalex836 Thank you very much!

**Review by khxu — APPROVED** [review]

**Pull request merged**
