### PR TITLE
default sign all commits with gpg key

### PR DESCRIPTION
**Pull request by l3nnartt**
### Why:

This way all commits are automatically signed and you dont have to set it up in each project

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@l3nnartt Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by japui** [comment]
padrão assina todos os commits com a chave gpg #

**Comment by l3nnartt** [comment]
Hello? 👀

**Comment by cmwilson21** [comment]
Thanks for checking in on this. This is up on the board for review. Someone will take a look at it soon! 👀 

We appreciate your patience as we are working through our backlog 💛

**Comment by vgrl** [comment]
👋 @l3nnartt Thanks for your contribution! I've chatted with the team about your PR and I see that we already mention this command in the "Tips" callout in "[Signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)". Given that, and since it's an optional, specific Git configuration that we don't have many users asking about, we won't be making the suggested change. Because of this, I'm closing the PR.

Thanks again for your work and your interest in improving GitHub's documentation!

**Comment by l3nnartt** [comment]
alright, thanks for the detailed answer! :D

**Pull request closed without merging**
