### PR TITLE
closing issue #18753 - adding a paragraph for un-archiving a repo

### LINKED ISSUE #18753: Create documentation for unarchiving-repositories
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

### What part(s) of the article would you like to see updated?

1. Create a page explaining how to unarchive a repository
2. Edit the archiving page to link to it in manner similar to how the [deleting a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository) page links to [restoring a deleted repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository).

### Additional information

Noted as missing here:
https://github.community/t/is-it-possible-to-unarchive-repository-one-it-is-archived/257681

### PR DESCRIPTION
**Pull request by CapitainFlam**
### Why:

Closes #18753 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I removed the text concerning UNarchiving in the paragraph about ARCHIVING, and created a NEW paragraph about UNarchiving, created the associated IMG, and GO !

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@CapitainFlam Thanks for opening a PR! I've made a slight change to your post to [link it with the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). 

I'll get this triaged for review! ⚡

**Comment by SiaraMist** [comment]
Hey @CapitainFlam, thank you for opening another PR! 🦸 

Your updates look great! I've [requested to make an update to one of the images](https://github.com/CapitainFlam/docs/pull/1) to more closely match the image style in [Archiving a repository](https://docs-20808-87c806.preview.ghdocs.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository). If you approve that change to your branch, I can get this PR merged! Thank you again for your contributions! ✨

**Comment by CapitainFlam** [comment]
> Hey @CapitainFlam, thank you for opening another PR! 🦸

you're welcome 😸 
> 
> Your updates look great! I've [requested to make an update to one of the images](https://github.com/CapitainFlam/docs/pull/1) to more closely match the image style in [Archiving a repository](https://docs-20808-87c806.preview.ghdocs.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository). If you approve that change to your branch, I can get this PR merged! Thank you again for your contributions! ✨

👍 merge has been validated ! 

Go for merge 🔀 ✅

**Review by SiaraMist — APPROVED** [review]

**Comment by SiaraMist** [comment]
Thank you for the quick response @CapitainFlam! I will get this merged now. 😃 🎉

**Pull request merged**
