### PR TITLE
Remove redundant notes

### LINKED ISSUE #18424: Redundant notes on "Events that trigger workflows" page
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

### What part(s) of the article would you like to see updated?

In the sections on the `pull_request` and `pull_request_target` events, the second note in each section essentially repeats information that is already contained in the first note.

On the other hand, the wording in the second note is clearer.  I propose combining the two notes (in each section), incorporating the better wording of the second note in each case.

As a side note, the second note in the `pull_request_target` section erroneously refers to the wrong event name: 

> By default, only the `opened`, `synchronize`, and `reopened` activity types trigger workflows that run on the `pull_request` event.

This should read

> By default, only the `opened`, `synchronize`, and `reopened` activity types trigger workflows that run on the `pull_request_target` event.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsrohde**
### Why:

Closes #18424

### What's being changed:

The first two notes in the `pull_request` and `pull_request_target` sections of the _Events that trigger workflows_ page are redundant.  This PR combines the notes and improves the wording.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@gsrohde Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by martin389 — COMMENTED** [review]
Thanks for spotting this duplication, and for creating this PR! ✨ I've added a couple of suggestions.

**Review by japui — COMMENTED** [review]
*Observação:** por padrão, apenas os tipos de atividade `opened` , `synchronize` e `reopened` acionam fluxos de trabalho executados no evento `pull_request` . Aprovado 👍

**Review by lucascosti — APPROVED** [review]
I've implemented @martin389's suggestions, so I think this is good to merge 🚢

**Pull request merged**
