### PR TITLE
Improve documentation issue no #1034

### PR DESCRIPTION
**Pull request by atharvashirdhankar**
Done with the minor fixes for open issue number #1034 .

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by nschonni** [comment]
👍 might be better to wrap the individual keys in `<kbd>` and keep the `+` separately in between as text

**Comment by StarTrooper08** [comment]
Thanks for help the doc looks clean with that tip .

**Comment by janiceilene** [comment]
Thanks so much @StarTrooper08! I'll triage this for review ⚡

**Comment by StarTrooper08** [comment]
That was a nice experience working with you guys😊.

**Comment by StarTrooper08** [comment]
@janiceilene is there any new issue in Google docs that I can solve. Please suggest . Thank you.

**Comment by janiceilene** [comment]
@StarTrooper08 You can check out [issues with a "help wanted" label](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) ⚡

**Comment by StarTrooper08** [comment]
Ok thank you ☺️

**Review by Markus85318531 — APPROVED** [review]

**Comment by StarTrooper08** [comment]
Can someone please review by work . 
If some issues are still there with issue no #1034 . Please let me know.

**Comment by janiceilene** [comment]
@StarTrooper08 This is definitely not stale! Thanks for your patience 💛  Our small team is working our way through reviewing all of the amazing contributions ✨

**Review by megbird — APPROVED** [review]
These changes look great! Thank you so much for your patience in getting a review 💛 I'll merge this in now 🚢 🎉

**Pull request merged**
