### PR TITLE
Grammar: lowest of multiple levels

### LINKED ISSUE #16304: Lower should be lowest as secrets can exist at more than two levels
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets

> If a secret with the same name exists at **multiple levels**, the secret at the _lower_ level takes precedence. 

Since there are more than two possible levels, the comparison should be `lowest`, not `lower`.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes #16304

### What's being changed:

image

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by jsoref** [comment]
@ramyaparimi thanks...
* the deployment seems broken
* a test failed and that seems unlikely to be my fault
* I'm getting way more spam than before

**Comment by ramyaparimi** [comment]
>     * the deployment seems broken

Deployment or the Content changes table comment works only on "content/*" changes. This PR has changes made to "reusable/*" and not content change, that is why the deployment doesn't show 💖 
 
>     * a test failed and that seems unlikely to be my fault

Yep, we are aware of it and our engineering team is working on a fix 💖  

>     * I'm getting way more spam than before

Yes, GitHub docs open repo does get a lot of spam 🙈

**Review by ramyaparimi — APPROVED** [review]
@jsoref 
Thanks so much for opening a PR with this fix! I'll get this merged once tests are passing 🍏

**Pull request merged**
