### PR TITLE
Update licensing-a-repository.md

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
### Why:
if someone needed more support on the license, they can contact the people who made the license, as they know everything about the license.

### What's being changed:
License information.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by SmashedFrenzy16** [comment]
Please approve of it. Thanks

**Comment by SmashedFrenzy16** [comment]
Hi

**Comment by SmashedFrenzy16** [comment]
This is vital in the ensuring that readers of the new doc that can hopefully be created can be reassured by being able to talk to those who created the licence

**Comment by SmashedFrenzy16** [comment]
Please adhere the otice that I have sent above

**Comment by SmashedFrenzy16** [comment]
*notice

**Comment by SmashedFrenzy16** [comment]
Thanks

**Comment by SmashedFrenzy16** [comment]
Please can someone respond ASAP

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by SmashedFrenzy16** [comment]
Ok thanks!

**Comment by SmashedFrenzy16** [comment]
Haven't I already filled ou the top comment?

**Comment by SmashedFrenzy16** [comment]
Haven't I already filled out the top comment?

**Comment by SmashedFrenzy16** [comment]
I have done this

**Comment by janiceilene** [comment]
@SmashedFrenzy16 Can you answer the **Why** and **What's being changed** questions in the top comment?

**Comment by SmashedFrenzy16** [comment]
@janiceilene I am saying that if someone needed more support on the license, they can contact the people who made the license, as they know everything about the license.

**Comment by janiceilene** [comment]
Thanks so much for that context @SmashedFrenzy16! I'll get this triaged for review ✨

**Comment by SmashedFrenzy16** [comment]
Thanks @janiceilene !

**Comment by ethanpalm** [comment]
👋  Hi @SmashedFrenzy16, thanks for contributing! We think the doc as written is addressing people's needs and the Disclaimer section above advises people what to do if they have questions regarding licenses, so I am closing this PR. Thanks for your passion and interest in improving the GitHub docs! ✨

**Pull request closed without merging**
