### PR TITLE
Update creating-a-personal-access-token.md

### PR DESCRIPTION
**Pull request by ramizackaryshamir**
### Why:

The screenshot image for Step 6 'Give your token a descriptive name' is incorrect. This can cause confusion for developers who are new to GiHub, especially since all the other steps have correct screenshots. Issue #851

### What's being changed:

Line 29: Replaced the current incorrect screenshot's url with a url for [the correct screenshot.](https://res.cloudinary.com/ramizackaryshamir/image/upload/c_scale,w_573/v1603818860/pullrequest-meetyourcreator-ramizackaryshamir-lines_28-29_htggx1.png)

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).
pullrequest-meetyourcreator-ramizackaryshamir-lines_28-29_htggx1

### CODE REVIEW

**Comment by janiceilene** [comment]
@MeetYourCreator Thank you so much for opening a PR! This is a great first pull request and we're excited that you've joined our community 💖 Updating this image is going to be a bit more complicated than it seems. This article covers multiple versions, so we need to track down when the change was made and possibly backport the image to older versions of GitHub Enterprise Server.

I'm going to close this PR and use the information from here (and your super helpful issue!) to create an internal issue for a writer to look at.

Thanks again for letting us know about this update!

**Review by djmareewish — COMMENTED** [review]
#112 #930 
Duplicate of #862

**Review by djmareewish — COMMENTED** [review]
#867

**Review by djmareewish — COMMENTED** [review]
#867 @djmareewish #867 #
Duplicate of 

>  #867 #`

**Pull request closed without merging**
