### PR TITLE
Update configuring-user-provisioning-for-your-enterprise.md

### PR DESCRIPTION
**Pull request by inpreman**
### Why:
Currently, the URL mentioned in the document is invalid and customers have been seeing error message: 
`"Invalid JSON Primative". ` 
https://github.com/github/docs-content/issues/3725

### What's being changed:

Updating the tenant URL to include `api/v3`

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@inpreman Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by akkarapon26 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this :upside_down_face: Sorry about that! Reopening and triaging this for review :yellow_heart:

**Comment by felicitymay** [comment]
Thanks for this PR. It looks as this was also raised as an internal issue and fixed by an internal PR.

**Comment by cheyen1608** [comment]
"Imágenesyno":"PNG",
"Isshowimages":Verdadero,
"Isstarsinwidget":FalloS,
"ColororDayBG":-1,
"Applang":"My",
"OPDSGARGERCOVERS":True,
"Tintcolor":-13665061,
"Remumitrrestmente":60,
"isalwaysopenasmagazine":falso,
"BgimageDayTransparence":200,
"Islocked":falso,
"CPBGLIGHT":-1,
"Sorbyb":0,
"Isrememmmode":falso,
"AsignadommorySorize":192,
"LastBookheight":0,
2021-02-2602:15:04.435-06:00[Inf]Versiónactual:2.61,Versiónactualmás:2.612021-02-2602:
15:04.435-06:00[Inf]Versiónactual:2.61,Versiónactualmás:2.612021-02-2602:15:04.435-06:
00[Inf]Versiónactual:2.61,Versiónactualmás:2.61"SupportMobi":FalloS,
"BoldertTextonimage":FalloS,
"Isrtl":FalloS,
"LastClosedActivity":"Main_tabs_all",
"LastBookPage":0,
"Isfirstsurname":FalloS,
"LastBookwidth":0,
"isbrowsegrid":falso,
"iseditmode":verdadero,
"BÚCQUEDAPATS":"\/almamanamiento\/emulado\/0",
"SelectingBleters":FalloS,
"Widgettype":1,
"isusetypeface":falso,
"Mousewheelspeed":70,
"Downlodspath":"\/almamanamiento\/emulado\/0\/descarta\/liberyra",
"Amatuosio2":falso,
"tabsderord":"0#1,1#1",
"Flippinginterval":10,
"Anotationtextcolor":"#0000FF",

**Review by Sutiwas031189 — COMMENTED** [review]
ไม่มีอะไรให้ดู

**Pull request closed without merging**
