### PR TITLE
Fixes Inconsistent description of scope of env set via `GITHUB_ENV`  & `core.exportVariable`

### LINKED ISSUE #7553: Inconsistent description of scope of env set via GITHUB_ENV
Description of GITHUB_ENV is inconsistent regarding if set envs are available across the workflow or only within a job.

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

### What part(s) of the article would you like to see updated?

> You can also use the GITHUB_ENV environment file to set an environment variable that **_the following steps in a workflow can use_**. The environment file can be used directly by an action or as a shell command in a workflow file using the run keyword. For more information, see "Workflow commands for GitHub Actions."

> Creates or updates an environment variable for any actions running next in a job. The action that creates or updates the environment variable does not have access to the new value, but **_all subsequent actions in a job will have access_**. Environment variables are case-sensitive and you can include punctuation.

### Additional information

I am having some trouble finding docs that summarizes scopes of variables, workspaces, etc. in GitHub Actions. It seems like this would be a fairly relevant to many pipelines and should be addressed directly in the docs.

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #7553 

### What's being changed:

Fixes the description of `GITHUB_ENV` & `core.exportVariable` in the Actions Reference.

[`GITHUB_ENV` Doc](https://docs.github.com/actions/reference/environment-variables#about-environment-variables)

[`core.exportVariable` Doc - Core Toolkit](https://docs.github.com/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by thispsj** [comment]
While the [`GITHUB_ENV`](https://docs-8392--fix-inconsistencies.herokuapp.com/actions/reference/environment-variables#about-environment-variables) is updated in the preview deployment, the [workflow commands page](https://docs-8392--fix-inconsistencies.herokuapp.com/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) is not. I don't know why 😅
preview deployment not updated

**Comment by ramyaparimi** [comment]
@thispsj Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by ramyaparimi — DISMISSED** [review]
@thispsj Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by ramyaparimi** [comment]
@thispsj Can you enable the checkbox to allow maintainer edits? Then I’ll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by thispsj** [comment]
@ramyaparimi I've checked the box.

But I'm still surprised to see that the preview deployment shows the previous changes. While the markdown file is shown updated.

**Comment by thispsj** [comment]
@ramyaparimi fixed the problem.

I just didn't notice the if condition (so it had to be updated at 2 places).

**Review by ramyaparimi — APPROVED** [review]

**Pull request merged**
