### PR TITLE
Update migrating-from-jenkins-to-github-actions.md

### LINKED ISSUE #395: misleading comparison of GHActions w/ Jenkins
### What is the current behavior?

This makes it seem like GHA supports matrices and Jenkins doesn't. 

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-jenkins-to-github-actions#building-with-multiple-operating-systems

### What changes are you suggesting?

Jenkins has supported matrix builds in pipelines for about a year now.
https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/

Please update the comparison doc.

### Additional information

I think this is cannonical-ish Jenkins pipeline that also matches your code sample linked above. (The indentation was like that in your code sample.)

```
pipeline {
agent none
stages {
  stage('Run Tests') {
    matrix {
      axes {
        axis {
          name: 'PLATFORM'
          values: 'macos', 'linux'
        }
      }
      agent { label "${PLATFORM}" }
      stages {
        stage('test') {
          tools { nodejs "node-12" }
          steps {
            dir("scripts/myapp") {
              sh(script: "npm install -g bats")
              sh(script: "bats tests")
            }
          }
        }
      }
    }
  }
}
}
```

### PR DESCRIPTION
**Pull request by casals**
### Why:

Fixes #395 using the proposed code snippet.

### What's being changed:

Jenkins code snippet (YAML) at the "Building with multiple operating systems" subsection.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks @casals! I'll get this triaged for review ✨

**Comment by casals** [comment]
Keeping the PR alive

**Comment by janiceilene** [comment]
Thanks for your patience @casals!

**Review by rachmari — APPROVED** [review]
@casals this update looks great! 👏 Thank you for making these contributions! I'll get this shipped right away. 🚢 🚀

**Review by tabathap — COMMENTED** [review]
👌

**Pull request merged**
