### PR TITLE
fixing Incorrect Use of HTML Code for Apostrophe

### PR DESCRIPTION
**Pull request by adityadees**
### Why:

based on this issue #9485

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by simonsabin** [comment]
The fix should be in TocLandingContext to fix across the board https://github.com/github/docs/blob/d07d253daff9b5b2149a2172713da1874316f7e0/components/context/TocLandingContext.tsx#L36

**Comment by adityadees** [comment]
> The fix should be in TocLandingContext to fix across the board
> 
> https://github.com/github/docs/blob/d07d253daff9b5b2149a2172713da1874316f7e0/components/context/TocLandingContext.tsx#L36

Ah ok, so you want to fix this to all pages. I will try to edit my code again.

**Comment by simonsabin** [comment]
In looking I think that’s the fixed required, however I have no idea of the knock on impact of such a change. Probably need someone from GH to comment

**Review by ramyaparimi — APPROVED** [review]
@adityadees 
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by ramyaparimi** [comment]
@adityadees 
Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by adityadees** [comment]
> @adityadees
> Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Yes, already do it.

**Comment by simonsabin** [comment]
@ramyaparimi Do you not want to fix the root issue rather than switch to using curly apostrophes, which aren't used elsewhere in the docs? see my comment in the issue https://github.com/github/docs/issues/9485#issuecomment-913205648

**Comment by ramyaparimi** [comment]
@adityadees Thanks so much for your time into this PR. @lee-dohm has looked into this problem and found a general solution that supersedes the original one. I am going to close this PR :yellow_heart:  and merge @lee-dohm's [PR](https://github.com/github/docs/pull/9932) :dolphin:

Thanks very much for the effort you put in to make GitHub’s docs better :sparkling_heart:

**Pull request closed without merging**
