### PR TITLE
Uppercase first letter in nativeName

### PR DESCRIPTION
**Pull request by dmitryburov**
The language, that i changed, need show uppercase, how like other

### Why:

Closes ISSUE

### What's being changed (if available, include any code snippets, screenshots, or gifs):

`/lib/languages.js` - languages constant, `ru` block and `nativeName` parameter.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@dmitryburov great catch! Thanks for spotting this and opening a PR ⚡ 

However, I noticed that this PR is trying to merge into our `repo-sync` as opposed to the `main` branch. Could you submit this PR against the main branch?

**Review by peterbe — DISMISSED** [review]

**Comment by peterbe** [comment]
@cmwilson21 I changed the target on this branch. And approved it. I don't know what your exact process is for landing things, but it looks good to me to go in now.

**Comment by m7mdxmeer** [comment]
‫أُرسلت من الـ iPhone‬‫في 09‏/12‏/2022 الساعة 5:03 م، كتب/كتبت ‏Peter Bengtsson ***@***.***>:‬﻿
@cmwilson21 I changed the target on this branch. And approved it. I don't know what your exact process is for landing things, but it looks good to me to go in now.

**Comment by cmwilson21** [comment]
@peterbe Thank you! I'll remember that option for next time. 😃 ✨

**Review by cmwilson21 — APPROVED** [review]
LGTM! ✨

**Comment by cmwilson21** [comment]
@dmitryburov Thanks for submitting this PR! I'll get it merged down once the checks have passed ✅

**Pull request merged**
