### PR TITLE
Patterns that start with `*` or `!` must use quotes

### LINKED ISSUE #26172: Missing quotes in file paths patterns
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

### What part(s) of the article would you like to see updated?

The patterns that start with `*` and `!` in the [Patterns to match file paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths) section need to be wrapped in quotes.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by miguelsousa**
### Why:

Closes: #26172

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added quotes to the patterns that start with `*` and `!`.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@miguelsousa Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Review by Krishnaa-tech — COMMENTED** [review]
Both the contents are same but there is a change with the indentation

**Comment by miguelsousa** [comment]
@cmwilson21 anything else I need to do to this PR to get it merged?

**Comment by cmwilson21** [comment]
@miguelsousa Thanks for checking in on this! It's up on the review board, so a writer will have eyes on it soon 👀

**Review by hubwriter — APPROVED** [review]
@miguelsousa - Many thanks for raising the docs issue and submitting this PR. 👍 

I'll get this merged and published.

It's good to get this corrected. Thanks again for your help. Much appreciated.

**Pull request merged**
