### PR TITLE
Update actions-scheduled-workflow-example.md

### PR DESCRIPTION
**Pull request by markbattistella**
The editor when changing a CRON time says the most frequent is 5 minutes. Either this section is incorrect or the editor pop over..

### Why:

To make it uniform across the options - either actions CRON can run every 5 minutes or 15 minutes.

### What's being changed:

Made it clearer as the expectation is that if the editor says every 5 minutes, and it doesn't run then there is something wrong with their codebase.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

Screen Shot 2022-02-03 at 1 06 25 pm

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@markbattistella 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Johni1688** [comment]
Hello there

**Review by A699999 — COMMENTED** [review]
Ksjsjsjs

**Review by ethomson — APPROVED** [review]

**Review by ramyaparimi — APPROVED** [review]
@markbattistella 
Thanks so much for opening a PR with this fix! I'll get this merged once tests are passing 🍏

**Pull request merged**
