### PR TITLE
docs: update nodejs template guide to match node versions

### PR DESCRIPTION
**Pull request by ghinks**
The node versions that are maintained as part of the LTS (long term support plan) have incremented by 2 in accordance with [LTS Plan](https://nodejs.org/en/about/releases/). The [nodeJS starter templates](https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml) were updated and I am updating these docs to reflect that.

Sincere thanks for github actions!

- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@ghinks Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by ghinks** [comment]
The pr is still valid

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions after the holidays ✨

**Review by shati-patel — CHANGES_REQUESTED** [review]
Thank you for fixing those outdated examples @ghinks, and apologies for the late review! 

The [template file](https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml) has actually changed again, for example to include version 15.x, add `on: pull_request:`, and remove the `env` syntax. 

Would you be able to copy in those changes too? Then I'll get this merged shortly. Thank you again for your help! ✨

**Comment by ghinks** [comment]
Will look after breakfast

**Review by shati-patel — APPROVED** [review]
Thank you for the updates, @ghinks! I've also added a small change to remove the `env:` step (since that was also deleted from the [template](https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml)). 

If you're happy with the change, I will get this merged 😃

**Comment by ghinks** [comment]
Yes, well spotted. Pls merge. 👍🏼

**Pull request merged**
