### PR TITLE
Fix casing of GeoJSON/TopoJSON

### PR DESCRIPTION
**Pull request by letmaik**
### Why:

File formats were spelled incorrectly.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Casing.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@letmaik Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by felicitymay** [comment]
Hi @letmaik - thanks for opening this pull request and its partner https://github.com/github/docs/pull/19030.

I can see from https://geojson.org/ that your change makes sense, but it looks as if we consistently use the current casing throughout the docs. Before I approve these two pull requests, I'll check in on whether there is a reason for using a different casing.

**Comment by felicitymay** [comment]
👋🏻 
I've had confirmation that this change is fine 🙂 

I'd like to ensure that we update this consistently across all files, doing a local search I see that we have this capitalization in the following files:

- content/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams.md:
     - ✅ Fixed in this pull request ✨ 

- content/repositories/working-with-files/using-files/working-with-non-code-files.md:
    - ✅ Fixed in https://github.com/github/docs/pull/19030

- content/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.md:
    ```
  71  
  72: You can also use code blocks to create diagrams in Markdown. GitHub supports Mermaid, geoJSON, topoJSON, and ASCII STL syntax. For more information, see "[Creating diagrams](/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)."
  73  
    ```
- data/glossaries/internal.yml:
    ```
  211: - term: geoJSON
  212    description: A format for encoding a variety of geographic data structures.

  621: - term: topoJSON
  622  description: An extension of GeoJSON that encodes topology.
    ```

I wondered if you'd be interested in opening pull requests to fix the remaining two files? Then we can merge them all together.

**Review by felicitymay — DISMISSED** [review]
Thanks for the update 🙂

**Comment by letmaik** [comment]
I added the remaining changes to this PR.

**Review by felicitymay — APPROVED** [review]
Thanks for making those updates so quickly 💖 
Very much appreciated.

I'll get these two PRs merged shortly and you should see the changes on the live site in a couple of hours or so.

**Pull request merged**
