### PR TITLE
[GitHub Actions] Fix typo (envrionment => number)

### LINKED ISSUE #25435: [GitHub Actions] Typo in the supported inputs types (`environment` should be `number`)
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Article:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

Heading:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype

### What part(s) of the article would you like to see updated?

[`on.workflow_dispatch.inputs.<input_id>.type`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype) reads:

> The value of this parameter is a string specifying the data type of the input. This must be one of: `boolean`, `choice`, `environment`, or `string`.

The `environment` is not a valid type. It should be `number` as correctly listed under [`inputs` context](https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iamazeem**
### Why:

Closes: #25435

### What's being changed (if available, include any code snippets, screenshots, or gifs):

image

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@iamazeem Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for fixing this! We'll get this merged for you.

**Comment by FidelusAleksander** [comment]
This shouldn't have been merged. Environment is a valid input type. I'm fixing this in https://github.com/github/docs/pull/29781

**Comment by iamazeem** [comment]
@FidelusAleksander
At the time, I wasn't aware of the `environment` input parameter.
Later I found its usage in an example under [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).

Please look at https://github.com/github/docs/issues/25938 also.
There may already be an active PR for this. Thanks!

**Comment by FidelusAleksander** [comment]
Thanks @iamazeem  I will mention this issue

**Pull request merged**
