### PR TITLE
authorization header requires bearer

### PR DESCRIPTION
**Pull request by krpatter-intc**
Fixed issue where docs reference "token" instead of "bearer" for the text before the actual token

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Kevinrp01** [comment]
I did not touch JS just markdown, so not sure why rendering failed here....

**Comment by ramyaparimi** [comment]
@Kevinrp01 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

I checked the modified preview in [this comment](https://github.com/github/docs/pull/16178#issuecomment-1064265750) and I was able to view it ✨

**Comment by Kevinrp01** [comment]
> @Kevinrp01 Thanks so much for opening a PR! I'll get this triaged for review ⚡
> 
> I checked the modified preview in [this comment](https://github.com/github/docs/pull/16178#issuecomment-1064265750) and I was able to view it ✨

Odd, When I go here: https://docs-preview-16178-73f5be.eastus.azurecontainer.io/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#finding-the-node-id-of-an-organization-project

the curl statement seems to be gone.

but it looks fine in the markdown piece:

https://github.com/github/docs/blob/c7d1459a97e9f9a19b79c718093faeb18ea99d69/content/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects.md

not sure what the different is...

**Review by skedwards88 — COMMENTED** [review]
Thanks for this PR! Can you explain more in the PR body about why you think that this change should be made, and why `token` was changed to `bearer` in two out of twelve places in this article?

**Review by skedwards88 — CHANGES_REQUESTED** [review]
(Requesting changes for my above review comment in order to match our review guidelines.)

**Comment by Kevinrp01** [comment]
If you feel my suggestions are in error to how the API works, please let me know and we can close...But there are descrepencies in the docs. vs. behavior as far as "token" vs. "bearer"

**Comment by ramyaparimi** [comment]
@Kevinrp01 Sorry about the stale bot 💛. One of the writers would get back to you soon. Thanks so much for your patience 💖

**Comment by skedwards88** [comment]
Thanks again for your patience on this. I followed up with the team for more details:
- `token` and `Bearer` are interchangeable EXCEPT if you are using a JWT. JWTs require `Bearer`. (If you were not using a JWT and still needed to use `Bearer`, I'm interested to hear more.)
- We are working up update our docs to consistently use `Bearer` everywhere to reduce this confusion. With that in mind, I'm going to keep this PR closed since we will make this change more holistically across the docs.

**Pull request closed without merging**
