### PR TITLE
Fixed Contributing Guide link (top link) within  /contributing/README.md

### LINKED ISSUE #30584: Fixed Contributing Guide link (top link) within  /contributing/README.md
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[https://github.com/github/docs/blob/main/contributing/README.md](https://github.com/github/docs/blob/main/contributing/README.md)

### What part(s) of the article would you like to see updated?

The top link to the contributing guide is broken.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by leabs**
### Why:

Closes: #30584 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Link to the contributing guide at the top of the README is broken

### Check off the following:

- [X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

### CODE REVIEW

**Comment by leabs** [comment]
I noticed this is within the contributing directory which has been depreciated, not sure it is needed but wanted to fix the link aways. If it is not needed this can be closed.

**Comment by nguyenalex836** [comment]
@leabs Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by subatoi** [comment]
Thank you for this fix, @leabs! I'll get this merged.

**Review by subatoi — APPROVED** [review]

**Comment by zashab** [comment]
> ### Why:
> Closes: #30584
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Link to the contributing guide at the top of the README is broken
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

**Pull request merged**
