### PR TITLE
Update about-writing-and-formatting-on-github.md

### PR DESCRIPTION
**Pull request by Hasbiallah1**
#hasbiallah 

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Hasbiallah1** [comment]
@https://www.facebook.com/Kamarulzaman666/

**Comment by Hasbiallah1** [comment]
#hasbiallah 
FB_IMG_1611574858046

**Comment by Hasbiallah1** [comment]
[#hasbiallah ](https://www.facebook.com/Kamarulzaman666/)

**Comment by Hasbiallah1** [comment]
#3332 
Duplicate of #

**Comment by Hasbiallah1** [comment]
@Hasbiallah1

**Comment by Randy2122519** [comment]
Done review

**Pull request closed without merging**
