### PR TITLE
Add ChromeOS support in defaultPlatform frontmatter

### PR DESCRIPTION
**Pull request by sirocyl**
Adds CrOS to defaultPlatform frontmatter, as a variant of Linux.

### Why:

As noted in #4101, ChromeOS is not identified in pages which have multiple platform-specific parts.

### What's being changed:
This change:
- adds "cros" to the list of user agent matches done in [`user-agent.js`](https://github.com/github/docs/blob/main/javascripts/user-agent.js), and
- maps "cros" to linux, in order to adjust the effective platform name, in [`display-platform-specific-content.js`](https://github.com/github/docs/blob/main/javascripts/display-platform-specific-content.js).

### Check off the following:
- [x] I have reviewed my changes in staging. (Works as expected in ChromeOS.)
- [n/a] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [n/a] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@sirocyl Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by heiskr — DISMISSED** [review]
Neat 💃🏼

**Comment by heiskr** [comment]
Oh, I think we'll need to update our event schema too; so that analytics events coming from ChromeOS pass the validation.

**Comment by janiceilene** [comment]
I don't think this one's stale! Reopening.

**Comment by sirocyl** [comment]
Just checking in - is there anything I need to do here, or are we just waiting to move through the pipeline?

**Review by heiskr — APPROVED** [review]

**Pull request merged**
