### PR TITLE
fix breadcrumbs block

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/github/docs/issues/2248

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR @Arhell! I see that this is currently a draft, let me know when you're ready for it to be triaged for review 💖

**Comment by janiceilene** [comment]
@Arhell Thanks for opening a PR! I'll get this triaged for review ✨

**Comment by Arhell** [comment]
update

**Review by heiskr — APPROVED** [review]
Makes sense to me.

**Comment by mohdhairul** [comment]
Thanks to all my buddies to help me

**Pull request merged**
