### PR TITLE
Change example published URL from .md to .html

### PR DESCRIPTION
**Pull request by AustinWise**
### Why:

The example URL after publishing is the .md file. While the markdown file is available after publishing, I assume most users would be interested in the HTML file generated by publishing.

### What's being changed:

`.md` -> `.html`

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Legionsixxx9** [comment]
Is this Austin that use to work with me at BJ's Restaurant in Tumecula?

**Review by ong555 — COMMENTED** [review]
Ok

**Review by rnerone35 — APPROVED** [review]

**Review by rnerone35 — APPROVED** [review]
@

**Comment by rnerone35** [comment]
Ok

**Review by shati-patel — APPROVED** [review]
Thank you for the fix, @AustinWise! Your change makes sense—I'll get this merged shortly 😃

**Pull request merged**
