### PR TITLE
Add PullRequestReviewEvent documentation

### LINKED ISSUE #2709: Undocumented event "PullRequestReviewEvent"
### What article on docs.github.com is affected?

* https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/github-event-types

### What part(s) of the article would you like to see updated?

Seems that while both *PullRequestEvent* and *PullRequestReviewCommentEvent* are referenced, but *PullRequestReviewEvent* is not.

### Additional information

Below is an extract of what the event looks like.
```js
  {
    id: '14732962106',
    type: 'PullRequestReviewEvent',
    actor: {...},
    repo: {...},
    payload: {
      action: 'created',
      review: {
        user: {...},
        body: '',
        state: 'approved',
      },
      pull_request: {
        user: {...},
        body: '',
        head: {...},
        base: {...},
        _links: {...},
      }
    },
    public: true,
    created_at: '2021-01-06T16:45:16Z'
  }
```

### PR DESCRIPTION
**Pull request by lowlighter**
### Why:

`PullRequestReviewEvent` is not documented though it exists
**Closes #2709** 

### What's being changed:

- [GitHub event types](https://docs.github.com/en/developers/webhooks-and-events/github-event-types)

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by lowlighter** [comment]
Still relevant

**Comment by janiceilene** [comment]
👋 @lowlighter I'm so sorry, I think this fell through the cracks because it's still a draft! Are you ready for a review of this PR or are you still working on it?

**Comment by lowlighter** [comment]
No worries 🙂 

Hum there's a few points that need to be clarified for this to be ready for review: 
* From what I tested in https://github.com/github/docs/issues/2709#issuecomment-792097057, the only possible action for the mentioned event is `created`, but the existing docs refers to other possible actions (though it may be a reliquat from a copy-paste as mentioned in other https://github.com/github/docs/issues/2709#issuecomment-794763024 ?) I'm not sure if it implies that these should be removed
* When checking [edited page on deployed instance](https://docs-4330--main.herokuapp.com/en/developers/webhooks-and-events/github-event-types#pullrequestreviewevent), tables are indeed merged (I checked the HTML), but it handles badly the YAML header so these are treated as rows. I can't figure if I've done something wrong, or if it's because `action` fields are different and the merging script doesn't handle it

If you have any of these infos or this needs edition, I'll be happy to update this PR 🙂 
Cheers

**Comment by janiceilene** [comment]
Thanks for the clear breakdown of your open questions @lowlighter! I'll triage this for the writers to take a look at from that perspective 💖

**Comment by lowlighter** [comment]
Updated to match @lecoursen's https://github.com/github/docs/issues/2709#issuecomment-812044070
* See https://docs-4330--main.herokuapp.com/en/developers/webhooks-and-events/github-event-types#pullrequestreviewevent
* Also added the missing `Event payload object` header to `PushEvent` on the same page for more consistency

**Review by lecoursen — APPROVED** [review]
Looks great! I'll merge this now. 😎

**Pull request merged**
