### PR TITLE
docs: update github-terms-of-service.md with correct mailto link

### PR DESCRIPTION
**Pull request by wmundev**
### Why:

- To fix a small issue with the mailto link of the copyright email address

### What's being changed (if available, include any code snippets, screenshots, or gifs):

- Update link of email address so it links correctly when clicked

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@wmundev Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
LGTM :shipit:

**Comment by mchammer01** [comment]
@github/site-policy-admins - could you take a quick look to make sure you're happy with the changes? Thank you 🙇🏻

**Review by literarytea — APPROVED** [review]
:+1:

**Pull request merged**
