### PR TITLE
Update to ed25519 from rsa

### PR DESCRIPTION
**Pull request by ryanlail**
Update command to add ssh key to ssh agent to ed25519 from rsa

### Why:

The docs are inconsistent with rsa and ed25519

### What's being changed:

updating a command to make the docs clearer

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by hrenee1978** [comment]
> Update command to add ssh key to ssh agent to ed25519 from rsa
> ### Why:
> 
> The docs are inconsistent with rsa and ed25519
> ### What's being changed:
> 
> updating a command to make the docs clearer
> ### Check off the following:
> 
>     * [ ]  All of the tests are passing.
> 
>     * [ ]  I have reviewed my changes in staging.
> 
>     * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> 
>     * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

Splunk

**Comment by janiceilene** [comment]
@Ryan-16 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by BaileyJM02** [comment]
This should also require [this pull request](https://github.com/Ryan-16/docs/pull/1) updating the follow-on article. Can be merged to Ryan's patch and therefore added here.

**Comment by eti666** [comment]
Ryan-16:patch-1

**Review by shati-patel — APPROVED** [review]
Thank you for the pull request @ryanlail! 

Some of your changes had been fixed by an earlier PR, but the remaining suggestions look great too 🎉  I'll get this merged once tests pass ✔️

**Pull request merged**
