### PR TITLE
Add further TOTP examples

### PR DESCRIPTION
**Pull request by bkmgit**
### Why:

https://github.com/github/docs/issues/11603

### What's being changed:

Add links to further TOTP options

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@bkmgit 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by lecoursen** [comment]
Thanks for you interest in our docs @bkmgit! This list of recommendations is maintained by our security team, and we don't accept outside additions. Let me know if you have any questions about that!

**Comment by bkmgit** [comment]
@lecoursen Thanks for your review. Will any of the options be considered? Given that TOTP is an open protocol, it is surprising that this is not mentioned in the documentation and only a few proprietary TOTP options have been given.

**Comment by lee-dohm** [comment]
@bkmgit We take our customers' security very seriously. Our security team chooses a short list of apps that they are supremely confident in for these purposes. And, while we don't explicitly state that there are other options, it is implied in the existing documentation.

**Pull request closed without merging**
