### PR TITLE
Explain how workflow run URL is constructed

### PR DESCRIPTION
**Pull request by FloEdelmann**
### Why:

There are two different GitHub Actions workflow run URLs:

* The workflow overview URL, e.g. [`https://github.com/sindresorhus/refined-github/actions/runs/387494159`](https://github.com/sindresorhus/refined-github/actions/runs/387494159)
* A specific job URL, e.g. [`https://github.com/sindresorhus/refined-github/runs/1464813172`](https://github.com/sindresorhus/refined-github/runs/1464813172)

The docs don't make it clear which of these URL parameters the `GITHUB_RUN_ID` environment variable is. This PR tries to clarify this.

### What's being changed:

I've added one sentence after the environment variables table:

grafik

### Check off the following:
- [x] All of the tests are passing.
- [X] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by ha1dyansyah — COMMENTED** [review]
#1454

**Comment by FloEdelmann** [comment]
@ha1dyansyah I don't see how that PR is related to this one. Can you please clarify?

**Comment by janiceilene** [comment]
@FloEdelmann Thanks so much for opening a PR! I'll get this triaged for review 🌟

**Comment by FloEdelmann** [comment]
@janiceilene Any news?

**Comment by janiceilene** [comment]
@FloEdelmann Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by FloEdelmann** [comment]
@janiceilene Sorry to bother you again, I just want to keep this PR from being closed.

**Comment by martin389** [comment]
Hi @FloEdelmann 👋 
Thanks for this contribution! It looks like there are a couple of things you'd like to address in this PR:
- Is your main concern that the URL paths seem unclear about which is the workflow ID, and which is the job ID? For example:
  - `https://github.com/sindresorhus/refined-github/actions/runs/387494159`
  - `https://github.com/sindresorhus/refined-github/runs/1464813172`
- For the workflow run URL, are you needing to retrieve this from within a job running on a runner? Otherwise, you could retrieve this using the API: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#get-a-workflow-run (`html_url`)

**Comment by FloEdelmann** [comment]
Hi @martin389, it's actually both:

I needed to retrieve the workflow run URL from within a job:
[This workflow](https://github.com/OpenLightingProject/open-fixture-library/actions?query=workflow%3A%22External+Links+Checker%22) (which is triggered by a daily cron job) runs [this script](https://github.com/OpenLightingProject/open-fixture-library/blob/master/tests/external-links.js) to regularly update a comment in [this issue](https://github.com/OpenLightingProject/open-fixture-library/issues/999#issuecomment-749141905), in which I wanted to link to the current specific workflow run.

https://github.com/OpenLightingProject/open-fixture-library/blob/5cd0b9d9ffefd2aa3b0e648664ad807269155a90/tests/external-links.js#L215

As the docs were not clear on how to construct the workflow run URL, I found out by [trial and error](https://github.com/OpenLightingProject/open-fixture-library/pull/1594/commits/2f54f766c491596674c6f8fda942ac3dfd113a93) and thus opened this PR to save others from making the same mistake :)

**Comment by FloEdelmann** [comment]
@martin389 @janiceilene Again, I just want to keep this PR from being closed. Please take all the time you need. Happy holidays! :fireworks:

**Comment by martin389** [comment]
Thank you @FloEdelmann! 🎉  I'm checking this approach with our support folks 👍

**Comment by FloEdelmann** [comment]
Friendly bump again :)

**Comment by martin389** [comment]
Following up on this 👍

**Comment by martin389** [comment]
The support folks are happy with this approach 👍 😄 Preparing to ship this update. 🚢

**Comment by martin389** [comment]
A preview of this update is available in staging: https://docs-1651--patch-1.herokuapp.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

**Review by martin389 — APPROVED** [review]

**Comment by martin389** [comment]
(Fixed merge conflict)

**Comment by martin389** [comment]
👍 The new note will be available here, once published: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

**Comment by FloEdelmann** [comment]
Great, thanks 😊

**Pull request merged**
