### PR TITLE
Add disclaimer to Name Squat Policy

### PR DESCRIPTION
**Pull request by Blooym**
### Why:

See https://github.com/github/site-policy/issues/564 for clarification

### What's being changed:

PR adds clarification on the enforcement of individual name squatting name requests 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by mchammer01** [comment]
@github/site-policy-admins 👋🏻 - can you weigh in on this update? Thank you 🙏🏻

**Comment by jaystyles** [comment]
@ dependabot merge

**Comment by jaystyles** [comment]
@ dependabot close

**Comment by BitsOfAByte** [comment]
> @BitsOfAByte Thanks for opening a PR! I spoke with the team and we're not going to accept this change to our site policy. 💛 
> 
> Thank you so much for your time and interest in improving GitHub Docs! 💖 

All good, the only reason I believed this change to be documented was due to the response given to me by support when i enquired about the policy.

Thanks for your time ❤

**Pull request closed without merging**
