### PR TITLE
Update typo on Visual Studio Code docs

### PR DESCRIPTION
**Pull request by marc-queiroz**
Fixing a typo with the word Syncing.

### Why:

There is a problem with documentation

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Rewrite the word Synching to Syncing

### Check off the following:

- [ x ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ x ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by ganibaLGanibal3** [comment]
oh, how the fuck!

**Comment by cmwilson21** [comment]
@marc-queiroz Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by YinChit** [comment]
> Fixing a typo with the word Syncing.
> 
> ### Why:
> There is a problem with documentation
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Rewrite the word Synching to Syncing
> 
> ### Check off the following:
> * [ x ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [ x ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

659b2ed

**Comment by YinChit** [comment]
[659b2ed](https://github.com/github/docs/pull/23810/commits/659b2edc554e58fe3f34b3901b4448383a60e583)

> > Fixing a typo with the word Syncing.
> > ### Why:
> > There is a problem with documentation
> > ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> > Rewrite the word Synching to Syncing
> > ### Check off the following:
> > 
> > * [ x ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> > * [ x ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> [659b2ed](https://github.com/github/docs/commit/659b2edc554e58fe3f34b3901b4448383a60e583)

**Comment by YinChit** [comment]
23810

**Review by mchammer01 — APPROVED** [review]
@marc-queiroz 👋🏻 - thanks so much for fixing this typo ✨

**Comment by YinChit** [comment]
> Fixing a typo with the word Syncing.
> 
> ### Why:
> There is a problem with documentation
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Rewrite the word Synching to Syncing
> 
> ### Check off the following:
> * [ x ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [ x ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

23810

**Pull request merged**
