### PR TITLE
Fix an incorrect alt attribute for the codespaces-commit-pr.png image

### PR DESCRIPTION
**Pull request by lupinitylabs**
### Why:

Closes #10934

### What's being changed:

This PR fixes a copy & paste error for the alt text for `/assets/images/help/codespaces/codespaces-commit-pr.png`, which seems to be copied from `/assets/images/help/codespaces/codespaces-commit-pr-button.png`. 

It changes the previous alt text of `Source control side bar with staging button highlighted` to `GitHub pull request side bar`, which more accurately describes the content of the screenshot.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@lupinitylabs 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Jassi10000-zz — COMMENTED** [review]
@lupinitylabs Buddy I guess Alt text are completely in hand of the docs maintainer and obvio they must have written this considering some pts.

Thanks for your contributions but am afraid it may be not be considered or termed as invalid 

You can look out for some other nice issues to contribute to 

All the best!!!

**Comment by lupinitylabs** [comment]
@Jassi10000 I just encountered this when working on something else and I don't know why someone would want the same alt text for two completely different images, considering the alt should help robots to index and screenreaders to describe what's going on in the picture.

In the end, it's just a pointer towards a potential issue. If you don't need it, no offense taken 😉

**Review by mchammer01 — APPROVED** [review]
LGTM ✨

**Pull request merged**
