### PR TITLE
Python: tox is lowercase

### PR DESCRIPTION
**Pull request by hugovk**
### Why:

For consistency, spell tox all in lowercase. This is how the tox project spells it, and these docs also have it lowercase in some places. 

https://tox.readthedocs.io/

https://twitter.com/jugmac00/status/1431712286557843457

### What's being changed:

Change example workflow to use lowercase tox. 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by jugmac00 — APPROVED** [review]
As a maintainer of tox, I'd say...

**Comment by ramyaparimi** [comment]
@hugovk 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by felicitymay — APPROVED** [review]
@hugovk - thanks for alerting us to this typo and for opening a pull request to fix it 💖 

I particularly appreciated the fact that you included links to show how this name is usually capitalized 🙇🏻‍♀️ 

@jugmac00 - thanks for commenting with your approval too 🚀

**Review by HlaingHtut — COMMENTED** [review]
writedraw money

**Pull request merged**
