### PR TITLE
Updated manipulating_file_prereqs.md

### PR DESCRIPTION
**Pull request by Shivam7-1**
### What's being changed:
I have done punchuation in manipulating_file_prereqs.md

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 doc

**Comment by Shivam7-1** [comment]
@all-contributors add @Shivam7-1  for code

**Comment by janiceilene** [comment]
@all-contributors please add @Shivam7-1 for doc

**Comment by janiceilene** [comment]
How frustrating 💛 @Shivam7-1 I'll look into this!

**Pull request closed without merging**
