### PR TITLE
Remove all duplicate '422' error notes from the REST API docs

### LINKED ISSUE #11784: [Improvement]: Duplicate content in description of "private" parameter for Update a Repo endpoint
### Is this issue for a product update or release that is not yet available to customers?

No? Then please continue. Thank you!

### What article(s) is affected?

https://docs.github.com/en/rest/reference/repos#update-a-repository

### Describe the desired docs changes and the problem they solve for customers.

Remove duplicate content.

There is a duplicated statement in the description of the "private" field:

>Either true to make the repository private or false to make it public. Default: false.
Note: You will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private. Note: You will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.
Default: false

To fix this, we should remove one of the duplicated sentences.

### Who does this affect?

REST API users

### What is the impact to users?

It's confusing to have duplicate sentences

### Are you willing to open a PR to make this fix? If not, do you know anyone (Hubber or not, we're open source!) who's willing to help write this documentation?

No 😸

### PR DESCRIPTION
**Pull request by tannerdolby**
### Why:

Closes #11784

### What's being changed:
Each of the duplicate "422 error notes" in REST API docs have been removed.

Screenshot showing duplicate note before removal:

Screen Shot 2021-11-08 at 1 15 05 PM

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by tannerdolby** [comment]
@ramyaparimi I couldn't find exactly where the values were being generated which contained the duplicate note. The only places I found using VS Code search was in the `lib/*` folder which I just discovered is a unacceptable contribution type.

Let me know what the next steps should be. I'm happy to revert my proposed changes as they won't be accepted, and then update the appropriate place in source where this duplicate note is being defined/used.

**Comment by ramyaparimi** [comment]
@tannerdolby 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by tannerdolby** [comment]
@ramyaparimi You're welcome! Ok great, thank you ⚡

**Comment by skedwards88** [comment]
Thanks for opening this PR! Those files are generated automatically, so your changes would quickly be overwritten. Instead, we need to fix this internally. I'll open an issue for the team to fix this internally.

**Pull request closed without merging**
