### PR TITLE
Fixed a sentence typo

### PR DESCRIPTION
**Pull request by harsh98trivedi**
### Why:

Closes [issue link]

### Check off the following:

- [✔️] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [✔️] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Review by Alimubarak773 — APPROVED** [review]

**Review by Alimubarak773 — APPROVED** [review]

**Review by janiceilene — APPROVED** [review]
Thanks so much for opening a PR with this fix and coming back to fill out the template, we really appreciate it! This change looks great 🎉 I'll update the branch and merge it once the tests are passing 🍏

**Comment by Alimubarak773** [comment]
I want see gst sury

في الثلاثاء، ٢٥ مايو، ٢٠٢١ ٧:٤٠ ص Janice ***@***.***> كتب:

**Comment by Alimubarak773** [comment]
The above this for i with my money from
***@***.*** can you hld my for this

في الثلاثاء، ٢٥ مايو، ٢٠٢١ ٧:٤٥ ص Ali Alaadh ***@***.***> كتب:

**Pull request merged**
