### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by FannyGautierr**
Hey :wave:,

This PR will fix :

1 typo in `content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/pinning-items-to-your-profile.md`
1 typo in `content/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers.md`
1 typo in `content/admin/configuration/configuring-your-enterprise/configuring-ssh-connections-to-your-instance.md`
1 typo in `content/admin/enterprise-management/configuring-high-availability/monitoring-a-high-availability-configuration.md`
1 typo in `content/admin/overview/about-github-enterprise-server.md`
1 typo in `content/apps/creating-github-apps/about-creating-github-apps/best-practices-for-creating-a-github-app.md`
1 typo in `content/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app.md`
1 typo in `content/apps/oauth-apps/building-oauth-apps/authenticating-to-the-rest-api-with-an-oauth-app.md`
1 typo in `content/code-security/codeql-cli/codeql-cli-reference/about-codeql-packs.md`
1 typo in `content/code-security/getting-started/dependabot-quickstart-guide.md`
1 typo in `content/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api.md`
1 typo in `content/get-started/using-github/keyboard-shortcuts.md`
1 typo in `content/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue.md`
1 typo in `content/site-policy/site-policy-deprecated/github-ae-data-protection-agreement.md`
1 typo in `data/reusables/two_fa/auth_methods_2fa.md`

Best!

### CODE REVIEW

**Comment by cmwilson21** [comment]
@FannyGautierr Thanks for submitting a PR! And welcome to the community! ✨ 

It looks like one of these corrections is in a file we don't accept contributions to. Can you remove that one from your PR? Then I can get this triaged for review ⚡ 

> 1 typo in content/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers.md

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by FannyGautierr** [comment]
I just remove the file ! Sorry about that

**Comment by cmwilson21** [comment]
@FannyGautierr No worries! Thanks for the quick action ⚡ 

I'll get this triaged for review. 👀 

In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍

**Review by skedwards88 — APPROVED** [review]
Thanks for these fixes! We'll get this merged for you.

**Review by margaret-tucker — APPROVED** [review]

**Pull request merged**
