### PR TITLE
fix some ghcr docker call examples had a typo when specifying image tag

### PR DESCRIPTION
**Pull request by tspascoal**
### Why:

Some of the docker examples had a typo when specifying the image tag

### What's being changed:

Changed a dot from colon (on two separate calls) , the separator between the image name and the tag is a colon, since a dot was being used the tag was part of the tag name which was not the intended.

### Check off the following:
- [ ] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@tspascoal Thanks for opening a pull request! Please fill out the rest of the pull request template to explain what changes you've made and we'll get this up for review 🌟

**Comment by tspascoal** [comment]
Done.

**Review by rachmari — APPROVED** [review]
@tspascoal thank you for fixing this bug! 🔧🐛  

This looks great. 🙌  I'll go ahead and merge it in for you. :shipit: 🚀 👏

**Review by Neftaysaly — APPROVED** [review]

**Comment by tspascoal** [comment]
@all-contributors please add tspascoal for Documentation

**Comment by tspascoal** [comment]
@all-contributors please add tspascoal for Documentation

**Pull request merged**
