### PR TITLE
Fix regression in artifact-attestations-step-for-container-images.md

### LINKED ISSUE #33794: Publishing Docker images page contains broken YML code
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All articles using the `{% data reusables.actions.artifact-attestations-step-for-container-images %}` template.
For example: https://github.com/github/docs/blob/main/content/actions/publishing-packages/publishing-docker-images.md

Specifically the problem is that the attestations-step-for-container-images is using an asterisk `*` instead of a dash `-` in the example.

Now it looks like this:
```yaml
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      
      * name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
```

This can be confusing as one could believe the asterisk is some kind of special case.

### What changes are you suggesting?

Change the https://github.com/github/docs/blob/main/data/reusables/actions/artifact-attestations-step-for-container-images.md file to use a `-` so the GitHub Actions examples using attestation step are not broken.

This also requires changing the setup so the linter does not complain. See my attempts at fixing this in closed PR: https://github.com/github/docs/pull/33793

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by janbrasna**
This is another approach to #33793

> ### Why:
> Fixes regression where the reusable artifact attestations step example was accidentally broken by a commit that replaced dashes with asterisks.
> 
> Commit that broke example: [0886a39](https://github.com/github/docs/commit/0886a399f07aedae418d587873ffc6c0810ae7eb)
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Swapped an asterisk in a GitHub actions step example with a dash.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

Fixes #33794

### CODE REVIEW

**Comment by janbrasna** [comment]
Nope, linter still angry.

**Comment by subatoi** [comment]
Hi @janbrasna—in hindsight, I think a better solution would probably be to just make these not-reusables, as there's only three instances of it anyway. I'm sorry for misleading you.

Let me run it by our Engineering team to see what they think—when we open a PR to fix it, whatever the fix looks like, I'll make sure you're added as co-contributor so you receive the credit, if that sounds OK?

**Comment by janbrasna** [comment]
@subatoi Sure, whatever feels more stable for now. I've updated this PR to getting rid of the reusable (which is not a bad idea after all, as it is probably the only occurrence where bits of code are placed in toplevel markdown file without any guardrails around defining what formatting/markup it's supposed be written in, a footgun in itself…)

Please don't bother with credits et al., I only wanted to get this moving — whatever path you end up picking feel free to just close this out, no worries;)

**Comment by Disastrous-young-411** [comment]
Feature

**Comment by Disastrous-young-411** [comment]
Feature

**Comment by Disastrous-young-411** [comment]
Feature

**Review by SiaraMist — APPROVED** [review]
Thanks for catching this and working with us to fix it, @janbrasna! I think the workaround you added looks good, so I'll go ahead and get this merged.

**Pull request merged**
