### PR TITLE
POST access_tokens returns an access token

### LINKED ISSUE #14824: POST access_tokens returns an access token
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/getting-started-with-apps/setting-up-your-development-environment-to-create-a-github-app#authenticating-as-a-github-app

### What part(s) of the article would you like to see updated?

On that page, the access token returned by `@app_client.create_app_installation_access_token(installation_id)` is used as a bearer token, not as an access token as it should.
```ruby
  @installation_client = Octokit::Client.new(bearer_token: installation_token)
```
should be:
```ruby
  @installation_client = Octokit::Client.new(access_token: installation_token)
```

The endpoint name suggests it is an access token, in https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation, it is used as an access token (`"Authorization: token YOUR_INSTALLATION_ACCESS_TOKEN"` – it would be `"Authorization: Bearer YOUR_INSTALLATION_ACCESS_TOKEN"` if it was a bearer token), and to be sure I also asked GitHub Support and was told it is indeed an access token.

### Additional information

In fact the token returned by that end point does seem to work as both an access token and a bearer token, but consistency would make it easier to follow.

### PR DESCRIPTION
**Pull request by vincentisambart**
`POST app/installations/:installation_id/access_tokens` returns an access token, not a bearer token.

The endpoint name suggests it's an access token, [this documentation page](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#authenticating-as-an-installation) uses it as an access token (`Authorization: token YOUR_INSTALLATION_ACCESS_TOKEN`, not `Authorization: Bearer YOUR_INSTALLATION_ACCESS_TOKEN`), and to be sure I also asked GitHub Support and I was told it is indeed an access token.

Using that token as a Bearer token does seem to work but consistency would make things more easy to follow.

### Why:

Closes #14824

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@vincentisambart 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by vincentisambart** [comment]
Found another place where a GitHub App installation **access token** is used as a Bearer token:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
I'm not even sure what is correct...

**Comment by sophietheking** [comment]
Hi @vincentisambart  👋 thank you for bringing this up. ✨ The team looked at your suggestion and found that it's part of a larger discussion. I'm going to close this pull request now so that we can pick it up internally. Thanks so much for taking your time in contributing to the GitHub docs. 💖

**Comment by vincentisambart** [comment]
Currently the docs about how to handle the token `POST app/installations/:installation_id/access_tokens` are confusing so I hope we'll end up with better explanations 😊

**Pull request closed without merging**
