### PR TITLE
Update migrating-oauth-apps-to-github-apps.md

### PR DESCRIPTION
**Pull request by HALUZ15**
These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by hieueuro — COMMENTED** [review]
Ok

**Review by Karitta123 — COMMENTED** [review]
gh pr checkout 10218

**Comment by m7adf7d** [comment]
> These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'
> 
> ### Why:
> Closes [issue link]
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Comment by m7adf7d** [comment]
https://github.com/m7adf7d/ptway-net/blob/5fee18b32a2923c00ce8c5bdf4cc32221c1c302c/.gitignore

**Comment by m7adf7d** [comment]
https://github.com/m7adf7d/ptway-net/blob/5fee18b32a2923c00ce8c5bdf4cc32221c1c302c/.gitignore

**Comment by m7adf7d** [comment]
> These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'
> 
> ### Why:
> Closes [issue link]
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Review by BIOSTYMA — COMMENTED** [review]
### ### ### ### ``

**Review by jeanp1209 — COMMENTED** [review]
Ok

**Comment by K-adot** [comment]
Skip to content
github /
docs
Public

    Code
    Issues 70
    Pull requests 25
    Discussions
    Actions
    Projects 2
    Security
    Insights

Jump to bottom
Update migrating-oauth-apps-to-github-apps.md #10218
Closed
HALUZ15 wants to merge 1 commit into github:main from HALUZ15:123MwanjeMike-patch-2
Closed
Update migrating-oauth-apps-to-github-apps.md
#10218
HALUZ15 wants to merge 1 commit into github:main from HALUZ15:123MwanjeMike-patch-2
Conversation 5
Commits 1
Checks 27
Files changed 1
Conversation
@HALUZ15 HALUZ15 commented on 22 Sep

These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'
Why:

Closes [issue link]
What's being changed:
Check off the following:

I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click View deployment).

    For content changes, I have completed the self-review checklist.

Writer impact (This section is for GitHub staff members only):

    This pull request impacts the contribution experience
        I have added the 'writer impact' label
        I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

@123MwanjeMike
@skedwards88
Update migrating-oauth-apps-to-github-apps.md
ced20ba
@welcome welcome bot commented on 22 Sep

Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.
@github-actions github-actions bot added the triage label on 22 Sep
@github-actions github-actions bot added this to Triage in Docs team reviews on 22 Sep
@ramyaparimi ramyaparimi added the invalid label on 22 Sep
@github-actions github-actions bot closed this on 22 Sep
Docs team reviews automation moved this from Triage to Done on 22 Sep
Karitta123
Karitta123 reviewed on 5 Oct
@Karitta123 Karitta123 left a comment

gh pr checkout 10218
CPH2239 referenced this issue 19 days ago
@ramyaparimi
Update working-in-docs-repository.md
622a26c
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
ProTip! Add comments to specific lines under Files changed.
Reviewers

@Karitta123
Karitta123

Assignees
No one assigned
Labels
invalid
triage
Projects
Docs team reviews
Done
Milestone
No milestone
Linked issues

Successfully merging this pull request may close these issues.

None yet
Notifications
Customize

You’re not receiving notifications from this thread.
4 participants
@HALUZ15
@Karitta123
@ramyaparimi
@123MwanjeMike

    © 2021 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

**Comment by K-adot** [comment]
Skip to content
github /
docs
Public

    Code
    Issues 70
    Pull requests 25
    Discussions
    Actions
    Projects 2
    Security
    Insights

Jump to bottom
Update migrating-oauth-apps-to-github-apps.md #10218
Closed
HALUZ15 wants to merge 1 commit into github:main from HALUZ15:123MwanjeMike-patch-2
Conversation 5
Commits 1
Checks 27
Files changed 1
Conversation
@HALUZ15 HALUZ15 commented on 22 Sep

These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'
Why:

Closes [issue link]
What's being changed:
Check off the following:

I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click View deployment).

    For content changes, I have completed the self-review checklist.

Writer impact (This section is for GitHub staff members only):

    This pull request impacts the contribution experience
        I have added the 'writer impact' label
        I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

@123MwanjeMike
@skedwards88
Update migrating-oauth-apps-to-github-apps.md
ced20ba
@welcome welcome bot commented on 22 Sep

Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.
@github-actions github-actions bot added the triage label on 22 Sep
@github-actions github-actions bot added this to Triage in Docs team reviews on 22 Sep
@ramyaparimi ramyaparimi added the invalid label on 22 Sep
@github-actions github-actions bot closed this on 22 Sep
Docs team reviews automation moved this from Triage to Done on 22 Sep
Karitta123
Karitta123 reviewed on 5 Oct
@Karitta123 Karitta123 left a comment

gh pr checkout 10218
CPH2239 referenced this issue 19 days ago
@ramyaparimi
Update working-in-docs-repository.md
622a26c
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
ProTip! Add comments to specific lines under Files changed.
Reviewers

@Karitta123
Karitta123

Assignees
No one assigned
Labels
invalid
triage
Projects
Docs team reviews
Done
Milestone
No milestone
Linked issues

Successfully merging this pull request may close these issues.

None yet
Notifications
Customize

You’re receiving notifications because you’re subscribed to this thread.
4 participants
@HALUZ15
@Karitta123
@ramyaparimi
@123MwanjeMike

    © 2021 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

**Comment by K-adot** [comment]
Skip to content
github /
docs
Public

    Code
    Issues 70
    Pull requests 25
    Discussions
    Actions
    Projects 2
    Security
    Insights

Jump to bottom
Update migrating-oauth-apps-to-github-apps.md #10218
Closed
HALUZ15 wants to merge 1 commit into github:main from HALUZ15:123MwanjeMike-patch-2
Conversation 5
Commits 1
Checks 27
Files changed 1
Conversation
@HALUZ15 HALUZ15 commented on 22 Sep

These changes are to include the 'Delete OAuth App' step in 'Migrating OAuth Apps to GitHub Apps'
Why:

Closes [issue link]
What's being changed:
Check off the following:

I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click View deployment).

    For content changes, I have completed the self-review checklist.

Writer impact (This section is for GitHub staff members only):

    This pull request impacts the contribution experience
        I have added the 'writer impact' label
        I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

@123MwanjeMike
@skedwards88
Update migrating-oauth-apps-to-github-apps.md
ced20ba
@welcome welcome bot commented on 22 Sep

Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.
@github-actions github-actions bot added the triage label on 22 Sep
@github-actions github-actions bot added this to Triage in Docs team reviews on 22 Sep
@ramyaparimi ramyaparimi added the invalid label on 22 Sep
@github-actions github-actions bot closed this on 22 Sep
Docs team reviews automation moved this from Triage to Done on 22 Sep
Karitta123
Karitta123 reviewed on 5 Oct
@Karitta123 Karitta123 left a comment

gh pr checkout 10218
CPH2239 referenced this issue 19 days ago
@ramyaparimi
Update working-in-docs-repository.md
622a26c
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
ProTip! Add comments to specific lines under Files changed.
Reviewers

@Karitta123
Karitta123

Assignees
No one assigned
Labels
invalid
triage
Projects
Docs team reviews
Done
Milestone
No milestone
Linked issues

Successfully merging this pull request may close these issues.

None yet
Notifications
Customize

You’re receiving notifications because you’re subscribed to this thread.
4 participants
@HALUZ15
@Karitta123
@ramyaparimi
@123MwanjeMike

    © 2021 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

**Review by Pacholink101010 — COMMENTED** [review]
Seres queridos vinculados

**Comment by Ship972** [comment]
👍🏾

**Comment by Nailequrbanova** [comment]
Hikmet

**Comment by Nailequrbanova** [comment]
Hikmeti

**Comment by Nailequrbanova** [comment]
nailequrbanova86@gmail.com

**Comment by q464pp** [comment]
可以拉取請求嗎謝謝

**Pull request closed without merging**
