### PR TITLE
Clarified the organizations that get visibility on 'internal' reposit…

### PR DESCRIPTION
**Pull request by rajbos**
### Why:

Clarified the visibility especially for 'internal' repositories to make it clear that this stays within the enterprise.

### What's being changed:

Text only

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@rajbos Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by SirJosh1987 — APPROVED** [review]

**Comment by lecoursen** [comment]
Hi @rajbos, it looks like I'm not able to leave a suggested change on this PR, perhaps because you deleted your fork? For us to merge this, we'll need to be able to make changes to the branch. Could you possibly restore your fork? Thanks!

**Comment by rajbos** [comment]
@lecoursen , darn it, seems like I cleaned it up to soon without realizing this was part of an open PR. Somehow it is not visible under my 'Deleted repositories' so no way to recover I guess? I can re-fork it and add the changes again, but then I'll have to create a new PR for it because I cannot link it to this PR, correct? Happy to do so then.

**Comment by lecoursen** [comment]
> I can re-fork it and add the changes again, but then I'll have to create a new PR for it because I cannot link it to this PR, correct? Happy to do so then.

Yes, I think that we might need to do that, unfortunately. Thanks for taking the time! Can you also make sure you check the box that allows edits from maintainers when you do recreate the PR? And feel free to @-mention me so you don't get added to the back of the queue. 😊

**Review by Chelle76 — APPROVED** [review]

**Review by Chelle76 — APPROVED** [review]

**Comment by rajbos** [comment]
Closing this PR in favor of #8286

**Pull request closed without merging**
