### PR TITLE
Package authentication documentation has confusing PAT wording

### LINKED ISSUE #33925: Package authentication documentation has confusing PAT wording
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
https://docs.github.com/en/packages/learn-github-packages/publishing-a-package

### What changes are you suggesting?

Remove the reusable section that states 
`GitHub Packages only supports authentication using a personal access token (classic). For more information, see "[Managing your personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."`. But this isn't true, and is directly contradicted by references to using `GITHUB_SECRET` in GitHub actions.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by syntastical**
### Why:

Closes: https://github.com/github/docs/issues/33925

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Both of the following links make reference to only being able to authenticate to GitHub packages using a PAT but that's misleading, and even contradicted on the same page by references to using `GITHUB_SECRET` in GitHub actions.
https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@syntastical Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by felicitymay** [comment]
Thanks for raising this PR. I agree that the text of the note is misleading and have proposed an alternative solution. See:

- https://github.com/github/docs/issues/33925#issuecomment-2225613443

While we discuss the best solution to the problem you identified, I'm going to label this PR as on hold.

**Comment by nguyenalex836** [comment]
Reopening per comment [here](https://github.com/github/docs/issues/33925#issuecomment-2239521479)!

**Review by Ripiou — COMMENTED** [review]
data/reusables/package_registry/authenticate-packages.md

**Pull request closed without merging**
