### PR TITLE
Add PowerShellForGitHub to the list of available REST libraries

### LINKED ISSUE #3069: Add PowerShellForGitHub to list of available REST libraries
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/overview/libraries

### What part(s) of the article would you like to see updated?

I'd like to add a `PowerShell` section to that list, and reference [microsoft/PowerShellForGitHub](https://github.com/microsoft/PowerShellForGitHub) in that new section.  The library has 89,000+ downloads and is under active development with help from the community.  It already has support for a substantial set of the entire v3 REST API surface.

### Additional information

n/a

### PR DESCRIPTION
**Pull request by HowardWolosky**
### Why:

[microsoft/PowerShellForGitHub](https://github.com/microsoft/PowerShellForGitHub) is a GitHub REST API v3 library written in PowerShell with 89,000+ downloads, and it is under active development with help from the community.  It already has support for a substantial set of the entire v3 REST API surface.

Resolves #3069 

### What's being changed:

Adding a `PowerShell` language section amongst the other languages listed, along with an entry for `PowerShellForGitHub` in that new section.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] ~~For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)~~
- [x] ~~For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).~~

### CODE REVIEW

**Comment by janiceilene** [comment]
@HowardWolosky Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by poke5352 — APPROVED** [review]

**Comment by HowardWolosky** [comment]
@janiceilene - looks like the bot closed this unmerged. Will you please reconsider this change?

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this :upside_down_face: Sorry about that! Reopening and triaging this for review :yellow_heart:

**Comment by martin389** [comment]
A rendered preview of this draft is available here: https://docs-3070--libraries-pg.herokuapp.com/en/rest/overview/libraries#powershell

**Comment by skedwards88** [comment]
Thank you for this addition! I'll get this merged down for you.

**Review by skedwards88 — APPROVED** [review]

**Pull request merged**
