### PR TITLE
Added build step to prepare script

### LINKED ISSUE #222: first local test run requires `npm run build`
A fresh clone of this repo requires `npm run build` to be run before all the tests will pass. This is an easy thing to forget because you only have to run it once and then `npm test` continues to work without a fresh build.

One way we can work around this is by adding a `pretest` script to package.json with a value of `npm run build`. That way the build will always run first when anyone runs `npm test`.

That would solve the immediate problem for first-time contributors, but it would also incur a performance penalty every time you run the tests locally, as the build currently takes ~4 seconds to run on my superfast computer. Maybe 4s doesn't matter much in the grand scheme of things... but it would be nice to not incur that cost.

🤔 What are some ways we can solve this?

cc @github/docs-engineering @jeffmcaffer

### PR DESCRIPTION
**Pull request by FarazzShaikh**
Added build step to prepare script and Removed redundant calls of build script

### Why:

Closes #222 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
I have added `npm run build` to the `prepare` script in `package.json`. As a result, I have attempted to remove all redundant calls of `npm run build`.

However, there are some calls that I am not sure how to handle. Here are they:

- https://github.com/FarazzShaikh/docs/blob/b08a65a90373d6cd92604b7ca63d6fd78b5a1265/.github/workflows/sync-single-english-algolia-index.yml#L51
- https://github.com/FarazzShaikh/docs/blob/b08a65a90373d6cd92604b7ca63d6fd78b5a1265/.github/workflows/test-windows.yml#L64
- https://github.com/FarazzShaikh/docs/blob/b08a65a90373d6cd92604b7ca63d6fd78b5a1265/.github/workflows/test.yml#L69
- https://github.com/FarazzShaikh/docs/blob/b08a65a90373d6cd92604b7ca63d6fd78b5a1265/script/enterprise-server-deprecations/archive-version.js#L110
- https://github.com/FarazzShaikh/docs/blob/b08a65a90373d6cd92604b7ca63d6fd78b5a1265/Dockerfile#L58

And maybe other that I might have missed. These calls perform some operations after `npm ci` and before `npm run build`.

**Review by Chelle76 — APPROVED** [review]

**Comment by janiceilene** [comment]
@FarazzShaikh Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by janiceilene** [comment]
Thanks for opening this PR @FarazzShaikh! Sometimes we need to run packages without making a build, having to build to install would be a deal breaker for some processes, so we can't accept this PR. 

Thanks so much for your interest and passion in improving the GitHub docs 💛

**Comment by FarazzShaikh** [comment]
@janiceilene thank you for your review. You should close #222 as well if this cannot be implemented.

**Comment by JamesMGreene** [comment]
@FarazzShaikh We really appreciate the PR you offered up. 🙇🏻‍♂️ 

Unfortunately, when the larger team reviewed your PR, one of the valid issues mentioned was that this change (adding a `prepare` script to run the `npm run build` script) would've forced us to _always_ run the build, even when we don't want or need to, and thus slowing down certain processes (e.g. in many of our Actions workflows). That was a perspective that I hadn't considered when I encouraged you to create this PR. 😓 

Since npm does not currently provide us a mechanism to opt-out of that behavior (other than `--ignore-scripts`, which also ignores all of the _dependencies'_ lifecycle scripts, too 😬 🙅🏻‍♂️), we decided it was better for us to stick with the opt-in behavior that we currently have. While we understand that does put a slight burden on contributors to execute that one extra step, we believe it is something that is easily enough learned and worked around. 🤷🏻‍♂️ 

Thank you especially for your thoroughness in taking the extra step of updating the contributor documentation, the Codespaces configuration, and the Actions workflows as well. ✨ 

We are thankful for your involvement and effort. We would love to see additional contributions from you in the future. ❤️

**Comment by FarazzShaikh** [comment]
Understood, Thanks for letting me know!  😄

**Pull request closed without merging**
