### PR TITLE
Curious omission of English in supported languages

### PR DESCRIPTION
**Pull request by greglow-sdu**
### Why:

There is a list of languages shown. It's not complete.

### What's being changed:

I added English to the list of languages. English is supported.

### Check off the following:
- [x] All of the tests are passing. N/A
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**) N/A
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by pes2020kk — APPROVED** [review]

**Review by pes2020kk — APPROVED** [review]

**Comment by janiceilene** [comment]
@greglow-sdu Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by janiceilene** [comment]
Thanks @greglow-sdu (and @charlesrutabanzibwa 😸 )! I'll get this triaged for review ⚡

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by janiceilene** [comment]
This was closed by stalebot over the holiday break, but it shouldn't have been! Re opening 💛

**Review by hubwriter — APPROVED** [review]
@greglow-sdu - Apologies for the delay getting this reviewed over the holiday period.

Excellent spot. Thank you very much for fixing this. 👍

**Comment by hubwriter** [comment]
Merging now 🚢

**Pull request merged**
