### PR TITLE
Windows changes - Update generating-a-new-ssh-key-and-adding-it-to-th…

### PR DESCRIPTION
**Pull request by paulyuk**
The current Windows pivot tab is all invalid showing bash/zsh steps.

This PR provides the working PowerShell commands.

I might need help ensuring the MarkDown renders correctly in the pivot tabs. 

Ensuring steps work in Windows and PowerShell

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@paulyuk Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Vindawg138** [comment]
Hi does this code mean it gets your SSH secure certificate and installs it for you I'm clear please can someone explain or elaborate thank you

**Comment by paulyuk** [comment]
Hi @Vindawg138 , yes.  Sticking to the original spirit of the article it shows you how to create your own SSH key, and then upload the public key to GH.  The only issue is the steps did not work on Powershell like they did for Bash/ssh on linux.  So this fixes the steps.

**Comment by Vindawg138** [comment]
Ok thanks you for your response what do I do to Open I sir?

**Review by vgrl — COMMENTED** [review]
Looks good, just one question about when an elevated terminal is required, and when it isn't.

**Review by vgrl — APPROVED** [review]
Double checked on preview and looks good! ⚡. I'll go ahead and get this merged.

**Pull request merged**
