### PR TITLE
Add required trailing dot for CNAME setup

### LINKED ISSUE #5358: CNAME configuration lacks missing trailing dots
### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#:~:text=anotherexample.com%20to-,%3Corganization%3E.github.io,-.%20The%20CNAME%20record

### What part(s) of the article would you like to see updated?

Add trailing dots to *"If you want to use the subdomain www.anotherexample.com for your organization site, create a CNAME record that points www.anotherexample.com to <organization>.github.io. The CNAME record should always point to <user>.github.io or <organization>.github.io, excluding the repository name."*

### Additional information

https://stackexchange.github.io/dnscontrol/why-the-dot

### PR DESCRIPTION
**Pull request by tomayac**
### Why:

Closes https://github.com/github/docs/issues/5358

### What's being changed:

Add trailing dots.

### Check off the following:
- [X] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@tomayac Thanks so much for opening an issue and PR for this fix! I'll get this triaged for review ⚡

**Review by lucalves — APPROVED** [review]

**Review by Nirzak — COMMENTED** [review]
I didn't get it actually. I have used CNAME before without the . in the end of the domain name and it works like a charm. I mean what's point to put a dot in the last of the domain!

**Review by nathanlayla — APPROVED** [review]
> 

> ``

**Review by mahdiamer — APPROVED** [review]

**Comment by tomayac** [comment]
Looks like someone else after @mahdiamer needs to approve for this to land.

**Review by Nirzak — APPROVED** [review]

**Comment by janiceilene** [comment]
@tomayac So sorry for the delayed response! I've spoken with our engineers and this isn't a change we're looking to make in the docs. Most DNS providers add the trailing dot implicitly and will remove it in the UI if you include the trailing dot, so this addition would add confusion for the majority of users.

Thank you so much for your interest in improving the GitHub documentation!

**Comment by duongxuantuan154** [comment]
.#5359

**Review by duongxuantuan154 — COMMENTED** [review]
#5359

**Comment by KHOENIX** [comment]
> ### Why:
> Closes #5358
> 
> ### What's being changed:
> Add trailing dots.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Pull request closed without merging**
