### PR TITLE
Document `@dependabot ignore this patch version` command

### LINKED ISSUE #32344: Undocumented dependabot command: `ignore patch version`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates

### What part(s) of the article would you like to see updated?

The list of available commands are missing the `ignore patch version` equivalent of major/minor version of this command

These commands exist, they are simply not documented and hence undiscoverable - except for analogy/trial&error

There's a corresponding issue for dependabot-core: https://github.com/dependabot/dependabot-core/issues/9260

### Additional information

The commands work even for patch:

image

### PR DESCRIPTION
**Pull request by corneliusroemer**
### Why:

Closes: #32344 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Document undocumented dependabot commands by adding list items:

image

image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@corneliusroemer Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by am-stead — APPROVED** [review]
👋 @corneliusroemer 
Thanks very much for opening this PR! 

It looks great, so I'm going to go ahead and get it merged.✨

Thanks for contributing to the docs!

**Comment by Primajin** [comment]
Thanks a lot for adding this @corneliusroemer , I was looking for exactly that. Right now it doesn't look like that @dependabot is already suggesting this when I expand the `Dependabot commands and options` yet - are we missing a deployment here or is this already planned?

**Comment by corneliusroemer** [comment]
The or was for docs only.  to change in the PR one would have to alter some code somewhere else

**Comment by Primajin** [comment]
Thanks @corneliusroemer for the clarification - I could follow the breadcrumbs back to https://github.com/dependabot/dependabot-core/issues/9662 👍🏻

**Pull request merged**
