### PR TITLE
Small tweak to an example file pattern match

### PR DESCRIPTION
**Pull request by magnetikonline**
### What's being changed:

Small update to a path match example to fit the format of other examples (no leading `/`).

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@magnetikonline Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by magnetikonline** [comment]
Hey thanks @janiceilene - happy to help out - even if only 1 character 😄 .

**Review by skedwards88 — APPROVED** [review]
⚡ Thanks for making this change! I'll get it merged down for you.

**Comment by magnetikonline** [comment]
Thanks team! 👍

**Pull request merged**
