### PR TITLE
Replaced "main" by "master"

### PR DESCRIPTION
**Pull request by theokoester**
The default branch is normally called master, not main.

With "main" there is an error:
_error: src refspec main does not match any_

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by FloorD** [comment]
@tvachkov the change to `main` is a deliberate one: https://github.com/github/renaming, and https://www.bbc.com/news/technology-53050955 👍

**Comment by mitsuhiko** [comment]
It would be better to name the branch explicitly on init considering the default branch name can be reconfigured.

**Comment by tvachkov** [comment]
I agree on that - _main_ is deliberated. But since the guide advices to call `git init` with no parameter for `--initial-branch=<branch-name>` resp. `-b <branch-name>'` this falls back to the default name: _master_.

Then one gets the _error: src refspec main does not match any_.

**Comment by mitsuhiko** [comment]
@tvachkov i think the right fix would be to change the init call to `git init -b main`. Github itself is changing the default branch name to `main` at the moment and git is making the default branch name reconfigurable. Considering that can cause confusion and a bad user experience, i think it's better to be explicit here on branch creation.

Also it's pretty evident that `main` is the preferred branch name now.

**Comment by janiceilene** [comment]
@tvachkov Thanks for opening a PR and thanks everyone else for the thoughtful conversation about the right wording in this article! I'll triage this for review 💖

**Review by megbird — APPROVED** [review]
Thank you for picking up what we missed ⚡

**Review by megbird — DISMISSED** [review]
Leaving another review because I had the diff backwards. As pointed out, the change from `master` to `main` was deliberate. We cannot merge any mentions of `master` in our content. See https://github.com/github/renaming for more information. 

The right solution for this would be to use `git init -b main` when a user first initializes a repo. We can publish that change in this PR or you can open a new PR for that change.

**Comment by infin8x** [comment]
Agree with @megbird that `git init -b main` is the right change to make here - thanks!

**Comment by janiceilene** [comment]
@tvachkov Would you like to make the changes @megbird layed out in her comment https://github.com/github/docs/pull/408#pullrequestreview-508798275? Thanks so much for taking the time to help us make these changes 💖

**Review by janiceilene — APPROVED** [review]
Thanks so much for making these updates @tvachkov! I'll get this branch updated and merge it once the tests are passing 🍏

**Pull request merged**
