### PR TITLE
Clarify that Dependabot does not support Maven as token-only

### PR DESCRIPTION
**Pull request by brrygrdn**
### Why:

A user received a configuration error when attempting to create a Dependabot configuration with a Maven Repository that used only a token for authentication as suggested by the current documentation.

### What's being changed:

On further investigation, we do not actually support Tokens for Maven Repositories at this time as token-only authentication is specific to GitHub Package Registry and unsupported by common Maven Repository specifications.

Since adding support for token-only access to GPR is a feature request we don't plan to solve immediately, let's update the documentation to reflect the current implementation.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by androideveloper — DISMISSED** [review]
Looks good! Thanks for the clarification!

**Comment by ramyaparimi** [comment]
@brrygrdn Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — COMMENTED** [review]
Thank you for this correction! Does the example under [this section](https://docs-9098--brrygrdnupdat-depen.herokuapp.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#registries) (line 498-501) need to change as well?

**Comment by brrygrdn** [comment]
Thanks for spotting that @skedwards88! I've made an update to fix that example as well.

**Review by skedwards88 — APPROVED** [review]
LGTM! I'll get this merged down.

**Review by L2021 — APPROVED** [review]
It's good

**Pull request merged**
