### PR TITLE
Update working-with-the-apache-maven-registry.md

### PR DESCRIPTION
**Pull request by Sukanya004Sinha**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Sukanya004Sinha** [comment]
Added mvn clean install

**Comment by faragwasan** [comment]
@faragwasan1

**Review by IcebergVerse — COMMENTED** [review]
sukanya004sinha:patch-1

**Review by IcebergVerse — COMMENTED** [review]
sukanya004sinha:patch-1

**Comment by cmwilson21** [comment]
@Sukanya004Sinha Thanks for submitting a PR! ⚡ 

I checked it over with the team and in order to remain consistent with other package installations, we are not going to merge this PR. 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Comment by Sufiyan74** [comment]
3

**Pull request closed without merging**
