### PR TITLE
Add instructions to download usage report for Codespaces

### LINKED ISSUE #13723: Missing detailed usage report on Codespaces billing docs
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/billing/managing-billing-for-github-codespaces/viewing-your-codespaces-usage

### What part(s) of the article would you like to see updated?

Adding an additional step to export the data.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 2percentsilk**
### Why: 
Users have been confused on how to get more fine-grained information on their codespaces usage (see https://github.com/github/feedback/discussions/9611 as an example). The Export Data button is often overlooked and isn't currently surfaced in our docs.

Closes https://github.com/github/docs/issues/13723

### What's being changed:

In the Usage docs for Codespaces, we added a step at the end of the procedural on how to download a CSV of your usage data for an organization.
It follows the same pattern as the Actions Billing docs.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@2percentsilk 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by hubwriter — APPROVED** [review]
All good. 👍 
I'll get this merged/published. 
🚀

**Review by Mondjoe — COMMENTED** [review]
done

**Comment by Blend1221** [comment]
Great job

**Comment by shirafkanomid73-blip** [comment]
UQARCjif3RrNmbJhi-BaCroho58Ly3Ne2evAToHpXw8mtKjf

**Comment by shirafkanomid73-blip** [comment]
UQCHTHBfC9LhkTD2OdvVTKXZWWCSXagqa_jSAPVLa4IG5-DF

**Pull request merged**
