### PR TITLE
Update SSH key capitalization

### LINKED ISSUE #9609: Inconsistent capitalization for "SSH key" in describing how to generate a new key
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Generating a new SSH key](https://github.com/github/docs/blob/main/content/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md)

### What part(s) of the article would you like to see updated?

There is only one instance of the lowercase usage of "ssh key" where the rest of the document uses a capitalized "SSH" when referring to "SSH key".

Specifically, occurs in the line:
> This creates a new ssh key, using the provided email as a label.

### Additional information

Inconstancy is relatively minor and shouldn't confuse anyone reading the documentation. But it's good for the documentation to be consistent throughout.

### PR DESCRIPTION
**Pull request by MrGeislinger**
### Why: Inconsistent capitalization for "SSH key"

Closes [#9609](https://github.com/github/docs/issues/9609)

### What's being changed:

Changing the line [Generating a new SSH key](https://github.com/github/docs/blob/main/content/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md):
`This creates a new ssh key, using the provided email as a label.` to `This creates a new SSH key, using the provided email as a label.`

Specifically changes `ssh key` to `SSH key` to match capitalization in the rest of the documentation.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by MrGeislinger** [comment]
Oops, accidentally closed this but it should still be open 😅

**Review by ramyaparimi — APPROVED** [review]
@MrGeislinger 
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by ramyaparimi** [comment]
@MrGeislinger 
Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by MrGeislinger** [comment]
> @MrGeislinger
> Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks @ramyaparimi for taking a look! It looks like I already had that checkbox checked for this PR (See screenshot). But I went ahead and unchecked then re-checked it. Hopefully that means you now have access to edits.

enable_maintainer_edits

**Comment by ramyaparimi** [comment]
@MrGeislinger Unchecking and checking it again for sure worked!! ✨

**Pull request merged**
