### PR TITLE
Update allowing-your-codespace-to-access-a-private-image-registry.md

### PR DESCRIPTION
**Pull request by joshspicer**
### Why:

Some minor nits I noticed.

### What's being changed:

Confusing lowercase characters (perhaps i'm missing the reason why this is lowercase), and a reference to "devcontainer" that I think is more suited to be "image"

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by joshspicer** [comment]
cc/ @2percentsilk

**Review by 2percentsilk — APPROVED** [review]
Thanks for the catch on these @joshspicer ! Edits look good to me 👍

**Comment by ramyaparimi** [comment]
@joshspicer 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by lecoursen — APPROVED** [review]
Thanks! I'll merge now. ⚡

**Pull request merged**
