### PR TITLE
Update merging-a-pull-request.md and fix #26546

### LINKED ISSUE #26546: Content in Merging PRs is incorrect
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request.md

### What part(s) of the article would you like to see updated?

In the section "About pull request merges", content says:

> Pull requests are merged using [the --no-ff option](https://git-scm.com/docs/git-merge#_fast_forward_merge), except for [pull requests with squashed or rebased commits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges), which are merged using the fast-forward option.

However, as [about-pull-request-merges](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges) says, and as issue #1387 and PR #11373 mentioned, PRs with rebased commits are NOT merged with fast-forward. The content aforementioned should be:

Pull requests are merged using [the --no-ff option](https://git-scm.com/docs/git-merge#_fast_forward_merge), except for [pull requests with squashed commits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges), which are merged using the fast-forward option.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Winson-Huang**
### Why:

Closes: #26546

### What's being changed (if available, include any code snippets, screenshots, or gifs):

https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request.md

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Winson-Huang Thank you for opening a PR and linking it to your issue! We appreciate all the extra context provided in the issue ✨ 

And welcome to the community! I'll get this triaged for review! :zap:

In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 👍

**Comment by Winson-Huang** [comment]
Thanks for your response, I'd like someone to review this PR

**Comment by sophietheking** [comment]
Hi @Winson-Huang 👋 Thanks for creating a PR and contributing to our docs, we really appreciate it! ✨ However, after careful consideration, we've found that your suggested change is not needed at the moment because the docs are accurate.

In the issue you raised, you mentioned:

> However, as [about-pull-request-merges](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges) says, and as issue https://github.com/github/docs/issues/1387 and PR https://github.com/github/docs/pull/11373 mentioned, PRs with rebased commits are NOT merged with fast-forward.

While we value your input, we must clarify that our existing documentation covers this scenario. The "[Rebase and merge your commits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits)" section says:

> When you select the Rebase and merge option on a pull request on [GitHub.com](http://github.com/), all commits from the topic branch (or head branch) are added onto the base branch individually **without a merge commit**. In that way, the rebase and merge behavior **resembles a fast-forward merge**

Since we have the information correctly represented, we have decided to close this PR. Nevertheless, we really appreciate you contributing to the community, and we encourage you to continue contributing in the future! 💖 Keep up the fantastic work! 🌟

**Comment by Winson-Huang** [comment]
Please see my response in initial [issue#26546](https://github.com/github/docs/issues/26546#issuecomment-1651134860), and consider reopen this PR if needed, thanks.

**Pull request closed without merging**
