### PR TITLE
Update configuring-dns-nameservers.md

### PR DESCRIPTION
**Pull request by timchepeleff**
### Why:

Closes the following enterprise support ticket: https://support.github.com/ticket/personal/0/1244355

### What's being changed:

Adding a note to additionally restart `dnsmasq` after adding custom nameservers to ensure no cached entries cause unexpected behavior.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ramyaparimi** [comment]
@timchepeleff Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mmm0171 — APPROVED** [review]
0xc4bef2ebdb7c7f72beb34db9950dcd16fef4d98f

**Review by mmm0171 — APPROVED** [review]
0xc4bef2ebdb7c7f72beb34db9950dcd16fef4d98f

**Review by lecoursen — APPROVED** [review]
Thanks so much for this! I'll merge now. ⚡

**Pull request merged**
