### PR TITLE
chore: Filter CI job for dependabot auto-merge

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

This job currently fires on all Pull Requests, and not just those that may be submitted by Dependabot

### What's being changed:

Filter the paths on the job to those files that Dependabot might touch in the future if the Dependabot config yaml is added to this repo.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks @nschonni! I'll get this triaged for review 🌟

**Comment by chiedo** [comment]
@JamesMGreene can you dig in to this one?

**Review by heiskr — APPROVED** [review]
Makes sense to me. Doesn't entirely avoid running the job as there's other PRs that touch those files, but yeah I'd be surprised if Dependabot went any further than this.

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by saintcriminal** [comment]
ophs!...

**Pull request merged**
