### PR TITLE
Fix GITHUB.SHA and GITHUB.REF for repository_dispatch

### LINKED ISSUE #1494: "repository_dispatch" event shows wrong GITHUB.SHA and GITHUB.REF information
### What article on docs.github.com is affected?
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch

### What part(s) of the article would you like to see updated?
The `GITHUB_SHA` and `GITHUB_REF` values seem to be wrong. As far as I can tell, there's no way to set a branch when triggering this event from the REST API. This presumption is also confirmed by the fact that the event has the following note:
```
Note: This event will only trigger a workflow run if the workflow file is on the default branch.
```
These values should both refer to the default branch. An example of what it should say:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#check_run

### Additional information
I believe this was a copy-paste error from the `workflow_dispatch` event.

### PR DESCRIPTION
**Pull request by ba32107**
### Why:

Fixes https://github.com/github/docs/issues/1494

### What's being changed:
I've changed the `GITHUB.SHA` and `GITHUB.REF` values to refer to the default branch. 

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@ba32107 Thanks so much for opening a PR! I'll get this triaged for review 💖

**Comment by ba32107** [comment]
Hi @janiceilene, just commenting so the PR doesn't go stale. Any chance this could be reviewed? Thanks.

**Comment by janiceilene** [comment]
@ba32107 Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by ba32107** [comment]
Bump

**Review by lucascosti — APPROVED** [review]
Thanks for this fix, @ba32107! Yep, I believe you are right, I'll get this merged! 🚀

**Pull request merged**
