### PR TITLE
Updated UI elements in the docs page

### LINKED ISSUE #20426: Update the UI elements in images to match the current elements
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

https://github.com/github/docs/blob/main/content/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews.md

### What part(s) of the article would you like to see updated?

All images/screenshots

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by codewithdev**
### Why:

Closes #20426 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updated the screenshots and placeholder images in the https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews page.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by steveward — APPROVED** [review]
Thanks for the PR @codewithdev! I took a look and these screenshots look great! I'll go ahead and get this merged.

**Review by VerisimilitudeX — COMMENTED** [review]
Looks great! Thanks for fixing the issue that I submitted earlier.

**Review by Nuttapon-Makchoos — COMMENTED** [review]
I’m

**Comment by cmwilson21** [comment]
Thanks so much for taking the time to submit this PR. :sparkles: We have a few issues that could use some extra help this [Hacktoberfest](https://github.blog/2022-10-04-expand-your-open-source-contributions-during-hacktoberfest-2022/). If you’re up for working on another help wanted issue, look for the [pumpkin-spice](https://github.com/github/docs/labels/pumpkin-spice) label.

**Pull request merged**
