### PR TITLE
Update configuring-dependency-review.md

### PR DESCRIPTION
**Pull request by jlahtinen**
Use correct indentation inside with key for fail-on-severity.

### Why:

Example yaml was incorrectly formatted.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

from 
image
to 
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by NATANASSEFA** [comment]
> Use correct indentation inside with key for fail-on-severity.
> 
> 
> 
> ### Why:
> 
> Closes: 
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> 
> 
> ### Check off the following:
> 
> - [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.
> 
>   - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> - [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 

natanassefa.00@gmail.com

**Comment by jlahtinen** [comment]
@cmwilson21 now ready (checks passed after rebase)

**Review by SiaraMist — APPROVED** [review]
Thanks for fixing this, @jlahtinen! Our repository is currently frozen for the rest of the week, but I'll add the `Merge after freeze` label to this so we can get your fix merged as soon as we can. 👍

**Comment by Trulytrue25** [comment]
Hello
  

  

  

  
  
  
  
  
>

**Pull request merged**
