### PR TITLE
Alternative TOTP Authenticator App (for all Apple Ecosystem devices)

### PR DESCRIPTION
**Pull request by 40504**
Alternative TOTP Authenticator App

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@40504 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Nhida2002** [comment]
Ok


Vào 23:30, Th 2, 24 thg 10, 2022 Courtney Wilson ***@***.***>
đã viết:

**Comment by Nhida2002** [comment]
Ok



Vào 2:24, CN, 23 thg 10, 2022 github-actions[bot] ***@***.***>
đã viết:

**Comment by Nhida2002** [comment]
Ok


Vào 8:16, Th 3, 25 thg 10, 2022 github-actions[bot] <
***@***.***> đã viết:

**Comment by cmwilson21** [comment]
@40504 Thanks for opening a PR! I've checked with the team, and we've decided not to accept this change. 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Pull request closed without merging**
