### PR TITLE
Sync favicons with github.com

### PR DESCRIPTION
**Pull request by RDIL**
Signed-off-by: Reece Dunham <me@rdil.rocks>

### Why:

- The favicons on github.com and docs.github.com are currently clearly different (see screenshot)

Screenshot 2021-01-05 at 20 22 04

### What's being changed:

I synced the files to the exact ones used by GitHub (well, at least for the favicon - I had to recreate the PNG with a website, so if there is an alternative file you want me to use please let me know.)

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by jbaez1994 — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by jbaez1994 — CHANGES_REQUESTED** [review]
No don't approve

**Comment by chiedo** [comment]
@simpsoka this ones for you!

**Review by jbaez1994 — COMMENTED** [review]
Ok

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by RDIL** [comment]
No worries.

**Comment by JamesMGreene** [comment]
Thank you for the submission! Unfortunately, we are actually going to pass on this one for now pending a recommendation from our internal Design team. 🙇🏻‍♂️

**Pull request closed without merging**
