### PR TITLE
Remove note about package immutability

### PR DESCRIPTION
**Pull request by jcansdale**
### Why:

The following section isn't true.

> **Public packages**: To prevent confusion and build problems, GitHub permanently reserves a package's name and version number. Even if an entire package is deleted, you cannot reuse the deleted package name in any repository owned by the same account.
>
> **Private packages**: If all versions of a private package are deleted, you can publish a package with a previously used name and version.
>
> To revise or replace a package version, we recommend you publish a new version of your package.

We don't reserve the namespace for public packages. Users can delete/move the associated repository or make the repository private and delete individual package versions. The namespace isn't reserved and would cause problems if it was.

I've removed this section to reflect the current behaviour.

### What's being changed:

Removed `package-immutability` section quoted above.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR @jcansdale! I'll get this triaged for writer review.

**Review by lucascosti — COMMENTED** [review]
Thanks for this change, @jcansdale!

That reusable is used in a few other articles too:

* https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/deleting-a-container-image#reserved-package-versions-and-names [[source](https://github.com/github/docs/blame/package-immutability/content/packages/managing-container-images-with-github-container-registry/deleting-a-container-image.md#L21-L23)]
* https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#reserved-package-versions-and-names [[source](https://github.com/github/docs/blame/package-immutability/content/packages/publishing-and-managing-packages/deleting-a-package.md#L38-L40)]

I assume it's incorrect for those too? If so we should remove ☝️ references, and also delete [the reusable file](https://github.com/github/docs/blob/package-immutability/data/reusables/package_registry/package-immutability.md).

**Comment by jcansdale** [comment]
@lucascosti,

Sorry I missed your reply. 😊 

> I assume it's incorrect for those too? If so we should remove ☝️ references, and also delete the reusable file.

Yes, there are incorrect as well.

**Comment by lucascosti** [comment]
Cool, I'll make the changes and get it merged 🚀

**Review by lucascosti — APPROVED** [review]
Looks good to merge when the tests pass ✅

**Pull request merged**
