### PR TITLE
Fix job name in example code

### PR DESCRIPTION
**Pull request by Mtze**
### Why:

The job name in the example does not reflect the content of the job

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Mtze Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — DISMISSED** [review]
Thanks for this fix! We'll get this merged down for you.

**Review by janiceilene — DISMISSED** [review]

**Comment by cmwilson21** [comment]
👋 @Mtze - So sorry, there was a merge conflict, and in resolving this, we accidentally deleted your commit. We tried to put it back, but do not have permission. Could you re-commit your changes? 🙈

**Comment by Mtze** [comment]
I added the change again :)

**Comment by cmwilson21** [comment]
@Mtze Thank you! We'll get this merged down once all the tests have passed. 🍏

**Review by cmwilson21 — APPROVED** [review]
Looks great to me! ✨

**Pull request merged**
