### PR TITLE
Git Authentication issue, potential resolution

### PR DESCRIPTION
**Pull request by thompkin**
The command I've listed resolved the connection issue for me with github.

### Why:

I was getting the error listed in the doc:
  > The authenticity of host '{% data variables.command_line.codeblock %} (IP ADDRESS)' can't be established.
  > RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
  > Are you sure you want to continue connecting (yes/no)?

But there was nothing that spoke about what to do in the event you saw this.

### What's being changed:

I found on google the command in the change so added the information to the documentation in case future people would find it useful.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@thompkin Thanks for opening a PR! Can you please fill out the **What's being changed** and **Why** sections of the pull request template in the top comment? Let me know when that's done and I'll get this triaged for review 💖

**Comment by thompkin** [comment]
I have updated the comments of the commit with more details as requested.

**Comment by janiceilene** [comment]
@thompkin Thank you so much! I'll get this triaged for review ⚡ 

Just a heads up, the team is out for the next two weeks, so we'll be very slow to respond 💛

**Comment by stevecat** [comment]
Hey @thompkin, thanks for opening this!

>> The authenticity of host '{% data variables.command_line.codeblock %} (IP ADDRESS)' can't be established.
>> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
>> Are you sure you want to continue connecting (yes/no)?
> 
> But there was nothing that spoke about what to do in the event you saw this.

The third step in the article you're updating does explain what to do when prompted with this confirmation message:

>Verify that the fingerprint in the message you see matches GitHub's RSA public key fingerprint. If it does, then type yes

If you type "yes" in response to the prompt, that will save the host to your `~/.ssh/known_hosts` file and you won't be prompted again.

We suggest that you compare the fingerprint with [our publicly documented SSH fingerprints](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints) to verify that you are connecting to a GitHub.com server and not falling victim to a [MitM attack](https://en.wikipedia.org/wiki/Man-in-the-middle_attack).

`ssh-keyscan github.com >> ~/.ssh/known_hosts` does the same as typing "yes" to the prompt but it removes the possibility of first verifying the server. For that reason, I worry it's dangerous for us to recommend it, especially when typing "yes" *should* be enough to proceed.

If I've misunderstood, and you've found yourself repeatedly typing "yes" each time you connect on the same machine, then it sounds like an issue with your config. You might want to reach out on our [community forums](https://github.community/) to see if anyone has any suggestions!

I'm going to close this now but I hope I've explained clearly why I'm doing so! ✨  Thanks again for spending time on this and contributing to our documentation.

**Pull request closed without merging**
