### PR TITLE
Add new required(ish) "parser" parameter to markdownlint custom rule examples in Content Linter README.md.

### PR DESCRIPTION
**Pull request by DavidAnson**
### Why:

`parser` is a new required (tho it's okay if it's not present for now) property on `markdownlint` custom rules. This PR adds it to the two relevant examples.

Closes: 

N/A

### What's being changed (if available, include any code snippets, screenshots, or gifs):

README

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@DavidAnson Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by gracepark** [comment]
Hi @DavidAnson thanks for reaching out and for the contribution! I did notice it recently when I was looking at updating one of our custom rules. I'll make sure to update them all and get this added. Thanks again!

**Review by gracepark — APPROVED** [review]

**Comment by DavidAnson** [comment]
FYI @gracepark if you are a rule maintainer, this new property does nothing at the moment, but I intend to use it soon to avoid loading the markdown-it parser once I have migrated all the core rules to micromark. Of course, if there are rules that need markdown-it tokens, it will be used and the tokens will still be available. From what I saw, GitHub rules take advantage of it, so there may not be a performance benefit for you folks. micromark is not yet available for public use, but that is also planned. Finally, note that if a rule doesn't use tokens at all, it can declare that.

**Comment by gracepark** [comment]
@DavidAnson - yes I'm apart of the team that maintains the rules. I'll let the others know as well. Thanks for the heads up.

**Pull request merged**
