### PR TITLE
Updated localization-checklist.md

### PR DESCRIPTION
**Pull request by Shivam7-1**
### What's being changed:
Updated with punchuation in localization-checklist.md

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1  for doc

**Review by janiceilene — APPROVED** [review]
Thanks @Shivam7-1! I'll update the branch and get this merged once tests are 🍏 I'm still working on the trouble with allcontributors, but I'll get you added as soon as it's fixed ✨

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 for doc

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1  for doc

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 for doc

**Comment by Shivam7-1** [comment]
I am unable to add me as a contributor can anyone add me as contributor

**Comment by janiceilene** [comment]
@Shivam7-1 Sorry for the frustration! We had to remove all contributors because our small team wasn't able to keep up with the influx of contributions 💛 More details are available in https://github.com/github/docs/pull/576.

**Pull request merged**
