### PR TITLE
Fixing non-working codesnippet.

### PR DESCRIPTION
**Pull request by jonatan-holmgren**
alert() does not exist in node.js. We can use console.log() instead.

### Why:

The codeblock shows a command not usable by default in Node.JS, only usable in the browser, yet the article is in a Node.JS context.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Changing the command.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Jontes-Tech Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Jontes-Tech** [comment]
Did I do anything wrong? Some checks failed...

**Comment by cmwilson21** [comment]
We have temporarily frozen our repo. 🧊 

The failed checks should pass once we lift the freeze. Your PR is on the board for review, so no additional action on your side is needed at this moment. Thanks for checking in on this! 💛

**Review by skedwards88 — APPROVED** [review]
Thanks for this fix! We'll get this merged down for you.

**Comment by Jontes-Tech** [comment]
Thank you guys so much for merging.

**Pull request merged**
