### PR TITLE
Added filter out documentation using `-`

### PR DESCRIPTION
**Pull request by Julian88Tex**
### Why:

- Fix issue: #1249

### What's being changed:

- Add one line mentioning search term filter out modifier `-`

### Contribution

- Idea for this method of filtering was provided by @davisagli

### CODE REVIEW

**Comment by janiceilene** [comment]
@Julian88Tex Thanks so much for opening a PR! I'll get this triaged for review 🌟

**Comment by janiceilene** [comment]
This is not stale! Thanks for your patience @Julian88Tex as our small team works through all of the amazing contributions 🌟

**Comment by Julian88Tex** [comment]
@janiceilene thanks for keeping it alive!

**Review by lecoursen — APPROVED** [review]
Thanks @Julian88Tex! I'll merge this now.

**Pull request merged**
