### PR TITLE
[SEO] Redirect "Contact GitHub" footer link to Support site

### PR DESCRIPTION
**Pull request by skullface**
This PR updates the redirect in place for "Contact GitHub" to minimize end-user redirects to have a positive impact on SEO.

### Why:

https://github.com/github/SEO/issues/64

### What's being changed:

- Old: `https://support.github.com/contact`
- New: `https://support.github.com`

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — COMMENTED** [review]
Hi there, thanks for the PR, as the bot mentioned earlier the `lib/redirects/*` can not be modified by any PR, so AFAIK sadly no one can accept this change to the code base. Unless the core team change this by themselves.

**Comment by skullface** [comment]
Thanks @SMicheal + @SMAKSS! I’ll notify the core team ^—^

**Comment by janiceilene** [comment]
Thanks for opening a PR @skullface! This was discussed in Slack and can be merged in once the engineering team takes a look and gives approval 💖

**Review by heiskr — APPROVED** [review]
👍🏼 Seems fine to me.

**Pull request merged**
