### PR TITLE
Add Discussions to list of supported products for saved replies

### LINKED ISSUE #21202: Discussions should be indicated in save replies about doc
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/working-with-saved-replies/about-saved-replies

### What part(s) of the article would you like to see updated?

The following (emphasized for better indication) is not correct:

> Once you've added a saved reply, it can be used in **both issues and pull requests**.

It can be also used on Discussions. The picture below shows how this is incorrect.

Picture that shows that there is a saved replies button which shows saved replies

So, this should be changed to this:

> Once you've added a saved reply, it can be used in issues, pull requests, and discussions.

### Additional information

#21203 fixes this.

### PR DESCRIPTION
**Pull request by ghost**
### Why:

Closes #21202

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Changes this:

> Once you've added a saved reply, it can be used in both issues and pull requests.

to this:

> Once you've added a saved reply, it can be used in issues, pull requests, and discussions.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Alotibi11** [comment]
و

**Comment by Alotibi11** [comment]
- [ ] و

**Review by SiaraMist — APPROVED** [review]
@softcode589 thank you so much for spotting this and opening a PR to fix it! ✨ 

Your updates look great to me! I'll go ahead and get this merged. 🚀

**Review by farzaneh53 — COMMENTED** [review]
gh pr checkout 21203

**Pull request merged**
