### PR TITLE
absent command (ssh)

### LINKED ISSUE #6642: SSH (backticks and absent command)
### What article on docs.github.com is affected?

[Generating a new SSH key and adding it to the ssh-agent
](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md

### What part(s) of the article would you like to see updated?

_Reduce the amount of provided OS specific information in the file._

Mac and Linux
```
$ eval "$(ssh-agent -s)"
> Agent pid 59566
```
Windows (uses backticks)  

_The command could be the same as on the above OSes._
```
# start the ssh-agent in the background
$ eval `ssh-agent -s`
> Agent pid 59566
```
[Adding your SSH key to the ssh-agent](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent)

_For Linux and Windows another line could be added accessing a new kill_ssh_agent.md file._

`4. {% data reusables.command_line.kill_ssh_agent %}`

kill_ssh_agent.md (proposed)

``````
Kill the current agent (given by the SSH_AGENT_PID environment variable).
```shell
$ eval "$(ssh-agent -k)"
> Agent pid 59566 killed
```
``````

Here's the sole reference to killing the agent PID.

```
$ grep -nr ssh-agent content | grep kill
content/github/authenticating-to-github/connecting-to-github-with-ssh/working-with-ssh-key-passphrases.md:84:The `ssh-agent` process will continue to run until you log out, shut down your computer, or kill the process.
$ 
```

_Perhaps the OS specific content regarding keychain could be hosted by the vendor and linked to._

<hr>

["Working with SSH key passphrases"](https://docs.github.com/en/articles/working-with-ssh-key-passphrases)

working-with-ssh-key-passphrases.md

[Mac version of the page]
Saving your passphrase in the keychain

_This content is perhaps dated._

[Windows version of the page]
Auto-launching `ssh-agent` on Git for Windows

_Perhaps this content could be shifted to a Wiki page._

### Additional information

If GitHub Inc. wants to hire me to review the entire repository send me an e-mail.

### PR DESCRIPTION
**Pull request by ghost**
### Why:

On Windows and Linux closes the socket (/tmp/ssh-XXXXXXXXXXXX/agent.59566) and unsets the shell variables (SSH_AGENT_PID and SSH_AUTH_SOCK), Mac is not addressed herein as the current recommendation is to use keychain.

https://github.com/github/docs/issues/6642

### What's being changed:

kill_ssh_agent.md (new file)
generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md (modified for Windows and Linux)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@fluesvamp Thanks for opening another PR for the additional fix! I'll get this triaged for review ✨

**Comment by lecoursen** [comment]
Reviewer, please answer this question in your review! 🙏🏻 

>Is it sufficiently unambiguous (with the changes) that one leaves the process running until one no longer needs it?

https://github.com/github/docs/issues/6642#issuecomment-853234245

**Comment by fluesvamp** [comment]
> Reviewer, please answer this question in your review! 🙏🏻

Otherwise this line could be added (for Windows and Linux).

The socket should get automatically removed when the agent exits.

**Comment by fluesvamp** [comment]
This PR is to emphasise to the reader to not leave an unneeded process running.

**Comment by janiceilene** [comment]
Thanks so much for opening a PR @fluesvamp! Since we're asking folks to use the ssh-agent, we're not going to add a command to kill it to the procedural. This update would likely cause additional confusion for the majority of our users.

Thanks so much for your interest and passion in the GitHub docs!

**Comment by fluesvamp** [comment]
A {% note %} for the end of the Windows and Linux [subsection](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent).

**Note:** The `ssh-agent` will continue to run until you kill the process.

**Pull request closed without merging**
