### PR TITLE
fix dropdown on mobile

### PR DESCRIPTION
**Pull request by Arhell**
### Why:
fix issue https://github.com/github/docs/issues/1722

### What's being changed:

Content won't jump

### CODE REVIEW

**Comment by Arhell** [comment]
cc @chiedo

**Comment by chiedo** [comment]
@Arhell can you explain the issue you're describing one more time? I'm not sure I understand. Also can you include before and after screenshots (maybe animated gifs if that will help)? Thanks!

**Comment by Arhell** [comment]
@chiedo 
Of course, when on mobile you click the dropdown then the content jumps
normal state

Before

content jumped down
after fix

the content is in place and the dropdown works correctly as it does in large resolutions without interfering with the content

**Comment by chiedo** [comment]
Thank you! That makes perfect sense. Thanks for the fix!

**Review by chiedo — APPROVED** [review]

**Pull request merged**
