### PR TITLE
Update about-pull-requests.md

### PR DESCRIPTION
**Pull request by nima0011**
### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).Skip to the content
Errietta's blog ☕
My thoughts on software engineering
Menu
Why I love contributing to open source software
erriettaOctober 5, 20147 Commentson Why I love contributing to open source software
I’m a generally quiet person, but if you ask me about open source projects, I’ll go on about them forever (I even had someone interview me about it). So, I thought I should finally get all of my honest thoughts down on my own blog as well!

freenode (or the biggest reason why I got into open source)
freenode is an IRC network dedicated to open source and peer-directed project development. It enables open source project developers to get together and discuss their work, and also provide support to their users.

I started supporting users in #freenode because I was bored in summer 2011 (literally because I was bored), then I realised I quite enjoyed it, so I just kept doing it (to the expense of my high school studies… it will be a cold day down below before I mention high school on this blog again.) Anyway, I was eventually offered to become staff, which I accepted, and I’ve been staff ever since. I’m not sure why anyone would enjoy to spend countless hours just supporting freenode users with any questions they have without expecting anything in return, but I loved it then and I love it now! I think freenode is awesome, because it helps bring many open source projects, companies and non-profits together with their users and assist in collaboration.

My role as a staff member involves helping representatives of on-topic projects manage their community on freenode, and helping other users with finding their way around and using the network.

I’m also involved with working on developing their group management system, which when deployed will help make project affiliation with freenode a lot easier. Groups will just be able to give us some information and perform verification on a website which will track requests, rather than having to manually do this with a staff member. They will also be able to take over channels for their users and perform other currently manual tasks through the portal.

Working on it helped me a lot, because I earned many of the skills I later used for my studies in University and my actual job. That’s another thing about me, I think working on open source projects ultimately helps me as much as it helps the project, at least most of the time!

Mozilla, webmaker, etc.
I also contribute to Mozilla’s projects. I fixed a few bugs for Firefox and Firefox for Mobile at first, but then I discovered webmaker, mostly thanks to social coding for good which pointed me to that project. Webmaker was easier and nicer for me to contribute to, because it used technologies I like and use, so it “stuck”. I also love Webmaker because of its goal – to provide web literacy all over the world! I think it’s extremely important because there are so many Internet users, and many of them would have their lives greatly improve if they could use the web to make ideas from their imagination come true and to express themselves. As with past open source projects, it helped me learn more about angularjs shortly before I started an angular project at work, so it was also helpful to me!

As a code contributor for webmaker, I look for bugs or feature requests filed by Mozilla employees and other contributors and resolve some of them.

I also have the unique opportunity to attend weekly demos, seeing what everyone else in the project has been up to, and even presenting my own work! This is really awesome for me because I get the opportunity to see amazing technologies in use and learn about how they were used.

Eventually I even started reviewing bugs for other contributors and Mozilla employees and mentoring bugs for new contributors, helping people get started on the project, which is also extremely rewarding and I’m really glad I get to do!

In general, I really love open source software. I think they always help people one way or another – after all, just by publishing your code so that everyone can see it you enable them to get ideas and learn (and in return you may get contributors from people who want to see their enhancements in your project!). I like contributing to certain open source projects, because they’re projects I use and/or care about, because it improves my skills, because I want a feature implemented or bug fixed so I fix it myself, because the community is awesome, and because I like being a small part of something big and awesome! I think it’s a good use of my time and knowledge, both for my own development and the community. Because of this, I plan to keep contributing for years to come!

 Posted In Open source
7 Comments
gopi
December 8, 2015 at 19:40
Thanks for sharing !! 🙂 Hope to get your guidance in case of doubts.

Reply
Melissa
May 20, 2020 at 03:20
Yes

Reply
Ivan
May 5, 2017 at 07:27
Thank you for being real! 😉

Reply
Dread Knight
October 3, 2017 at 11:23
Nice article, great to see another open source lover and to find out about Code Alliance, I’ll give it a try as I’m building a NPO that’s all about making free open source games (web based essentially) and promoting open source software, so I could use some volunteers to help out with code and such. I hope it will work out and that my NPO will become a partner later down the road. Thanks and keep up the good work, open source FTW! <3

Reply
mfct
August 13, 2018 at 05:47
Sir, please help me develop the project together.

Reply
Mahdi
June 24, 2019 at 01:49
Win&win

Reply
Tomtam
May 31, 2020 at 20:34
I am currently working on the same but I will be able to make it to the end of the course as soon as possible.

Reply
Leave a Reply
Your email address will not be published. Required fields are marked *

Comment

Name *
Email *
Website

 Save my name, email, and website in this browser for the next time I comment.

This site uses Akismet to reduce spam. Learn how your comment data is processed.

Search for:
Search …
Recent Posts
Python argparse cheat sheet
Documenting a Django API with OpenAPI and Dataclasses
13 ways the Internet is broken
New WP install for this site
Making Jenkins Behave 2: Electric Boogaloo
Meta
Log in
Entries feed
Comments feed
WordPress.org
Categories
android
angularjs
AWS
Browsers
chrome
CI
Cordova
CSS
debugging
es6
General software engineering
HTML
IRC
java
JavaScript
jenkins
Linux
localisation
nodejs
Open source
perl
PHP
Python
Raspberry pi
Scratch
STEMnet
Typescript
web development
Copyright © 2020. Errietta's blog ☕
Powered By WordPress and Individuality

### CODE REVIEW

**Review by Rafal050691 — APPROVED** [review]

**Review by Rafal050691 — APPROVED** [review]

**Comment by stevenans9859** [comment]
Wait wait... What happens... I am not really good with the repo access
definition, just was try only, what have I done

**Comment by stevenans9859** [comment]
Be right back OK, give me few minutes, just to let me. Some issues from a
third-party. Be back....

**Comment by stevenans9859** [comment]
Is it back to normal

**Review by stevenans9859 — APPROVED** [review]

**Review by stevenans9859 — APPROVED** [review]

**Review by SMAKSS — COMMENTED** [review]
This is just a spam. 😶

**Review by tashaemery — APPROVED** [review]

**Review by tashaemery — APPROVED** [review]

**Pull request closed without merging**
