### PR TITLE
indentation mistake

### PR DESCRIPTION
**Pull request by YSSVR**
commit-some.png is properly aligned after correcting indentation of stashed change section

### Why:Indentation mistake

**Closes [issue link]**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening a PR @YSSVR! When I look at your updates on [staging](https://docs-4773--patch-1.herokuapp.com/en/desktop/contributing-and-collaborating-using-github-desktop/committing-and-reviewing-changes-to-your-project) versus the [site](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/committing-and-reviewing-changes-to-your-project) the indentation looks the same. 

What change were you hoping to make? When I look at it, I think `stashed-changes.png` is indented correctly, but `commit-all.png` is wonky with one word from the bullet rendering after the image. It'll probably take some messing around with the markdown to make that fix, though.

**Review by lucascosti — APPROVED** [review]
Thanks for this, @YSSVR!

Yep the indentation was one problem, but there was also another in that the images weren't spaced out from their preceding paragraphs. It should look a lot better now. 👍 

I'll get this merged!

**Comment by 1SatoshiNakamoto** [comment]
Must indent.  LoL ty

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 1:53 AM, ***@***.***> wrote:   


Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our help wanted issues ⚡

**Comment by 1SatoshiNakamoto** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 1:55 AM, heidi ***@***.***> wrote:   
    Must indent.  LoL ty

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 1:53 AM, ***@***.***> wrote:   


Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our help wanted issues ⚡

**Pull request merged**
