### PR TITLE
Make two examples of `format(...)`consistent

### LINKED ISSUE #22991: Github Actions `format(...)` Expression Examples are Inconsistent
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#format

### What part(s) of the article would you like to see updated?

The two examples of how to use `${{ format(...) }}` are inconsistent, one is a simple inline code block while the other has full syntax highlighting. See screenshot.

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by norwd**
### Why:

The two [examples of how to use `${{ format(...) }}`](https://docs.github.com/en/actions/learn-github-actions/expressions#format) are inconsistent, one is a simple inline code block while the other has full syntax highlighting. See screenshot.

screenshot

Closes #22991

### What's being changed (if available, include any code snippets, screenshots, or gifs):

To make the two examples consistent with each other, I've duplicated the markdown around the second example around the first as well. This makes the example pop more visually and makes it clearer to the reader that the is an example, not an output or something else.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by norwd** [comment]
Looks fantastic in preview: 
image


Note: Have checked failing translation step, appears to be failing due to missing token (likely because I don't have the secret set up in my fork), this shouldn't be a problem since no translations should be affected, this is a formatting only change.

**Comment by cmwilson21** [comment]
@norwd Thank you for opening a PR and linking it to your issue! ✨ 

We appreciate the info and screenshots, too! I'll get this triaged for reivew ⚡

**Comment by Nassarjj1** [comment]
No ‫أُرسلت من الـ iPhone‬‫في ٠٥‏/٠١‏/٢٠٢٣ الساعة ٤:٢٦ م، كتب/كتبت ‏Courtney Wilson ***@***.***>:‬﻿
@norwd Thank you for opening a PR and linking it to your issue! ✨
We appreciate the info and screenshots, too! I'll get this triaged for reivew ⚡

**Review by cmwilson21 — APPROVED** [review]
Great catch. Thanks for submitting the PR! ⚡

**Comment by cmwilson21** [comment]
Thanks for the PR! I'll get this merged down once all the checks have passed ✅

**Pull request merged**
