### PR TITLE
Update restricting-repository-creation-in-your-organization.md

### PR DESCRIPTION
**Pull request by Aungphyothu86mmmm**
##

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Aungphyothu86mmmm** [comment]
@frankcasper

**Comment by Aungphyothu86mmmm** [comment]
perfact full

**Comment by Paulo1125** [comment]
My cel ok!

Enviado do meu iPhone

**Comment by Paulo1125** [comment]
Qual o andamento da minha Crypto FreeCoin? E como fica os lucros obtidos e  equestao da quantidade de moedas q terei?

Enviado do meu iPhone

**Pull request closed without merging**
