### PR TITLE
Move period inside ending quotation

### LINKED ISSUE #34222: Move period inside quotation marks in configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-app
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-app

### What part(s) of the article would you like to see updated?

> ...see "Configuring two-factor authentication using a security key" and "Configuring two-factor authentication using GitHub Mobile".

Move period inside ending quotation marks to align with our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SeanAverS**
### Why: Move period inside ending quotation to align with style guide 

Closes: #34222 

### What's being changed (if available, include any code snippets, screenshots, or gifs):
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by SeanAverS** [comment]
Hi @nguyenalex836,  

I noticed #34223 also uses the same tags for the  `...see "Configuring two-factor authentication using a security key" and "Configuring two-factor authentication using GitHub Mobile".` part.  Should I include that issue in this PR? if not then please let me know 👍

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@SeanAverS Thanks for opening a PR with this fix 👍 I'll update the branch and get this merged once tests are passing 🍏

**Comment by nguyenalex836** [comment]
@SeanAverS Hello! 👋 Great catch - feel free to include update this PR to account for https://github.com/github/docs/issues/34223 as well. Ping me whenever you are finished, and I'll get this merged 🍏

**Comment by nguyenalex836** [comment]
@SeanAverS Apologies - I added this PR to the merge queue and forgot to remove it 🤦 feel free to open a new PR for https://github.com/github/docs/issues/34223. Thank you! 💛

**Pull request merged**
