### PR TITLE
Fix Text

### LINKED ISSUE #25314: Update "Add theme to Pages site"
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
adding-a-theme-to-your-github-pages-site-using-jekyll.md

### What changes are you suggesting?

I tried to follow the guide step by step, so I chose a github pages deploy branch, it worked perfectly. The site was up and working as expected. 
When I tried to install a theme through adding `_config.yml` file and typed `theme: slate` I received the error: 
`github-pages 228 | Error:  The slate theme could not be found.`
Well, that's not right, so I tried to set up the source for pages from `GitHub Actions'.
Again, received same error:
```
Configuration file: /github/workspace/./_config.yml
             Theme: slate
github-pages 228 | Error:  The slate theme could not be found.
```
Since I obviously couldn't do what I wanted, I think you should update this page.

You can see the exact stacktrace by following this link - https://github.com/DRMPN/open-source-ops

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Sriparno08**
### Why:

This change will allow users to use the right command.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I have changed:

- `theme: THEME-NAME` to `theme: jekyll-theme-THEME-NAME`
- `theme: minima` to `theme: jekyll-theme-minima`

GitHub Docs URL: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Sriparno08 Thanks for submitting a PR! I'm going to triage this but place it on hold per comment [here](https://github.com/github/docs/issues/25314#issuecomment-1541625735) as we investigate it a bit further. 👍

**Review by rnsishan — COMMENTED** [review]
correct

**Comment by Sriparno08** [comment]
Hey @cmwilson21, is there any update on the PR?

**Comment by cmwilson21** [comment]
@Sriparno08 Thanks for checking in! Sorry for the delay, we've had to do a bit of digging as to why this doesn't work for all themes. Still working on it, though!

**Comment by Sriparno08** [comment]
Its OK, @cmwilson21 👍

Thanks for the update!

**Comment by Sriparno08** [comment]
Hey @cmwilson21, is there any update?

**Comment by Githubwix** [comment]
@mention plz approve for me

**Review by Githubwix — COMMENTED** [review]
@mention

**Review by vgrl — COMMENTED** [review]
Update supported theme example, following this [content design plan](https://github.com/github/docs/issues/25314#issuecomment-1804911996).

**Comment by Sriparno08** [comment]
Okay, @vgrl 👍

**Review by vgrl — APPROVED** [review]
Double checked on preview and looks good! ⚡. I'll go ahead and get this merged.

**Pull request merged**
