### PR TITLE
Update about-workflows.md: fix intro section

### PR DESCRIPTION
**Pull request by Teagum**
Add missing hyphen and missing preposition to intro section.

### Why:

Wrong grammar

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Intro section 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Teagum Thanks for opening a PR! Great catch, I'll get this merged once all the checks are passing ✅ 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Review by cmwilson21 — APPROVED** [review]
Looks good to me!

**Review by NostalgicGareth — COMMENTED** [review]
- [ ]

**Comment by Fabeduz88** [comment]
#24946

**Pull request merged**
