### PR TITLE
issue #12410 fixed the github token scopes

### LINKED ISSUE #12410: GITHUB_TOKEN scope column doesn't have the literal scopes
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

### What part(s) of the article would you like to see updated?

There is a table that describes permissions we can specify in the workflow.

When I tried to add it for Pull Requests, I just copied `pull requests` in the configuration but it didn't work because it has to be `pull-requests`.

I can see there are several "permissions" that contains a space but it should be valid name for the workflow configuration.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by keshav-bohr**
### Why:

Closes https://github.com/github/docs/issues/12410

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by keshav-bohr** [comment]
Hi @ramyaparimi @lucascosti 

Added this PR. Please check and let me know if there are any changes required.

Thanks

**Comment by KMCNopparat** [comment]
gh pr checkout 14213

**Comment by KMCNopparat** [comment]
[story-joe-edit-reviewed.txt](kulpripratrat@gmail.com)

**Comment by KMCNopparat** [comment]
@bruce

**Review by lucascosti — APPROVED** [review]
Awesome! thanks, @keshav-bohr!

**Pull request merged**
