### PR TITLE
Fix indentation causing duplicate "reusables.ssh.add-public-key-to-github" step on Linux steps for "Adding your SSH key"

### PR DESCRIPTION
**Pull request by WaviestBalloon**
### Why:

Closes: 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removal of the duplicate step as shown in the first highlighted area.
image

### Check off the following:

- [X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by WaviestBalloon** [comment]
> @WaviestBalloon Thanks so much for submitting a PR! I'll get this triaged for review ⚡

Thank you! :)

**Comment by subatoi** [comment]
@WaviestBalloon Thank you very much for raising this issue! You're absolutely right about the duplication; however, the line you've deleted isn't what's causing it.

I believe what's happening is that the `mac` environment has some bad indentation on lines 165-167, which doesn't match the rest of the `note` environment it's in:

https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md?plain=1#L165-L167

That's then causing [line 171](https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md?plain=1#L171) which contains `{% data reusables.ssh.add-public-key-to-github %}` to bleed into the Windows and Linux environments, unintentionally.

If you're happy to go ahead and amend this PR to re-add the line you've deleted, and make the amendments I suggest instead, you should see the desired outcome in your preview and then we can accept this PR.

Please let me know if you have any questions 👍

**Comment by WaviestBalloon** [comment]
Oh, I tried to revert the commit to made the changes but it automatically closed the PR.
I did not mean to do that

**Comment by WaviestBalloon** [comment]
Oh, I tried to revert the commit to made the changes but it automatically closed the PR.
I did not mean to do that

**Comment by WaviestBalloon** [comment]
> @WaviestBalloon Thank you very much for raising this! You're absolutely right about the duplication; however, the line you've deleted isn't what's causing it.
> 
> I believe what's happening is that the `mac` environment has some bad indentation on lines 165-167, which doesn't match the rest of the `note` environment it's in:
> 
> https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md?plain=1#L165-L167
> 
> That's then causing [line 171](https://github.com/github/docs/blob/main/content/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent.md?plain=1#L171) which contains `{% data reusables.ssh.add-public-key-to-github %}` to bleed into the Windows and Linux environments, unintentionally.
> 
> If you're happy to go ahead and amend this PR to re-add the line you've deleted, and make the amendments I suggest instead, you should see the desired outcome in your preview and then we can accept this PR.
> 
> Please let me know if you have any questions 👍

I believe I have made the correct changes, apologies, I'm having a hard time understanding the formatting of the markdown files. 😅

**Comment by WaviestBalloon** [comment]
All seems to be fixed!
image

**Comment by subatoi** [comment]
As far as I can tell, that change looks good, thank you! There's something flaky going on with the OS selector on the preview and the builds were also flaky for this PR, so we're just going to take a closer look before merging. I'll get back to you as soon as I can!

**Comment by WaviestBalloon** [comment]
👍🏻

**Review by subatoi — APPROVED** [review]
This looks good, thank you! I'll get this merged

Just to note that I'll shortly change this content into a reusable because another user identified a [different issue ](https://github.com/github/docs/pull/28379) that coincidentally touches the same content, but the indentation issue would still exist there so needed fixing, and in any case you'll be fully credited as contributor on this PR 😄 

Thank you again for your help!

**Pull request merged**
