### PR TITLE
add discussions to contribution graph

### PR DESCRIPTION
**Pull request by bdresser**
### Why:

Documentation is out of date! Discussion activity shows up on the contribution graph.

### What's being changed:

adds "opened a discussion; answered a discussion" to list of activities that show in contribution graph. 

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by evi-liu — APPROVED** [review]

**Comment by evi-liu** [comment]
thank you for opening this PR! 🙌

**Review by janiceilene — APPROVED** [review]
Thanks so much for opening a PR @bdresser! This change looks 💯 I'll update the branch and get this merged 🚀 

Edit: I just saw @cheshire137 is requested for review, so I'll hold off until that's done 👍

**Review by cheshire137 — APPROVED** [review]
This is accurate!

**Comment by janiceilene** [comment]
Thanks folks! I'll update the branch and get this merged in soon ⚡

**Pull request merged**
