### PR TITLE
Add `pull requests from`

### LINKED ISSUE #22492: `has read-only permissions in forked repositories` is incorrect
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://github.com/github/docs/blob/6d25c89672596b801f4885eda80d043f7c568c56/data/reusables/developer-site/pull_request_forked_repos_link.md?plain=1#L5

### What part(s) of the article would you like to see updated?

The part that says:

> has read-only permissions in forked repositories.

It should _probably_ say

> has read-only permissions in _pull requests from_ forked repositories.

### Additional information

https://github.com/PowerDNS/pdns/pull/12249#discussion_r1041069218

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes #22492

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Adds `pull requests from `

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 Hey @jsoref - Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by sabrowning1 — APPROVED** [review]
Looks great, thanks for another contribution @jsoref! I'll merge this shortly 👍🏼

**Comment by Shardin1995** [comment]
> 

https://github.com/github/docs/pull/22729#issue-1499688095

**Comment by Githubant123** [comment]
help

**Pull request merged**
