### PR TITLE
Style guide fixes to linking-a-pull-request-to-an-issue.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Per MS style guide and many other style guides, avoid:

* Please except in situations where the customer is asked to do something inconvenient or the application or site is to blame for the situation.
* Future tense.
* Parenthetical clauses.

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@Rick-Anderson 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — COMMENTED** [review]
@Rick-Anderson 👋🏻 - This LGTM ✨ 
Just making a minor suggestion that I'm going to apply.

**Comment by mchammer01** [comment]
I'm going to try and merge this but previews aren't currently working 🤷🏻

**Review by mchammer01 — APPROVED** [review]
Ready to ship :shipit:

**Pull request merged**
