### PR TITLE
Github Actions Release Trigger | docs wrongly state that release-Action is triggered on draft

### PR DESCRIPTION
**Pull request by kohlerdominik**
### Why:

My tests lead me to the assumption, that the `released`-action is only triggered when a release is done (either directly or by finishing a draft).

The docs say, `release` is also triggered when a release-draft is published. But IMO this isn't the case. And it wouldn't make sense with an action called `release`, as a draft is NOT a release.

### What's being changed:

The docs state, that a Webhook with the `action=released` is triggered, when a draft is published.

> `released`: a release or draft of a release is published, or a pre-release is changed to a release

But IMO this is neither the case, nor would it make sense regarding the naming. A draft is NOT a release.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@kohlerdominik 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Danielferencz21** [comment]
Kodex

**Review by davidmerwin — COMMENTED** [review]
❤️

**Comment by davidmerwin** [comment]
❤️

**Review by lucascosti — APPROVED** [review]
Thanks for this fix, @kohlerdominik.

**Pull request merged**
