### PR TITLE
Update automatically-redelivering-failed-deliveries-for-a-github-app-webhook.md

### PR DESCRIPTION
**Pull request by beliaev-maksim**
The `octokit` package has been updated to an ES Module. As a result, user needs adjust the script for ES Module compatibility, and convert the file to use the ES Module format. As part of this PR we also bump NodeJS version as 18 is soon EOL

### Check off the following:

- [ ] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [x] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [x] All CI checks are passing.

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@beliaev-maksim Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by Saeidhavashem — COMMENTED** [review]
Saeid

**Review by Saeidhavashem — COMMENTED** [review]
Saeid1

**Review by Jano1141 — COMMENTED** [review]
beliaev-maksim:patch-1

**Review by gr2m — APPROVED** [review]
Changes look good to me from the @octokit JS SDK prespective. Thank you Maksim, Grüße nach Berlin 🐻

**Comment by beliaev-maksim** [comment]
> Changes look good to me from the @octokit JS SDK prespective. Thank you Maksim, Grüße nach Berlin 🐻 

Thank you for the review!

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@beliaev-maksim Thanks again for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Pull request merged**
