### PR TITLE
Make examples consistent

### PR DESCRIPTION
**Pull request by AlekSi**
### Why:

Example uses different paths.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Sync paths with the workflow above.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@AlekSi Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by rachaelrenk — APPROVED** [review]
Hi @AlekSi 👋  Your content changes look good to me. Can you resolve the merge conflicts on your fork? Once those are resolved, this is approved and we can get it merged. Thanks! 🛸

**Comment by AlekSi** [comment]
@rachaelrenk done, PTAL

**Review by rachaelrenk — APPROVED** [review]
Great! I'll get this merged. ✨ 🛸

**Pull request merged**
