### PR TITLE
Update about-issues.md

### PR DESCRIPTION
**Pull request by meetxpress**
### Why:
Because it is a silly mistake that might confuse the user or might not.

### What's being changed:

I have put a '/' after the path given to redirect to a particular file.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by Shivam7-1 — APPROVED** [review]

**Review by mainendra — APPROVED** [review]
Looks good.

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the pull request template and we'll get this up for review!

**Comment by janiceilene** [comment]
Thanks @meetxpress! I'll update the branch and get this merged once tests are green 🍏

**Review by janiceilene — APPROVED** [review]

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 for content docs

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 for docs

**Comment by Shivam7-1** [comment]
@all-contributors please add @Shivam7-1 for doc

**Pull request merged**
