### PR TITLE
Small wording change in the 'Setting a status' section

### PR DESCRIPTION
**Pull request by kristlyuen**
### Why:

Closes [issue link]

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Currently the `Setting a status` section of the doc says to click `Set your status`, but that option is now just `Set status`. _The associated screenshot will need to be updated as well._ I didn't add an updated screenshot because I could only take one from my personal account. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by farzaneh53** [comment]
در تاریخ دوشنبه ۱۷ اکتبر ۲۰۲۲،‏ ۲۰:۳۴ welcome[bot] ***@***.***>
نوشت:

**Comment by cmwilson21** [comment]
@kristlyuen Thanks for submitting a PR! We have guidance on [screenshots](https://github.com/github/docs/blob/main/contributing/images-and-versioning.md#best-practices-for-taking-screenshots) where we suggest contributors use their browser's developer tools to change their information to [octocat's](https://github.com/octocat) username and profile pic. 

Feel free to give that a try, if you'd like! I'll get this triaged for review. ⚡

**Review by isaacmbrown — CHANGES_REQUESTED** [review]
Hi @kristlyuen,

Thanks for opening this PR! ✨ As you say, the UI text has changed.

Could I ask you to also update the screenshot? Please feel free to use the one below if that's easiest.

set-status-on-profile

Thanks!

**Review by isaacmbrown — APPROVED** [review]
Screenshot updated in https://github.com/github/docs/pull/21469 - looks good to go

**Pull request merged**
