### PR TITLE
Fix incorrect indentation in managing-a-custom-domain-for-your-github-pages-site.md

### LINKED ISSUE #22180: "Manage a custom domain" > "Configuring a subdomain" has broken formatting
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

### What part(s) of the article would you like to see updated?

The number of the list items seems incorrect; "Navigate to your DNS provider and create..." is currently numbered as "1" but should probably be numbered as "5":
https://github.com/github/docs/blob/88c31e99c779fbf721caf7fac222ad369be8bc0c/content/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site.md?plain=1#L59

Incorrect numbering screenshot

---

The Markdown rendering of the warning box is broken:
Broken Markdown rendering screenshot

Note: That warning box is actually used multiple times, but only the rendering of this occurrence is broken.

### Additional information

I am not going to submit a pull request because I am not familiar enough with how these Markdown files are processed and how why these issues might occur.

### PR DESCRIPTION
**Pull request by Marcono1234**
### Why:

Closes #22180

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Fixes incorrect indentation of the note. Previously it was not indented and would cause the list to be split, with the next item starting at "1." again, see also description of #22180.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Marcono1234** [comment]
Now the list numbering seems to be correct, but Markdown rendering is broken for this note:
Broken Markdown screenshot

Maybe this is also only an intermittent issue like the broken rendering in #22180, though that is really weird then. I am seeing this in Firefox and Edge, both in private windows, so I don't think this is caused by the browser cache (?).

**Comment by cmwilson21** [comment]
@Marcono1234 Thanks for opening a PR! I'll get this triaged for review ⚡ 

As for the markdown in the note, I followed your advice with Firefox and a private browser and have been unable to recreate it. Perhaps you are right and it was a temp bug or it may have been fixed in an internal PR. Either way, thanks for the heads up about it! ✨

**Review by vgrl — COMMENTED** [review]
Thanks, @Marcono1234  ⚡ I'm going to make a small edit, and then I'll merge this.

**Review by vgrl — APPROVED** [review]
Looks good on preview now. 🎉 

I'll go ahead and get this PR merged, thanks again @Marcono1234 !

**Pull request merged**
