### PR TITLE
HaliilIbrahim

### PR DESCRIPTION
**Pull request by Haliil**
https://office-insider-media.azurefd.net/media/2020/06/landscape_vp1_539x349_0000s_0001_1144533673.jpg

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Haliil** [comment]
https://support.microsoft.com/ar-sa/office/%D8%A8%D8%AF%D8%A1-%D8%AF%D8%B1%D8%AF%D8%B4%D8%A9-%D9%81%D9%8A-teams-0c71b32b-c050-4930-a887-5afbe742b3d8

**Comment by Haliil** [comment]
https://office-insider-media.azurefd.net/media/2020/06/landscape_vp1_539x349_0000s_0001_1144533673.jpg

**Comment by Haliil** [comment]
9XPM7QNH

**Review by Robabe1987 — COMMENTED** [review]
05314347250

**Pull request closed without merging**
