### PR TITLE
Change `productVersions` to `versions` in content templates

### LINKED ISSUE #6798: Content templates use `productVersions` which looks like it should be `versions`
### What article on docs.github.com is affected?

https://github.com/github/docs/blob/main/contributing/content-templates.md

### What part(s) of the article would you like to see updated?

Looks like the `productVersions` frontmatter field is actually named [`versions`](https://github.com/github/docs/tree/main/content#versions). I will open a PR suggesting changes in a minute...

### PR DESCRIPTION
**Pull request by davegaeddert**
### Why:

Closes #6798

### What's being changed:

Renamed the frontmatter field in the examples and the link to the section about that field.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@davegaeddert Thank so much for opening an issue and PR 💖 I'll get this triaged for review ⚡

**Review by emilyistoofunky — APPROVED** [review]
Thanks @davegaeddert! ⚡

**Comment by emilyistoofunky** [comment]
👋🏻 @davegaeddert Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by davegaeddert** [comment]
@emilyistoofunky I could be missing it, but I'm not seeing that option... is it because I opened the PR from an organization-owned fork instead of user-owned? I went ahead and hit the update button.

**Comment by janiceilene** [comment]
@davegaeddert Our branches get out of date so quickly (sometimes before the tests even pass!), so we'll try to troubleshoot next week to figure out why there's no "update" button for us next week. If you happen to figure it out in the interim, let us know!

**Comment by janiceilene** [comment]
👋 @davegaeddert Could you try adding me as a collaborator to your fork? That would also allow me to update the branch 🤞 

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by davegaeddert** [comment]
@janiceilene I invited you with write access. Let me know if that does it otherwise I can try transferring the fork to my personal account? I'm hoping to open a PR to discuss some "partner owned docs" so definitely want to get this figured out!

**Comment by janiceilene** [comment]
@davegaeddert It worked! Thanks so much for sticking with us as we worked through it 🎉 Updating the branch now and I'll get this merged once tests are passing 🍏

**Comment by janiceilene** [comment]
@davegaeddert We've got a [Partner-owned product documentation](https://github.com/github/docs/issues/new?assignees=&labels=partner&template=partner-contributed-documentation.md&title=) issue template that should have everything you need! Let me know if you have any questions there ⚡

**Pull request merged**
