### PR TITLE
Ok adding-an-existing-project-to-github-using-the-command-line.md

### PR DESCRIPTION
**Pull request by alexbodn**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by alexbodn** [comment]
pulling or otherwise merging is needed after local repository init for the case remote changes would be already committed in the github party.

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by sarahs** [comment]
👋 We did some content restructuring that resulted in a conflict with your PR. It looks like we may not have access to check out your fork. Let us know if you need a hand resolving the conflict!

**Comment by janiceilene** [comment]
Closing this issue for now, but if you fill out the pull request template and would like it reopened, let us know!

**Pull request closed without merging**
