### PR TITLE
Fix spelling of `RSA`

### LINKED ISSUE #30812: `RSA` is misspelled as `DSA`
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-ci-checks-with-a-github-app#store-your-apps-identifying-information-and-credentials

### What part(s) of the article would you like to see updated?

> Copy and paste the entire contents of the file into your .env file as the value of GITHUB_PRIVATE_KEY, and add double quotes around the entire value.
>
> Here is an example .env file:

```
GITHUB_APP_IDENTIFIER=12345
GITHUB_WEBHOOK_SECRET=your webhook secret
GITHUB_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----
...
HkVN9...
...
-----END DSA PRIVATE KEY-----"
```

### Additional information

I've had a tool that I've delayed running on this repository for a really long time, but this week I added a new feature to it, and this was the first error it found (I didn't expect this feature to find bugs, but...):

https://github.com/check-spelling-sandbox/github-docs/security/code-scanning/1109
image

Fwiw, here's the current rough list of corrections it has turned up: https://github.com/check-spelling-sandbox/github-docs/compare/main..spell-check-with-spelling~

I don't intend to create one ticket per typo as that'd flood things (I created https://github.com/github/docs/issues/30791 for a set of other violations, and I'd imagine I'd do something similar for content typos).

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes: #30812 

#### Before
https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-ci-checks-with-a-github-app#store-your-apps-identifying-information-and-credentials
image

#### After
https://docs-30813-531f5b.preview.ghdocs.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-ci-checks-with-a-github-app#store-your-apps-identifying-information-and-credentials
image

`DSA` is being changed to `RSA` to match the `BEGIN RSA PRIVATE KEY` marker a few lines above

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
Great catch, @jsoref! Thanks for opening a PR with this fix - I'll update the branch and get this in the queue to merge once tests are passing 🍏

**Review by nguyenalex836 — APPROVED** [review]

**Comment by jsoref** [comment]
@nguyenalex836: great.

Any thoughts about the [longer possible series of fixes](https://github.com/check-spelling-sandbox/github-docs/compare/main..spell-check-with-spelling~)?

**Comment by nguyenalex836** [comment]
@jsoref Larger batches of fixes (PRs that touch more lines / files) will need to be reviewed by our team. Thank you for your patience while our team is enjoying the holidays ✨

**Comment by jsoref** [comment]
Sure, I'm patient, just wondering if it makes more sense for me to send a single large batch or try to chunk it into smaller things.

**Comment by nguyenalex836** [comment]
@jsoref Appreciate the consideration on the optimal process 💛 From a reviewer's perspective, it's likely better to batch similar typo fixes into one PR, so that the reviewer can just go through each fix more quickly / efficiently within a single PR. That also keeps our queues from overflowing 👍

**Comment by jsoref** [comment]
Most things are simple typos.

I think I'll split off:
* brand typos
* markdown syntax 
* scripts
* file renames

**Comment by nguyenalex836** [comment]
Sounds like a plan, @jsoref 👍

**Pull request merged**
