### PR TITLE
Amend git pull --set-upstream origin main to git push

### PR DESCRIPTION
**Pull request by ghost**
Amend "git pull --set-upstream origin main" to "git push --set-upstream origin main" because this is about pushing an existing project first time to github.

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by rcowsill** [comment]
The instructions are correct in using `git pull` for this case. Step 3 uses the GitHub CLI to create the repository on GitHub, and then `git pull` is used to pull `origin/main` into `main` and set up the remote tracking branch.

There's another section on that page that explains how to create a repository locally and push it up to GitHub. It uses `git push` as expected:
https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line#adding-a-project-to-github-without-github-cli

**Comment by dayanmasiha** [comment]
> Amend "git pull --set-upstream origin main" to "git push --set-upstream origin main" because this is about pushing an existing project first time to github.
> 
> ### Why:
> Closes [issue link]
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Comment by ramyaparimi** [comment]
@asklittlkat

**Comment by skedwards88** [comment]
> The instructions are correct in using `git pull` for this case. Step 3 uses the GitHub CLI to create the repository on GitHub, and then `git pull` is used to pull `origin/main` into `main` and set up the remote tracking branch.
> 
> There's another section on that page that explains how to create a repository locally and push it up to GitHub. It uses `git push` as expected: https://docs.github.com/en/github/importing-your-projects-to-github/importing-source-code-to-github/adding-an-existing-project-to-github-using-the-command-line#adding-a-project-to-github-without-github-cli

Excellent explanation, @rcowsill ! You need to `git pull` to get the changes from the GitHub repository that you created (if you added any files like a `gitignore` during repo creation). The following step instructs you to do a `git push`. 

@asklittlkat I'm going to close this PR, but I'd love to see more contributions from you in the future ✨

**Pull request closed without merging**
