### PR TITLE
Delete extra 'or' on sentence

### PR DESCRIPTION
**Pull request by joaquinricci**
### Why:

To fix a typo.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by bishal7679 — COMMENTED** [review]
@joaquinricci Thanks for raising a PR. I like this typo error fixed!
Whenever you are making a PR please make an issue before that (even it's a small one).
Follow this approach for your next contribution 
I hope you understand :)

**Review by bishal7679 — COMMENTED** [review]
LGTM!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by cmwilson21** [comment]
@joaquinricci Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by cmwilson21 — APPROVED** [review]
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by joaquinricci** [comment]
> @joaquinricci Thanks for raising a PR. I like this typo error fixed! Whenever you are making a PR please make an issue before that (even it's a small one). Follow this approach for your next contribution I hope you understand :)

Thank you very much! I will definitely open an issue next time.

**Pull request merged**
