### PR TITLE
Create Noob/one

### PR DESCRIPTION
**Pull request by sangnguyen696969**
`<!--`
Thank you for contributing to this project! You must fill out the information below before we can review this pull request. By explaining why you're making a change (or linking to an issue) and what changes you've made, we can triage your pull request to the best possible team for review.
-->

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by bignicky9978 — COMMENTED** [review]
👌🏻

**Review by Amirko22 — COMMENTED** [review]
#26982 []()

**Comment by sanrodarmawan98** [comment]
Thanks u variemixs

**Review by sanrodarmawan98 — COMMENTED** [review]
Feedback

**Pull request closed without merging**
