### PR TITLE
Change wording in enterprise team synchronization

### LINKED ISSUE #26290: Change wording in enterprise team synchronization documentation from "organization" to "enterprise".
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/managing-team-synchronization-for-organizations-in-your-enterprise

### What part(s) of the article would you like to see updated?

Step 5 says:

> Confirm that SAML SSO is enabled for your organization. For more information, see "[Managing SAML single sign-on for your organization](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-saml-single-sign-on-for-your-organization)."

It should read: 

"Confirm that SAML SSO is enabled for your **_enterprise_**"... 

and then link to enterprise SSO documentation like this page:
https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-saml-for-enterprise-iam/configuring-saml-single-sign-on-for-your-enterprise

instead of linking to org level SAML docs.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Harshil-Jani**
### Why:

Closes: #26290 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Mdashad071192** [comment]
Why

**Comment by Harshil-Jani** [comment]
> Why

Sorry. What ?

**Comment by Mdashad071192** [comment]
I always learning about new things are you help me

**Comment by Harshil-Jani** [comment]
> I always learning about new things are you help me

This is a pull request(PR) which attempts to solve any raised concern about the project. In context of this pull request, I am trying to resolve a wording confusion on the github documentation regarding organization or enterprise. The issue was already triaged in #26290 . Now, If the change is good to be merged then someone from github team will come and merge this PR and the change will go live.

**Comment by cmwilson21** [comment]
@Harshil-Jani Thanks for the PR! ⚡ 

And thank you for being kind in the comments above ✨ 

I'll get this triaged for review! In the meantime, if you'd like to find other ways to contribute, check out our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on. 💖

**Comment by cmwilson21** [comment]
And welcome to the community! 🎉

**Review by rachaelrenk — APPROVED** [review]
LGTM! ✨  Thanks for opening this PR @Harshil-Jani. I'll get it approved and added to the merge queue.

**Pull request merged**
