### PR TITLE
Fix 'Allow select actions' wording and description

### PR DESCRIPTION
**Pull request by lucascosti**
Replaces PR: https://github.com/github/docs/pull/941, and done in collaboration with @Simran-B 

### Why:

* The description for **Allow select actions** does not mention that local actions are also allowed when using that setting.
* The docs incorrectly name the setting **Allow specific actions**, when the label in the UI is **Allow select actions**.

### What's being changed:

Adds some wording to the description stating that local actions are also allowed, and fixes the label text.

Stage previews:

* https://docs-1112--lucascostiallow-spe.herokuapp.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository
* https://docs-1112--lucascostiallow-spe.herokuapp.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/disabling-or-limiting-github-actions-for-your-organization
* https://docs-1112--lucascostiallow-spe.herokuapp.com/en/free-pro-team@latest/github/setting-up-and-managing-your-enterprise/enforcing-github-actions-policies-in-your-enterprise-account

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by lucascosti** [comment]
Thanks for the original content for this, @Simran-B! Because I'm the creator of this PR, we have to wait until someone else on the docs team reviews and approves it 🙂

**Comment by Simran-B** [comment]
joshmgross [said](https://github.com/github/docs/pull/941#discussion_r518144982) that
> Local actions also includes any within an enterprise account.

It still doesn't say so here:
> When you enable local actions only, workflows can only run actions located in your repository or organization.

https://docs-1112--lucascostiallow-spe.herokuapp.com/en/enterprise-server@2.22/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#about-github-actions-permissions-for-your-repository

**Review by joshmgross — APPROVED** [review]
Should we improve the description of "local actions" in this PR too?

**Review by skedwards88 — APPROVED** [review]
LGTM 🚀

**Comment by lucascosti** [comment]
> It still doesn't say so here:

> Should we improve the description of "local actions" in this PR too?

Ah, yes! Thanks for calling that out. Done in https://github.com/github/docs/pull/1112/commits/271c99ac4d430815d7a76a7a0924ba4aa0376525 🚀 

I'll get this merged 🚢

**Comment by walid161hatam** [comment]
Send perfactmon money-05001eced277062d2577f1c7ae43e96e85b76916

**Pull request merged**
