### PR TITLE
chore: flatten and document pinned actions

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

There are a few different versions of the sha versions of the `action/*` tasks used across the various jobs. This standardizes them on the latest versions and document what the sha commit actually represents.

### What's being changed:

Moves all the existing pinned hashed versions of the `actions/*` libraries to their latest versions that are already in use here. Adding notes in the file that controls the allowed version to indicated the upstream friendly version number in order to more easily find what version the hashes represent.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @nschonni Thanks for opening a PR! Is this still in progress? When you're ready for review, can you fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) and let me know? Then I'll get it triaged for you!

**Comment by nschonni** [comment]
@janiceilene I've checked off the checkboxes now

**Comment by janiceilene** [comment]
@nschonni Could you fill out the **Why?** and **What's being changed:** sections to help ensure that this is triaged to the right team(s) for review, thanks!

**Review by heiskr — APPROVED** [review]
Makes sense to me.

**Comment by chiedo** [comment]
This is fantastic @nschonni!

**Comment by chiedo** [comment]
@nschonni seeing a test failure. It looks like `actions/github-script@44b873bc975058192f5279ebe7579496381f575d` is referenced somewhere in the codebase but it isn't in the allowed actions list. So you may need to update a reference somewhere to the latest version of github script and confirm it still works / there aren't any breaking changes.

**Comment by nschonni** [comment]
Think https://github.com/github/docs/pull/864 created a conflict after merging the branch. I'll rebase it

**Comment by nschonni** [comment]
@chiedo CI is green again 😄

**Comment by nschonni** [comment]
@chiedo fixed the failure for the new job in https://github.com/github/docs/commit/bce0499998774ec72874a8b0f0cf11d16707ac43

**Pull request merged**
