### PR TITLE
Update setting-up-code-scanning-for-a-repository.md

### LINKED ISSUE #8956: Bulk Code Scanning Article Update - Non Powershell Example :)
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's Code of Conduct.

### What article on docs.github.com is affected?

[bulk-set-up-of-code-scanning](https://docs.github.com/en/enterprise-server@2.22/github/finding-security-vulnerabilities-and-errors-in-your-code/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#bulk-set-up-of-code-scanning)

### What part(s) of the article would you like to see updated?

There is a great example already provided in Powershell. However, there are customers who are not running Powershell or have a Powershell environment to use 😢 I am adding an example using NodeJS, which is a lot wider available and people may be familiar with. 

The current example is great, I 100% do not want to replace it, just add another example for our customers to use 💯 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by NickLiffen**
### Why:

Closes #8956 

### What's being changed:

The "Bulk Code Scanning Enablement" section. Customers do not all have Powershell and would like an example that can be run within a NodeJS environment. 😄 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by amirnateghi1980 — APPROVED** [review]
Update

**Comment by NickLiffen** [comment]
Thanks @hubwriter 💯 I see a CI check is failing. If I have missed anything, more then happy to fix if if you need anything from me 😄

**Comment by hubwriter** [comment]
Hi @NickLiffen - thanks, the "Repo Freeze Check" is currently failing. This is expected because we've temporarily frozen merges to this repo pending some major docs work that's finalizing today.

**Review by hubwriter — APPROVED** [review]
LGTM, thanks. 👍 
I'll get this merged soon.

**Comment by NickLiffen** [comment]
Thanks for your help @hubwriter ❤️

**Comment by 0823969789** [comment]
#8957

**Pull request merged**
