### PR TITLE
Add  max char limit of 65535 in Checks docs

### LINKED ISSUE #3765: Document checks output.text field length
### What article on docs.github.com is affected?

https://docs.github.com/en/rest/reference/checks#create-a-check-run

### What part(s) of the article would you like to see updated?

The documentation for the field output.text should include that it is limited to 65535 characters

I have created a CI integration that reports output of my different stages as the text of a check run. When I got to one particular stage I got this error:

```json
{
  "message": "Invalid request.\n\nOnly 65535 characters are allowed; 121090 were supplied.",
  "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"
}
```

Which is fine for my usecase (I just have to decide which part of the output to include) but it would have been better had I known about the limitation beforehand instead of finding out a while later when my build output got big enough.

### PR DESCRIPTION
**Pull request by HeroicHitesh**
### Why:

**Closes #3765**

### What's being changed:

Show maximum character limit of 65535 for various fields of `output` object in `Checks` api

Screenshot 2021-03-22 at 4 59 28 PM

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by HeroicHitesh** [comment]
@janiceilene I am confused as my changes are showing expected result and I am unable to find any other file updating which will give the expected result and the file that I updated is in restricted files list. So, what is the way to solve this issue? Can you please guide me. Thanks in advance.

**Comment by janiceilene** [comment]
🙈 I'm so sorry @HeroicHitesh! I didn't realize that the change would need to be made in an article that's autogenerated from an internal repo. I've opened an issue internally to make this fix and I'll need to close this PR (we just can't make the changes from this repo). I'll close the issue as well (and note that it's an internal fix) to avoid any additional confusion.

Thank you so much for opening an PR and working to improve the GitHub docs! And I apologize for the misinformation 💛

**Comment by baentsch** [comment]
When creating output building our own little CI system I also stumbled into this limitation. It seems it still isn't documented, so can you please re-open this issue? Alternatively/in addition can you suggest how to report long output from ChecksAPI runs? Thanks in advance.

**Comment by ramyaparimi** [comment]
@baentsch Thank you for letting us know. I have opened an internal issue to track this 💖.

Thanks so much for your passion in contributing to the GitHub docs 💖

**Pull request closed without merging**
