### PR TITLE
Tiny headline adjustment for the Issue event types page

### PR DESCRIPTION
**Pull request by abjerner**
### Why:

The **Issue event types** page has a number of *Event object properties* headlines. All but one are H4s, as a single is a H3 instead.

As a H3 gets a link in the page navigation to the right, I thought I would change that to a H4 as well 😉 

Since this is such a tiny change, I haven't created an issue.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in [staging](https://docs-2004--patch-1.herokuapp.com/en/free-pro-team@latest/developers/webhooks-and-events/issue-event-types#event-object-properties-4).
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@abjerner Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by abjerner** [comment]
@janiceilene I've updated the PR now. I wasn't sure about check list, but makes more sense now that the tests have completed.

**Comment by janiceilene** [comment]
Thanks so much @abjerner! I'll get this triaged for review ⚡

**Review by lucascosti — APPROVED** [review]
Thanks for fixing this, @abjerner!

**Pull request merged**
