### PR TITLE
Update setting-up-your-development-environment-to-create-a-github-app.md

### PR DESCRIPTION
**Pull request by macedogm**
### Why:
Fix two small typos in the documentation.

### What's being changed:

1. You'll won't -> You won't
2. I'm getting seeing -> I'm getting

### Check off the following:
- [X] All of the tests are passing.
- [X] I have reviewed my changes in staging.
- [X] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [X] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@macedogm Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janiceilene** [comment]
This is not stale! @macedogm Thank you for your patience as our small team works through the amazing contributions ✨

**Review by shati-patel — APPROVED** [review]
Oops 😄 Thank you for the fix, @macedogm! We really appreciate all the community contributions to help us improve our docs 🎉 

I'll get this merged shortly!

**Comment by macedogm** [comment]
> Oops 😄 Thank you for the fix, @macedogm! We really appreciate all the community contributions to help us improve our docs 🎉
> 
> I'll get this merged shortly!

Thanks for reviewing and merging @shati-patel !

**Pull request merged**
