### PR TITLE
Fix grammatical issue in CodeQL CLI extractor options documentation

### LINKED ISSUE #24757: Minor grammatical issue in CodeQL CLI extractor options documentation
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options

### What part(s) of the article would you like to see updated?

There is a missing space character in the opening paragraph of the [About extractors](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options#about-extractors) section of the CodeQL CLI extractor options documentation, immediately following the tool name ('CodeQL CLI'):

> The CodeQL CLIuses special programs...

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marcransome**
### Why:

Fixes a minor grammatical issue in the CodeQL CLI extractor options documentation.

Closes: #24757

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The opening paragraph of the [About extractors](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/extractor-options#about-extractors) section of the CodeQL CLI extractor options page is being changed to introduce a space character following the tool name.

From:

> The CodeQL CLIuses special programs...

To:

> The CodeQL CLI uses special programs...

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by mchammer01 — APPROVED** [review]
@marcransome - thanks for spotting this ✨ 
LGTM :shipit:

**Review by devilshezi0 — COMMENTED** [review]
components/search/SearchResults.tsx

**Comment by jaybimaplan** [comment]
Hi @marcransome 

I spotted few more grammatical mistakes and I will fix those.

**Comment by marcransome** [comment]
> Hi @marcransome
> 
> I spotted few more grammatical mistakes and I will fix those.

See issue #24777 and its associated PR #24778 in case there's any overlap.

**Pull request merged**
