### PR TITLE
Update docs for generating a new SSH key for windows

### PR DESCRIPTION
**Pull request by williamtorres1**
I was trying to add a ssh key to my github using windows 10, and i was uncapable to procceed.
And i found that the commands `$ eval $(ssh-agent -s)` don't work on windows, but  ` $ eval `ssh-agent -s` ` works fine

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@williamtorres1 Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by prdarm — APPROVED** [review]

**Review by shati-patel — APPROVED** [review]
I can confirm this works on Windows ✔️ 

Thank you very much for your contribution @williamtorres1, I'll get this merged once the tests pass 🎉

**Comment by Simran-B** [comment]
In what windows shell does this work?

**Comment by shati-patel** [comment]
> In what windows shell does this work?

It should work in a Git Bash shell for Windows 🙂 

In fact, both the `$ eval $(ssh-agent -s)` and ```$ eval `ssh-agent -s` ```  syntax work in my version, but the latter seems more universal (according to various comments on stackoverflow 😅).

**Comment by shati-patel** [comment]
I'm going to quickly close and re-open this PR to (hopefully) kick-start the staging deployment 🤞🏽

**Comment by Simran-B** [comment]
Thanks for the clarification! I missed that the instructions say "Open Git Bash" earlier. I would prefer a true Windows solution that doesn't require an emulated Linux, but this is still a meaningful change.

**Pull request merged**
