### PR TITLE
Restore correct section range in TOS

### PR DESCRIPTION
**Pull request by ltm**
### Why:

The reference to "Sections D.4 — D.7" was inadvertently changed to "Sections D.4 — D.1" in 1dfa5c251e99d2a91cc15cb8685db1007f7f5502.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Restores the correct "Sections D.4 — D.7" range.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by mchammer01 — APPROVED** [review]
@ltm - thanks for noticing this, and fixing the issue ✨

**Comment by mchammer01** [comment]
@github/site-policy-admins 👋🏻 - we need your approval before I can merge this PR. Can you take a look? Thanks 🙇🏻

**Comment by mchammer01** [comment]
@github/site-policy-admins - a gentle bump on my request above 💜

**Comment by mchammer01** [comment]
@github/site-policy-admins - we need an approval from you before we can merge this PR. Can you help? 🙏🏻 🙇🏻

**Review by margaret-tucker — APPROVED** [review]

**Pull request merged**
