### PR TITLE
Update configuring-user-provisioning-for-your-enterprise.md based on setting up GHAE for github.githubenterprise.com

### PR DESCRIPTION
**Pull request by therealadeel**
@bikwan In walking through this for GHAE I would recommend making it clear that the SCIM endpoint includes `api`.

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by hubwriter** [comment]
Related pull request: https://github.com/github/docs/pull/3165

**Review by lokera07 — APPROVED** [review]

**Review by tashaemery — APPROVED** [review]

**Review by tashaemery — APPROVED** [review]

**Review by tashaemery — APPROVED** [review]

**Review by tashaemery — APPROVED** [review]

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Review by myarb — COMMENTED** [review]
👋🏼  thanks for opening this PR, @therealadeel! In the original markup, we indicate that _YOUR-GITHUB-AE-HOSTNAME_ is replaceable text by using italic markup. This is standard across the docs per our style guide, so I don't think we'll make this change at this time. ✨

**Comment by therealadeel** [comment]
What's missing is the `api` in the url. The **YOUR-GITHUB-AE-HOSTNAME** stay but need to be prepended with "api."

**Comment by mattpollard** [comment]
Thanks, @therealadeel! We actually updated this in https://github.com/github/docs/commit/6b3d0bef1e78cdbb968c89d73ff7833746821a8f, so it's indicated the `api` subdomain for a little while now 🙇🏻

**Comment by fomi4112** [comment]
a

**Review by zbyte-king — COMMENTED** [review]
remove stale staging resources

**Pull request closed without merging**
