### PR TITLE
Add section on viewing contributions graph for a specific repository

### PR DESCRIPTION
**Pull request by SudhiSumesh**
Add a new section to the article that explains how to view users contributions graph for a specific repository. The section includes step-by-step instructions on how to navigate to the repository’s page, where to find the contributions graph, and how to select a specific time period. This information is useful for users who want to see their contributions for a specific repository, rather than their overall contributions

### Why:
Adding a section on viewing contributions graph for a specific repository is useful because it provides users with a way to view their contributions for a specific repository, rather than their overall contributions. This can be helpful for users who want to see how active they are in a particular repository, or who want to track their contributions to a specific project. The current problem with viewing contributions graph for a specific repository is that it is not immediately clear how to do so. By adding a section to the article that explains how to view your contributions graph for a specific repository, users will have a clear and concise set of instructions to follow. 
Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@SudhiSumesh Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by faisaldadkhan13 — COMMENTED** [review]
Needs approval on this PR.

**Review by SudhiSumesh — COMMENTED** [review]
ok

**Comment by SudhiSumesh** [comment]
> @SudhiSumesh Thanks so much for opening a PR! I'll get this triaged for review ✨

You’re welcome! I’m glad to be of help.Hope this change will merge soon

**Comment by subatoi** [comment]
Thank you for raising a PR for this and for describing in detail the rationale behind your suggested changes.

Unfortunately, we won't be approving this change. The reason for that is that the functionality you're describing shows the most _active_ contributors for a given repository: it isn't a reliable way for a user to see their activity in a specific repository.

We document this functionality correctly under https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors.

Thank you for your interest in the GitHub Docs!

**Pull request closed without merging**
