### PR TITLE
Add explicit bareRepository configuration when pushing bare mirror

### PR DESCRIPTION
**Pull request by jdknight**
### Why:

Was following the instructions outlined in [Detaching a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork) and noticed that step 5 was failing for me.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

If a user has configured `bareRepository=explicit` in their configuration, the push operation in this example will fail with the message:

    fatal: cannot use bare repository '<path>.git' (safe.bareRepository is 'explicit')

By adding `-c "safe.bareRepository=all"` to the default instruction set, this should prevent issues for users who have bareRepository configured.

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@jdknight Thank you for your patience while our SME team reviewed! 💛 Our SMEs reviewed and responded with the following:

--------------------------

The problem they're trying to fix sounds real to me, but I think their solution is a bit complicated. The git-config(1) manual page has this to say about safe.bareRepository setting's explicit value:

>  explicit: Git only works with bare repositories specified via the top-level --git-dir command-line option, or the GIT_DIR environment variable (see git(1)).

So, instead of:
`git -c "safe.bareRepository=all" push --mirror https://github.com/EXAMPLE-USER/FORK-NAME.git`

I think the correct answer would be something more like:
`git --git-dir https://github.com/EXAMPLE-USER/FORK-NAME.git push --mirror`

Those will both do the same thing in practice, but this version is getting there without needing to override a setting.

--------------------------

If you are able to update your PR to match what our SME provided, we will be happy to get this merged ✨ thank you!

**Comment by jdknight** [comment]
- Tweaked the command to use `--git-dir <bare>` over moving (`cd`) into the bare before trying to push up the mirror.
- This drops the requirements of `cd`ing in and out of the bare repository.
- Tweaked `FORK-NAME` to just `FORK` to minimize the longer command length in an attempt to fit the command on a single line.

**Comment by nguyenalex836** [comment]
@jdknight Apologies on behalf of our bot! Your latest updates are being reviewed by our SME team, and I'll ping you here as soon as I have a response from them 💛

**Review by wiseemily88 — APPROVED** [review]
I tested out the steps and this worked for me!

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@wiseemily88 Thank you very much for the review! ✨ 

@jdknight Thank you again for opening this PR! I'll update the branch and get this merged once tests are passing 💛

**Review by shahedy2276541 — COMMENTED** [review]
Fork

**Pull request merged**
