### PR TITLE
Fix accessibility issues on homepage and individual article pages

### LINKED ISSUE #2159: Accessibility audit is flagging markup errors
### What article on docs.github.com is affected?

- Homepage
- All article pages

### What part(s) of the article would you like to see updated?

- Links which are `aria-hidden` are keyboard accessible
- Page headings do not always increment by one
- Page elements exist outside of roles
- The navigation in the sidebar contains invalid nested unordered lists
- There is more than one `<main>` element on individual article pages

### PR DESCRIPTION
**Pull request by barrymcgee**
### Why:

Accessibility can nearly always be improved. This site was already built with accessibility clearly in mind but I noticed some remaining issues flagged in my [aXe accessibility browser](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) plugin so I thought I'd address them.

Fixes #2159

### What's being changed:

- Removed `aria-hidden` link wrapping the Github logo mark in the site header from the tab index so it's no longer keyboard accessible. This means keyboard users will skip straight to the next link around 'Github docs' which is the same.
- Make headings semantic and ensuring they only increment by one sequentially while maintaining the current visual styling.
- Wrap sidebar navigation in `<nav>` sectioning element to confer semantic meaning.
- Fix up incorrectly nested `<ul>`'s in the sidebar navigation
- Fix up duplicate nested `<main>` elements on article pages - there should only be one per page.

Each commit for each change has a link containing full supplementary rationale.

The biggest remaining issues are coming from the third party Agolia search box which is out of my control and there are also some color contrast issues but that will require collaboration and sign off from a designer.

#### Lighthouse Accessibilty score on production:

Screenshot 2020-12-16 at 14 35 47

#### Lighthouse Accessibilty score on this Heroku demo:

Screenshot 2020-12-16 at 14 36 50

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)

Not applicable:

- [ ] ~~For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)~~
- [ ] ~~For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).~~

### CODE REVIEW

**Comment by janiceilene** [comment]
@barrymcgee Thanks so much for opening a PR! I'll get this triaged for review 💖

**Review by nalharbi21 — APPROVED** [review]

**Review by nalharbi21 — APPROVED** [review]

**Review by nalharbi21 — APPROVED** [review]

**Comment by barrymcgee** [comment]
Holiday break 🎅

**Comment by mmnbmm23** [comment]
CONTRIBUTING.md

**Review by mmnbmm23 — APPROVED** [review]

**Comment by barrymcgee** [comment]
Bumping this once more as we're now just out of the holiday period and I'm hopeful it might get reviewed this week.

**Review by heiskr — APPROVED** [review]
👋🏼 Hi @barrymcgee , this looks pretty great. I think this checks one or two boxes in https://github.com/github/docs/issues/141 as well.

We have an automated accessibility script we run once a day, `pa11y-ci` in the repo as well. I checked out this branch and ran `npm run pa11y-test` on it. I'm seeing the form issue you've mentioned:

```
 • This form does not contain a submit button, which creates issues for those
   who cannot submit the form using the keyboard. Submit buttons are INPUT
   elements with type attribute "submit" or "image", or BUTTON elements with
   type "submit" or omitted/invalid.

   (html > body > main > div:nth-child(1) > header > div:nth-child(2) > div >
   div > div > div:nth-child(2) > div:nth-child(2) > form)

   <form class="mb-0"> <div id="search-input-contai...</form>
```

I think this is coming from https://github.com/algolia/instantsearch.js/. That said, the actual form element in question is here:
https://github.com/github/docs/blob/main/includes/search-form.html So I think we could move up the `aria-hidden` to the form element and no longer get that message.

But this is definitely an upgrade as is.

**Comment by barrymcgee** [comment]
@heiskr Thank you for your review! I've made your suggested change and the `pa11y-test` check now passes without error.

**Comment by heiskr** [comment]
It looks like the heading level change had the side effect of breaking a few "rendering" tests

**Comment by Geno2tattedXXX** [comment]
> This PR is stale because it has been open 7 days with no activity and will be automatically closed in 3 days. To keep this PR open, update the PR by adding a comment or pushing a commit.

Cool beans,@smd

**Comment by Geno2tattedXXX** [comment]
Gang Gang

**Comment by barrymcgee** [comment]
@heiskr Sorry, now rebased and all fixed up.

**Comment by chiedo** [comment]
Thanks for the contribution @barrymcgee!

**Pull request merged**
