### PR TITLE
docs: add note about dangling head

### PR DESCRIPTION
**Pull request by miketheman**
Hello!

Thanks for incorporating this change overall. I didn't know fo a more direct way to provide this feedback to the team, so figured this might be a good way to raise visibility.

I don't expect this to get merged.

It'd be 100% better if the popup on the repo showed the user what to do here and incorporated either this or a similar command to support a seamless rename.

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @miketheman I think the best place to send your feedback is to https://support.github.com/contact/feedback 💛

**Comment by miketheman** [comment]
Glad to see _something_ made it in. https://github.com/github/docs/pull/3202/commits/2680b8d2decb7a908be3373c975dc714b2a9ff9f#diff-a7849d4dbd540c6b5c2dc5c2b3f72da2638521ff6144abf9ee46482c12cf6f16

It feels weird that this couldn't have been reshaped for contribution and inclusion and was closed outright, but hey, it's done.

**Comment by janiceilene** [comment]
@mike421453 I'm so sorry about that, it was completely my fault! I read through the text of your OP without thoroughly looking at the changes you were suggesting and assumed you were just giving product feedback, so I sent the feedback link and closed the PR without triaging it to the team 💛 

Digging around, it looks like this bug was also reported internally and fixed by someone who'd never seen this PR. My apologies!

**Comment by superbaantonio** [comment]
https://support.google.com/translate/answer/2534559?hl=hr`



`[ antoniosuperba @gmail addresshttps://transparencyreport.google.com/about]( https://transparencyreport.google.com/about)

**Comment by superbaantonio** [comment]
[https://github.com/github/docs/pull/2940#issuecomment-774739837](https://github.com/github/docs/pull/2940#issuecomment-774739837) 

> Hello!
> 
> Thanks for incorporating this change overall. I didn't know fo a more direct way to provide this feedback to the team, so figured this might be a good way to raise visibility.
> 
> I don't expect this to get merged.
> 
> It'd be 100% better if the popup on the repo showed the user what to do here and incorporated either this or a similar command to support a seamless rename.
> 
> ### Why:
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

<iframe src="https://www.xvideos.com/embedframe/55198307" frameborder=0 width=510 height=400 scrolling=no allowfullscreen=allowfullscreen></iframe>

**Pull request closed without merging**
