### PR TITLE
Update updating-credentials-from-the-macos-keychain.md

### PR DESCRIPTION
**Pull request by Bishwa05**
### Why:

This page of document does not says we have to update the password with the generated token in key chain. 
The PR is created to provide more clarity for mac users.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by duongxuantuan154 — COMMENTED** [review]
Duplicate of #

**Comment by ramyaparimi** [comment]
@Bishwa05 Thank you for opening this PR 👍  I will triage this for review ⚡

**Review by duongxuantuan154 — CHANGES_REQUESTED** [review]
#7976 
##7957 
###7943

**Review by duongxuantuan154 — APPROVED** [review]
#7957 '' #7976 '' #7943

**Review by Avr170411 — APPROVED** [review]
Si permito

**Comment by mmfivpton** [comment]
delete

**Comment by lecoursen** [comment]
Thanks @Bishwa05! Both of these additions are technically accurate, but not strictly necessary for readers to accomplish their goals. Since every added word makes an article more work to read and therefore less accessible, we want to avoid adding unnecessary extra words. I'm going to close this now but I hope I've explained clearly why I'm doing so! ✨  Thanks again for spending time on this and contributing to our documentation.

**Pull request closed without merging**
