### PR TITLE
Add OpenID Connection configuration for Alibaba Cloud

### PR DESCRIPTION
**Pull request by JacksonTian**
### Why:

Closes: 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by JacksonTian** [comment]
Why can't contribute the `content/actions/deployment/security-hardening-your-deployments/**`.

**Comment by JacksonTian** [comment]
Hope someone can help me.

**Comment by JacksonTian** [comment]
@cmwilson21 Thank you for your feedback.

**Comment by JacksonTian** [comment]
Hello, any feedbacks?

**Comment by SiaraMist** [comment]
Hey @JacksonTian, thank you so much for writing this article and opening an PR to add it to our docs! ✨ 

Do you know if there is any Alibaba doc that can be cross referenced for GitHub OIDC integration? After checking with our engineering team, we are hoping to use this to internally verify an Alibaba set up.

**Comment by JacksonTian** [comment]
Hello @SiaraMist . The article <https://www.alibabacloud.com/help/en/ram/user-guide/overview-of-oidc-based-sso> describe how to use OIDC on Alibaba Cloud.

And we have a GitHub Action <https://github.com/aliyun/configure-aliyun-credentials-action> to integrate with GitHub OIDC.

Thanks for your feedback.

**Comment by SiaraMist** [comment]
Hey @JacksonTian, thank you so much for your patience as the team works through our backlog. 💛 

I took your PR and the configuration documents you sent back to the team for review. They suggested that we add links to the Alibaba Cloud information from another article instead of adding this new one. I've gone ahead and opened a PR for that, and you can see the Alibaba Cloud mentions [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#using-official-actions) and [here](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#accessing-resources-in-your-cloud-provider). 

I'm going to close out this PR in favor of those changes. We really appreciate your thoughtful contribution to the GitHub docs. ✨

**Pull request closed without merging**
