### PR TITLE
Update github-community-guidelines.md

### PR DESCRIPTION
**Pull request by Pcharlesme**
Emphasized key points

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@Pcharlesme Thank you for opening a PR! ✨ 

> Emphasized key points

Can you expand on why you made these updates, and what you feel they add to this doc? 💛

**Comment by Pcharlesme** [comment]
@nguyenalex836 Thank you 
 Why: Simplifying language makes the document more accessible to a wider audience. Even though the topic is technical, it's important that both technical and non-technical readers can grasp the concepts quickly, This is particularly important for a policy or guideline document, where clarity and focus are critical
 
What it adds: By using straightforward terms like "We prioritize" instead of "We optimize for," it reduces cognitive load

**Comment by nguyenalex836** [comment]
@Pcharlesme Thank you for your elaboration! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@Pcharlesme Thank you for your patience! After discussion, our team determined you will need to open a contribution within the [Site Policy](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md) repository, as their team will need to approve your PR 💛 

I'll go ahead and close this issue. Thank you for your desire to contribute to our docs!

**Pull request closed without merging**
