### PR TITLE
Replace old unsubscribe image with the latest one

### LINKED ISSUE #10320: Unsubscribe art positioning appears stale
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unsubscribing-from-notifications-in-your-inbox

### What part(s) of the article would you like to see updated?

This art does not appear to match what I see:
Drop down

For me, the `unsubscribe` and `done` buttons are no longer in a drop down.

### Additional information

_No response_

---
Edited by maintainer 

Step 3 in [this section](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unsubscribing-from-notifications-in-your-inbox) of the article should be replaced with the below screenshot to match current usage.

image

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #10320 

### What's being changed:

The image in step 3 of [this doc](https://docs.github.com/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions#unsubscribing-from-notifications-in-your-inbox)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@thispsj Thanks for opening this PR! Are you still working on this one? I am not able to see any files that are changed yet !!

**Comment by thispsj** [comment]
@ramyaparimi Oh yes ! I forgot to update the corresponding file 😅

**Review by ramyaparimi — CHANGES_REQUESTED** [review]
@thispsj Thanks so much for the fix ✨ Could you please reduce the size of the screenshot to look something like this? That way, the focus is more **unsubscribe** button 🐬 
image

**Comment by thispsj** [comment]
> @thispsj Thanks so much for the fix ✨ Could you please reduce the size of the screenshot to look something like this? That way, the focus is more **unsubscribe** button 🐬 image

@ramyaparimi Done :+1:

**Review by ramyaparimi — APPROVED** [review]
@thispsj 
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Pull request merged**
