### PR TITLE
Update secret scanning docs

### PR DESCRIPTION
**Pull request by lucie-docs**
### Why:

Closes https://github.com/github/docs-content/issues/5712 

### What's being changed:

Screenshots at step 4 and 5 for `ftp` and `ghec`.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by mchammer01** [comment]
I took a look at this PR and contacted @lucie-docs via Slack about versioning matters.

**Comment by lucie-docs** [comment]
@mchammer01 So I think the versioning worked but somehow now the deployment fails haha. Not sure what `Error: Process completed with exit code 1.` refers to?

**Review by mchammer01 — APPROVED** [review]
@lucie-docs - LGTM ✨ 
Thanks for implementing the suggested versioning 💖

**Comment by mchammer01** [comment]
I'll take a look 👀

**Comment by mchammer01** [comment]
This is ready to merge once we know more why `Staging - Deploy PR` is failing.

**Pull request merged**
