### PR TITLE
Fix typo in pages/verifying custom domain

### LINKED ISSUE #29169: Typo in Pages/Verify Custom Domains
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

### What part(s) of the article would you like to see updated?

image

Verifying is spelt incorrectly as Veryifying

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by GinOwO**
Fixed typo from Veryifying -> Verifying on line 17

### Why:

Closes: #29169

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Changed Veryifying to Verifying
image

to

image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by SiaraMist — APPROVED** [review]
Thank you for fixing this typo! 🚀

**Comment by GinOwO** [comment]
uhh @SiaraMist any idea why it failed a check?

**Comment by SiaraMist** [comment]
@GinOwO I think it was a bug, but now it's fixed and we were able to merge this successfully! 🎉

**Comment by smoothzebra** [comment]
ในวันที่ พ. 18 ต.ค. 2023 02:43 น. Siara ***@***.***> เขียนว่า:

**Pull request merged**
