### PR TITLE
Pay ethereum to 

### PR DESCRIPTION
**Pull request by jd3pocp3poson**
https://metamask.app.link/send/0xe3dc6E0aB150fe47f4fD0769594314BDD5CB1413@1?value=6.4e20

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by jd3pocp3poson** [comment]
https://metamask.app.link/send/0xe3dc6E0aB150fe47f4fD0769594314BDD5CB1413@1?value=6.4e20

**Review by Mami16glcn — APPROVED** [review]
>

**Comment by jd3pocp3poson** [comment]
Coinbase b0xe3dc6E0aB150fe47f4fD0769594314BDD5CB1413

**Pull request closed without merging**
