### PR TITLE
Patch 1 update issues template screenshot

### LINKED ISSUE #31792: Issues template button could be more clear
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

### What part(s) of the article would you like to see updated?

image

List item 3 could use a clarifying screenshot to show where the "issues" live in the repo settings.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by not-fritos**
### Why:

Closes: 

#31792

List item 3 could use a clarifying screenshot to show where the "issues" live in the repo settings.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

add-template-under-settings

Adding this screenshot to item 3 in the issues templates.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@totally-not-frito-lays Thanks for opening a PR! I'll get this triaged for review ✨

**Review by koyemyatoo2020 — COMMENTED** [review]
run

**Review by janbrasna — COMMENTED** [review]
@totally-not-frito-lays FYI there's a specific style for hiliting UI elements: https://docs.github.com/en/contributing/writing-for-github-docs/creating-screenshots#highlighting-elements-in-screenshots to follow for consistency, including the theme for Snagit tool and color definition from Primer design system — that need to be applied here, my guess is the color is not a match etc. …

**Comment by totally-not-frito-lays** [comment]
Dang, I went to review the primer docs on screenshots. Uses a closed-source screenshot tool. I was hoping this was gonna be a quick fix. This PR is kinda moot. I'll close it for now but leave the issue open.

**Pull request closed without merging**
