### PR TITLE
Update to include mention of SQL query generation

### PR DESCRIPTION
**Pull request by toolboc**
### Why:

We focus primiarly on code generation features, but mention of database query support is not provided.  Copilot absolutely supports this capability see:
* https://content.dsp.co.uk/does-github-copilot-fly-with-pl/sql

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Include messaging to provide awareness of copilot support for database query generation

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@toolboc Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by toolboc** [comment]
#sign-off

**Comment by shamankayka** [comment]
root me

**Review by jules-p — APPROVED** [review]
Hi @toolboc, thanks for opening this! I've made a tiny adjustment, but I will get this PR merged for you now.

**Pull request merged**
