### PR TITLE
Fix docs for adding ssh key for commit signing

### LINKED ISSUE #20114: SSH commit signing: Missing "key::" prefix for literal key in setup instructions
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

### What part(s) of the article would you like to see updated?

Step 4 of "Telling Git about your SSH key" configures the signing key incorrectly. When using the literal contents of a key, the config value needs to be prefixed with "key::", e.g.

`$ git config --global user.signingkey 'key::ssh-ed25519 AAAAC3(...) user@example.com'`

With a key residing in a file, the path to the key can be provided (without a prefix).

See also https://lore.kernel.org/git/20220628162342.ootjobbjtxg7b7ay@fs/t/

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by shuklaayush**
The config command expects a path to the private/public key and needs to be prefixed with `key::` when using the public key directly 
ref: https://git-scm.com/docs/git-config#Documentation/git-config.txt-usersigningKey

### Why:

Closes [20114](https://github.com/github/docs/issues/20114)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@shuklaayush thanks for opening a PR! It looks like someone opened an issue about this yesterday, so I'm going to edit your post to link the two of them together. 

I'll get this triaged for review! ⚡

**Comment by 0649044724** [comment]
ทำไม่เป็นคนแบบนี้เห็นแกได้ประโยคของคนอื่น

**Review by robookwus — COMMENTED** [review]
Hey I'd like to help with the docs

**Review by rachaelrenk — APPROVED** [review]
Looks good! ✨ Thank you for making this update.

**Pull request merged**
