### PR TITLE
kbd shortcuts updated

### PR DESCRIPTION
**Pull request by parassaini29**
### Why:
Since, in the issue #13900 it was mentioned that the kbd shortcuts are not according to updated version to meet github docs style.

Closes [#13900 ]

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Screenshot (131)
 Updated keyboard shortcuts according to updated version to meet the requirements for github docs style as seen in the above page.

### Check off the following:

- [+] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [+] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Paras-Saini Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by heiskr** [comment]
Asked another team member, we're good with the `<kbd>` but we would like to keep the indentation as it was, if it would be possible to revert the indentation change.

**Review by heiskr — APPROVED** [review]

**Comment by cmwilson21** [comment]
👋 @Paras-Saini Would you mind adding the indention back in per the comment above? Then we can get this merged down ✨

**Comment by Paras-Saini** [comment]
Yeah, sure,,i'll do it.

**Comment by Paras-Saini** [comment]
Thank you @cmwilson21 I have learned many things through github docs, thank you for this beautiful community.

**Comment by cmwilson21** [comment]
@Paras-Saini Thank you for contributing to it! 💖

**Pull request merged**
