### PR TITLE
fix broken tables in permission requirements

### PR DESCRIPTION
**Pull request by shogo82148**
### Why:

The table in "Permission requirements for security features" section is broken.

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#permission-requirements-for-security-features

image

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@shogo82148 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by shogo82148** [comment]
It looks fine. https://docs-8724--patch-2.herokuapp.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#permission-requirements-for-security-features

image

**Comment by shogo82148** [comment]
oops, it is still broken with ghes 2.22

https://docs-8724--patch-2.herokuapp.com/en/enterprise-server@2.22/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

image

**Comment by shogo82148** [comment]
fixed

https://docs-8724--patch-2.herokuapp.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization
image

https://docs-8724--patch-2.herokuapp.com/en/enterprise-server@2.22/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization
image

**Comment by lucascosti** [comment]
Thanks for noticing this @shogo82148, and for providing a fix, but it looks like someone internally has already fixed this in https://github.com/github/docs/commit/b42910e0fbb1b173dcb2fecb1687ccaeea609d94 🙂

**Comment by youngkinglo** [comment]
3057083318

**Pull request closed without merging**
