### PR TITLE
docs: include subdirectories note

### PR DESCRIPTION
**Pull request by jef**
### Why:

To match the other documentation in `CODEOWNERS`.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a pull request @jef! I'll triage this for review 💖

**Review by felicitymay — APPROVED** [review]
👋🏻 Hi @jef - thanks for raising this pull request.

Your change looks good to me 😄

**Comment by felicitymay** [comment]
Once the tests have passed on the updated branch, this will be ready to merge ✨

**Comment by jef** [comment]
@all-contributors please add @jef for documentation

**Comment by felicitymay** [comment]
Not sure why the allcontributors bot's not happy. I'll ask for help.

**Comment by jef** [comment]
Definitely not pressing. Thanks for the help!

**Pull request merged**
