### PR TITLE
Add Alternate Method of Skipping CI Checks to "About Status Checks" page

### PR DESCRIPTION
**Pull request by Julian88Tex**
### Why:

Relevant ways to skip checks/workflows are not listed in a logical document that explains only one of the two methods currently.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Julian88Tex Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Julian88Tex** [comment]
@cmwilson21 thanks! Anything else you need from me?

**Comment by sophietheking** [comment]
@Julian88Tex Thanks for opening this PR and contributing to our Docs! 💖 I've made a slight change to your addition. I'll update the branch and get this merged once tests are passing 🍏.

**Review by sophietheking — DISMISSED** [review]

**Review by sophietheking — APPROVED** [review]

**Comment by Julian88Tex** [comment]
> @Julian88Tex Thanks for opening this PR and contributing to our Docs! 💖 I've made a slight change to your addition. I'll update the branch and get this merged once tests are passing 🍏.

got it thanks!

**Pull request merged**
