### PR TITLE
Update personalizing-your-profile.md

### PR DESCRIPTION
**Pull request by Pathum-lakshan**
### Why:

Closes ISSUE

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Pathum-lakshan** [comment]
please aprove

**Comment by mlkmooeeeed** [comment]
> ### Why:
> Closes ISSUE
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

**Comment by mlkmooeeeed** [comment]
pathum-lakshan:patch-1

**Review by mlkmooeeeed — COMMENTED** [review]
pathum-lakshan:patch-1

**Comment by mlkmooeeeed** [comment]
pathum-lakshan:patch-1

**Comment by mlkmooeeeed** [comment]
From 996133fb58e470f9cccb22eed44039b745fc80d5 Mon Sep 17 00:00:00 2001
From: Pathum Lakshan <54094629+Pathum-lakshan@users.noreply.github.com>
Date: Sun, 1 Jan 2023 20:22:36 +0530
Subject: [PATCH] Update personalizing-your-profile.md

---
 .../customizing-your-profile/personalizing-your-profile.md      | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md b/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
index 2d9b69cef292..0573318cb4b5 100644
--- a/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
+++ b/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
@@ -18,7 +18,7 @@ versions:
 topics:
   - Profiles
 shortTitle: Personalize
----
+----
 ## Changing your profile picture
 
 Your profile picture helps identify you across {% data variables.product.product_name %} in pull requests, comments, contributions pages, and graphs.

**Review by mlkmooeeeed — COMMENTED** [review]
From 996133fb58e470f9cccb22eed44039b745fc80d5 Mon Sep 17 00:00:00 2001
From: Pathum Lakshan <54094629+Pathum-lakshan@users.noreply.github.com>
Date: Sun, 1 Jan 2023 20:22:36 +0530
Subject: [PATCH] Update personalizing-your-profile.md

---
 .../customizing-your-profile/personalizing-your-profile.md      | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md b/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
index 2d9b69cef292..0573318cb4b5 100644
--- a/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
+++ b/content/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile.md
@@ -18,7 +18,7 @@ versions:
 topics:
   - Profiles
 shortTitle: Personalize
----
+----
 ## Changing your profile picture
 
 Your profile picture helps identify you across {% data variables.product.product_name %} in pull requests, comments, contributions pages, and graphs.

**Comment by mlkmooeeeed** [comment]
> ### Why:
> Closes ISSUE
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

**Comment by mlkmooeeeed** [comment]
pathum-lakshan:patch-1

**Comment by cmwilson21** [comment]
This seems to have been opened accidentally, I am going to close it now :yellow_heart: 

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

**Pull request closed without merging**
