### PR TITLE
Update add-ssh-key-to-ssh-agent documentation

### PR DESCRIPTION
**Pull request by GuillaumeBAECHLER**
### Why:

Update the add-ssh-key-to-ssh-agent documentation with the new key generation algorithm used in ssh key creation step (ed25519)

### What's being changed:

Replaced `id_rsa` with `id_ed25519` in :
- data/reusables/ssh/add-ssh-key-to-ssh-agent-commandline.md
- data/reusables/ssh/add-ssh-key-to-ssh-agent.md

### Check off the following:
- [ ] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @GuillaumeBAECHLER Thank you so much for opening a PR! Some of the updates in this PR are already being addressed in https://github.com/github/docs/pull/1063. Would you mind removing the duplication? 💖

**Comment by GuillaumeBAECHLER** [comment]
Hi @janiceilene ! Can't find any duplication in the linked PR, the files concerned are not the same. Btw, I find there are a lot of PRs for this topic now. So we can close this PR if you want to address all changes linked to ed25519 documentation in a single one. 😄

**Review by shati-patel — APPROVED** [review]
Thank you for the pull request @GuillaumeBAECHLER! 


To come back to this: 

> Can't find any duplication in the linked PR, the files concerned are not the same. Btw, I find there are a lot of PRs for this topic now. So we can close this PR if you want to address all changes linked to ed25519 documentation in a single one. 😄

You're right, there are quite a few similar PRs 😅 I'm working my way through them in reverse chronological order. Yours is one of the first, so I'll merge this and close any later duplicates 🎉

**Comment by mmfivpton** [comment]
`set=0
get
set`

**Pull request merged**
