### PR TITLE
IDR/Bitcoin

### PR DESCRIPTION
**Pull request by Daudbpp2021**
### Why:

**Closes [issue link]**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by Daudbpp2021** [comment]
My Otorisation all CoinCyrptocurrance and no everyone

**Review by Daudbpp2021 — COMMENTED** [review]
Finish review back on

**Comment by Daudbpp2021** [comment]
Open Transactions bank Mandiri 1055666344

**Comment by Daudbpp2021** [comment]
Bank BNI 1055666344

**Comment by Daudbpp2021** [comment]
Open transactions account Bank Mandiri 1055666344

**Comment by 4393445** [comment]
ในวันที่ จ. 10 พ.ค. 2021 06:53 น. Daudbpp2021 ***@***.***>
เขียนว่า:

**Comment by 4393445** [comment]
ในวันที่ จ. 10 พ.ค. 2021 06:57 น. Daudbpp2021 ***@***.***>
เขียนว่า:

**Pull request closed without merging**
