### PR TITLE
Fix extra space in `CODE_OF_CONDUCT.md`.

### PR DESCRIPTION
**Pull request by tylermilner**
### Why:

Closes: N/A

After running the GitHub Super Linter against my repo that contained a copy of the default `CODE_OF_CONDUCT.md`, I noticed that it fixed a spot in the "Permanent Ban" section where there was an extra space.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removed extra space in the `### 4. Permanent Ban` section. See screenshot below:

code-of-conduct-fix-extra-space

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@tylermilner Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by Trungga64** [comment]
> ### Why:
> Closes: N/A
> 
> After running the GitHub Super Linter against my repo that contained a copy of the default `CODE_OF_CONDUCT.md`, I noticed that it fixed a spot in the "Permanent Ban" section where there was an extra space.
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Removed extra space in the `### 4. Permanent Ban` section. See screenshot below:
> 
> code-of-conduct-fix-extra-space
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
###

**Comment by Klein550** [comment]
> ### Why:
> Closes: N/A
> 
> After running the GitHub Super Linter against my repo that contained a copy of the default `CODE_OF_CONDUCT.md`, I noticed that it fixed a spot in the "Permanent Ban" section where there was an extra space.
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> Removed extra space in the `### 4. Permanent Ban` section. See screenshot below:
> 
> code-of-conduct-fix-extra-space
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

**Review by invisiblepancake — COMMENTED** [review]
seewhatyoumean.has.something.to.do.with.workflows.and.people.are.still.learning

**Review by Fool256 — COMMENTED** [review]
Fool Bar

**Review by CosmicJesterX — COMMENTED** [review]
looks nice? 8)

**Comment by silsilaenoorzahra-dotcom** [comment]
[silsilaenoorzahra-dotcom_noor_c65121.json](https://github.com/user-attachments/files/28923515/silsilaenoorzahra-dotcom_noor_c65121.json)

**Pull request merged**
