### PR TITLE
Update gmail-buttons.png

### LINKED ISSUE #20325: Update Gmail buttons screenshot
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Configuring notifications](https://docs.github.com/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#customizing-your-email-notifications)

### What part(s) of the article would you like to see updated?

Customizing your email notifications, the `gmail-buttons.png` screenshot does not reflect how Gmail currently looks.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aisgbnok**
### Why:

- Closes #20325

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updating the `gmail-buttons.png` to reflect current look of Gmail and show more buttons.

### Check off the following:

- [X] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by aisgbnok** [comment]
Should I update this:

https://github.com/github/docs/blob/b21369d527bdc4b8cf5a0defa9da075172bda3fb/content/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications.md?plain=1#L102

To say something like: "..to visit the original issue, pull request, release, or commit that generated..."?

**Comment by cmwilson21** [comment]
@aisgbnok Thanks for submitting a PR and linking it to your issue! 💖 

I'll get this triaged for review! ⚡

**Review by PIYUSH-MISHRA-00 — COMMENTED** [review]
a more clear and bigger image for better understanding

**Review by Abhinavkar — COMMENTED** [review]
Nice one

**Review by cmwilson21 — APPROVED** [review]
This looks great!

**Comment by cmwilson21** [comment]
@aisgbnok Thanks for updating this image. I appreciate you taking the time to make sure this one is very clear while blurring out the personal emails. Regarding your other question, I think the wording still communicates what a user can expect to find, so we'll leave that as is for now. 🎉 

Thanks again for your interest and passion for improving GitHub docs! 💖

**Pull request merged**
