### PR TITLE
Update MIT License year from `2022` -> `2023`

### PR DESCRIPTION
**Pull request by yusufsheiqh**
### Why:

- Year in MIT License is outdated.

Closes: N/A

### What's being changed (if available, include any code snippets, screenshots, or gifs):

- Year is updated; `2022` -> `2023`.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by ivannggnnavi — COMMENTED** [review]
Too

**Comment by ivannggnnavi** [comment]
Jj

**Review by cmwilson21 — APPROVED** [review]

**Comment by cmwilson21** [comment]
@yusufsheiqh Thanks for the PR! Great catch

I'll get this merged once the tests have all passed ✅

**Review by ecemce326 — COMMENTED** [review]
****### #

**Comment by McCollum2024** [comment]
> ### Why:
> 
> - Year in MIT License is outdated.
> 
> Closes: N/A
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> - Year is updated; `2022` -> `2023`.
> 
> ### Check off the following:
> 
> - [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.
> 
>   - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> - [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
>

**Review by McCollum2024 — COMMENTED** [review]
no

**Review by Rabbeahimed — COMMENTED** [review]
Raddi

**Review by CuTungBo88 — COMMENTED** [review]
Ok

**Pull request merged**
