### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by YJ8CJY3MRGJ7MLLT9H3Q**
### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Review by SMAKSS — COMMENTED** [review]
Looks like spam. 😶

**Comment by YJ8CJY3MRGJ7MLLT9H3Q** [comment]
في الأحد، ٨ نوفمبر ٢٠٢٠ ٢:٤٣ م iwaki710 <notifications@github.com> كتب:

**Comment by YJ8CJY3MRGJ7MLLT9H3Q** [comment]
863946

في الأحد، ٨ نوفمبر ٢٠٢٠ ٣:٣٧ م Qwe Asd <asdq59486@gmail.com> كتب:

**Comment by iwaki710** [comment]
これからの私の人生の希望になります。

**Comment by DboyRedd** [comment]
Try again

**Comment by DboyRedd** [comment]
> ### Why:
> ### What's being changed:
> ### Check off the following:
> * [x]  All of the tests are passing.
> * [x]  I have reviewed my changes in staging.
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Review by walid161hatam — APPROVED** [review]

**Review by Suhandissss — COMMENTED** [review]
#1115

**Pull request closed without merging**
