### PR TITLE
add missing article before "account" to sentence

### PR DESCRIPTION
**Pull request by ghost**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ramyaparimi — APPROVED** [review]
@karlpilgram-oviva 
Thanks so much for opening a PR with this fix! Our repo is currently frozen until early January. I will get this merged once the repo is unfrozen 🧊  🍏

**Comment by Wadewas74** [comment]
https://github.com/github/docs/pull/13563#issuecomment-1003488695

**Review by Wadewas74 — COMMENTED** [review]
Ok

**Comment by masumh** [comment]
Please help me

**Comment by karlpilgram-oviva** [comment]
> @karlpilgram-oviva Thanks so much for opening a PR with this fix! Our repo is currently frozen until early January. I will get this merged once the repo is unfrozen 🧊 🍏

Thank you  ✨  I'm really happy to hear that.

**Pull request merged**
