### PR TITLE
Request to support

### PR DESCRIPTION
**Pull request by Moazzem-Hossain-pixel**
### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks for your contributions

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks for your contributions.

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks for your contributions.

**Comment by Farzineeee** [comment]
You're welcome 😎

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
I will glad if you can take the needed action. 
Thanks

**Comment by Moazzem-Hossain-pixel** [comment]
Great

**Comment by Moazzem-Hossain-pixel** [comment]
Great!

**Comment by Moazzem-Hossain-pixel** [comment]
Thanks for the impact

**Comment by Hayzlee11** [comment]
Hi Github/Docs

Jami Schmidt

**Pull request closed without merging**
