### PR TITLE
Fix: Fixed small typo in script/README file

### PR DESCRIPTION
**Pull request by bobychaudhary**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ramyaparimi — APPROVED** [review]
@bobychaudhary 
Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Review by skidrow123456 — COMMENTED** [review]
Lost

**Comment by bobychaudhary** [comment]
What "Lost" ?

**Review by MarianoRui — COMMENTED** [review]
@
Aprobado 
>

**Review by Notfoyou0 — COMMENTED** [review]
Duplicate of #

**Review by MarianoRui — COMMENTED** [review]
Ok

**Comment by ramyaparimi** [comment]
@bobychaudhary I spoke with the team and want to let you know that changes to `script/` directory are not accepted. I am going to close this PR now and apologize for the confusion 💛 

Thanks so much for contributing to our docs 💖

**Pull request closed without merging**
