### PR TITLE
Add a research paper about GitHub Discussions to Further reading

### PR DESCRIPTION
**Pull request by hideakihata**
### Why:

Share the results of an empirical study on GitHub Discussions with GitHub users.

### What's being changed:

Add a paper reference to Further reading.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Eltoro69** [comment]
> ### Por qué:
> Comparta los resultados de un estudio empírico sobre las discusiones de GitHub con los usuarios de GitHub.
> 
> ### Qué se está cambiando:
> Agregue una referencia en papel a la lectura adicional.
> 
> ### Marque lo siguiente:
> * [x] He revisado mis cambios en la puesta en escena (busque "Comentario generado automáticamente" y haga clic en **Modificado** para ver sus últimos cambios).
> * [x] Para cambios de contenido, he completado la [lista de verificación de autoevaluación](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review) .
> 
> ### Impacto del escritor (esta sección es solo para miembros del personal de GitHub):
> * [ ]  Esta solicitud de extracción afecta la experiencia de contribución
>   
>   * [ ]  He añadido la etiqueta "impacto del escritor".
>   * [ ]  Agregué una descripción o un video de demostración de los cambios a continuación (por ejemplo, un "video de antes y después")

**Comment by ramyaparimi** [comment]
@hideakihata 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by mchammer01** [comment]
I'll review this 🙂

**Comment by b4mboo** [comment]
@hideakihata Thanks again for opening this pull request. We generally try to stay away from linking out to external resources as much as possiple, though I realize that your paper seems to be the result of throrough research, is well written, doesn't have any obvious ties to anyone who might profit financially from it, and also comes with some solid suggestions for how to adopt GitHub Discussions. 
I still need to discuss this with some other folks in our organization next week, but I wanted to give you a heads up that we're leaning towards not including this paper in our documentation.
However, since I personally think this paper could be a valuable resource, would you be OK with me pointing it out to our marketing and research team, such that they can reach out to you if they're interested in using it in some way?

**Comment by hideakihata** [comment]
Thank you very much for your kind attention to this matter. Actually, I had received an email from the product manager at GitHub Discussions for an earlier version of this paper that I had uploaded to arXiv. I also heard that some co-authors, who live in Europe, gave a talk about this research at GitHub.

I hope to not only connect with the GitHub teams, but also inform GitHub users about this research. Now I understand the policy of not linking external resources in the documentation. I would like to explore what we can do as open science.

**Comment by b4mboo** [comment]
>I had received an email from the product manager at GitHub Discussions for an earlier version of this paper that I had uploaded to arXiv

I'm glad to hear that you are already in contact with the respective product manager. ✨ 
As expected, the consensus on the Docs team is to rather not include external references like this one. Hence, I'm going to respectfully close this pull request. Thanks for understanding.

**Pull request closed without merging**
