### PR TITLE
Change the color of the warning links

### LINKED ISSUE #5349: Blue link text in notices is unreadable due to blue background
### What is the current behavior?

Screen Shot 2021-04-13 at 7 05 58 PM

### What changes are you suggesting?

Use a more visible link color in notices.

### PR DESCRIPTION
**Pull request by lucalves**
### Why:

As reported in Issue #5349, the color of the link in the notices is unreadable due to the blue background. 
I changed it to the color `-color-bg-info` of [premier.style](https://primer.style/css/support/color-system#backgrounds).

With the change, it will look like this:

link-color

This will also affect documentation in [Portuguese](https://docs.github.com/pt), [Spanish](https://docs.github.com/es) and [Japanese](https://docs.github.com/ja), in addition to [Chinese](https://docs.github.com/cn).

**Closes #5349**.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by heiskr** [comment]
I suspect we want to change the background color of the banner instead of the link color. 🙏🏼

**Comment by lucalves** [comment]
> I suspect we want to change the background color of the banner instead of the link color. 🙏🏼

Hi, @heiskr! I tested it by changing the background color and it really got better. However, I am not allowed to make this change, since the `.css` file that enables this change is inside the `/dist` folder and this folder is in the project's `.gitignore` file.

What to do in this situation?

**Comment by heiskr** [comment]
I think the file you want to update is `includes/header-notification.html`, `color-bg-info-inverse`

**Comment by lucalves** [comment]
> I think the file you want to update is `includes/header-notification.html`, `color-bg-info-inverse`

You're right, thanks. It includes the necessary changes.

**Review by heiskr — APPROVED** [review]

**Pull request merged**
