### PR TITLE
Add GitHub Actions icon in reusable

### PR DESCRIPTION
**Pull request by AnilSeervi**
### Why:

Closes [issue link]

### What's being changed:
- Adds GitHub Actions (play) icon to the reusable

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@AnilSeervi 
Thanks for opening a PR :+1: Please fill out "why" and "what's being changed" in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

**Comment by AnilSeervi** [comment]
> @AnilSeervi Thanks for opening a PR 👍 Please fill out "why" and "what's being changed" in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

it is filled out.

**Comment by ramyaparimi** [comment]
@AnilSeervi 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for this PR! Our repo is frozen until early January, but we will merge this for you once the freeze lifts.

**Comment by AnilSeervi** [comment]
> Thanks for this PR! Our repo is frozen until early January, but we will merge this for you once the freeze lifts.

Sure, No problem.

**Pull request merged**
