### PR TITLE
Properly capitalize "macOS"

### LINKED ISSUE #1155: "macOS" should always be properly capitalized
### What article on docs.github.com is affected?

This affects several articles and one reusable note:

- [About actions](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions)
- [About self-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners)
- [Specifications for GitHub-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners)
- [Running CodeQL code scanning in a container](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/running-codeql-code-scanning-in-a-container)
- [Running CodeQL code scanning in your CI system](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/running-codeql-code-scanning-in-your-ci-system)
- [macos-runner-preview.md](https://github.com/github/docs/blob/main/data/reusables/github-actions/macos-runner-preview.md)

### What part(s) of the article would you like to see updated?

The name of Apple's desktop operating system should always be capitalized with a lowercase "m", like this:

> macOS

You can see this on Apple's website: [macOS Catalina](https://www.apple.com/macos/catalina/)

### PR DESCRIPTION
**Pull request by stephenwade**
### Why:

The name of Apple's desktop operating system should always be capitalized with a lowercase "m", like this:

> macOS

Issue #1155

### What's being changed:

Change all occurrences of "MacOS" to "macOS".

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening an issue and PR @stephenwade! I'll get this triaged for review 🎉

**Comment by stephenwade** [comment]
@janiceilene Just recreated this to remove any edits to the translations folder. I understand that content in this folder can't be changed with a PR.

**Comment by janiceilene** [comment]
Thanks so much @stephenwade!

**Comment by stephenwade** [comment]
not stale. cc: @janiceilene

**Comment by janiceilene** [comment]
@stephenwade You're right, it's not stale! Thanks for your patience 💛  Our small team is working our way through reviewing all of the amazing contributions ✨

**Review by shati-patel — APPROVED** [review]
Thank you for the contribution, @stephenwade! You're absolutely right about the capitalization 😄 

Apologies for the initial delay, but we'll get this merged shortly!

**Pull request merged**
