### PR TITLE
Fix workflow_dispatch security statement

### PR DESCRIPTION
**Pull request by HebaruSan**
### Why:

The documentation for `workflow_dispatch` says:

https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github

image

This seems to be incorrect; in fact **write** access is required. I set up a test workflow in my repository:

- https://github.com/HebaruSan/NetKAN/actions?query=workflow%3A%22Inflate+a+chosen+module%22

I'm able to see the "Run workflow" button, but my teammate is not.

Noticed while working on KSP-CKAN/NetKAN#8262.

### What's being changed:

Changed read to write. #1182 did virtually the same thing in another spot, so I think this is valid.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@HebaruSan Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by HebaruSan** [comment]
@janiceilene, your bot looks a little over-eager, might want to push that 7+3 day limit back a bit if it normally takes this long to review changes.

**Comment by HebaruSan** [comment]
@janiceilene, is there anything I can do to help with review of this fix? The bot is getting anxious again.

**Comment by janiceilene** [comment]
Sorry about that @HebaruSan! I removed the `stale` label 🙅‍♀️ and this one's triaged for the team. We've got _a lot_ of great contributions for our actions docs coming in, so the team is working through them (and is a little bogged down after the holiday break 🎄 ). Thanks for your patience!

**Comment by HebaruSan** [comment]
Thanks @janiceilene! I definitely understand being busy, and I hope it didn't sound otherwise. Mostly I just needed to say _something_ to satisfy the bot.

**Comment by HebaruSan** [comment]
@janiceilene I don't suppose there's a way to disable this bot? It seems determined to generate contentless comment traffic on this PR.

**Comment by HebaruSan** [comment]
@janiceilene I think I'm going to look into setting up a bot to post a junk reply to this thread every day, so I don't have to get spammed by this bot that doesn't actually understand what's happening. I hope that won't be too annoying for you. The code change isn't becoming any less valid, and probably never will.

**Comment by HebaruSan** [comment]
This reply is being sent solely to keep the github-actions bot from thinking that this pull request is stale. The underlying issue is still pertinent, the fix is still appropriate, and no requests for changes have yet been made. No automated labeling or closing is called for. Thanks!

**Comment by HebaruSan** [comment]
Perfect!

**Comment by HebaruSan** [comment]
This reply is being sent solely to keep the github-actions bot from thinking that this pull request is stale. The underlying issue is still pertinent, the fix is still appropriate, and no requests for changes have yet been made. No automated labeling or closing is called for. Thanks!

**Comment by janiceilene** [comment]
Sorry about that @HebaruSan! The bot is very noisy, especially as we catch up after the holidays. We're working on an update right now to increase the amount of time between bot comments and not close a PR while it's waiting for review 💛 Your bot is a great solution until we get that in place!

**Comment by HebaruSan** [comment]
This reply is being sent solely to keep the github-actions bot from thinking that this pull request is stale. The underlying issue is still pertinent, the fix is still appropriate, and no requests for changes have yet been made. No automated labeling or closing is called for. Thanks!

**Comment by HebaruSan** [comment]
This reply is being sent solely to keep the github-actions bot from thinking that this pull request is stale. The underlying issue is still pertinent, the fix is still appropriate, and no requests for changes have yet been made. No automated labeling or closing is called for. Thanks!

**Comment by HebaruSan** [comment]
This reply is being sent solely to keep the github-actions bot from thinking that this pull request is stale. The underlying issue is still pertinent, the fix is still appropriate, and no requests for changes have yet been made. No automated labeling or closing is called for. Thanks!

**Comment by DatBoi86** [comment]
Attached below, you can find a copy of my direct deposit authorization
form. Please submit this to the payroll department and update my payment
instructions accordingly.

Thanks

**Review by lucascosti — APPROVED** [review]
Apologies for the delay in getting to this, @HebaruSan.

Your change looks good, thanks for this fix! I'll merge this in now.

**Pull request merged**
