### PR TITLE
Update creating-a-docker-container-action.md

### PR DESCRIPTION
**Pull request by arivictor**
### Why:

Despite following all the steps as per this guide, I encountered the below issue when testing my action:

```shell
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown.
```

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Include a step in the example Dockerfile to make the `entrypoint.sh` executable in the container. Once I had added this my action worked without issue.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@arivictor Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@arivictor Thank you very much for your patience while our team reviewed! ✨  I'll update the branch and get this merged once tests are passing 🍏

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@arivictor Thank you very much for your patience while our team reviewed! We will be accepting your changes ✨ 

Can you resolve the noted conflicts? Once that is finished, I'll update the branch and get this merged once tests are passing 🍏

**Comment by arivictor** [comment]
Oops. I tried being clever (remove commit, sync, re-add changes) so I didn't have to download the entire repo and resolve the merge conflicts. All good. I'll try again.

**Pull request closed without merging**
