### PR TITLE
Consistent YAML indentation

### PR DESCRIPTION
**Pull request by hoxu**
### Why:

YAML indent in the examples is inconsistent. While not strictly unparseable, some tools complain about the indent in the examples.

**Closes [issue link]**

### What's being changed:

Change YAML indent to be consistent and follow YAML spec examples.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by hoxu** [comment]
@janiceilene done.

**Comment by erkkkkkkkkk** [comment]
S

**Review by hung1167 — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks so much @hoxu! I'll get this triaged for review ⚡

**Review by shati-patel — APPROVED** [review]
Thank you for the update, @hoxu 😃

We'll get this merged shortly!

**Pull request merged**
