### PR TITLE
Specify the same port in the loopback OAuth redirect_url

### PR DESCRIPTION
**Pull request by AlexPykavy**
### Why:

Use the same port for the loopback OAuth redirect_url both in the description and code block to avoid confusion.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@AlexPykavy Thanks for submitting a PR! Would you mind filling out the "Why" section with a short description of the change you are making? That'll make it easier for review. Then I'll get it triaged 👍

**Comment by AlexPykavy** [comment]
@cmwilson21 , updated.

**Comment by cmwilson21** [comment]
@AlexPykavy Thank you!! That's really helpful to our team to have that information. I'll get this triaged for review! ✨

**Review by skedwards88 — APPROVED** [review]
Thanks for this update! We'll get this merged for you.

**Comment by Romana100198** [comment]
ok Sent from Mail for Windows From: Sarah EdwardsSent: 8 сентября 2023 г. 22:40To: github/docsCc: SubscribedSubject: Re: [github/docs] Specify the same port in the loopback OAuth redirect_url (PR ***@***.*** approved this pull request.Thanks for this update! We'll get this merged for you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Pull request merged**
