### PR TITLE
Clarifiy that warning and error message numbers start at 1

### PR DESCRIPTION
**Pull request by Marcono1234**
### Why:

Closes [issue link]

### What's being changed:

- Clarifies that line and column number start at 1 (and not at 0)
⚠️ Actually I was not able to verify that column numbers start at 1; the GitHub web interface does not seem to use this information
- Change wording to "column <del>(`col`)</del> number <ins>(`col`)</ins>" to not separate the two words

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@Marcono1234 Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by lecoursen — APPROVED** [review]
Looks great. Thanks so much for contributing!

**Comment by Marcono1234** [comment]
Thanks! As pointed out in the description, I hope that assumption that column numbers start at 1 is correct (I was not able to verify that).

**Comment by ramyaparimi** [comment]
@Marcono1234 Yes, it is correct! Thanks for contributing 🎉

**Pull request merged**
