### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by lawalalao**
add solution link to 14th lines

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by lawalalao** [comment]
done

**Comment by janiceilene** [comment]
@lawalalao Can you answer the **Why?** and **What's being changed?** to help us understand why you want to add a solutions link? When I look at the [staging link](https://docs-1679--patch-1.herokuapp.com/en/free-pro-team@latest/rest) for the changes you've made, there isn't a new page listed. 

What page are you looking to add a link to?

**Review by Eiygyveyron — APPROVED** [review]

**Comment by shati-patel** [comment]
Thank you again for taking the time to contribute, @lawalalao! 😃 I'm going to close this PR for now, as we don't have a `solution` file to link to. Feel free to re-open, or open a new PR if you have any further suggestions 📝

**Pull request closed without merging**
