### PR TITLE
Update workflow-syntax-for-github-actions.md

### PR DESCRIPTION
**Pull request by logankilpatrick**
Update bash command for Fail-fast behavior per this thread: https://github.community/t/workflow-default-error-action-preference/149931 validated across multiple resources. See here: https://explainshell.com/explain?cmd=set+-e+o+pipefail and here: https://dougrichardson.us/2018/08/03/fail-fast-bash-scripting.html

### Why:

Pointed out in this thread: https://github.community/t/workflow-default-error-action-preference/149931

### What's being changed:

Updated Bash command to remove space. 

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — APPROVED** [review]

**Comment by janiceilene** [comment]
@logankilpatrick Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by logankilpatrick** [comment]
Stay alive :)

**Comment by logankilpatrick** [comment]
Please don't close me :')

**Review by lucascosti — APPROVED** [review]
Sorry for the delay in reviewing this!

Yep, this is a bug; thanks for the fix! 🚀

**Pull request merged**
