### PR TITLE
Update gh-pkg doc sample release-package.yml

### PR DESCRIPTION
**Pull request by raysonkoh**
### Why: 
In the original sample `release-package.yml` file, running `npm ci` would cause the build to fail since there is no `package-lock.json` file (if one were to follow the quickstart guide from the beginning).

### What's being changed: 
`npm ci` in the sample `release-package.yml` file to `npm i` to ensure build runs successfully.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

Edit: formatting

### CODE REVIEW

**Comment by janiceilene** [comment]
@raysonkoh Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by raysonkoh** [comment]
Hello @janiceilene , are there any updates on the review for this PR?

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by jmarlena** [comment]
Hey @raysonkoh! 

Thank you so much for taking the time to update the docs. Sorry for the delay in response here. 

I tested out this quickstart without running into the error you mentioned. 

It looks like someone has already updated the quickstart to include a step that adds the `package-lock.json` file with: 
> Run npm install to generate the package-lock.json file, then commit and push your changes to GitHub.

Since `npm ci` is considered best practice for CI flows we're going to keep it and the new step means that users shouldn't run into this error anymore. 

More info on `npm ci` here: https://www.boxpiper.com/posts/npm-ci-vs-npm-install

Thank you for caring about the docs. 💛

**Pull request closed without merging**
