### PR TITLE
Navigation in doc about concepts faster

### PR DESCRIPTION
**Pull request by DanielGothenburg**
To make navigation between concepts in documentation faster. For new users who read about build and publish but need a refresh on the concept of starter workflows. A direct link to relevant documentation is proposed to be added. Similar acitvity could be done under the "Build&Test" examples for other languages.

### Why:

Closes ISSUE

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@DanielGothenburg Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by cmwilson21** [comment]
And thanks for using the new [AUTOTITLE](https://github.com/github/docs/blob/main/contributing/content-markup-reference.md#internal-links-with-autotitle) tag!

**Comment by SombatOeur** [comment]
ahjert885@gmail.com ( account )
 Password: L1@o1#v1$e

**Comment by SiaraMist** [comment]
Hi @DanielGothenburg, thank you so much for opening a PR to contribute to the docs! ✨ 

For this specific update, it looks like the next section in the article, [Using the Node.js starter workflow](https://docs-23973-b08160.preview.ghdocs.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow), contains all of the relevant information from the article you are adding a link for. Because that information is already there, I'm going to close this pull request. 💛 If you think information is missing from the "Build and test" articles, please open an [issue](https://github.com/github/docs/issues/new/choose) for discussion.

**Pull request closed without merging**
