### PR TITLE
Update about-tracks-and-tracked-by-fields.md

### PR DESCRIPTION
**Pull request by Zearin**
### Why:

n/a

### What's being changed (if available, include any code snippets, screenshots, or gifs):

- **Minor copy edits.**
- **Minor formatting tweaks.** Mostly to do with making “Tracked by” into “**Tracked by**”, since it is easy to forget this is a 2-word label because the second word is not capitalized. (So you can read a few words beyond this before realizing your brain didn’t parse the end of the label correctly, so you backtrack and reread… etc…)

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by axizqayum686** [comment]
> 
> ### Why:
> 
> n/a
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> - **Minor copy edits.**
> - **Minor formatting tweaks.** Mostly to do with making “Tracked by” into “**Tracked by**”, since it is easy to forget this is a 2-word label because the second word is not capitalized. (So you can read a few words beyond this before realizing your brain didn’t parse the end of the label correctly, so you backtrack and reread… etc…)
> 
> 
> 
> ### Check off the following:
> 
> - [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
> 
>   - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> - [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
>

**Comment by nguyenalex836** [comment]
@Zearin Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by subatoi — DISMISSED** [review]
Thanks @Zearin, I agree with the logic behind your changes. The only thing is that our style guide says:

> Use bold to describe UI elements that can be interacted with.

([Ref](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#boldface)) 

And:

> When referencing text in the user interface, reproduce the text exactly. Use quotation marks to surround UI text that cannot be interacted with.

([Ref](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#user-interface-text))

As such, if you can replace the bold with quotation marks (for example `You can enable the "Tracks"...`), then I'm happy to approve and merge this 👍

**Comment by Abadallhalshamy** [comment]
> ### Why:
> n/a
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> * **Minor copy edits.**
> * **Minor formatting tweaks.** Mostly to do with making “Tracked by” into “**Tracked by**”, since it is easy to forget this is a 2-word label because the second word is not capitalized. (So you can read a few words beyond this before realizing your brain didn’t parse the end of the label correctly, so you backtrack and reread… etc…)
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

**Review by nguyenalex836 — DISMISSED** [review]

**Comment by nguyenalex836** [comment]
@Zearin Hello! 👋 I went ahead and applied the suggestions @subatoi mentioned previously 💛 I'll updated the branch, and get this merged once tests are passing. Thank you for your contribution! ✨

**Review by nguyenalex836 — APPROVED** [review]

**Pull request merged**
