### PR TITLE
setting-exit-codes-for-actions.md C

### PR DESCRIPTION
**Pull request by i-like-ICEs**
### Why:
Update definitions

**Closes [issue link]**

### What's being changed:
A more clear definition 

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Review by DevilBride — COMMENTED** [review]
Willi0728:patch-2

**Comment by Willi0728** [comment]
> Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

-------reply-------
I already put the template in the first comment I posted.

**Comment by janiceilene** [comment]
@Willi0728 Can you fill out the **Why** and **What's being changed** questions in the template?

**Comment by janiceilene** [comment]
Stalebot didn't know that an update was added to the OP, reopening this and triaging it for review.

**Review by skedwards88 — APPROVED** [review]
🎉 LGTM! I'll get this merged down for you.

**Pull request merged**
