### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gepbird**
### Why:

The sentence `Use the text editor edit the page's content.` is grammatically incorrect.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added a missing `to` word.

Before:
before
 
After:
after

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@gutyina70 Thanks for opening a PR :+1: Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by gutyina70** [comment]
@cmwilson21 I have filled it out.

**Comment by cmwilson21** [comment]
@gutyina70 Thank you! I appreciate you going back and providing the screenshots, as well. 🎉 

I'll get this triaged for review! ⚡

**Review by cmwilson21 — APPROVED** [review]
LGTM! ✨

**Pull request merged**
