### PR TITLE
Removes outdated note about X.509 Certs in Linux `gpgsm`

### LINKED ISSUE #8227: Clarify usage of X.509 certificates to sign commits on Linux
### What article on docs.github.com is affected?

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key

### What part(s) of the article would you like to see updated?

On the "Linux" tab, the blue box at the top of the page states:

> Note: X.509 keys are not supported on Linux. You can configure gpgsm to provide encryption and signing services, however, this is not currently supported by GitHub. For more information, see the gpgsm topic in the GnuPG documentation.

Maybe I do not fully understand what you mean by "is not currently supported by GitHub", but I think this is wrong. I was just able to sign my commit using gpgsm on Linux without issues.

grafik

Maybe this note is outdated?

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #8227 

### What's being changed:

Removes the note about X.509 certs being not supported on Linux `gpgsm`. 

[This Doc](https://docs.github.com/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@thispsj Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by ramyaparimi — APPROVED** [review]
@thispsj Thanks for working on this. The changes look good to me 👍

**Comment by ramyaparimi** [comment]
@thispsj Can you enable the checkbox to allow maintainer edits? Then I’ll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by thispsj** [comment]
@ramyaparimi is it ok now or should I tick the "Allow edits by maintainers" ?

**Comment by ramyaparimi** [comment]
@thispsj Please tick `Allow edits by maintainers` so it lets me update branch and merge it 🍏

**Comment by thispsj** [comment]
@ramyaparimi done 👍

**Pull request merged**
