### PR TITLE
basic-writing-and-formatting: add `raw=true` also for images of same repo

### PR DESCRIPTION
**Pull request by phil-blain**
It seems it is sometimes necessary to use the '?raw=true' parameter,
mentioned on the "In issues, pull requests and comments of another
repository" line of the table, even if the image linked to is in the
same repository as the issue or pull request.

Add it to the example in the line "In issues, pull requests and comments
of the repository" also.

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@phil-blain 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Marco071086** [comment]
010101001010101001010100

**Review by akenneth — APPROVED** [review]
Lgtm!

**Review by cmwilson21 — APPROVED** [review]
This looks great! Thanks for contributing to the docs! I'll get this merged once the tests have all passed.

**Pull request merged**
