### PR TITLE
Update about-github-campus-program.md

### PR DESCRIPTION
**Pull request by bassa846**
I'm opening a PR to address these changes made by @skedwards88 , which have been approved.

### Why:

[Content updated for GitHub Education's Docs Page](https://github.com/github/docs/issues/5212)
[Update about-github-education.md](https://github.com/github/docs/pull/2172)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much for opening this PR @bassa846 and sorry again about the confusion 💛 I've triaged it for review ⚡

**Comment by sarahs** [comment]
👋 We did some content restructuring that resulted in a conflict with your PR. It looks like we may not have access to check out your fork. Let us know if you need a hand resolving the conflict!

**Comment by bassa846** [comment]
@sarahs Hey, yes I'd like help with resolving the conflict 🥰

**Comment by janiceilene** [comment]
@jmarlena can help fix those conflicts next week 💖

**Comment by Rayyan335** [comment]
http://docs.google.com/messages/inbox/Norohaa4Qg/message_1.html

**Comment by jmarlena** [comment]
@bassa846 and I met up today and we decided to close this PR in favor of https://github.com/github/docs/pull/6735. 💖

**Pull request closed without merging**
