### PR TITLE
Not all Dependabot languages support private repos

### PR DESCRIPTION
**Pull request by wilg**
Ran into this (a quite frustrating one, given that Ruby isn't supported, which is what GitHub is built in.)

Didn't follow the review guidelines, sorry.

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request. Let me know when that's done and I'll get this up for review!

**Comment by wilg** [comment]
@janiceilene I'm not highly motivated to follow the particulars of GitHub's internal documentation guidelines, as it's not my job to work on GitHub's docs. I've highlighted an important deficiency in the docs about a frustrating limitation and tried to help out, but it's up to someone at GitHub to take it from here.

**Review by M-Feve0-1 — COMMENTED** [review]
>

**Comment by wilg** [comment]
Sounds good, thanks everyone!

**Pull request closed without merging**
