### PR TITLE
Update changing-your-sponsorship-tiers.md

### LINKED ISSUE #4317: Add background information on /changing-your-sponsorship-tiers#editing-or-retiring-a-tier
### What article on docs.github.com is affected?

https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/changing-your-sponsorship-tiers#editing-or-retiring-a-tier

### What part(s) of the article would you like to see updated?

I propose that there be some background information about editing or retiring a tier because when I went to these docs, I wasn't looking for instructions but rather background knowledge on what happens when you retire a tier.

### PR DESCRIPTION
**Pull request by ArsalaBangash**
I added some background information about editing or retiring a tier because when I went to these docs, I wasn't looking for instructions but rather background knowledge on what happens when you retire a tier.

### Why:

**Closes #4317**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@ArsalaBangash Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by myarb — CHANGES_REQUESTED** [review]
👋🏼  @ArsalaBangash thanks so much for opening this PR! Because this information is already communicated at the top of this article, the team has decided we don't need to duplicate the information in this section. 

I see you added a few helpful links to the paragraph, which I think would go well at the bottom of the page in a "Further reading" section (see an example [here](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization#further-reading)). If you're up for making these changes, let us know and we can review this again when you're ready! 🎉

**Comment by ArsalaBangash** [comment]
@myarb Thank you for pointing that out. I'm not sure how I missed it. If I'm honest, I don't have the capacity at this moment to make the other fix :) 

Should I proceed by closing this pull request and associated issue?

**Comment by janiceilene** [comment]
> Should I proceed by closing this pull request and associated issue?

Opening an issue with those changes would be very helpful! I'll close this issue out. Thank you so much for your interest and passion for improving the GitHub Docs 💖

**Pull request closed without merging**
