### PR TITLE
Update SMIME instructions for Linux/WSL2

### PR DESCRIPTION
**Pull request by N6UDP**
### Why:

Closes: 
https://github.com/github/smimesign/issues/30
https://github.com/github/smimesign/issues/45

### What's being changed (if available, include any code snippets, screenshots, or gifs):
Adding information for GPGSM on Linux and a note for both Windows and Linux about how to configure it on WSL2.

### Check off the following:
- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Review by LukeLisakennard — COMMENTED** [review]
@mirahcarey
@kbsparkman

**Comment by nguyenalex836** [comment]
@N6UDP Thanks for opening a PR! ✨ 

It looks like this is still a draft. Could you ping me when this is ready? Then, I'll get it up for review ⚡

**Review by loungkaye3 — COMMENTED** [review]
loungkaye3

**Comment by N6UDP** [comment]
@nguyenalex836 this should be good to go now.

**Review by loungkaye3 — COMMENTED** [review]
@loungkaye3

**Review by loungkaye3 — COMMENTED** [review]
@loungkaye3

**Review by loungkaye3 — COMMENTED** [review]
@loungkaye3

**Comment by nguyenalex836** [comment]
@N6UDP Awesome, thanks for letting me know! This has been triaged for review ✨

**Comment by jc-clark** [comment]
Hey @N6UDP thank you for the contribution. We checked in with our engineering team on this and GitHub doesn't officially support `gpgsm`. As such, we won't add documentation to our public docs for this use case. I'll go ahead and close this PR.

**Comment by N6UDP** [comment]
@jc-clark even we don't want to add docs related to `gpgsm` you all should clarify the [existing](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key?platform=linux#telling-git-about-your-x509-key) docs as they currently imply that smimesign *is* supported on linux which it is not.

**Comment by jc-clark** [comment]
I see what you're saying here, @N6UDP thank you for the feedback. I can work with our team on the best follow up for that.

**Comment by jc-clark** [comment]
@N6UDP We had a chance to chat about this and you're right that the docs currently imply that `smimesign` is supported on linux. 

So we should fix that. 

For this, we should make sure the x.509 information only shows up for the Mac and Windows versions of this doc and doesn't show up for Linux. 

We can do that by [replacing line 123](https://github.com/N6UDP/docs/blob/6689530d892dd796ed727d60bd5d364e11303c64/content/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key.md#L123) with the following: 

```
{% windows %}

{% data reusables.gpg.x-509-key %}

{% endwindows %}

{% mac %}

{% data reusables.gpg.x-509-key %}

{% endmac %}
```

You or anyone else is welcome to open a new PR suggesting these changes.

**Pull request closed without merging**
