### PR TITLE
Bump juliangruber

### PR DESCRIPTION
**Pull request by Noc21**
I’m sorry I don’t know if you’re trying to help me or just have a “free” license on everything on my phone. I don’t understand.

### CODE REVIEW

**Comment by clowndogloko** [comment]
> I’m sorry I don’t know if you’re trying to help me or just have a “free” license on everything on my phone. I don’t understand.

its on my phone too, and im just trying to opt out of this cloned account. I think you must be having the same problem im having. lets discuss?

**Review by clowndogloko — COMMENTED** [review]
these credits are mine, thats why im changing anything and everything but if you think this is fun, well not to me, im taking this very serious. so if you dont want to take over the licences just go and bother someone else, i might not know what im doing but im preety sure im doing it well..

**Comment by clowndogloko** [comment]
say something?

**Comment by eliasaadeh** [comment]
Sorry for that but i have the same problem and i was trying to solve that
but I didn’t realize that am doing you bad sorry

**Pull request closed without merging**
