### PR TITLE
Remove starter workflows from code examples

### PR DESCRIPTION
**Pull request by andymckay**
### Why:

👋🏾 This PR removes starter workflows from code examples on the docs page (I think). The workflows are all visible when a user hits the Actions tab and starts a new workflow. But on the way we do a transformation for example `$default-branch` to whatever your default branch is. So they don't work too well.

Some of the other things in the actions org might work, although not sure they qualify as good examples for learning from.

### What's being changed:

image (17)

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by andymckay** [comment]
Please don't close stale 😄

**Review by palejana — APPROVED** [review]

**Comment by martin389** [comment]
I've let docs engineering know about this PR 👍

**Comment by simpsoka** [comment]
Thanks @andymckay! I'm 👍 on this one.

**Review by JamesMGreene — APPROVED** [review]
Thanks, @andymckay! We'll get this merged in the next few days after [GitHub Universe](https://githubuniverse.com/) (shameless plug). :octocat:

**Pull request merged**
