### PR TITLE
Clarified that SQL Server sample is also applicable to Azure SQL

### LINKED ISSUE #21732: Highlight that the SQL example just created is also applicable to Azure SQL
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/codespaces

### What part(s) of the article would you like to see updated?

Highlight that the SQL example just created is also applicable to Azure SQL

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yorek**
### Why:

Closes #21732

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updated the description of the newly created SQL sample in the Code examples section of [Codespaces docs landing page](https://docs.github.com/en/codespaces)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by yorek** [comment]
Where I can find the "Automatically generated comment" link so that I can check the results?

**Comment by cmwilson21** [comment]
@yorek Great question! Since this is in our yaml file, the automatically generated comment won't automatically generate. That workflow is triggered by changes in our content vs the yaml file. Sorry for the confusion there. Otherwise, with content changes, it'll generate beneath your opening comment after you open your PR. If it doesn't generate, another option would be to check your local server where the changes have been applied.

Hope this info if helpful! ✨

**Comment by yorek** [comment]
@cmwilson21 my suggestion would be then to update the checklist to mention that one should check the deployment by clicking on this link: 

image

which I found almost by chance :) 

I have reviewed the result and I think it looks good (just fixed a minor issue right now).

**Review by lecoursen — APPROVED** [review]
Thanks @yorek! We'll get this merged as soon as our current freeze is over.

**Pull request merged**
