### PR TITLE
JSON code sample fix

### PR DESCRIPTION
**Pull request by nickQuant**
The left and right double quote characters (Unicode chars U+201C and U+201D) are used around the features element in the JSON sample.  These are not valid JSON.
The PR changes these to U+0022 - straight double quote

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by skedwards88 — APPROVED** [review]
Thanks for this fix! We'll get this merged down for you.

**Review by Kingmax1981 — COMMENTED** [review]
edited to remove spammy content

**Review by cmwilson21 — APPROVED** [review]

**Comment by nickQuant** [comment]
> 👋 @nickQuant - Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. ⚡
> 
> Thank you!
> 
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Hi Courtney - it looks like this option isn't available for PRs that originate from organizational accounts (https://github.com/community/community/discussions/9921).  
I've added you an an admin on the upstream repo - does that do the trick?

**Comment by cmwilson21** [comment]
Thanks, Nick! That got it working. It's now merged. Thanks for contributing and improving the docs! 🎉

**Comment by nickQuant** [comment]
Thanks so much 😊   From: Courtney WilsonSent: Thursday, 15 September 2022 1:20 AMTo: github/docsCc: nickQuant; MentionSubject: Re: [github/docs] JSON code sample fix (PR #20396) Thanks, Nick! That got it working. It's now merged. Thanks for contributing and improving the docs! 🎉—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request merged**
