### PR TITLE
Update example with Octokit Checks API methods

### PR DESCRIPTION
**Pull request by matiasalbarello**
Octokit supports creating and updating checks by using `create_check_run` and `update_check_run`: https://rdoc.info/gems/octokit/Octokit/Client/Checks

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@matiasalbarello Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by madhamid** [comment]
Very good and nice

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Review by skedwards88 — APPROVED** [review]
Thank you for this update! I'll get it merged down for you.

**Review by totongcute — APPROVED** [review]

**Pull request merged**
