### PR TITLE
Update about-github-security-advisories.md

### PR DESCRIPTION
**Pull request by maxmash1**
Update About CVE and CVE Numbering Authorities links from the older .mitre.org to the new .org ones.

### Why:

The "About CVE" and "CVE Numbering Authorities" links point to older (transitioning) cve.mitre.org site. This pull request updates the two links to the new cve.org site.
Closes [issue link] -> I couldn't find any existing issues in the issues list tied to these proposed changes.

### What's being changed:

In the "About GitHub Security Advisories" page update the two links associated with "About CVE" and "CVE Numbering Authorities" links to direct to the new cve.org site

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by maxmash1** [comment]
Updated 2 links. Please let me know if anything additional is necessary.

**Comment by ramyaparimi** [comment]
@maxmash1 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by felicitymay — COMMENTED** [review]
@maxmash1 - many thanks for taking the time to update this article with links to the new site for MITRE. It's much appreciated. ✨ 

I notice that we have one more article that contains a link to the deprecated site and I'm going to add a commit to your PR to update that too for completeness.

**Review by felicitymay — APPROVED** [review]

**Comment by maxmash1** [comment]
Thank you @felicitymay @ramyaparimi. Glad I could help.

**Pull request merged**
