### PR TITLE
Add some missing properties on workflow_run events

### LINKED ISSUE #2599: The  workflow_run payload docs is incomplete
### What is the current behavior?

Here there https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run the workflow_run property is missing, she contains at least pull_requests as in check_suite https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#check_suite

### What changes are you suggesting?

Add all the missing property

### Additional information

Example of job that runs on workflow_run: https://github.com/camptocamp/tilecloud/runs/1653892847?check_suite_focus=true

### PR DESCRIPTION
**Pull request by sbrunner**
### Why:

Fix #2599

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@sbrunner Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by sbrunner** [comment]
@janiceilene what's the status?

**Comment by janiceilene** [comment]
@sbrunner Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Comment by sbrunner** [comment]
UP

**Comment by sbrunner** [comment]
What does the close by github-actions means?

**Comment by janiceilene** [comment]
So sorry about that @sbrunner! It looks like our new action inadvertently closed this :upside_down_face: Reopening and triaging this for review :yellow_heart:

**Comment by sbrunner** [comment]
@janiceilene Thanks :-)

**Review by lucascosti — APPROVED** [review]
Thanks a lot for these changes, @sbrunner!

For the workflow run properties: because they're largely identical to the check suite ones, instead of repeating them I've edited your table to consolidate the descriptions and link to the check suite descriptions.

Because I've made a few changes, I'll get one of the other writers on the team to double-check this PR 👍

Stage: https://docs-2767--workflow-run-proper.herokuapp.com/en/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run

**Review by martin389 — APPROVED** [review]
Looks good to me, thank you for this PR!  🎊 🎉

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
