### PR TITLE
Update configuring-notifications.md to add link for Custom Routing

### PR DESCRIPTION
**Pull request by shadoath**
Add link to the Custom Routing URL.

### Why:

Shorten the path to reaching the page needed.

Closes: 

N/A

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@shadoath Thank you for opening a PR! ✨ Just for context, I wanted to share a link to our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#user-interface-elements) regarding user interface elements 💛 

If you are proposing this update because the UI isn't quite correct, can you elaborate on the changes you think are needed?

**Comment by shadoath** [comment]
What needs the UI updates are the images and steps to get to the "Notification" settings page:

Screenshot 2024-10-11 at 1 41 25 PM

Screenshot 2024-10-11 at 1 41 14 PM

What I did here was provide an easy shortcut to the notifications (Although most links like this are to other docs.github.com pages.). Reading more of the doc there is a link below to that page, so maybe this is not worth it.

**Comment by nguyenalex836** [comment]
@shadoath Thank you for providing that context! I'm looping in one of our technical writers @subatoi to assist in reviewing your last comment. We'll provide an update once we determine what next best steps will be 💛

**Comment by subatoi** [comment]
Hi, I'm afraid we can't accept this contribution— https://github.com/github/docs/pull/34903#issuecomment-2407772940 already pointed out the style issue with hyperlinks. We don't link to specific parts in the UI from instructional procedures like this. This page is designed to be use on a section by section basis and as a reference article, and we already link to the relevant section at the top of the page:

Screenshot 2024-10-13 at 08 42 34

In actual fact, the Dependabot settings section you linked to should link to https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#choosing-your-notification-settings rather than using the wording it does. 

I'm happy to leave this PR open whilst we figure out what you mean regarding the UI being out of date, but I'm not sure about this because the images seem to match the current experience. Are you able to take screenshots of your own experience so I can see if I'm missing something? Just to let you know: the best resolution may be to direct you to a Discussion or to our Support team, depending on the case.

**Comment by shadoath** [comment]
Sure here is a screenshot of my profile where I don't see anything that looks like the indicated options as the prior screenshots show:
Screenshot 2024-10-14 at 3 48 03 PM

**Comment by subatoi** [comment]
I'm going to go ahead and close this out as there isn't a UI issue. Feel free to check out our issues marked `help wanted` and thank you for your interest in the GitHub Docs

**Pull request closed without merging**
