### PR TITLE
Update github-developer-program.md

### PR DESCRIPTION
**Pull request by Daniel-TheProgrammer**
### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Daniel-TheProgrammer** [comment]
Please deploy to heroku

**Comment by janiceilene** [comment]
👋 @Daniel-TheProgrammer That section header needs to be a `##` to match with the rest of the docs, so I'm going to close out this PR.

You can see your changes on Heroku by clicking **View deployment** above and navigating to the page where you made changes.
image

Feel free to ask any questions you may have in [discussions](https://github.com/github/docs/discussions)!

**Comment by Daniel-TheProgrammer** [comment]
Okay

**Review by Daniel-TheProgrammer — COMMENTED** [review]
Great

**Pull request closed without merging**
