### PR TITLE
Bump to upload-artifact@v2

### PR DESCRIPTION
**Pull request by asciimike**
### Why:

The version is behind what I believe the latest version is.

### What's being changed:

It seems like `upload-artifact@v2` is used in other places, e.g. https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#configuring-a-custom-artifact-retention-period

Is there a reason we still use `upload-artifact@v1` here?

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by asciimike** [comment]
Docs LGTM: https://docs-3631--mm-v1-to-v2.herokuapp.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

**Comment by janiceilene** [comment]
@asciimike Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by jiniuj — COMMENTED** [review]
leave a comment

**Review by skedwards88 — APPROVED** [review]
🚀 Thank you for your contribution! I'll get this merged down for you.

**Pull request merged**
