### PR TITLE
docs: remove trailing newlines in code blocks

### LINKED ISSUE #27989: Superfluous newlines found in some code blocks
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group

### What part(s) of the article would you like to see updated?

The `on.merge_group` example contains a superfluous trailing newline.
image

Compared to examples without trailing newline(s):
image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by muzimuzhi**
### Why:

Closes: #27989

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Several trailing and a single beginning newlines inside markdown code blocks are removed.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by muzimuzhi** [comment]
> Please note that changes to the `data` directory will not show up in this table.

I've also reviewed all the pages affected by the changes to `data` dir.

**Comment by cmwilson21** [comment]
@muzimuzhi Thanks for opening an issue and submitting a PR! We appreciate the details you've provided 👍 

I'll get this triaged for review! :zap:

**Review by subatoi — APPROVED** [review]
Thank you for fixing this (and for raising an issue)—it's very much appreciated ✨

**Review by Ambassadormathismathews — COMMENTED** [review]
Unblock all

**Pull request merged**
