### PR TITLE
Add missing step in deleting oauth apps

### LINKED ISSUE #18052: Additional step needed in deleting OAuth App doc
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/apps/deleting-an-oauth-app

### What part(s) of the article would you like to see updated?

Between steps 4 and 5 there is another step. The Delete application button exists on the Advanced tab, not the default, General tab, so users need to navigate there to see it.

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #18052 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

As pointed out by @docs-bot, adds the missing step.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by steveward — DISMISSED** [review]
Thanks for the PR @thispsj! This looks good to me. I'll get this merged. ✨

**Review by E-fais — COMMENTED** [review]
Good 👍

**Review by jules-p — APPROVED** [review]
I've made one tiny edit to align with our style guide, but this looks great! Thank you so much for contributing ✨

**Comment by Ari07092000** [comment]
> ### Why:
> Closes #18052
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> As pointed out by @docs-bot, adds the missing step.
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

**Pull request merged**
