### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prasadjivane**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Aizmansor** [comment]
Dihantar daripada telefon Huawei saya-------- Mesej asal --------Daripada: "welcome[bot]" ***@***.***>Tarikh: Isn, 4 Jul 2022, 11:49 PTGKepada: github/docs ***@***.***>Sk: Subscribed ***@***.***>Tajuk: Re: [github/docs] Update README.md (PR #18927)
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the contributing guidelines.

**Comment by cmwilson21** [comment]
@prasadjivane Thanks for opening a PR 👍  Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review! ⚡

**Comment by cmwilson21** [comment]
@prasadjivane I'll get this triaged for review. On future PR's, we would appreciate it if you would fill out the information in the PR template including the "Why" section and including the link to an open issue that the PR fixes. If there isn't one, we encourage users to always open an issue first, then make their PR and link the two, as this helps us in our review process. See our [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) for more information. 💖 

Thank you for your passion in improving our docs! ✨

**Review by cmwilson21 — APPROVED** [review]
Thanks for catching the missing word and correcting it! I'll get this merged once all the tests are passing ⚡

**Comment by cmwilson21** [comment]
I did add the comma back to the first suggested change. We use the Oxford comma per our content guide. You can find more information about that [here](https://github.com/18F/content-guide/blob/18f-pages/_pages/our-style/punctuation.md#commas).

**Pull request merged**
