### PR TITLE
LICENSE.rst is also supported

### LINKED ISSUE #3669: LICENSE.rst is also supported
### What article on docs.github.com is affected?

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

### What part(s) of the article would you like to see updated?

Should mention ``LICENSE.rst`` too

### Additional information

See PR #3586

### PR DESCRIPTION
**Pull request by peterjc**
### Why:

**Closes #3669**

### What's being changed:

Adds a few words to https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by peterjc** [comment]
Issue filed and template filled out a bit.

**Comment by janiceilene** [comment]
Thanks so much for filling out the PR template and opening an issue @peterjc! I'll get this triaged for review ✨

**Review by megbird — APPROVED** [review]
Thanks for this addition ⚡ 👍  we'll get it merged in soon!

**Comment by peterjc** [comment]
The "Browser Tests / build (pull_request)" failure looks like a time out

**Pull request merged**
