### PR TITLE
docs: replace id_token to id-token

### LINKED ISSUE #11778: docs: Correct id_token references
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

All references of id_token should be id-token per [the schema](https://json.schemastore.org/github-workflow.json).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AjkayAlan**
### Why:

Closes #11778

### What's being changed:

Replaces `id_token` with `id-token`. `id_token` is not valid per [the schema](https://json.schemastore.org/github-workflow.json), but `id-token` is. I have validated that `id-token` works in my [personal repo](https://github.com/AjkayAlan/aws-account-bootstrap/blob/main/.github/workflows/build-and-deploy.yaml).

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by AjkayAlan** [comment]
FYI that I have reviewed the changes and check list, and they all look good, but I have not been able to preview the change on the staging branch yet as I believe the workflows need to be approved (this is my first contribution to this repo).

**Comment by ramyaparimi** [comment]
@AjkayAlan 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by martin389 — APPROVED** [review]

**Comment by martin389** [comment]
Looks good in staging: 
- https://docs-11779--main.herokuapp.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
- https://docs-11779--main.herokuapp.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by martin389** [comment]
Thanks for this great PR! 🎊

**Pull request merged**
