### PR TITLE
Remove note about uploading academic verification

### LINKED ISSUE #19342: No way to upload proof of academic status for education benefits
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/use-github-in-your-classroom-and-research/apply-for-an-educator-or-researcher-discount

### What part(s) of the article would you like to see updated?

The [instructions for applying for an educator or researcher discount](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/use-github-in-your-classroom-and-research/apply-for-an-educator-or-researcher-discount#applying-for-an-educator-or-researcher-discount) include a way to upload proof of academic status, but the (current) form does not have an upload button -- just the ability to take a picture using the computer's camera. See the screenshot in "Additional information" (below), which shows the missing upload button.

### Additional information

Screen Shot 2022-07-27 at 10 39 46 AM

### PR DESCRIPTION
**Pull request by joel-coffman**
The education benefits request no longer has a way to upload proof of
academic status -- just taking a picture using the computer's camera.
Thus, this change removes the reference to uploading an image in the
documentation for applying for an educator discount.

### Why:

Closes #19342

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The [instructions for applying for an educator or researcher discount](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/use-github-in-your-classroom-and-research/apply-for-an-educator-or-researcher-discount#applying-for-an-educator-or-researcher-discount) references a way to upload proof of academic status, but the (current) form does not have this button -- just the ability to take a picture using the computer's camera.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@joel-coffman Thanks for opening a pull request and linking it to your issue! ⚡ 

I'll get this triaged for review ✨

**Review by Chardelyce — COMMENTED** [review]
Issue is confirmed to be resolved as instructions are now on the site https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/github-global-campus-for-teachers/apply-to-github-global-campus-as-a-teacher issue can be closed

**Comment by cmwilson21** [comment]
@joel-coffman - Sorry for the delay here. We have been tracking this and working on other updates internally. We have an internal PR in the works that should update this, so I'm going to go ahead and close this PR now. 💛 

Please take a look at our [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) section to find open issues you can work on.

Thank you for your passion and interest in improving GitHub Docs! :sparkling_heart:

**Comment by joel-coffman** [comment]
> @joel-coffman - Sorry for the delay here. We have been tracking this and working on other updates internally. We have an internal PR in the works that should update this, so I'm going to go ahead and close this PR now. 💛

Thanks for the update, @cmwilson21!

For my own future reference, what kind of contributions does GitHub accept / is GitHub interested in when it comes to documentation? I've submitted a handful of issues and offered to contribute changes, but the response usually seems to be that they'll be addressed internally. While it didn't take a great deal of time to create this pull request, I don't really want to do that if GitHub prefers to resolve these issues on its own. Should I wait for the "help wanted" tag to be applied to an issue before working on it in the future?

**Comment by cmwilson21** [comment]
@joel-coffman - Great question! We are interested in all contributions that improve our docs! I can't speak for the others you may have submitted, but this one comes down to timing. The team in charge over education and the application process has been rolling out updates behind the scenes and have been gradually updating the docs in the process. I wasn't sure when this update would take place so I left this PR open for tracking. I'm sorry. That's on me. I could have better communicated that.

We understand that our contributors take time out of their day to submit these PRs and issues. We truly appreciate our community's involvement and enthusiasm for helping maintain the docs. We encourage all our users to contribute when they see something that could be updated. Opening an issue before a PR does give our team a chance to review the issue and confirm it or decide if it is best handled internally. In the mean time, the [help wanted board](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) is a fantastic place to work on open issues that have already been approved. ✅ 

Thank you, again, for your interest in contributing, and thank you for opening up this conversation and asking these questions. We look forward to seeing future contributions from you! 💖

**Pull request closed without merging**
