### PR TITLE
Patch the missing `edited` action type for xxx_event_api_properties.md

### LINKED ISSUE #12590: The issue_event_api_properties.md and pull_request_event_api_properties.md lose the edited action.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#issuesevent
- https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#pullrequestevent

### What part(s) of the article would you like to see updated?

The `action`  properties of the `PullRequestEvent` and `IssuesEvent`  lost the `edited` action.

### Additional information

None

### PR DESCRIPTION
**Pull request by Mini256**
### Why:

close #12590

### What's being changed:

The `edited` action will be added for the `IssueEvent` and `PullRequestEvent`.

image

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
- [ ] I have added the 'writer impact' label
- [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Mini256** [comment]
It works.

image

**Comment by ramyaparimi** [comment]
@Mini256 
Thanks for opening a PR :+1: Please fill out "why" and "what's being changed" in the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, so I can get this up for review!

**Comment by ramyaparimi** [comment]
@Mini256 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for this PR! Our repo is currently frozen until early January, but we will get this merged for you once the freeze lifts.

**Review by totallylost-helpme — COMMENTED** [review]
Great job!!

**Pull request merged**
