### PR TITLE
Correct path to known-hosts file.

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
### Why:

Fix for change from #21871 .
[See comment](https://github.com/github/docs/issues/21871#issuecomment-1355946528).

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added a missing slash to the path to the user's `known_hosts` file.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@Clockwork-Muse Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by vgrl — APPROVED** [review]
LGTM! Thank you for a getting PR up with this fix so quickly!

Note that we have frozen our repo until January 3rd (see https://github.com/github/docs-team/discussions/2467), so the changes will not be published until after then. Thanks!

**Review by nitindudeja2107 — COMMENTED** [review]
#22621 #22795 #22750 #22727

**Review by nitindudeja2107 — COMMENTED** [review]
#22771

**Pull request merged**
