### PR TITLE
Discuss uninstalling webhooks

### LINKED ISSUE #16605: Discuss uninstalling webhooks
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks

### What part(s) of the article would you like to see updated?

A page should be added that talks about uninstalling webhooks.

It should explain what an app author should do if they've added a webhook to a repository using their app and the repository has uninstalled their app, resulting in webhook events that they can't suppress as they no longer have permissions to manage the repository.

### Additional information

https://github.community/t/repository-webhook-removal-after-app-uninstall/219177

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes #16605 

### What's being changed:

image

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by apn666** [comment]
#apnZM#

Begin forwarded message:

**Comment by apn666** [comment]
#apnZM#

Begin forwarded message:

**Review by timrogers — APPROVED** [review]
This looks good to me! ❤️ Thanks for taking the time to submit this PR.

**Review by skedwards88 — APPROVED** [review]
Thanks for this addition! We'll get this merged down for you.

**Pull request merged**
