### PR TITLE
Added update to "Adding your SSH key to the ssh-agent"

### PR DESCRIPTION
**Pull request by RDxR10**
An alternative to establishing a connection to the ssh-auth agent.

### Why:

Added an alternate command here(this PR would solve part of this issue) [https://github.com/github/docs/issues/6642]

### What's being changed:

```
exec ssh-agent bash
```

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by fluesvamp** [comment]
The ssh-agent man page adequately addresses ways to get an agent set up.

I am opposed to the merging of this pull request.

**Review by admin-githup — COMMENTED** [review]
Goog

**Comment by janiceilene** [comment]
@RDxR10 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by RDxR10** [comment]
Let me know if it needs any further clarification.

**Comment by lecoursen** [comment]
Thanks for taking the time, @RDxR10, but our docs are purposefully opinionated. We document one way to accomplish a task and only mention alternatives if there's a compelling reason to do so. I'm going to close this PR, but let me know if there's further explanation for why this alternative is important to document.

**Comment by RDxR10** [comment]
@lecoursen the reason is that depending on the os or Linux environment, the command may vary.
More detailed info here: https://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent.
Variant: https://stackoverflow.com/a/20403535/456814

**Comment by lecoursen** [comment]
> the reason is that depending on the os or Linux environment, the command may vary.

Thanks for clarifying! From those links, it seems that there are more than two possibilities. We can't list them all, so we should instead clarify in `{% data reusables.command_line.start_ssh_agent %}` that the command we're listing is only an example and that you may need a different command depending your environment. Feel free to reopen this PR if you want to update it accordingly!

**Pull request closed without merging**
