### PR TITLE
fix: 优化翻译 Optimize translation

### LINKED ISSUE #7664: improve zh-cn translations
### What article on docs.github.com is affected?

[`translations/zh-CN/data/ui.yml`](https://github.com/github/docs/blob/translations/zh-CN/data/ui.yml)

### What part(s) of the article would you like to see updated?

image

### Additional information

修改的主要原因为：

1. 标点不符合规范
2. 多出来的空格
3. 句子关系

### PR DESCRIPTION
**Pull request by PassionPenguin**
### Why:

Closes #7664

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue for one of our translators to review 💛

**Comment by janiceilene** [comment]
Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.

See https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for more details.

I've opened an internal issue for one of our translators to review 💛

**Comment by PassionPenguin** [comment]
> Thanks for opening this pull request! Unfortunately, we are not able to accept pull requests for translated content. Our translation process involves an integration with an external service at crowdin.com, where all translation activity happens. We hope to eventually open up the translation process to the open-source community, but we're not there yet.
> 
> See [https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations for](https://github.com/github/docs/blob/main/CONTRIBUTING.md#earth_asia-translations%C2%A0for) more details.
> 
> I've opened an internal issue for one of our translators to review 💛

Hi, could i have a chance to offer helps to translate your documents?

**Comment by janiceilene** [comment]
Thank you so much for the offer @PassionPenguin 💝 Unfortunately, our translations aren't currently open sourced.

**Pull request closed without merging**
