### PR TITLE
repo sync

### PR DESCRIPTION
**Pull request by Octomerger**
This is an automated pull request to sync changes between the public and private repos.

:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
@runleonarun Hi Leona, this change broke all our integrations via a GitHub action that automatically merged Dependabot pull requests using the built-in GITHUB_TOKEN. Is there a way to reach out to somebody about this change?

**Comment by runleonarun** [comment]
@simoneb Let me find someone who can help!

**Comment by simoneb** [comment]
> @simoneb Let me find someone who can help!

It's sorted already, thank you and apologies for bothering you

**Comment by runleonarun** [comment]
> It's sorted already, thank you and apologies for bothering you

@simoneb I'm so relieved to hear that!

**Comment by WtfJoke** [comment]
@runleonarun  We have exactly the same problem (our dependabot pull requests cant access the secrets anymore and cant install the dependencies from our private registry). 
Can you please help us, too :D

Or how did you sorted it out @simon-engledew

**Comment by simoneb** [comment]
@WtfJoke "sorted", it's now the default behavior that the GITHUB_TOKEN is readonly, so you'll have to find workarounds. See the announcement here https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/.

Very useful information about alternatives and workarounds here https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md

**Pull request merged**
