### PR TITLE
I have added "current enrollment date"

### PR DESCRIPTION
**Pull request by sejalrane777**
It will help reader because when i gone through this i didn't knew that think but if reader will read with current enrollment date then he realises what he actually want to upload

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by sanicki** [comment]
👍 The application is explicit about the enrollment date requirement so it makes sense that the help article should be, too. Good suggestion!

**Review by janiceilene — APPROVED** [review]
This update looks good from a writer perspective 🎉 I'll get this merged soon. Thanks so much for opening a PR with this fix @sejalrane777 💖

**Comment by ko7580** [comment]
@sejalrane777
I have added "current enrollment date" …
315913a
It will help reader because when i gone through this i didn't knew that think but if reader will read with current enrollment date then he realises what he actually want to upload

**Comment by janiceilene** [comment]
👋 @sejalrane777 While we were frozen for GitHub Universe, I think this article was renamed and your pull request now has conflicts. Would you mind making this same change on the new article: https://docs.github.com/en/free-pro-team@latest/education/teach-and-learn-with-github-education/apply-for-a-student-developer-pack#applying-for-a-github-student-developer-pack

Thank you so much for contributing and I'm sorry about the timing of the rename 💛

**Comment by sejalrane777** [comment]
> 👋 @sejalrane777 While we were frozen for GitHub Universe, I think this article was renamed and your pull request now has conflicts. Would you mind making this same change on the new article: https://docs.github.com/en/free-pro-team@latest/education/teach-and-learn-with-github-education/apply-for-a-student-developer-pack#applying-for-a-github-student-developer-pack
> 
> Thank you so much for contributing and I'm sorry about the timing of the rename 💛

**Comment by sejalrane777** [comment]
> 👋 @sejalrane777 While we were frozen for GitHub Universe, I think this article was renamed and your pull request now has conflicts. Would you mind making this same change on the new article: https://docs.github.com/en/free-pro-team@latest/education/teach-and-learn-with-github-education/apply-for-a-student-developer-pack#applying-for-a-github-student-developer-pack
> 
> Thank you so much for contributing and I'm sorry about the timing of the rename 💛

Done👍 . I make changes on new article.

**Comment by janiceilene** [comment]
Thank you! I'm closing this PR out in favor of the updated https://github.com/github/docs/pull/2103 ✨

**Pull request closed without merging**
