### PR TITLE
Fix invalid example in "Syntax for GitHub's form schema"

### PR DESCRIPTION
**Pull request by MrBartusek**
### Why:

This PR fixed an invalid example in [Syntax for GitHub's form schema](https://docs.github.com/en/enterprise-cloud@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#example). Using provided code show following errors:

image

I have not opened an issue since it's minor problem.

### What's being changed:

Changes example to the valid one.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Mounkoung — COMMENTED** [review]
#17109

**Review by Mounkoung — COMMENTED** [review]
#204

**Comment by Shakib018142** [comment]
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>from</title>
  <style>
  *{
    background-color:#dfcccc;
    color:#000000;
  
  }
  h1{
    background-color:#ff15d2;
    color: black;
    text-align: center;
  }
  table{
    padding-left:10
    size:100%;
 }
  </style>
  
</head>

<body>
  <h1>form</h1>
  <form method="post" action="https://superbipap.com" autocomplete="on">
    <table>
    <tr>
      <td><label for"শিক্ষার্থীর পূর্ণ নাম ">শিক্ষার্থীর নাম</   lable></t>
      <td><input type="text" name="Enter your name" required autofocus placeholder="              শিক্ষার্থীর পূর্ন নাম"></td>
    </tr>
    <tr>
    
    <td><label> ডাক নাম</label></td>
    <td><input ty""pe="text" name="Enter your name"placeholder="                    ডাক নাম"></td>
   </tr>
   <tr>
    <td><label>জন্ম তারিখ</label></td>
    <td><input type="date" name="date of birth " placeholder="        DD/MM/YYYY"></td>
    </tr>
    <tr>
    <td><label>বয়স</label></td>
    <td><input type="number" name="age" placeholder="                        বয়স" min="6" mix="25"></td>
    </tr>
    <tr>
    
    <td><label> 
    রক্তের গ্রুপ </label></>
    <td><input type="radio" name="blood_group" value="A+"><label for="A+">A+</label>
    <input type="radio" name="blood_group" value="A-"><label for="A-">A-</label>
    <input type="radio" name="blood_group" value="B+"><label for="B+">B+</label>
    <input type="radio" name="blood_group" value="B-"><label for="B-">B-</label>
    <input type="radio" name="blood_group" value="O+"><label form="O+">O+</label>
    <input type="radio" name="blood_group" value="O-"><label for="O-">O-</label>
    </td>
    </tr>
    <tr>
    <td><label>জন্মনিবন্ধন নং </label></td>
    <td><input type="number" name="nid name" value="number" placeholder="               জন্মনিবন্ধন নং"  min="10000000000000000" mix="99999999999999999"></td>
    </tr>
    <tr>
   <td> <label>পিতার নাম</label></td>
    <td><input type="text" name="Enter your father name" placeholder="                পিতার নাম"></td>
    </tr>
    <tr>
    
    <td><label>পিতার পেশা</label></td>
    <td><select name="পিতার পেশা">
      <option value="পেশা" disabled selected> পেশা কি? </option>
      <option value="প্রবাসী">প্রবাসী </option>
      <option value="ব্যবসায়ী ">ব্যবসায়ী</option>
      <option value="কৃষক">কৃষক</option>
      <option value="মিস্ত্রি">মিস্ত্রি </option>
    </select>
    </td>
    </tr>
    <tr>
      
    <td><label>পিতার মোবাইল</label></td>
    <td><input type="number" name= number placeholder="                পিতার মোবাইল" min="10000000000" mix="99999999999"></td>
    </tr>
    <tr>

    <td><label>স্থায়ী গ্রাম </label></td>
     <td><input type="text " name=village
     placeholder="                      স্থায়ী গ্রাম" ></td>
    </tr>
    <tr>
   <td> <label>ডাকঘর </label></td>
    <td><input type="text " name="post" placeholder="                        ডাকঘর" office ></td>
    </tr>
    <tr>
    
    <td><label>উপজেলা </label></td>
    <td><input type="text " name="opojela" placeholder="                      উপজেলা"></td>
    </tr>
    <tr>
    
    <td><label>জেলা </label></td>
    <td><input type="text " name="district " placeholder="                         জেলা"></td>
    </tr>
    <tr>

    <td><label>অভিভাবকের নাম </label></td>
    <td><input type="text" name="obibabok" placeholder="              অভিভাবকের নাম"></td>
    </tr>
    <tr>
    
    <td><label>অভিভাবক পেশা </label></td>
    <td><select>
          <option selected disabled  >পেশা কি? </option>
      <option value="#">ব্যবসায়ী </option>
      <option value="#">প্রবাসী </option>
      <option value="#">কৃষক </option>
     <option value="#">গৃহিণী </option>
     <option value="#">মিস্ত্রি </option>
     <option value="#">চাকরী </option>
    
    </select></td>
    </tr>
    <tr>
     <td><label>অভি: মোবাইল</label>  </td>
    <td><input type="number" name= number placeholder="             অভিভাবকের মোবাইল" min="10000000000" mix="99999999999"></td>
    </tr>
     <tr>
    <td><label>পূর্বের ক্লাস </label></td>
    <td><input type="text " name="class" placeholder="                    পূ্র্বের ক্লাস""></td>
    </tr>
      <tr>
    <td><label>ইচ্ছুক ক্লাস </label></td>
    <td><input type="text " name="class" placeholder="                    ইচ্ছুক ক্লাস""></td>
    </tr>
    <tr>
    <td><label>বর্তমান ক্লাস </label></td>
    <td><input type="text " name="class" placeholder="                    বর্তমান  ক্লাস""></td>
    </tr>
    <tr>
    
    <td><label>পূর্বের রেজাল্ট (গড়) </label></td>
    <td><input type="text " name="opojela" placeholder="                    পূর্বের রেজাল্ট"></td>
    </tr>
    
    <tr>
    <td class="btn"><input type="submit" value="click">
    </td>
    </tr>
 
 
   </form>
  
    
  

</body>

</html>

**Review by lecoursen — APPROVED** [review]
Thanks, this looks great!

**Pull request merged**
