### PR TITLE
 Add example for outputting a gpg public key 

### PR DESCRIPTION
**Pull request by elessar-ch**
### Why:
Docs to add an existing GPG key do not show how to print said public key.

Closes [issue link]

### What's being changed:
A new reusable has been inserted with the command to show a GPG public key and is being referenced in the docs page "Checking for existing GPG keys"

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@elessar-ch 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Barbarafriedley — COMMENTED** [review]
[8707400340](BarbiDoll)

**Review by hubwriter — APPROVED** [review]
@elessar-ch - Many thanks for raising this PR to help improve the GitHub documentation. 👍 

We don't add reusables until text needs to be used in more than one place. As this PR adds a reusable but only uses it in one place it's better to add the new text as normal inline text for now. We can pull it out into a reusable if we want to use it in multiple places.

Thanks again for making this change. I'll get this merged/published now. 🚀

**Review by Cl0udtN9ne — COMMENTED** [review]
@cl0udtn9ne

**Pull request merged**
