### PR TITLE
Added row for deleting a discussion in repository permissions table

### PR DESCRIPTION
**Pull request by adithyasunil26**
### Why:
This is with reference to issue #2665 for missing permissions for deleting a discussion

### What's being changed:

content/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization.md

Added code:
```
| Delete a discussion | | | | **X** | **X** |
```

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@adithyasunil26 Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by hubwriter — CHANGES_REQUESTED** [review]
@adithyasunil26 - thanks for raising this PR. 

There are a couple of little changes needed. If you'd like to apply these changes I'll get this merged.

Thanks again for helping with the GitHub documentation. 👍

**Comment by hubwriter** [comment]
@adithyasunil26 - Thanks again for doing this. I'll merge this PR now.

**Review by hubwriter — APPROVED** [review]

**Comment by adithyasunil26** [comment]
@hubwriter Always happy to contribute.

**Comment by Mrnathanwayne1** [comment]
Opt-out

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request merged**
