### PR TITLE
Update authenticate-to-container-registry-steps.md

### PR DESCRIPTION
**Pull request by ben-elttam**
Instructions are not currently possible due to a bug. Added note regarding bug, and work-around.

### Why:

https://github.community/t/how-to-create-a-pat-with-write-packages-and-without-repo-permissions/149416

### What's being changed:

See the diff.

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@ben-elttam Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by matthewphillips01** [comment]
> Instructions are not currently possible due to a bug. Added note regarding bug, and work-around.
> 
> ### Why:
> https://github.community/t/how-to-create-a-pat-with-write-packages-and-without-repo-permissions/149416
> 
> ### What's being changed:
> See the diff.
> 
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

Not at all better of man kind

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by jmarlena** [comment]
Hi @ben-elttam! 

It seems this workaround isn't working anymore. We're actually tracking a different type of fix for this issue in https://github.com/github/docs/pull/3746 so I'm going to close this PR for now. 

We appreciate your time and care! 💛

**Pull request closed without merging**
