### PR TITLE
Apps introLink is broken

### PR DESCRIPTION
**Pull request by leabs**
Incorrectly points to https://docs.github.com/en/apps/creating-github-apps/building-github-apps/about-apps should point to https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/about-apps

### Why:

Closes ISSUE

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The Header link on https://docs.github.com/en/apps (About Apps) is broken.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- I tested my update locally!
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by abolfazlpiltanes341** [comment]
Abolfazlpiltan

**Comment by cmwilson21** [comment]
@leabs Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
🚀 Thanks for this fix! We'll get this merged down for you.

**Comment by 7koma95** [comment]
- [ ] lightstep/lightstep-action-predeploy
**[]()**

**Pull request merged**
