### PR TITLE
#7975 Added missing activity types to pull_request trigger

### LINKED ISSUE #7975: Activity type "converted_to_draft" is missing from Events that Trigger Workflows
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

In the "activity types" list for the "pull_request" trigger the activity type "converted_to_draft" is missing.  It is present on the webhook events and payloads page.  In addition, now that I compare the two directly, the following activity types also seem to be missing: auto_merge_disabled, auto_merge_enabled.

### PR DESCRIPTION
**Pull request by westonpace**
### Why:

Closes #7975 

### What's being changed:

pull_request_img1
pull_request_img2

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by westonpace** [comment]
I checked and the tags appear to be properly controlling the version-dependent inclusion of the auto merge activity types.

**Review by Artek199 — APPROVED** [review]

**Comment by gsteele178** [comment]
I wouldn't create a log lol

**Comment by ramyaparimi** [comment]
@westonpace Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
🚀 This looks great! I'll get this merged down for you.

**Pull request merged**
