### PR TITLE
Fix copy-paste mistake

### PR DESCRIPTION
**Pull request by TWiStErRob**
`mutation` response will match the mutation name.

### Why:

Closes no issue, trivial problem.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects#adding-a-draft-issue-to-a-project

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by nutty323 — COMMENTED** [review]
#[Auto Merge Dependency Updates](https://github.com/github/docs/actions/workflows/automerge-dependencies.yml)

**Comment by cmwilson21** [comment]
@TWiStErRob Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for fixing this! We'll get this merged down for you.

**Comment by TWiStErRob** [comment]
@skedwards88 thanks, it looks like it's blocked on an approval of a workflow; hopefully you see which one.

**Pull request merged**
