### PR TITLE
[DO NOT MERGE] Just testing the Azure Preview Deploy workflow

### PR DESCRIPTION
**Pull request by peterbe**
Me testing the updated credentials 
Part of https://github.com/github/docs-engineering/issues/4325

### CODE REVIEW

**Comment by peterbe** [comment]
It worked.

**Comment by NET6666STREEM** [comment]
[Notify about production deployment](https://github.com/github/docs/actions/workflows/notify-about-deployment.yml)

**Review by OKEAMAH — COMMENTED** [review]
Sm

**Review by Osama2535 — COMMENTED** [review]
Oatef4313@gmail.com

**Pull request closed without merging**
