### PR TITLE
Use the same processor name that it is in _config.yml

### PR DESCRIPTION
**Pull request by Davidy22**
### Why:

Trim confusion, call it GFM instead of commonmark since that's what people have to type in _config.yml to use it.

### What's being changed:

Changed one instance of the work commonmark to GFM

### Check off the following:

- [y ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [y ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@Davidy22 Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hubwriter** [comment]
@Davidy22 - Thank you for contributing this change. However, I disagree with your suggestion because the previous paragraph explains that 2 processors are supported (kramdown and CommonMark) and then this sentence states that you need to use CommonMark if you want to match the results you see on GitHub. I think it's clearer to leave this sentence referring to CommonMark.

I'm going to close this PR, but thank you again for suggesting the change.

**Comment by Davidy22** [comment]
I actually came to the help page because I received an email with the following text:

> You are currently using the 'commonmark' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://docs.github.com/github/working-with-github-pages/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll.

Which I made this ticket for because the email promises imminent cessation of commonmark, so I figured the help page would need to be updated so people don't use it. I did make an assumption that the replacement would be GFM, from the description that it was an extension of commonmark.

**Review by hubwriter — APPROVED** [review]
I've removed the reference to CommonMark. I think we can go ahead and get this merged. 👍

**Pull request merged**
