### PR TITLE
Revert "repo sync"

### PR DESCRIPTION
**Pull request by dhivyadharshin**
Reverts github/docs#9141

### CODE REVIEW

**Comment by dhivyadharshin** [comment]
sure!

**Comment by ramyaparimi** [comment]
@dhivyadharshin This seems to be opened accidentally, I am going to close it now :yellow_heart: Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions :sparkles:

**Comment by dhivyadharshin** [comment]
Thanks, I'll check it out.

**Comment by cyborgspace01** [comment]
Hiii i am new to it help me  in contributing projects?

**Comment by ArnoWestraadt** [comment]
Hi yes

**Pull request closed without merging**
