### PR TITLE
Fix cleanup example to use pull_request_target trigger

### LINKED ISSUE #31321: The workflow named "cleanup caches by a branch" is not working as expected
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

### What part(s) of the article would you like to see updated?

Modify the workflow example in [Managing caches > Force deleting cache entries](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries)

Why:
When triggered by the `pull_request` event, the `GITHUB_TOKEN` does not have permission to delete the cache of the base repository in a cross-repository pull request. This results in the error `Error: Resource not accessible by integration`.

### Additional information

This always happens for cross-repository pull requests.

### PR DESCRIPTION
**Pull request by Mogyuchi**
### Why:

Closes: #31321 

### What's being changed (if available, include any code snippets, screenshots, or gifs):
image

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@Mogyuchi Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by corneliusroemer — COMMENTED** [review]
I tested this change and it does _not_ fix the issue unfortunately

I still get the same error, at least when triggering manually (having added `workflow_dispatch:` to do so)

Maybe that's as expected, maybe the permissions are only granted when you merge a PR, hard to tell/test

I see, the right permissions might be auto-granted due to this change:
>When a workflow is triggered by the [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event, the GITHUB_TOKEN is granted read/write repository permission, even when it is triggered from a public fork. For more information, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)."
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

I've added explicit token permissions in #31582, this allowed me to test via `workflow_dispatch:`

**Comment by Mogyuchi** [comment]
@jc-clark
https://github.com/github/docs/pull/31582#issuecomment-1979764206
> What would you think of keeping `pull_request` as the triggering event here but adding a note above the example that links to "[`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)" and describes the cross-repo pull request use case?

No… I think we should use "[`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)".
Especially in public repositories, I think there is a possibility that cross-repo pull requests will be made even if the repository owner does not assume it. Therefore, I think we should present the example that takes into account the existence of cross-repo pull requests.

**Review by Boozing1973 — COMMENTED** [review]
Duplicate of #

**Pull request closed without merging**
