### PR TITLE
Updating caching dependencies

### LINKED ISSUE #6920: Maven caching dependencies not working.
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

### What part(s) of the article would you like to see updated?

This should change-->  restore-keys: ${{ runner.os }}-m2
To this--> restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

### PR DESCRIPTION
**Pull request by ankur512512**
Caching was not working as expected and was getting cache not found due to mismatch between key and restore key.

### Why:

Cache dependency was not working for maven.

Closes https://github.com/github/docs/issues/6920

### What's being changed:

restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@ankur512512 Thanks so much for opening a PR and an issue! I'll get this triaged for review ⚡

**Comment by lucascosti** [comment]
👋 Hi @ankur512512, thanks for submitting this PR! 🙇‍♂️ 

The change you're suggesting shouldn't be necessary because the cache action already matches on `key`, and `restore-keys` should also works with partial matches. (see our caching doc for more info: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)

If you are still having issues, you could [contact our support team](https://support.github.com/).

**Comment by ankur512512** [comment]
> 👋 Hi @ankur512512, thanks for submitting this PR! 🙇‍♂️
> 
> The change you're suggesting shouldn't be necessary because the cache action already matches on `key`, and `restore-keys` should also works with partial matches. (see our caching doc for more info: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)
> 
> If you are still having issues, you could [contact our support team](https://support.github.com/).

Oh thanks, that makes sense.

**Review by duongxuantuan154 — COMMENTED** [review]
Cập nhật phần phụ thuộc vào bộ nhớ đệm

**Pull request closed without merging**
