### PR TITLE
Update troubleshooting-required-status-checks.md

### LINKED ISSUE #24181: Added more info to Handling skipped but required checks
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

### What part(s) of the article would you like to see updated?

In the section `handling-skipped-but-required-checks`, the docs do not shed any light for the case mentioned below:

When someone sends a pull request that changes the files listed under `paths` and also changes a file that is not listed under `paths-ignore` in the other workflow. In such a case, both workflows must be executed and the associated status checks must pass in order to merge the PR.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cb-shivamagarwal**
### Why:

Closes #24181 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added more information

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@cb-shivamagarwal Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Comment by cb-shivamagarwal** [comment]
@cmwilson21 Thank you for getting this triaged for review.

**Comment by cb-shivamagarwal** [comment]
Hey @cmwilson21 ,
   It seems this has not been reviewed yet. May you please help ?

**Comment by cmwilson21** [comment]
@cb-shivamagarwal Thanks for checking in! This is on the board and waiting for writer review. Someone will have eyes on it soon 👀 

We appreciate your patience as we are working through our backlog. 💖

**Comment by zxieroblox** [comment]
curious - if one workflow passes (the one that is no-op with paths-ignore) and the other (the real workflow with `paths`) failed, will the branch protection block the merge? I cannot find documentation on if branch protection works as a `need-all-to-succeed` or `at-least-one`. Thanks.

**Comment by cb-shivamagarwal** [comment]
> curious - if one workflow passes (the one that is no-op with paths-ignore) and the other (the real workflow with `paths`) failed, will the branch protection block the merge? I cannot find documentation on if branch protection works as a `need-all-to-succeed` or `at-least-one`. Thanks.

Yes, it will block the merge. Even I could NOT find the documentation. Hence, this PR was created.

**Comment by cb-shivamagarwal** [comment]
Closing this PR as the docs have been updated

**Comment by cmwilson21** [comment]
@cb-shivamagarwal Thanks so much for coming back and closing it out 💖

**Pull request closed without merging**
