### PR TITLE
Explain that a "list" means "of lines" not of YAML

### PR DESCRIPTION
**Pull request by kousu**
### Why:

If I try

```
    - name: caching
      uses: actions/cache@v2
      with:
        path:
          - ~/.cache
        key: build-${{ github.ref }}
        restore-keys: |
          build-
```

I just get an unexplained "Startup Failure": https://github.com/spine-generic/data-multi-subject/actions/runs/742876119. Switching to a YAML multiline string

```
    - name: caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
        key: build-${{ github.ref }}
        restore-keys: |
          build-
```

works: https://github.com/spine-generic/data-multi-subject/actions/runs/742878382

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@kousu Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by martin389** [comment]
### Changes in this PR
| Article in staging  | Changes |
| --- | --- | 
“[Using the `cache` action](https://docs-5309--patch-1.herokuapp.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action)” | Clarifies how to define multiple paths in `path`.

### Tests
All tests are passing! :green_apple:

**Comment by martin389** [comment]
Thanks for the PR @kousu 🎊 This is really helpful!

I've also added an example codeblock to the section, because I noticed we don't demonstrate multiple paths in the article.

**Review by martin389 — APPROVED** [review]

**Comment by martin389** [comment]
Added some edits based on peer review

**Pull request merged**
