### PR TITLE
Update deploying-to-google-kubernetes-engine.md

### PR DESCRIPTION
**Pull request by dmlls**
### Why:

Without adding the role `container.clusterViewer` to the created service account I was getting the error: `Error: Required "container.clusters.get" permission(s)` when running `google-github-actions/get-gke-credentials@v0.2.1`. Adding that role, as stated in the [action readme](https://github.com/marketplace/actions/get-gke-credentials#authorization) fixed it.

Also, I believe there was a mistake in the step "Store the project ID as a secret named `GKE_PROJECT`", since then the `GKE_SA_KEY` was exported.

### What's being changed:

- Add the role  `container.clusterViewer` to the created service account.
- Fix misleading step when creating secret for `GKE_SA_KEY`.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@dmlls Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by dmlls** [comment]
Just commenting to prevent the PR from being closed by the bot.

**Comment by martin389** [comment]
Thanks for this PR! Checking these changes with our support folks 👍

**Comment by martin389** [comment]
### Changes in this PR

(These links will stop working once this PR is merged)
| Article in staging  | Changes |
| --- | --- | 
“[Configuring a service account and storing its credentials](https://docs-3488--patch-1.herokuapp.com/en/actions/guides/deploying-to-google-kubernetes-engine#configuring-a-service-account-and-storing-its-credentials)” |  Changes to steps 3 and 5.

### Tests
All tests are passing! :green_apple:

**Comment by martin389** [comment]
(Just closing and reopening this PR for CI purposes)

**Comment by martin389** [comment]
Confirmed that this is queued for review 👍

**Review by Hbutlercapone — APPROVED** [review]
Connected google

**Comment by duongxuantuan154** [comment]
Phê duyệt

**Review by SalDenizardJr — APPROVED** [review]

**Review by SalDenizardJr — APPROVED** [review]

**Review by SalDenizardJr — APPROVED** [review]

**Review by francisfuzz — APPROVED** [review]
@dmlls - Thanks for helping improve this documentation. I reviewed these changes and am leaving a "formal" approval here. We really appreciate it!

cc: @martin389 - tagging you in for the final approval. 👍

**Review by martin389 — APPROVED** [review]

**Comment by martin389** [comment]
(Closing and reopening this PR for CI purposes)

**Comment by martin389** [comment]
Aha, looks like I can't reopen this PR because `dmlls:patch-1` was removed.

@dmlls - would you mind recreating this PR and keeping your repo around until this gets merged? We've got all the approvals we'll need for the proposed changes, so  it'll be quick for me to process the new PR.

**Comment by dmlls** [comment]
@martin389 my bad! I recreated the PR at https://github.com/github/docs/pull/8759 :)

**Comment by martin389** [comment]
@francisfuzz - thanks so much for reviewing! I've merged these changes under this PR: https://github.com/github/docs/pull/8759

**Pull request closed without merging**
