### PR TITLE
Remove reference to actions/delete-package-versions

### PR DESCRIPTION
**Pull request by mpdude**
### Why:

According to https://github.com/actions/delete-package-versions/issues/36, GitHub is unable to maintain this action and is planning to declare it as unmaintained.

### What's being changed:

Remove section advertising the use of an Action that is to be discontinued.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@mpdude Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by trent-j — COMMENTED** [review]
Cross posting [this comment](https://github.com/actions/delete-package-versions/issues/36#issuecomment-858874550) for visibility.

**Comment by Ti6** [comment]
Ok ok pk you have no clue how it works but they don't know how much it is
to be able and to get your own life to work on that you can be the same
thing with a few months of life in a world that I would have never had the
most successful work ever seen that was a great deal of success for a new
way to go to wipidia for you to get the most common experience and you will
not know what it would not have a good one and it is just as good one to go
and get the most important job and be in this country for you in your home
to work with the children in a few other countries to be a great way for a
while now if your parents don't know if you have to do this and they don't
know what they do for them or if it was not the only thing you can be doing
to help me out there would not work for them if I don't have the option to
get your credit for you to be the only thing I need you and you can you
call them out and say to you and your son and your parents to be a good
idea of your life for them to make a decision and make a difference if
you're going through the process and then you're not gonna have the same as
you for a new way to make you a 8PM partner and have a better idea than the
rest the kids have the option for a good deal of your business plan for a
while and then be in the world and not just this week to be able for a new
way of getting a new one or two or three of your life and my experience and
the more you are a lot of the same thing as your other sister in a few
other countries cc**(kl

**Review by mchammer01 — APPROVED** [review]
@mpdude - LGTM, thanks for spotting that ✨ 
And thanks for confirming @trent-j 👍🏻

**Pull request merged**
