### PR TITLE
Add `ci_activity` to email notifications Cc list

### LINKED ISSUE #4327: Add `ci_activity` to email notifications Cc list
### What article on docs.github.com is affected?

[Configuring notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications)

### What part(s) of the article would you like to see updated?

The [Filtering email notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#filtering-email-notifications) section lists the ways in which GitHub includes notification metadata in notification emails. Part of that metadata is the `Cc` field which includes a reason why the user is receiving the email.

Currently, email notifications about completed action runs are sent with `ci_activity@noreply.github.com` in the `Cc` field. This is not documented here, so I believe it should be added.

### Additional information

I only use GitHub actions for CI, so I don't know how non-GHA CI is handled by notifications. I imagine that it is handled the same way, though, given that the reason is a generic `ci_activity` rather than something more specific like `workflow_activity` or `action_activity`.

### PR DESCRIPTION
**Pull request by Rylan12**
### Why:

**Closes https://github.com/github/docs/issues/4327**

The [Filtering email notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#filtering-email-notifications) section of the [Configuring notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications) documentation lists the ways in which GitHub includes notification metadata in notification emails. Part of that metadata is the `Cc` field which includes a reason why the user is receiving the email.

Currently, email notifications about completed action runs are sent with `ci_activity@noreply.github.com` in the `Cc` field. This is not documented here, so I believe it should be added.

### What's being changed:

I've added the following element to the `Cc` row in the table:

> - `ci_activity`: An action run that you initiated finished.

I'm not completely sure about the wording here. I chose not to use the GitHub Actions product name because this is referring to an instance of a GitHub Actions "thing". I also wasn't sure if "action run" is necessary or simply "action" is sufficient. I'll differ to you for the specific terminology that should be used (e.g. workflow, action, ci run, etc.)

Also, as noted in https://github.com/github/docs/issues/4327, I don't know if the wording should be modified to not be exclusive to GitHub Actions CI. If non-GHA CI would also trigger these notifications, it may make more sense to use generic wording such as:

> - `ci_activity`: A CI run that you initiated finished.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Rylan12** [comment]
As this PR hasn't yet been reviewed, I'd like it to remain open.

**Comment by janiceilene** [comment]
@Rylan12 Thanks so much for opening a PR! I'll get this triaged for review ✨ Sorry about the delay, I was out last week 💛

**Review by lucascosti — APPROVED** [review]
Thanks a lot for this contribution, @Rylan12! 🙇‍♂️ 

I made an edit to add versioning for the products that GitHub Actions is in, as well as our terminology (`workflow run`).

> I don't know if the wording should be modified to not be exclusive to GitHub Actions CI. If non-GHA CI would also trigger these notifications, it may make more sense to use generic wording

I'm 90% sure that this notification is only for GitHub Actions 👍 

I'll get it merged in! 🎉

**Comment by 1SatoshiNakamoto** [comment]
Wow I a so pleased to hear you are ON THE BALL man!!!!!! Great job(✷‿✷)(✷‿✷)(✷‿✷)



This is my usual face the first 7 years! LoL maybe you can teach me some cool gigs
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 12:44 AM, ***@***.***> wrote:   


Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our help wanted issues ⚡

**Comment by 1SatoshiNakamoto** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 12:47 AM, heidi ***@***.***> wrote:   Wow I a so pleased to hear you are ON THE BALL man!!!!!! Great job(✷‿✷)(✷‿✷)(✷‿✷)



This is my usual face the first 7 years! LoL maybe you can teach me some cool gigs
Sent from Yahoo Mail on Android 
 
  On Mon, Mar 29, 2021 at 12:44 AM, ***@***.***> wrote:   


Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our help wanted issues ⚡

**Pull request merged**
