### PR TITLE
Create npm-publish.yml

### PR DESCRIPTION
**Pull request by Small25**
### Why:

**Closes [issue link]**

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [x] This pull request impacts the contribution experience
  - [x] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Review by Ice991 — COMMENTED** [review]
รุ่นโหนด : 12
      - รัน : npm ci
      - รัน : ทดสอบ npm

  เผยแพร่ -npm :
    ความต้องการ : สร้าง
    รันบน : อูบุนตูล่าสุด
    ขั้นตอน :
      - ใช้ : actions / checkout @ v2
      - ใช้ : actions / setup-node @ v2
        กับ :
          รุ่นโหนด : 12
          URL รีจิสทรี : https://registry.npmjs.org/
      - รัน : npm ci
      - รัน : เผยแพร่ npm
        env :
          NODE_AUTH_TOKEN : $ {{secret.npm_token}}

  เผยแพร่ -gpr :
    ความต้องการ : สร้าง
    รันบน : อูบุนตูล่าสุด
    สิทธิ์ :
      เนื้อหา : อ่าน
      แพ็คเกจ : เขียน
    ขั้นตอน :
      - ใช้ : actions / checkout @ v2
      - ใช้ : actions / setup-node @ v2
        กับ :
          รุ่นโหนด : 12
          รีจิสทรี-url : https://npm.pkg.github.com/
      - รัน : npm ci
      - รัน : เผยแพร่ npm
        env :
          NODE_AUTH_TOKEN : $ {{secret.GITHUB_TOKEN}}

**Comment by kevcreamer** [comment]
Hi there - Thank you for all of your help. Please forgive me but I have
absolutely no understanding about any of this from webhooks to pull
requests to dependabots let alone how to decipher what actions I should
take based off of your comments let alone how to implement them. If you
could please act like I don't understand your language and update me where
things stand, how soon or confident you are they will be resolved and if
there is anything I need to do (explained as simply and clearly as
possible). Also I also received an email that the NuGet application has
been added to my account and I'm not sure if that is on purpose or another
issue but I am reticent to even search on the page now because of
vulnerabilities. Thank you all SO MUCH for your help.

Also I don't know how to navigate the multiple responses
from multiple users from notifications and docs and from different groups.
Is there a way to know that Ii have reached a final resolution from a
defining source? If I need to pay more to help coordinate all the great
work you have done ini order to receive a distinct solution from a
presiding individual I will be happy to do so. Again, thank you for your
help.

Best,
Kevin

**Review by Ice991 — COMMENTED** [review]
จบ

**Comment by linhhai997** [comment]
-

**Comment by linhhai997** [comment]
> 👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions. The complete list of files we can't accept are:
> translations/**
> lib/rest/static/**
> .github/workflows/**
> .github/CODEOWNERS
> translations/**
> assets/fonts/**
> data/graphql/**
> lib/graphql/**
> lib/redirects/**
> lib/rest/**
> lib/webhooks/**
> 
> You'll need to revert all of the files you changed in that list using [GitHub Desktop](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/reverting-a-commit) or `git checkout origin/main <file name>`. Once you get those files reverted, we can continue with the review process. :octocat:

**Pull request closed without merging**
