### PR TITLE
Fix the table overflowing sidebar

### LINKED ISSUE #1205: Table with long words overlaps with sidebar
Hi there! Thanks so much for the great documentation <3

It seems #56 is back on another page. This time in a table with a word that is too long.

### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls

### What part(s) of the article would you like to see updated?

The following table not overlap with the sidebar:

image

### PR DESCRIPTION
**Pull request by SMAKSS**
Fixes #1205
Changing the table markup in the [Commit SHAs](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls#commit-shas) according to the previous fix which controls the overflow of the table with the use of [javascript/wrap-code-terms.js](https://github.com/github/docs/blob/main/javascripts/wrap-code-terms.js).

### Why:
Well, this PR will fix #1205 where the table has overflowed the sidebar like below:
original

### What's being changed:
I tried to stick with the previous fix which fixes the #56 with the use of [javascript/wrap-code-terms.js](https://github.com/github/docs/blob/main/javascripts/wrap-code-terms.js), so I just tried to change the current markup of the table. Since the current logic will only support the breaking of contents within a `<code>` tag I had to wrap the necessary items which cause them to overflow in the `<code>` tag.

So it will look like this:
bold

But since the current style of the `<code>` tags within the table will make them bold I had to remove it from the general style to make the whole table look better, it may break changes in other pages *(like [this one](https://docs.github.com/en/enterprise-server@2.22/github/working-with-github-pages/about-github-pages))* but I think they are overall looking good without `font-weight: bold;` but this is for owners to decide, so if there is any other suggestion to make it better I will be happy to make the necessary changes in the codebase.

The final look of the table:
final

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks so much @SMAKSS! I'll get this triaged for review ⚡

**Review by sarahs — APPROVED** [review]
Thanks @SMAKSS! Using `<code>` tags here is a good change. 👍 And we agree the tables look better without the bold. Thanks for checking in about that!

**Comment by simpsoka** [comment]
One question I had about this... and we don't have to do it as part of this PR, but something to think about. If anything is bolded on the table, should it be the column headers?

**Comment by SMAKSS** [comment]
@simpsoka It is really interesting I guess. IMO it even looks nicer than normal headers.

Here is an approximate then and before pic of it to give a rough idea about how it looks nicer 😁 to those who don't have time to try it.

Before
original

Then
bold

At the end if there are any decision to make this happened I will be happy to make another teeny tiny PR to change this.

**Comment by simpsoka** [comment]
@SMAKSS I like the bold column titles :)

**Comment by composio-dev** [comment]
### PR Changes Summary

#### Objective
This PR aims to address an issue related to table overflow in the sidebar. It modifies the current markup of the table to use JavaScript to wrap code terms, thereby preventing overflow issues.

#### Changes

- **Type:** Fix
- **Important Files: **
    1. `content/github/writing-on-github/autolinked-references-and-urls.md`: Adjusted the formatting of URLs and repository references. Modified 4 lines, including additions and deletions.
    2. `stylesheets/tables.scss`: Removed the bold font-weight from table headers to comply with the new table structure.

Feel free to review the changes [here](https://github.com/github/docs/compare/d8cb56243ee7f00aab2e0be1eba374056ef0c986...4f0d4ceb34c15543910c27f444a9cd0f8a7abdb7).

**Pull request merged**
