### PR TITLE
Update and rename responsible-disclosure-of-security-vulnerabilities md to coordinated-disclosure-of-security-vulnerabilities.md

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Remove the word "responsible" from vulnerability disclosure policy, replace with "coordinated".

### Why:

For lots of the discussion and points here I'll be referencing this article [Coordinated Vulnerability Disclosure: Bringing Balance to the Force](https://docs.microsoft.com/en-us/archive/blogs/ecostrat/coordinated-vulnerability-disclosure-bringing-balance-to-the-force) by [Katie Moussouris](https://twitter.com/k8em0) from 2010.

"Responsible" implies a set of ethics and morals are involved in vulnerability disclosure. "responsible" is also very subjective. From the perspective of the security researcher, the company (in this case GitHub) may be the "irresponsible" party for releasing the vulnerable code without adequate testing. From the perspective of the company, in this case GitHub, the researcher may be "irresponsible" if they choose to go public with a vulnerability before the vulnerability is fully patched and shipped to customer. As such, much of the industry has moved away from the term "Responsible" to the term "Coordinated".

> Responsible Disclosure should be deprecated in favor of something focused on getting the job done, which is to improve security and to protect users and systems.

Additionally, Coordinated Vulnerability Disclosure (CVD) has been the norm at Microsoft for 11 years. GitHub should similarly match the language around vulnerability disclosure that Microsoft has.

### What's being changed:

This replaces the term "responsible" with "coordinated" with respect to GitHub's vulnerability disclosure policy.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by lee-dohm — DISMISSED** [review]
Looks good from a site-policy perspective.

**Review by ethanpalm — APPROVED** [review]
These changes look good to go from a docs' perspective. Thanks for creating this PR, @JLLeitschuh ✨

**Comment by JLLeitschuh** [comment]
> While this is being addressed. I believe the following change should also be made here:
> 
> > [bounty.github.com/#legal_safe_harbor](https://bounty.github.com/#legal_safe_harbor)
> 
> Currently:
> 
> > We want you to responsibly disclose through our bug bounty program, and don’t want researchers put in fear of legal consequences because of their good faith attempts to comply with our bug bounty policy. We cannot bind any third party, so do not assume this protection extends to any third party. If in doubt, ask us before engaging in any specific action you think might go outside the bounds of our policy.
> 
> Should be changed to:
> 
> > We want you to coordinate disclosure through our bug bounty program, and don’t want researchers put in fear of legal consequences because of their good faith attempts to comply with our bug bounty policy. We cannot bind any third party, so do not assume this protection extends to any third party. If in doubt, ask us before engaging in any specific action you think might go outside the bounds of our policy.

Thanks all! Can we also make sure that this part is also resolved as well please.

**Comment by vollmera** [comment]
💯 @JLLeitschuh - We requested the changes on bounty.github.com/#legal_safe_harbor and are keeping an eye out!

(I'd mentioned 👇 in https://github.com/github/site-policy/issues/477#issuecomment-965815619)
>@JLLeitschuh I pushed github/docs@ec06da1 to ~responsible~ **coordinated** in one more spot and added Bug Bounty Program - Legal Safe Harbor to your PR.
>
>https://bounty.github.com/#legal_safe_harbor is maintained separately. We'll update the site-policy docs in the meantime.

**Comment by vollmera** [comment]
@JLLeitschuh - the change you requested is now live on https://bounty.github.com/#legal_safe_harbor 🎉 

thanks again for your ✨ contributions to these docs!

**Comment by JLLeitschuh** [comment]
Awesome! Thank you so much!

**Pull request merged**
