### PR TITLE
Update linking-a-pull-request-to-an-issue.md

### PR DESCRIPTION
**Pull request by casals**
### Why:

Fixes part of #165 (last suggestion made by the author)

### What's being changed:

Issue #165 requires two different fixes. This is the first one, related to changing the document "[Linking a pull request to an issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)". As suggested by the linked issue's author, I changed the introductory sentence at the beginning of the referenced section to "You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message."

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks @casals! I'll send both of these PRs to the @github/docs-content-core team to review 😸

**Comment by myarb** [comment]
Thanks for this PR! I see you made this same change (along with others) in https://github.com/github/docs/pull/199, so I'll close this PR in favor of that one 💖 ✨ and we'll get it reviewed and merged 🔜

**Comment by myarb** [comment]
👋🏼 @casals I'm sorry if I misunderstood. If you look at the edited file in this PR ([here](https://github.com/github/docs/pull/198/files)) and the edited file in the other PR ([#199, here](https://github.com/github/docs/pull/199/files)), the paragraph under the header `Linking a pull request to an issue using a keyword` is edited in both with "or in a commit message." I believe #199 captures both alterations, but please let me know if I misunderstood!

**Comment by casals** [comment]
Hey @myarb - you're right - I'm terribly sorry. I had another pair of PRs related to the same issue and I thought this was the right pair. I have absolutely no idea why I opened 2 PRs for the same file 😅 Sorry for the confusion!

**Pull request closed without merging**
