### PR TITLE
Update writing-mathematical-expressions.md: Unsupported Math Blocks in <details> Blocks

### PR DESCRIPTION
**Pull request by alernety**
This issue is about displaying math blocks inside of the `details` blocks (and potentially other HTML blocks) regardless of the type of math block. This can include blocks such as 

```
$$
\begin{pmatrix}
  0 & 1 \\
  2 & 3
\end{pmatrix}
$$
```

or blocks written like this: 

~~~
```math
\begin{pmatrix}
  0 & 1 \\
  2 & 3
\end{pmatrix}
```
~~~

This issue is currently blocking the use of math blocks inside of `details` blocks, as well as other HTML blocks. This limitation prevents users from taking full advantage of these blocks, and should be noted in documentation. To ensure users are not held back, we must actively search for a potential solution to this issue so that math blocks can be displayed in these blocks.

### Why:

Closes ISSUE

### What's being changed (if available, include any code snippets, screenshots, or gifs):

code
rendered

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by shango420** [comment]
> This issue is about displaying math blocks inside of the `details` blocks (and potentially other HTML blocks) regardless of the type of math block. This can include blocks such as 
> 
> ```
> $$
> \begin{pmatrix}
>   0 & 1 \\
>   2 & 3
> \end{pmatrix}
> $$
> ```
> 
> or blocks written like this: 
> 
> ~~~
> ```math
> \begin{pmatrix}
>   0 & 1 \\
>   2 & 3
> \end{pmatrix}
> ```
> ~~~
> 
> This issue is currently blocking the use of math blocks inside of `details` blocks, as well as other HTML blocks. This limitation prevents users from taking full advantage of these blocks, and should be noted in documentation. To ensure users are not held back, we must actively search for a potential solution to this issue so that math blocks can be displayed in these blocks.
> 
> 
> 
> ### Why:
> 
> Closes ISSUE
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> 
> 
> ### Check off the following:
> 
> - [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
> - [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 

> []()

**Review by shango420 — COMMENTED** [review]
content/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions.md 
-mathematical-expressions.md

**Comment by cmwilson21** [comment]
@ALernety Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by isaacmbrown** [comment]
Hi @ALernety, thanks for the PR! It appears to me that matrices render correctly IF you include a line of whitespace after the HTML tag.

For example,

````
<details>
<summary>Matrix</summary>

```math
\begin{pmatrix}
  0 & 1 \\
  2 & 3
\end{pmatrix}
```

</details>
````

Appears to render correctly:

<details>
<summary>Matrix</summary>

```math
\begin{pmatrix}
  0 & 1 \\
  2 & 3
\end{pmatrix}
```

</details>

I wonder if you could check whether this works for your use case too, and update your PR to reflect this if so? ✨

**Review by osama184 — COMMENTED** [review]
Co-authored-by: Laura Coursen <lecoursen@github.com>
Co-authored-by: Matt Pollard <mattpollard@users.noreply.github.com>

**Comment by cmwilson21** [comment]
It doesn't look like any updates have been on this for a while, so I'm going to go ahead and close it out 💛 

Feel free to ping me here to reopen if it continues to be an issue.

**Comment by DARKo6o6o6** [comment]
Ty for your help I'm just a little busy have 😳been on GitHub today

**Pull request closed without merging**
