### PR TITLE
Update form-schema required key information

### LINKED ISSUE #23524: Dropdown validation section does not specify it only works for public repositories.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#dropdown

### What part(s) of the article would you like to see updated?

The dropdown section, specifically the validation section, where it states `required` is a possible option, but it does not state it ONLY works for public repositories.

It is however stated in the quick-guide when editing an already commited yml file inside the ISSUE_TEMPLATE directory.

Screenshot is from the quick-guide.
Screenshot 2023-01-27 at 13 33 36

Screenshot is from the article:
image

### Additional information

I can see this is an issue for all the validations -> required fields on the docs.

### PR DESCRIPTION
**Pull request by MagnusHJensen**
### Why:

Closes #23524 
To fix missing information that is not present in the docs, but present in the in-file form schema editor:
Screenshot 2023-01-27 at 13 33 36

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Adds the `Only for public repositories` text on each required key.
Screenshot 2023-01-27 at 13 53 28

To align with the github in-file editor documentation: 
Screenshot 2023-01-27 at 13 33 36

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@MagnusHJensen Thank you for opening a PR and linking it to your issue! ✨ 

We appreciate all the screenshots 🤩 

I'll get this triaged for review! :zap:

**Review by afshinns — COMMENTED** [review]
data/reusables/form-schema/required-key.md

**Review by felicitymay — COMMENTED** [review]
@MagnusHJensen - many thanks for highlighting this difference between the help within the UI and the docs. It was especially helpful to have screenshots of the help, showing exactly what you were referring to ✨ 

I checked with the internal team and they agree that your change would make this much clearer to users 💖

**Review by felicitymay — APPROVED** [review]
@MagnusHJensen - thanks for this improvement to the docs 💖 

We have a note about the `required` field key in a different article: [Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), but the article you've updated seems to be missing this information. Adding it to this reusable is a great way to make this clearer to users 👍🏻 

I'll get this PR tested and ready to merge.

**Pull request merged**
