### PR TITLE
Clarify the wording here to match what is in the OKTA form.

### PR DESCRIPTION
**Pull request by adamrr724**
### Why: The wording should reflect the actual field name in OKTA, instead of a description of what the field is. 

Closes ISSUE https://github.com/github/docs/issues/22475

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updating the wording here to reflect the actual field name in the OKTA form.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by adamrr724** [comment]
@stacycarter to review the wording here.

**Comment by cmwilson21** [comment]
👋 @adamrr724 - Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by sophietheking — APPROVED** [review]
@adamrr724 👋  Thanks for opening a PR and clarifying this for our users! I've made a tiny change to this PR by adding quotation marks around the field name so it's in line with the rest of our documentation. I'll get this merged for you! 💖

**Comment by janl3577** [comment]
Pls help me

**Pull request merged**
