### PR TITLE
Fix maven code example to match instructions

### LINKED ISSUE #16562: Maven code example has wrong target
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

### What part(s) of the article would you like to see updated?

The first `mvn` command should be 'package' instead of `verify` as expected in the instructions.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dawinkweon**
### Why:

Closes #16562

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@dawinkweon 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ethomson** [comment]
Good catch @dawinkweon - thanks for the fix. LGTM.

**Comment by dawinkweon** [comment]
@ethomson Hi there, could we get an approval to get this in? Thanks, Dawin.

**Review by ramyaparimi — APPROVED** [review]
Approving to merge after tech review ✨

**Review by doc-svg — COMMENTED** [review]
#...http://-and-testing-java-with-maven.md...<          >...
[]()

**Comment by doc-svg** [comment]
[<>](www.pscinsuranceaustralia.com.au) Cntrl e

**Comment by doc-svg** [comment]
#...Delete...
#16563 
#17488 
#15325 
#17486 
#17485

**Comment by doc-svg** [comment]
@

...Delete ALL SYSTEM FILES.xls

**Review by doc-svg — COMMENTED** [review]
#15325 @matthewisabel

**Comment by doc-svg** [comment]
...[](100DaysOfKubernetes.patch)...
...(https://archiveprogram.github.com/)...

**Review by nattakritchotc — COMMENTED** [review]
https://www.sooddan.com
https://www.sooddan.cloud
https://www.sooddan.net
https://www.sooddan.space

**Comment by nattakritchotc** [comment]
- [ ]

[ ]

**Pull request merged**
