### PR TITLE
Clarify nature of GITHUB_ENV/GITHUB_PATH variables

### LINKED ISSUE #9235: Environment variable availability with GITHUB_ENV is unclear
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

### What part(s) of the article would you like to see updated?

Clarify that $GITHUB_ENV variables needs to be explicitly referenced in later steps, but $GITHUB_PATH applies automatically to subsequent steps.

### Additional information

PR will be opened shortly with suggested changes.

### PR DESCRIPTION
**Pull request by davidjb**
### Why:

When reading the existing documentation at https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable, I was under the impression that `$GITHUB_ENV` and `$GITHUB_PATH` would both be applied in the same way, both being available as environment variables within a given shell (the `run` command) in subsequent steps.  However, the former requires _explicit_ referencing in expression syntax (or use of the `$GITHUB_ENV` file directly) whereas the latter is introduced in the shell environment's `$PATH` automatically.  The docs don't currently state this; they allude to it in various other pages but not specifically spell this out.

Closes https://github.com/github/docs/issues/9235

### What's being changed:

This adds a note and clarification around the explicit nature of using $GITHUB_ENV but the implicit, automatic application of $GITHUB_PATH. 

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@davidjb Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Kittenmoon21 — APPROVED** [review]

**Review by L2021 — COMMENTED** [review]
Its interesting

**Review by L2021 — COMMENTED** [review]
Keep it up friend

**Review by Kittenmoon21 — APPROVED** [review]
workflows: example-workflow: jobs: - aws-ecs/deploy-service-update: cluster-name: #inventory control family: # accounts receivable

**Review by skedwards88 — DISMISSED** [review]
🎉 Thanks for making this addition! I'll get this merged down for you.

**Comment by ramyaparimi** [comment]
@davidjb It looks like I don't have permission to resolve the merge conflict. I think if you enable the checkbox to allow maintainer edits, then I will be able to resolve this. (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork ) Alternatively, could you resolve the merge conflict?

**Comment by davidjb** [comment]
@ramyaparimi the checkbox was already enabled so hopefully that’s good to go. Otherwise, I can take a look tomorrow and rebase the changes.

**Review by ramyaparimi — APPROVED** [review]
Approving again after resolving conflicts!

**Pull request merged**
