### PR TITLE
Clarify that environment variables should be treated as case sensitive

### LINKED ISSUE #19627: Clarify that env vars are at least somewhat case insensitive on Windows
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

### What part(s) of the article would you like to see updated?

> The names of environment variables are case-sensitive, and you can include punctuation.

This is true on Linux (and macOS).

However, my understanding is that this is at least partially untrue on Windows:
https://github.com/actions/runner/blob/cb19da9638790019f6e7be193cd4282311992b12/src/Runner.Worker/ActionCommandManager.cs#L158-L162

I say partially, because I haven't extensively tested the code paths.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

Closes:  #19627

### What's being changed (if available, include any code snippets, screenshots, or gifs):

image

image

image

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 Hey @jsoref!

Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by hubwriter — CHANGES_REQUESTED** [review]
@jsoref - This is great. Thanks for making the changes.

I have a couple of minor comments for you to consider.

Thanks again 👍

**Comment by emon738** [comment]
IMG20230721175045
Fre3

**Review by lhero19970 — COMMENTED** [review]
jsoref:issue-19627

**Review by hubwriter — APPROVED** [review]
LGTM 👍 
Thanks for the changes.
We'll get this merged when the current merge freeze is lifted.

Many thanks for this PR. 🎖️

**Pull request merged**
