### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #17811: PR template referencing things not present
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md

### What changes are you suggesting?

The PR template instructs me to some things that don't sound right, it may be just outdated terminology. Before addressing any of that in an actual PR I'm raising these for discussion:

1. "changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes"
   - I don't see anything "Modified" in the comment; there's a separate deployment timeline event, and the comment contains only "Preview", "Production" and empty "What's changed". Nothing more there to click. 🤷‍♂️ 
Was this meant to be something that's not there all the time, or has been removed/replaced?

2. The PR intro mentions linking a PR, that sounds like a place for referencing an issue to me, so maybe:

```diff
-By explaining why you're making a change (or linking to a pull request) and what changes you've made, …
+By explaining why you're making a change (or linking to an issue) and what changes you've made, …
```

3. The "local" links to `CONTRIBUTING.md` and `types-of-contributions.md` don't work in the context of a `/compare…` URL where the preview for new PR is being displayed, i. e. these two need to be converted to absolute like the others in the template.

I'll happily fix it if that's ok to touch the template file…

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cmwilson21**
### Why:

Closes [#17811](https://github.com/github/docs/issues/17811)

### What's being changed:
This is an overall refresh to the PR template while considering the concerns brought up in the issue linked above. The overall template has been slimmed down in general. More specifically:
- Relative links have been removed as they are in HTML comments and are un-clickable. Because they are relative links, users cannot copy and paste the entirety of the address. 
    - The contributing.md link was removed as it is linked under the PR box display.
    - Both translated content and site policy references were completely removed as there are not many of those. If these numbers increase after removal, we can add them back in again. 

Other smaller updates were made to tighten up screen space and update to current wording in the preview section.  

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Ruslan786136** [comment]
https://github.com/github/docs.git

**Comment by rsese** [comment]
I think docs-eng was pinged for review because of CODEOWNERS but this seems like something more for @janiceilene? 

I did take a peek though and 👍 on the update about the auto generated content comment -- wasn't changed to reflect updates so thanks for catching that!

**Comment by cmwilson21** [comment]
@rsese Sorry for the ping on the eng team, but thanks for taking a peek at it! I wish I could take the credit for noticing the auto generated comment, but that was from the issue creator. Then we decided the whole template could use a bit of an update. ✨ 

Thanks again for taking a look! 💖

**Review by janiceilene — APPROVED** [review]
This looks great! Thanks for making these updates :shipit:

**Comment by japui** [comment]
PULL_REQUEST_TEMPLATE.md #

**Review by ejgdfgidf — COMMENTED** [review]
- # @cmwilson21 #18810 @cmwilson21 

> ###  @**_`[](url)`_**

**Pull request merged**
