### PR TITLE
Update issue_comment Webhook Description

### LINKED ISSUE #6597: `issue_comment` webhook description doesn't include pull request comments
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

### What part(s) of the article would you like to see updated?

The short description for the `issue_comment` webhook should note the fact that this event is also triggered on PR comments.

### Additional information

I'm working on this

### PR DESCRIPTION
**Pull request by velocity23**
### Why:

Closes #6597

### What's being changed:

The short description for the `issue_comment` webhook. It now informs readers that the event is also triggered for pull request comments.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Comment by velocity23** [comment]
Unable to review in staging, the webhook events & payloads page is too big to render on Heroku.

**Comment by fhjlnnn** [comment]
чт, 20 май 2021, 1:13 Kai Malcolm ***@***.***>:

**Comment by janiceilene** [comment]
@velocity23 Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by khalakhras — APPROVED** [review]

**Review by ccsdscs — APPROVED** [review]

**Review by lecoursen — APPROVED** [review]
Thanks @velocity23! Merging now. ⚡

**Pull request merged**
