### PR TITLE
fix: deleting and restoring package - GHES versioning update 

### LINKED ISSUE #15736: [Improvement]: Document new way to restore a package version in an organization
**This issue is reserved for MLH fellow program**

### What article(s) is affected?

https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package

### Describe the desired docs changes 

- "[Deleting and restoring a package](https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#package-deletion-and-restoration-support-on-github)" article
  - Update article's YAML front matter versioning to exclude GitHub Enterprise Server 3.0 and 3.1 (article should only be versioned for `fpt`, `ghec`, `ghes > 3.1`, and `ghae`)

### PR DESCRIPTION
**Pull request by riteshsp2000**
### Why:

Closes #15736 

### What's being changed:

- update article's yaml frontmatter to exclude GitHub Enterprise Server 3.0 and 3.1 versions (support for >=3.2)

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by ethanpalm — DISMISSED** [review]
👋🏼  Hi @riteshsp2000, thanks for making this change. Your update to the front matter of "Deleting and restoring a package" is perfect. Since this article now only displays for `GHES >= 3.2`, we need to also update any links to it from older GHES versions. So I made some changes to "About permissions for GitHub packages" and other articles because the GHES 3.1 version of those articles were linking to "Deleting and restoring a package," which now results in a 404 error.

Let me know if you have any questions about this! I'll get the branch up to date and merged once the checks are passing.

**Comment by ethanpalm** [comment]
@ramyaparimi, this should be ready to merge, but it continues to fail the rendering test. I think it's a false positive, but I cannot get it to pass

**Review by ethanpalm — APPROVED** [review]

**Comment by ramyaparimi** [comment]
@ethanpalm Yep! There is another fix along way for this test to pass. I will be able to merge this once its fixed. Thank you for adding the `ready to merge` label. It's very helpful for me to merge things when tests are all passing ✨

**Comment by riteshsp2000** [comment]
Hey @ethanpalm Thank you for helping me with this. I was a bit stuck finding and fixing all the links.

**Pull request merged**
