### PR TITLE
Update apply-for-a-student-developer-pack.md

### PR DESCRIPTION
**Pull request by saurabha994**
Add instructions on how to reverify your academic affiliation.

### Why:

Closes [https://github.com/github/education-web/issues/4036]

### What's being changed:

Added additional information so that user can easily reverify their academic affiliation.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [x] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

Before 

Screenshot 2022-02-22 at 7 02 46 PM

After

Screenshot 2022-02-22 at 7 27 23 PM

Masked username image used

image (1)

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@saurabha994 
Thanks so much for opening a PR! I'll get this triaged for review :zap:
And, thank you for providing such clear screenshots on what changes have been made 💖

**Comment by hubwriter** [comment]
New image for using for masking:
reverify-academic-affiliation

**Comment by saurabha994** [comment]
> New image for using for masking: reverify-academic-affiliation

Thanks for your comment, I have updated the image with masked username

**Comment by hubwriter** [comment]
@saurabha994 - Hi 👋 

I added the new image here just so that I could apply a mask to it. The image needs to be saved to the correct place in the repo. This is going to be easier for me to do in our internal repo, so I'm going to close this pull request and open a new one internally. I will ping you a link and ask you to review/approve it there.

Thanks for raising this. 👍

**Pull request closed without merging**
