### PR TITLE
Update about-protected-branches.md

### PR DESCRIPTION
**Pull request by SNiTEBoBy**
### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by hafixo** [comment]
Merge pull requested

**Comment by DozerKatDC10** [comment]
Merge commit okay 👌

**Review by DozerKatDC10 — COMMENTED** [review]
I've viewed your changes

**Review by DozerKatDC10 — COMMENTED** [review]
Reviewed 😊

**Review by DozerKatDC10 — COMMENTED** [review]
Approved thanks 😊

**Comment by adamhayrettin11** [comment]
Teşekkürederim aşkım

9 Oca 2021 Cmt 12:28 tarihinde DozerKatDC10 <notifications@github.com> şunu
yazdı:

**Comment by adamhayrettin11** [comment]
Teşekkürler canım

9 Oca 2021 Cmt 12:28 tarihinde DozerKatDC10 <notifications@github.com> şunu
yazdı:

**Review by DozerKatDC10 — COMMENTED** [review]
Uninstall ed firefox deleted other emails

**Comment by adamhayrettin11** [comment]
✋🏻

9 Oca 2021 Cmt 12:49 tarihinde DozerKatDC10 <notifications@github.com> şunu
yazdı:

**Pull request closed without merging**
