### PR TITLE
Update code examples in building-a-login-with-github-button-with-a-github-app.md

### PR DESCRIPTION
**Pull request by arthurgubaidullin**
Remove unnecessary body from http get request

### Why:

Sending body in a get request is redundant.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I corrected the code examples in sections:

- [Add code to generate a user access token](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app#add-code-to-generate-a-user-access-token)
- [Full code example](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app#full-code-example)

What's fixed:
```diff copy
def user_info(token)
  uri = URI("https://api.github.com/user")

  result = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
-    body = {"access_token" => token}.to_json

    auth = "Bearer #{token}"
    headers = {"Accept" => "application/json", "Content-Type" => "application/json", "Authorization" => auth}

-   http.send_request("GET", uri.path, body, headers)
+   http.send_request("GET", uri.path, nil, headers)
  end

  parse_response(result)
end
```

Documentation:

- [`send_request`](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#method-i-send_request)

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by h4cksco** [comment]
> [!NOTE]
>

**Comment by h4cksco** [comment]
``

**Comment by h4cksco** [comment]
[Uploading squarespace_backup_codes_www.aswinmm18@gmail.com (2).txt…]()

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@arthurgubaidullin Thank you so much for your patience while our SME team reviewed! They agreed with your changes ✨ I'll update the branch and get this merged once tests are passing 🍏

If you're looking for another issue to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on 💛

**Pull request merged**
