### PR TITLE
Add guide on using the .NET Octokit SDK #23845

### LINKED ISSUE #23845: Add a guide on how to use the .NET Octokit SDK
The GitHub docs now include a guide about how to use GitHub's JavaScript Octokit SDK to use the REST API: https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript

We would like to add a similar guide for the [.NET Octokit SDK](https://github.com/octokit/octokit.rb).

The guide should:

- Follow the same format as https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript. You can copy this guide to use as a template, but please be sure to update all JavaScript-specific content.
- Follow best practices for .NET, including adhering to a standard .NET linter
- Not recommend OAuth Apps, but instead recommend [GitHub Apps](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/about-creating-github-apps)

### PR DESCRIPTION
**Pull request by SimardeepSingh-zsh**
### Why:

Closes: #23845

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by steveward** [comment]
Thanks for the PR @SimardeepSingh-zsh! I'll get this triaged for review! ⚡

**Review by skedwards88 — CHANGES_REQUESTED** [review]
Thanks for opening this PR! For this issue (https://github.com/github/docs/issues/23845), we would like the .NET guide to follow the same structure as the [JavaScript guide](https://docs.github.com/rest/guides/scripting-with-the-rest-api-and-javascript), especially the detailed explanations and code examples for each section. It's also important that this guide follows our [style guide](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide).

It might be helpful to copy the Javascript guide as a starting point, and then replace the JavaScript-specific things with the .NET-specific things.

**Review by SimardeepSingh-zsh — COMMENTED** [review]
This PR is a great start towards creating a .NET guide for the Octokit SDK. The structure and content closely follow the JavaScript guide and provide a clear introduction to using the .NET Octokit SDK. However, there are some additional points to consider:

.NET-specific Content: While the structure is aligned with the JavaScript guide, it would be beneficial to add more .NET-specific details, code examples, and best practices to make it more relevant for .NET developers.

Missing Code Samples: In the "Making API Requests" section, there's mention of creating a GitHub client instance, but the code example is incomplete. Please include a complete code sample for creating the GitHub client instance.

Formatting and Styling: Ensure that the guide adheres to our style guide, including consistent code formatting and styling.

Consistency: In the "Making API Requests" section, the subheading "OAuth Apps vs. GitHub Apps" is repeated. Please remove the duplication.

Testing: Consider adding a section on testing, as testing is an important aspect of any development guide.

Linking: Add hyperlinks to external resources, such as links to GitHub documentation or specific library documentation.

**Comment by mehjwj3hsekrv** [comment]
كيف انشى بوت

**Pull request closed without merging**
