### PR TITLE
Commit link raw text contained unnecessary information

### PR DESCRIPTION
**Pull request by ArnoutDevos**
### Why:
Raw reference for "Username/Repository@SHA" contained non-raw things.

### What's being changed:
raw text to create commit link

New description is sufficient to create correct short link and is more in line with the other rows.

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by janiceilene — APPROVED** [review]
Thanks so much for the contribution @ArnoutDevos! I'll get this branch updated and merge it when everything's green 🍏

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Comment by ArnoutDevos** [comment]
@all-contributors please add @ArnoutDevos for Documentation

**Comment by janiceilene** [comment]
@all-contributors please add @ArnoutDevos for Documentation

**Comment by janiceilene** [comment]
Sorry about that @ArnoutDevos 💛 We had a syntax error that was upsetting the all contributors bot!

**Pull request merged**
