### PR TITLE
Center align Guide Cards for all devices

### LINKED ISSUE #30757: [UI Issue] : Guides are not center aligned on Mobile View
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- I am using Google Chrome. 
- It is on the [Get Started Page](https://docs.github.com/en/get-started)
image

- The Guide Section is not center aligned in Mobile View.

### What changes are you suggesting?

The section should be center aligned.
It just works as a better UI element.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adsingh14**
### Why: Guide cards are not center aligned

Closes: #30757

### What's being changed (if available, include any code snippets, screenshots, or gifs): 
|image
|:--:|
|*Before/After center align cards*|

Primarly, guide cards are not looking good on tablets and mobile screens because of offset alignment. 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by adsingh14** [comment]
@nguyenalex836 Please check this PR. I hope the refrenced issue will clarify the whole context in brief.

**Comment by adsingh14** [comment]
@nguyenalex836 Please check out this PR. I hope the referenced issue will clarify the whole context in brief.

**Comment by nguyenalex836** [comment]
@adsingh14 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by tinabme — APPROVED** [review]
Looks good, thank you for the fix.

**Comment by mchammer01** [comment]
The error message is as follows:

```
 content/get-started/onboarding/getting-started-with-your-github-account.md has versions that are not available in parent category
```

**Comment by mchammer01** [comment]
Latest error message:
```
  Custom message:
      In the front matter of get-started/index.md there is 1 .featuredLinks front matter entry that is not correct.
    index: 5 URI: /get-started/onboarding/getting-started-with-github-ae	Page not found
```

I think it's definitely related to GitHub AE.

**Comment by nguyenalex836** [comment]
@mchammer01 Thank you for the review and response here! ❤️ Will follow up with you in [Slack](https://github.slack.com/archives/C0128FB8J3H/p1705422757696159?thread_ts=1704815722.933999&cid=C0128FB8J3H)!

**Pull request merged**
