### PR TITLE
Reorg LICENSE files to be more discoverable

### PR DESCRIPTION
**Pull request by jeffmcaffer**
### Why: 
See #203

### What's being changed:

Here we move the LICENSE files up to the root and identify the CC-BY-4.0 content license as the "primary" license (e.g., it is in the LICENSE file) since doc is the major role of the repo.  Also updated the README and a couple tools that seem to treat license files specially.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by zeke — APPROVED** [review]
Nice 👍🏼

**Comment by jeffmcaffer** [comment]
@all-contributors please add @jeffmcaffer for docs

**Review by 966566081639 — COMMENTED** [review]
124 7

**Comment by isphosting** [comment]
gh pr checkout 204

**Comment by isphosting** [comment]
> ### Why:
> See #203
> 
> ### What's being changed:
> Here we move the LICENSE files up to the root and identify the CC-BY-4.0 content license as the "primary" license (e.g., it is in the LICENSE file) since doc is the major role of the repo. Also updated the README and a couple tools that seem to treat license files specially.
> 
> ### Check off the following:
> * [ ]  All of the tests are passing.
> * [ ]  I have reviewed my changes in staging.
> * [ ]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [ ]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Review by Samiec0 — COMMENTED** [review]
f3a5bdc0905d8caaee7b5a544ba8d210367c358a

**Review by isphosting — COMMENTED** [review]
re-usable

**Review by Antonio9212 — COMMENTED** [review]
LICENSE-CODE

**Pull request merged**
