### PR TITLE
Fix format of the links

### PR DESCRIPTION
**Pull request by de-oz**
### Why:

Closes [issue link]

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Removed quotes and periods from the links in accordance with the [styleguide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#links).

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
@de-oz Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
@de-oz 👋🏻 - this LGTM, thanks for making these improvements ✨ 
@github/site-policy-admins - could you review this small PR? It has a minor update to a site-policy article 🙇🏻

**Review by literarytea — APPROVED** [review]
❇️

**Review by Ray0light — COMMENTED** [review]
Yes

**Pull request merged**
