### PR TITLE
Added transitions to some Elements for a better UX Flow

### PR DESCRIPTION
**Pull request by verbose117**
### Why:

**Closes [issue link]**

### What's being changed:
The things that are changed are :
1. Added hover background to Getting started cards.
2. Transition to The arrow button in the Navbar 

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by haneenmahd** [comment]
Getting started cards hover background not working!

**Review by bruna17 — APPROVED** [review]

**Review by krishmodels12 — APPROVED** [review]

**Comment by Abhishek577270** [comment]
> ### Why:
> **Closes [issue link]**
> 
> ### What's being changed:
> The things that are changed are :
> 
> 1. Added hover background to Getting started cards.
> 2. Transition to The arrow button in the Navbar
> 
> ### Check off the following:
> * [x]  I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
> * [x]  For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
> * [x]  For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

0

**Comment by Abhishek577270** [comment]
@Abhishek577270

**Comment by janiceilene** [comment]
@haneenmahd Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by chiedo** [comment]
@myarb let us know if this is design direction you want us to move forward with! 🙇🏿

**Comment by chiedo** [comment]
Thank you @haneenmahd but we've choose not to head this direction. We love new ideas though so if you have any more open up an issue and we'll check them out!

**Comment by Abhishek577270** [comment]
What I do

**Pull request closed without merging**
