### PR TITLE
Clarify OIDC process for AWS

### LINKED ISSUE #19656: OIDC on AWS documentation improvement
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

### What part(s) of the article would you like to see updated?

IAM policy currently only shows a snippet and should have a full almost-working example

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by baolsen**
### Why:

I've recently used the OIDC on AWS documentation and found it difficult to use. After some rummaging around the internet I managed to get a fully working example and expanded on the documentation in this PR accordingly.

Closes #19656
Relates to [#15324]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by baolsen** [comment]
Preview of changes:
https://docs-19657-beb2cd.preview.ghdocs.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

**Comment by cmwilson21** [comment]
@baolsen Thanks for opening an issue and PR! I made a slight edit to your original message to connect the issue to this PR. ⚡ 

I'll get this triaged for the team to take a look 👀

**Comment by baolsen** [comment]
bump

**Comment by cmwilson21** [comment]
@baolsen Thanks for checking in on this. It's on the board and a team member will be reviewing it soon. 

We appreciate your patience as we work through our backlog 💛

**Comment by baolsen** [comment]
Branch was getting a bit stale, rebased.

**Review by javeedashraf — DISMISSED** [review]
Changes looks good 👍 And adds more info to the Doc 📖

**Review by martin389 — COMMENTED** [review]
Added some edits for docs style

**Review by martin389 — APPROVED** [review]

**Comment by martin389** [comment]
Changes were approved by engineering here: https://github.com/github/docs/pull/19657#pullrequestreview-1100423863

**Comment by martin389** [comment]
Changes look good in staging: https://docs-19657-beb2cd.preview.ghdocs.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy

**Pull request merged**
