### PR TITLE
fix: various typos

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

Took another pass with cSpell for the non-restricted folders

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Eminealtug** [comment]
Telegram hesapları mı kullanmak istiyorum

**Comment by Eminealtug** [comment]
Yardım

**Comment by cmwilson21** [comment]
@nschonni Thanks for opening a PR! We appreciate you taking the time to submit this ✨ 

However, some of these changes we won't be [able to accept](https://github.com/github/docs/pull/22770#issuecomment-1356868410), some are in code comments, and some, I think, are in auto-generated content. Due to the size of this PR, the untangling between what we can and cannot accept, and because most of our staff are on holiday break and won't be returning full force until late January, I'm going to go ahead and close this PR 💛 

For future PRs of this nature, we encourage folks to [open an issue](https://github.com/github/docs/issues/new/choose) first so we can verify the need for the proposed change and catch the things we can't accept or modify. 👍

**Comment by nschonni** [comment]
@cmwilson21 it's been awhile since I contributed here (still No. 33 in contributors https://github.com/github/docs/graphs/contributors).
I excluded the the generated files mentioned in https://github.com/github/docs/pull/22770#issuecomment-1356868410 except for `script` because I used `scripts` from the message above for the ignore list, which is also a typo in a file you no longer accept fixes for

**Pull request closed without merging**
