### PR TITLE
Fix typo metadata-syntax-for-github-actions.md

### LINKED ISSUE #1455: Typo about using outputs
### What article on docs.github.com is affected?
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions

### What part(s) of the article would you like to see updated?
In the [#outputs-for-composite-run-steps-actions](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-run-steps-actions) section it speaks of `outputs.<output_id.value>`.
When I expected this to be `outputs.<output_id>.value` (the **>** placement) according to the surrounding documentation.
Just like it is for `outputs.<output_id>.description`

**Expected**
`outputs.<output_id>.value`

**Actual**
`outputs.<output_id.value>`

### Additional information
N/A

### PR DESCRIPTION
**Pull request by cassshh**
Fix typo for metadata-syntax-for-github-actions#outputs-for-composite-run-steps-actions

### Why:
I expect this to be a mistake in the documentation.
Resolves #1455 

### What's being changed:
`outputs.<output_id.value>` -> `outputs.<output_id>.value`

**Screenshot of current content:**
(Red line is being changed)
Screenshot 2020-11-19 at 12 32 08

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@cassshh Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by cassshh** [comment]
A friendly bump to keep the PR from being closed 🙂

**Comment by janiceilene** [comment]
Thanks for your patience! Our small team is working our way through reviewing all of the amazing contributions ✨

**Review by shati-patel — APPROVED** [review]
Thank you for spotting that typo and fixing it, @cassshh 🎉 We really appreciate all the community contributions to help us improve our docs!

I'll get this merged shortly 😄

**Comment by cassshh** [comment]
Superb. Thank you both!

**Pull request merged**
