### PR TITLE
docs(pull_request_webhook_properties): update ‘action’ description

### LINKED ISSUE #2257: Add in definition of terms like "synchronize" for Github Action Activity types
### What article on docs.github.com is affected?

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

### What part(s) of the article would you like to see updated?

This page references activity types like: "synchronize" but does not provide a definition of what this means. To my understanding, it means that a commit has been made to a pull request branch but it's not clear based on the docs if this is correct. 

### Additional information

It may be worth considering adding a definition for all of the "Activity Types" given it may not be fair to assume every user will know of the full GitHub functionality when reading the docs.

### PR DESCRIPTION
**Pull request by jai**
Signed-off-by: Jai Govindani <jai@honestbank.com>

### Why:

**Closes #2257**

### What's being changed:

Turned the description of the `pull_request` payload object `action` into a list to prepare for adding a description to various terms like `synchronize` (as mentioned in #2257)

CleanShot 2021-05-02 at 12 07 02@2x

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (eg. a "before and after video")

### CODE REVIEW

**Comment by jai** [comment]
Not sure if the list delimiters (between the item and the description) should be hyphens or colons, seeing both on 

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request_review
CleanShot 2021-05-02 at 12 23 12

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
CleanShot 2021-05-02 at 12 23 25

**Comment by jai** [comment]
Link to specific section in preview deployment: https://docs-5945--jaifix-2257.herokuapp.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

**Comment by janiceilene** [comment]
@jai Thank you so much for opening a PR to make this fix and giving such detailed information about your changes! I'll get this triaged for review ⚡

**Review by skedwards88 — APPROVED** [review]
🎉 Thank you for opening this PR! I like your idea to turn the info into a bulleted list to make it more readable. 

Our repo is currently frozen for a release tomorrow, but I will queue this to merge as soon as the freeze lifts.

**Comment by skedwards88** [comment]
> Not sure if the list delimiters (between the item and the description) should be hyphens or colons, seeing both

Good catch! Given this discrepancy, either choice is good. As a long term fix, we should choose one and update the style guide/existing articles. (You are quite welcome to open an issue for this, but definitely not expected to!)

**Comment by jai** [comment]
I'll open an issue and propose an addition to the Style Guide, coming soon!

**Comment by jai** [comment]
@skedwards88 I proposed something here https://github.com/github/docs/pull/6010. Hope the wording wasn't too meta/obscure, happy to make it more human-friendly. Writing docs on how to write docs is a bit meta after all 😂

**Comment by jai** [comment]
> I'll open an issue and propose an addition to the Style Guide, coming soon!

opened #6009

**Comment by mehdi40277** [comment]
> 🎉با تشکر از شما برای باز کردن این روابط عمومی! من دوست دارم ایده شما این باشد که اطلاعات را به یک لیست گلوله ای تبدیل کند تا خوانایی آن بیشتر شود.
> 
> repo ما در حال حاضر برای انتشار فردا منجمد شده است ، اما من در صف قرار می گیرم تا به محض بلند شدن انجماد ادغام شود.

i am Satoshi Nakomoto, the original creator of Bitcoin. In 2010, I presented my text formula with c ++ program, which is exactly the output of Excel. Many people in the world want to know what Satoshi was or who he was. The world is a method based on clear codes and clearly displayed by the World Bank is a trace of capital participation in choosing a healthy income. Satoshi Nakamato

**Comment by mehdi40277** [comment]
i am Satoshi Nakomoto, the original creator of Bitcoin. In 2010, I presented my text formula with c ++ program, which is exactly the output of Excel. Many people in the world want to know what Satoshi was or who he was. The world is a method based on clear codes and clearly displayed by the World Bank is a trace of capital participation in choosing a healthy income. Satoshi Nakamato

**Pull request merged**
