### PR TITLE
Removed 'from'

### PR DESCRIPTION
**Pull request by HarrySpce**
This will make the sentence grammatically correct

### Why:

The sentence was not grammatically correct.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

I removed the word 'from' to make the sentence correct.

fromtoyour

### Check off the following:

- [✓] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [✓] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by HarrySpce** [comment]
Hey @cmwilson21, I accidently forked the docs repo and so when I deleted it off my profile I think that closed the PR. If you could reopen it that would be good, Thanks 😁

**Comment by cmwilson21** [comment]
Gotcha! Reopened now. I'll get this triaged for review! ⚡

**Review by SiaraMist — APPROVED** [review]
Hey @HarrySpce, thanks so much for opening a PR! Your grammar updates look good to me, so I'll go ahead and get this merged. 🚀

**Comment by HarrySpce** [comment]
Sounds good @SiaraMist, Thank you.

**Comment by SiaraMist** [comment]
Hey @HarrySpce, apologies for the delay in communication on this. It looks like I can't merge this PR because the fork was deleted. I'm going to close this PR, but if you'd like to open another one and keep your fork open, we'd love to accept your changes! ✨  You can find contributing instructions [here](https://github.com/github/docs/blob/main/CONTRIBUTING.md#make-changes-locally), if that's helpful. 💛

**Pull request closed without merging**
