### PR TITLE
Typo: make container name consistent

### PR DESCRIPTION
**Pull request by blue-jam**
### Why:

Fixing typo. Example container image names IMAGE_NAME and IMAGE-NAME are mixed on the page. This PR replaces the hyphen version with the underscore version to make them consistent.

### What's being changed:

Replaced `IMAGE-NAME` (all capital ones) with `IMAGE_NAME` on [this page](https://docs-17600-8e1054.preview.ghdocs.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by blue-jam** [comment]
There is one failing check "filterContentDir". As far as I read a log from the action, it seems the action tried to get diff between main and patch-2 in github/docs (https://api.github.com/repos/github/docs/compare/main...patch-2 ) rather than one between main and patch-2 in my forked repository (https://api.github.com/repos/github/docs/compare/main...blue-jam:patch-2 ).

**Review by skedwards88 — DISMISSED** [review]
Thanks for this fix! We'll get this merged down for you.

**Review by skedwards88 — APPROVED** [review]
re-approving after resolving merge conflict

**Review by SoeAung95 — COMMENTED** [review]
gh run list
gh run view <run-id> --log

**Pull request merged**
