### PR TITLE
Minor typo fix - extra period

### PR DESCRIPTION
**Pull request by jim-nvidia**
Removed extra period in second paragraph of the "Require status checks before merging" section.

### Why: Typo

Closes: 

### Check off the following:

- [x ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by Ozzi78** [comment]
tir. 25. jul. 2023, 18:18 skrev welcome[bot] ***@***.***>:

**Comment by por1981** [comment]
> Removed extra period in second paragraph of the "Require status checks before merging" section.
> 
> ### Why: Typo
> Closes:
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs): Removing extra period
> ### Check off the following:
> * [x ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.
>   
>   * For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

**Comment by cmwilson21** [comment]
@hibler13 Great catch! Thanks for submitting a PR to fix this ✨ 

I'll get this merged once all the checks have passed ✅

**Review by cmwilson21 — APPROVED** [review]
LGTM 🚢

**Pull request merged**
