### PR TITLE
Fix link in about-the-dependency-graph.md

### PR DESCRIPTION
**Pull request by mtnalonso**
### Why:

The link to "Reviewing dependency changes in a pull request" (`/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-dependency-changes-in-a-pull-request`) is pointing to a wrong location (`/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request`).

### What's being changed:

Source | Staging | Production | What Changed
-- | -- | -- | --
[content/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph.md ](https://github.com/github/docs/blob/4bdae020b27c63ee24440c74db0997f27b59f2e3/content/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph.md)| [Modified](https://docs-12057--patch-2.herokuapp.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) | [Original](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) |  Updated link reference

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@mtnalonso 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by mchammer01 — APPROVED** [review]
@mtnalonso - thank you for fixing the incorrect link ✨

**Comment by Ambassadormathismathews** [comment]
> ### Why:
> The link to "Reviewing dependency changes in a pull request" (`/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-dependency-changes-in-a-pull-request`) is pointing to a wrong location (`/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request`).
> 
> ### What's being changed:
> Source	Staging	Production	What Changed
> [content/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph.md ](https://github.com/github/docs/blob/4bdae020b27c63ee24440c74db0997f27b59f2e3/content/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph.md)	[Modified](https://docs-12057--patch-2.herokuapp.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph)	[Original](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph)	Updated link reference
> ### Check off the following:
> * [x]  I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> * [x]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")
Apollo DN330 at Chelmsford, ca. 1985
The DN300 and later DN330 were integrated desktop systems not much bigger than the included monitor.

In the late 1980s, Apollo introduced a new pair of machines. The DN3000 and DN4000 used 68k processors, but were housed in IBM PC style cases of the time and had IBM-AT compatible ISA expansion slots and PC-compatible disk drives. These became the mainstay of the Apollo range in the mid to late 1980s. In principle, a user or third party could install a standard AT expansion card, but since this required the writing of a special device driver, in practice this was very rare. However, the size and design of the boxes made installing or replacing components very easy. A typical system could have between 2 MiB and 32 MiB of memory, a 76 MB, 150 MB or 330 MB (very occasionally 660 MB) hard disk, and 32-bit 68020 or 68030 processor running at 12 MHz to 33 MHz, depending on model. A half-height expansion bay could take either a 5¼-inch floppy disk drive or a QIC-type cartridge tape drive, capacity 30 MB, 45 MB, or 60 MB depending on cartridge. For printer access, the system came with a serial port as standard; a serial/parallel expansion card could provide a parallel printer port if this was required.

The DN3000 and DN4000 were later upgraded to DN3500 and DN4500 with a faster 68030 CPU. The DN3500 was approximately as powerful as the DN4000. A DN5500 with a 68040 was also produced in limited quantities.

A DN2500 workstation was released which was advertised as "4 Mips, 4 MB of memory, for under $4,000". This was a single integrated motherboard that used PC standard DRAM DIMM modules. This was a significant departure from previous designs and those of the competition which had custom memory modules. The motherboard included a high resolution (1280x1024) black and white bitmapped display and SCSI disk interface. The systems included a single AT expansion slot for a network card to allow the system to attach to any of the three supported networks (Apollo Token Ring, IBM Token Ring, or Ethernet)

After the purchase of Apollo Computer by HP, a merged line of workstations that could run either Domain/OS or HP-UX was produced with the name HP/Apollo 425t and HP/Apollo 433s. The 425t was a "pizza box" design with a single network expansion slot. The 433s was a desk-side server systems with multiple expansion slots.

Compatibility	Edit
PC compatibility was possible either through software emulation, using the optional product DPCE, or through a plug-in card carrying an Intel 80286 processor. A third-party plug-in card with a 386 was also available.

An Apollo Token Ring network card could also be placed in a standard PC and network drivers allowed it to connect to a server running a PC SMB (Server Message Block) file server.

Usage	Edit

**Comment by Ambassadormathismathews** [comment]
Bootstrap

**Review by Ambassadormathismathews — COMMENTED** [review]
Reviewing dependency changes in a pull request](/pull

**Pull request merged**
