### PR TITLE
docs: make single vs double star glob patterns documentation clearer

### PR DESCRIPTION
**Pull request by dsotirakis**
### Why:

When visited this documentation, it felt a little bit unclear to me what each pattern was supposed to do, based on the documentation. I hope this change helps others as well :) 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The description about single and double star glob patterns.

### Check off the following:

- [ ] A subject matter expert (SME) has reviewed the technical accuracy of the content in this PR. In most cases, the author can be the SME. Open source contributions may require a SME review from GitHub staff.
- [x] The changes in this PR meet [the docs fundamentals that are required for all content](http://docs.github.com/en/contributing/writing-for-github-docs/about-githubs-documentation-fundamentals).
- [ ] All CI checks are passing.

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@dsotirakis Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by subatoi — APPROVED** [review]
Thanks @dsotirakis—I agree this is a reasonable change, and I'll get this merged for you now. Thanks for your interest in the Docs!

**Comment by dsotirakis** [comment]
this was fast, thank you so much @nguyenalex836, @subatoi! 🙇

**Comment by nguyenalex836** [comment]
Thank _you_, @dsotirakis! 💛 

If you're ever looking for other issues to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on 🙇

**Pull request merged**
