### PR TITLE
Fixed wrong keyboard shortcuts for Visual Studio in getting-started-with-github-copilot.md

### PR DESCRIPTION
**Pull request by DomenicoAltieri**
### Why:
 The proof is in the Options -> Environment -> Keyboard -> Edit.NextSuggestion or Edit.PreviousSuggestion keyboard shortcuts in Visual Studio if you have installed Visual Studio with Copilot.

Visual Studio Settings

I think the mistake is due to the fact that Visual Studio Code tools use Alt+] and Alt+[, but not Visual Studio.

### What's being changed (if available, include any code snippets, screenshots, or gifs):
The Keyboard shortcuts showed in the Github Copilot getting started page for Visual Studio for Next Suggestion and Previous Suggestion. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@DomenicoAltieri Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ayim** [comment]
image
I'm seeing these two shortcuts in VS

**Comment by jules-p** [comment]
Thank you for checking @ayim ❤️ I have now been able to verify this issue specifically for cycling through suggestions on my machine.

Thank you @DomenicoAltieri for highlighting this and raising the PR. I will get this reviewed and merged for you. :sparkles:

**Review by jules-p — APPROVED** [review]
This looks great, thank you @DomenicoAltieri for contributing to our docs - we really appreciate it 🚀

**Pull request merged**
