### PR TITLE
Add another common permission denied case

### PR DESCRIPTION
**Pull request by xyz1hang**
### Why:

I think it is not uncommon to hit this error if someone follows any kind of git "get started" documentation and copy-pasting values from Github site e.g. from "Clone" button. The error message itself doesn't reflect the actual cause hence not easy to spot.

Just wanted to contribute to this page and help others.

### What's being changed:

Added one section to "Permission denied troubleshooting doc"

### Check off the following:
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@Phoenix1708 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by Phoenix1708** [comment]
> @Phoenix1708 Thanks so much for opening a PR! I'll get this triaged for review ✨

Thanks

**Comment by lee-dohm** [comment]
Hello @Phoenix1708! Thanks for reaching out 🙇‍♂️ 

I reviewed this with the team and we're not looking to add this scenario to this documentation at this time. It overlaps with the "Always use the 'git' user" section and we provide the easy copy buttons in the GitHub UI specifically to minimize this kind of copy-paste error.

Thanks very much for your passion and interest in improving the GitHub Docs!

**Comment by lee-dohm** [comment]
In spite of the fact that we aren't interested in adding this change, we are curious how you ran into this problem specifically as something to keep in mind for other areas of the documentation. Were you copy-pasting out of a document? or chat channel? If you can give us a better idea of how you ran into this, it could help us understand so we can improve our documentation in other areas.

Thanks again @Phoenix1708!

**Comment by Phoenix1708** [comment]
Thanks. [Likely to the terminal](https://superuser.com/a/1298168). Just happen to found out that there's a whole page about "Permission Denied" hence was hoping to help others.

**Comment by lee-dohm** [comment]
> hoping to help others.

We appreciate it! Keep the suggestions coming 🙇‍♂️

**Pull request closed without merging**
