### PR TITLE
Adds github.action_status to available contexts

### PR DESCRIPTION
**Pull request by mike-carey**
### Why:

The `github.action_status` context is not listed within the Contexts page.

### What's being changed:

Adds the `github.action_status` context to the list of available contexts under `github`.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by mike-carey** [comment]
I am not sure how to check the changes in staging.  I see a deployment went out but might be restricted as it times out when I attempt to view.

**Comment by mike-carey** [comment]
Sorry, I just did not give enough time for it to spin up.  All looks good in the preview on my end.

**Comment by ramyaparimi** [comment]
@mike-carey 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ethomson** [comment]
Thanks for fixing this @mike-carey!  👍

**Review by skedwards88 — DISMISSED** [review]

**Review by skedwards88 — APPROVED** [review]

**Pull request merged**
