### PR TITLE
Update about-github-code-search.md

### PR DESCRIPTION
**Pull request by ababiec**
Clarify that code search does not include binary files.

### Why:

Closes:  https://github.com/orgs/community/discussions/116489

### What's being changed (if available, include any code snippets, screenshots, or gifs):

One addition to the list of entries for the current limitations on indexed code.

### Check off the following:

- [X] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [X] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@ababiec Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by look — APPROVED** [review]
This is covered by the UTF-8-only limitation, but I agree it's worth calling out separately for clarity. It might make sense to move higher in the list for readability. For example, above the UTF-8 limitation.

**Comment by nguyenalex836** [comment]
> It might make sense to move higher in the list for readability. For example, above the UTF-8 limitation.

@look Thank you for that suggestion! @ababiec Would you be able to apply the suggested update? Once that is finished, I'll get this merged 💛

**Comment by ababiec** [comment]
I will make the requested modification

**Comment by ababiec** [comment]
> > It might make sense to move higher in the list for readability. For example, above the UTF-8 limitation.
> 
> @look Thank you for that suggestion! @ababiec Would you be able to apply the suggested update? Once that is finished, I'll get this merged 💛

Change applied.

**Review by nguyenalex836 — DISMISSED** [review]

**Review by nguyenalex836 — APPROVED** [review]

**Pull request merged**
