### PR TITLE
Replace CodeQL product name with CLI command name

### LINKED ISSUE #24777: Replace CodeQL product name with CodeQL CLI command name in examples
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/creating-codeql-databases

### What part(s) of the article would you like to see updated?

Several example CodeQL CLI commands in the [Creating CodeQL databases](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/creating-codeql-databases) page use the CodeQL product name in place of the CLI command name (i.e. `CodeQL` instead of `codeql`). Such commands may only work on case-insensitive filesystems. For consistency, the actual CodeQL CLI command casing should be used (`codeql`), which is also used in many other pages.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marcransome**
### Why:

Several example CodeQL CLI commands in the [Creating CodeQL databases](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/creating-codeql-databases) page use the CodeQL product name in place of the CLI command name (i.e. `CodeQL` instead of `codeql`). Such commands may only work on case-insensitive filesystems.

Closes: #24777

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Example CodeQL CLI commands have been updated to use the correct casing (`codeql`). An additional line break has also been introduced in one example code block, to separate a comment (prefixed with `#`) from the example command.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by marcransome** [comment]
Currently unable to review changes in staging due to [filterContentDir](https://github.com/github/docs/actions/runs/4568520320/jobs/8063683710?pr=24778) job stalling and timing out.

**Comment by cmwilson21** [comment]
@marcransome Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Review by shamankayka — COMMENTED** [review]
> #24706

**Review by mhtv24 — COMMENTED** [review]
ok my mhtv24.com
mehedi hasan sujon

**Review by mhtv24 — COMMENTED** [review]
mhtv24/mhtv24.com

**Review by mchammer01 — APPROVED** [review]
@marcransome 👋🏻 - thanks for fixing these ✨

**Pull request merged**
