### PR TITLE
chore: Add EditorConfig for IDE whitespace

### PR DESCRIPTION
**Pull request by nschonni**
### Why:

Allows IDEs and GitHub web editor to detect the whitespace settings when editing files https://editorconfig.org/

### What's being changed:

Add a basic .editorconfig file, but don't run any normalizaton

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks @nschonni! I'll get this triaged for review ✨

**Comment by chiedo** [comment]
@nschonni just confirming, this `.editorconfig` file as you've proposed it, would make the following editors automatically conform to our whitespacing preferences
Screen Shot 2020-11-05 at 11 02 54 AM
?

**Comment by nschonni** [comment]
Yes, the whitespace settings are picked up, so when you hit the Tab key, it inserts the indicated number of spaces, and will add the EOF marker if it is missing.
For VS Code, you can added the plug-in as a recommended extension https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig, by adding a `extensions.json` in the `.vscode` folder with the following:

```json
{
	"recommendations": ["EditorConfig.EditorConfig"]
}
```

Didn't add that in this PR to keep the discussion focused, but I can add that in if you want.

It looks like `standard` that you use for the JS linting doesn't have native support for it. Standard is an oppionated wrapper around ESLint. ESLint itself recommends the whitespace rules be delegated to Prettier, which does respect EditorConfig 😆 

I had taken a quick look at what flipping to plain ESLint + Prettier would look like, but it reformatted so much I didn't want to submit it out of the blue

**Review by JasonEtco — APPROVED** [review]
This looks great to me, thanks for the addition @nschonni! If I was going to write a `.editorconfig` file, this is exactly what I'd write 📝 I'll leave it to @chiedo or @janiceilene to actually merge this once they're ready, but 👍 from an eng perspective. ✨

**Comment by mont1985** [comment]
#1032

**Comment by mont1985** [comment]
- [ ]

**Comment by mnoori1201** [comment]
854238357105a6da2bdc1f32e14a343ff0352a98

**Pull request merged**
