### PR TITLE
fix: change sender field for CodeScanningAlert event to match other payloads

### LINKED ISSUE #3906: Clarify the `sender` property of the `CodeScanningEvent` webhook
### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#code_scanning_alert

### What part(s) of the article would you like to see updated?

The description of the `sender` property.

In the docs it says that the sender property is `github` for the `created`, `fixed`, `reopened`, `appeared_in_branch` actions.
But, what are the values for the sender property?
Currently the example uses the values from the [`GET /orgs/github` REST endpoint](https://api.github.com/orgs/github) while the other webhooks use similar values to the [`GET /user/github` REST endpoint](https://api.github.com/users/github)

### Additional information

I'm a contributor to [`octokit/webhooks`](https://github.com/octokit/webhooks), and a staffer sent a PR (octokit/webhooks#366) with some updates to the `CodeScanningAlert` event that were currently in progress.
The other day, we have another staffer send us [a PR](https://github.com/octokit/webhooks/pull/371) that doesn't match the `sender` field in the example payload in the docs and that uses values pulled from the [`GET /users/github`](https://api.github.com/users/github) enpoint.

My understanding of the docs right now is that the sender property is the user that triggered the event.
And for the actions `reopened`, `fixed`, `created`, `appeared_in_branch`, the user that triggered the event is `github`

ref: octokit/webhooks#379; octokit/webhooks#371

### PR DESCRIPTION
**Pull request by wolfy1339**
### Why:

In octokit/webhooks#371, a GitHub staffer sent us a PR with some new payload examples for the CodeScanningAlert event, the sender field was set to the value of the Github user (roughly the values of the REST endpoint `GET /users/github`) and not the GitHub org (the values of the REST endpoint `GET /orgs/github`)

All the other webhooks use the values that resemble the `GET /users/{user}` enpoint.

### What's being changed:

Updates the `sender` field for the `CodeScanningAlert` event to reflect my findings, and to match the other webhook payloads

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by shati-patel** [comment]
Hi @wolfy1339, thank you for the pull request 😃 

I've checked with our code scanning team and your updated example looks good. If you'd like to reopen this pull request, we'd love to take the contribution! Otherwise, we can make the change internally. 

Thanks again for helping us improve our docs 🎉

**Comment by wolfy1339** [comment]
I reopened the pull request

**Comment by wolfy1339** [comment]
Fixes #3906

**Review by shati-patel — APPROVED** [review]
Thank you! I'll get this merged shortly.

**Pull request merged**
