### PR TITLE
Update GitHub Actions code example "with" syntax to map instead of array

### PR DESCRIPTION
**Pull request by Shegox**
### Why:

The GitHub Action examples on the codeql page (https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning) use the "with" as an array, but this needs to be a map (see the actions docs [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith)).

### What's being changed:

Update GitHub Action code snippet on the "configuring code scanning" page to use correct map syntax for the variables in the "with" attribute instead of the array syntax. 

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @Shegox Thanks for opening a PR! Please fill out the missing section of the PR template "What's being changed," then we can get this triaged for review ✨

**Comment by Shegox** [comment]
Hi @janiceilene, 

updated the section. Please let me know if I should further elaborate that. Thanks.

**Comment by janiceilene** [comment]
Thanks so much @Shegox! I'll get this triaged for review 💝

**Review by 88pronet — APPROVED** [review]

**Review by felicitymay — APPROVED** [review]
@Shegox - many thanks for spotting and fixing these typos ✨ 

Thanks also for taking the time to fill out the PR summary with details of why you thought the existing docs were wrong - it makes it so much easier to review changes 😄

**Comment by janiceilene** [comment]
If you haven't already, you can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

**Pull request merged**
