### PR TITLE
Fix incorrect operator example

### LINKED ISSUE #4488: Example of an "if" expression is not correct
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The example of how to use an expression with an `if:` conditional appears to be inconsistent.
The "Contexts and expression syntax for GitHub Actions" article begins with the following:

> When you use expressions in an `if` conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the if conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within `${{ }}` to explicitly mark it for evaluation. For more information about if conditionals, see "Workflow syntax for GitHub Actions."

The article then provides the following example usage:

```yaml
name: CI
on: push
jobs:
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
```

The `==` symbol is an operator, and therefore requires the expression syntax.
Using this example without the expression syntax will result in the GitHub Action to fail.

### Additional information

See https://github.com/shipwright-io/build/pull/661

### PR DESCRIPTION
**Pull request by lucalves**
### Why:

I included a syntactic expression in the example of the article [Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions), because the expression in the example has `==` as an operator, and according to the documentation it needs a `$ {{ }}` to explicitly mark it for evaluation.

**Closes #4488**.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
Thanks for opening a PR @lucalves and thanks to @adambkaplan for opening an issue! I'll get this triaged for the team to review ⚡

**Review by skedwards88 — APPROVED** [review]
🎉 Thank you for fixing this! I'll get it merged down for you.

**Comment by jaqx0r** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif also contains this error btw.

**Comment by cmwilson21** [comment]
@jaqx0r Thanks for catching that and reporting it. Would you mind opening a new issue with this information? Then we can triage it and get it up for review ⚡

**Pull request merged**
