### PR TITLE
Broken Markup fixed

### LINKED ISSUE #21606: Broken markup in OIDC docs
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-environment-variables

### What part(s) of the article would you like to see updated?

The shell command should be:
```
        IDTOKEN=$(curl -H "Authorization: bearer ${{steps.script.outputs.TOKEN}}" ${{steps.script.outputs.IDTOKENURL}} -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
```

But the stuff inside `{{ }}` seems to be pre-processed out, leaving just `$` signs. See screenshot below.

### Additional information

Screenshot from 2022-10-25 12-04-13

---
maintainer edit

### Content plan [here](https://github.com/github/docs/issues/21606#issuecomment-1292716025)

### PR DESCRIPTION
**Pull request by codewithdev**
### Why:

Closes #21606 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

image
Wrapped the command with reusables {% raw %}/ {% endraw %}

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@codewithdev Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by Grek1313 — COMMENTED** [review]
https://github.com/github/docs/blob/903bf34e199aebea94ab5d861e355f3882f79e38/content/sponsors/receiving-sponsorships-through-github-sponsors/managing-your-sponsorship-tiers.md

**Review by skedwards88 — APPROVED** [review]
Thanks for this fix! We'll get this merged down for you.

**Comment by skedwards88** [comment]
It looks like we prevent changes to this file for security reasons 🤔  I'm pinging in the leads for this area to see if we can override this check or need to make the change internally instead: @martin389 @dihydroJenoxide

**Pull request merged**
