### PR TITLE
Change `can` to `must` for SCIM in EMUs

### PR DESCRIPTION
**Pull request by datanerd**
SCIM user provisioning in EMUs is not an option

### Why:

In case of EMUs, SCIM provisioning is not really an option, that's the only way users get allocated to the instance, so really should replace `can` with either `must` or `should`.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Gee1990 — COMMENTED** [review]
Dankeschön

**Comment by ramyaparimi** [comment]
@andrekolodochka 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by lecoursen — APPROVED** [review]
Thanks, I'll merge this now!

**Pull request merged**
