### PR TITLE
reference ruby/setup-ruby for cache

### PR DESCRIPTION
**Pull request by lauraGgit**
### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by 2100553** [comment]
T

**Comment by 2100553** [comment]
https://youtu.be/AHlL3j86be0

**Comment by janiceilene** [comment]
@lauraGgit Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Review by jace4511 — APPROVED** [review]

**Comment by lauraGgit** [comment]
@janiceilene reviewed the pr template. should be good to take a look

**Comment by janiceilene** [comment]
@lauraGgit Can you answer the **Why:** and **What's being changed:** in the top comment to help us better understand your suggested changes?

**Comment by lauraGgit** [comment]
@janiceilene **why** currentlythe caching module doesn't quite work for the ruby, **what** so point toward an alternate implementation of caching for ruby that speeds up the builds.

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Review by lucascosti — APPROVED** [review]
Thanks a lot for this contribution, @lauraGgit!

I've moved your sentence a bit further down and modified it a little to fit in with our style.

I'll get this merged in when the tests pass. 👍

**Comment by walli55** [comment]
Alomaisi

**Comment by lauraGgit** [comment]
Thank you!

**Pull request merged**
