### PR TITLE
Remove beta label of discussions

### LINKED ISSUE #9130: Discussions is now out of Beta.
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

According to [this](https://github.blog/changelog/2021-08-17-github-discussions-is-now-out-of-beta) GitHub Discussions is now out of Beta . But the docs still have the beta label on discussions everywhere.

### What part(s) of the article would you like to see updated?

Remove the beta label from Discussions docs.

### Additional information

N/A

### PR DESCRIPTION
**Pull request by thispsj**
### Why:

Closes #9130 

### What's being changed:

Removes the beta label for discussions from a reusable.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### CODE REVIEW

**Review by ramyaparimi — APPROVED** [review]
@thispsj Thanks so much for opening a PR with this fix! I'll update the branch and get this merged once tests are passing 🍏

**Comment by ramyaparimi** [comment]
@thispsj Can you enable the checkbox to allow maintainer edits? Then I'll be able to hit the update button and get this merged in. Thank you! https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by thispsj** [comment]
@ramyaparimi done 👍

**Review by Rob122783 — APPROVED** [review]

**Comment by Rob122783** [comment]
#
Duplicate of #

**Comment by taquila123** [comment]
Thank you  #9189

**Pull request merged**
