### PR TITLE
Fix incorrect use of "backslashes"

### LINKED ISSUE #23123: Typo: regex's should be surrounded by forward slashes, not backslashes
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

### What part(s) of the article would you like to see updated?

Regular expressions should be surrounded by _forward slashes_, but this doc referred to them as both "forward slashes" and "backslashes" in different places.

I'll submit a PR updating "backslashes" -> "forward slashes".

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by atenni**
Regular expressions should be surrounded by _forward slashes_, but this doc referred to them as both "forward slashes" and "backslashes" in different places.

This PR updates "backslashes" -> "forward slashes".

### Why:

Closes https://github.com/github/docs/issues/23123

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by nickserv — COMMENTED** [review]
How about just "slashes" instead of "forward slashes"? I believe the average user should already understand the difference. Additionally, a quick search in this repository shows 5 results for "forward slash", and 11 results for "slash" (excluding the prefix).

**Comment by atenni** [comment]
@nickmccurdy No problem - done :)

My initial instinct is _explicit is better than implicit_ – but given the audience and the fact that there is example code for this on the page I think your suggestion reads better.

**Comment by bialyh2o449** [comment]
> @nickmccurdy No problem - done :)
> 
> My initial instinct is _explicit is better than implicit_ – but given the audience and the fact that there is example code for this on the page I think your suggestion reads better.

Jeszcze tego nie instalowałem, w obecnej chwili windows serwer 2022. Visual, paczki kodów c++, PHP, C+, C, itd. instaluje prubki kodów albo gotowe, rozszerzenia w chrom beta, bev, canary,... Windows 10, 11. Zrobiłem w domu sieć urządzeń, potrzebnych do obsługi netu... Prawie dziś wszystko, Smart... Jakie mam wyjście na konfiguruje to wszystko w zasadzie pod dom kamery, odkurzacze, czy inne bajery* bo nie podłączony do neta to jak jak byś nie żył. 
A ostatnio pokazywałem żonie badaniem, jak szybko pędzi światłowód, akurat kilka kB. Na ping ... Ale udowodniłem że takie coś ma miejsce, o jesteśmy to w stanie nawet poczuć nie tylko telefon mogą lampą wibruje potwierdzenie przychodzi z serwerów w US.  Dość dużoma rzeczami się zadaje teraz jakoś tak wyszło... No ale to chyba taki etap w życiu.

**Review by saritai — APPROVED** [review]
@atenni Thanks so much for opening this PR to improve the docs! ✨ Great catch, you are definitely correct - and thanks @nickmccurdy for the review, I agree "slashes" makes sense as well 👍 

I'll go ahead and merge this! 🚀

**Pull request merged**
