### PR TITLE
#42 docs: Add missing > in OpenID Connect GCP doc, Update README.md, Add links to generic information for CodeQL & Rest

### PR DESCRIPTION
**Pull request by conorheffron**
Add additional read me links to main README.md.

### Why:

Allow users to navigate to other useful components and documentation such as CodeQL & Rest from the main `README.md`.

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by TeachMastermindPat** [comment]
```markdown
**Empowering Financial Inclusion and Sustainable Water Solutions with AfricaCryptoChainx**

Introducing AfricaCryptoChainx, powered by per-2-per tokens for seamless peer-to-peer transactions, revolutionizing finance with DeFi solutions, and addressing water sustainability.

**AfricaCryptoChainx Wallet:**

🔐 **Secure Infrastructure:**
Top-tier security for funds and data.

🔄 **Integration with P2P Networkers:**
Seamless direct bank transactions for enhanced accessibility.

**Security Commitment:**

🔒 **Asset Protection:**
Advanced security measures.

**Innovative UX:**

🌐 **Intuitive Interface:**
Seamless navigation.

💡 **Educational Resources:**
Empowering users with blockchain knowledge.

**Community Building:**

🤝 **Local Partnerships:**
Addressing sustainability challenges.

📢 **Engaging Community:**
Fostering a vibrant community.

**Join Us:**

1. **Visit Africacryptochainx.com**
2. **Secure Wallet Registration**
3. **Learn and Master**
4. **Community-driven Growth**

Thank you for being part of our journey. Let's redefine financial inclusion, security, and community ethos while addressing water sustainability with the power of DeFi.
```

**Review by TeachMastermindPat — COMMENTED** [review]
**Empowering Financial Inclusion and Sustainable Water Solutions with AfricaCryptoChainx**

AfricaCryptoChainx is at the forefront of empowering financial inclusion and sustainable water solutions. Powered by peer-to-peer tokens, it revolutionizes finance through DeFi solutions while addressing critical sustainability challenges.

**ACC Wallet:**

🔐 **Secure Infrastructure:** Top-tier security ensures the safety of funds and data.

🔄 **Integration with P2P Networkers:** Seamlessly facilitates direct bank transactions, enhancing accessibility.

**Security Commitment:**

🔒 **Asset Protection:** Advanced security measures safeguard users' assets.

**Innovative UX:**

🌐 **Intuitive Interface:** Seamless navigation enhances user experience.

💡 **Educational Resources:** Empowers users with blockchain knowledge for informed decisions.

**Community Building:**

🤝 **Local Partnerships:** Addresses sustainability challenges through collaboration.

📢 **Engaging Community:** Fosters a vibrant and supportive ecosystem.

**Join Us:**

1. **Visit Africacryptochainx.com**
2. **Secure Wallet Registration**
3. **Learn and Master**
4. **Contribute to Community-driven Growth**

Thank you for being part of our journey. Let's redefine financial inclusion, security, and community ethos while addressing water sustainability with the power of DeFi.

**Comment by TeachMastermindPat** [comment]
[Empowering Financial Inclusion and Sustainable Water Solutions with AfricaCryptoChainx](https://africacryptochainx.com)

**Comment by nguyenalex836** [comment]
@conorheffron Thanks so much for opening a PR! I'll get this triaged for review ✨

**Pull request closed without merging**
