### PR TITLE
Add context information for `jobs.<job_id>.uses`

### PR DESCRIPTION
**Pull request by lachieh**
### Why:

As far as I can tell, this property does not have access to any context and needs to be a statically defined string. If this is incorrect, it'd be great to have some clarification here.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Add row for `jobs.<job_id>.uses` into context availability table. Alternatively, a note at the top of this section could be used instead saying indicating that if the key is not listed in the table, it does not/may not support expression evaluation from context data.

As a third option, a note about this behavior could be added to the [relevant section on the workflow syntax page](https://docs-34833-5eac20.preview.ghdocs.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses).

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@lachieh Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by nguyenalex836** [comment]
@lachieh Thank you for your patience while our SME team reviewed! ✨ They responded with the following:

--------

I don't think this is the right place to convey this information.  We don't list where contexts cannot be used in the availability table, we only list where they can be used.  Right above that table we state:

> The following table indicates where each context and special function can be used within a workflow. Unless listed below, a function can be used anywhere.

So this is the part that could be clearer to me.  We have two things: contexts and functions.  In the table, the contexts column lists the only places where the given contexts can be used.  However, the functions column only lists the places where either 1) Functions cannot be used at all or 2) Only a specific set of functions can be used.  So unless that's clear to the reader going in they might have the wrong expectation.
Perhaps something like this to replace that would be a better option:

> The following table lists the restrictions on where each context and special function can be used within a workflow. The listed contexts are only available for the given workflow key, and may not be used anywhere else. Unless listed below, a function can be used anywhere.

--------

Would you be open to updating your PR to make the changes our SME team suggested instead? We'll be happy to merge this PR once that is finished 💛

**Comment by LucifeMORNINGSA84** [comment]
As far as I can tell, this property does not have access to any context and needs to be a statically defined string. If this is incorrect, it'd be great to have some clarification here.
---
 .../accessing-contextual-information-about-workflow-runs.md

**Review by LucifeMORNINGSA84 — COMMENTED** [review]
As far as I can tell, this property does not have access to any context and needs to be a statically defined string. If this is incorrect, it'd be great to have some clarification here.
  jobs.<job_id>.uses #7356

**Comment by lachieh** [comment]
@nguyenalex836 Thanks for the review. I made the change to the text before the table, and removed the added row. I do feel that it is still not quite clear, as neither functions nor context appear to be usable in this key. The same restrictions apply in many other places, such as `defaults.run`. Because of that, I've copied [the sentence from that section](https://docs-34833-5eac20.preview.ghdocs.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrun:~:text=defaults.run.-,You%20cannot%20use%20contexts%20or%20expressions%20in%20this%20keyword.,-When%20more%20than) into [the section for `jobs.<job-id>.uses`](https://docs-34833-5eac20.preview.ghdocs.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses:~:text=are%20not%20allowed.-,You%20cannot%20use%20contexts%20or%20expressions%20in%20this%20keyword.,-Example%20of%20jobs). Happy to remove this change if needed.

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@lachieh I had a messaged queued up, but forgot to send before I merged your PR!

> Because of that, I've copied [the sentence from that section](https://docs-34833-5eac20.preview.ghdocs.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrun:~:text=defaults.run.-,You%20cannot%20use%20contexts%20or%20expressions%20in%20this%20keyword.,-When%20more%20than) into [the section for jobs.<job-id>.uses](https://docs-34833-5eac20.preview.ghdocs.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses:~:text=are%20not%20allowed.-,You%20cannot%20use%20contexts%20or%20expressions%20in%20this%20keyword.,-Example%20of%20jobs).

I think this is a fair addition 💛 thanks again for your contribution! ✨

**Comment by lachieh** [comment]
Thank you!

**Pull request merged**
