### PR TITLE
Address 20 En-US Standardizations

### PR DESCRIPTION
**Pull request by SeanKilleen**
### Why:

* Supports #23188 
* A follow-up to #23189, as I was asked to create new PRs for any one-off spelling issues I found there.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by SeanKilleen** [comment]
ℹ️ NOTE: I'm operating under the assumption that the standard dialect for English in these docs is `en-US`, given the other examples. This PR isn't a question of right/wrong so much as it is standardization.

**Review by mchammer01 — APPROVED** [review]
@SeanKilleen - thanks for fixing these ✨

**Review by Md0135 — COMMENTED** [review]
Türkiye

**Review by GJustin361 — COMMENTED** [review]
8 change have been made and reviewed

**Review by por1981 — COMMENTED** [review]
gh pr checkout 25095

**Pull request merged**
