### PR TITLE
fix github actions file location: `.workflows` -> `.github/workflows`

### PR DESCRIPTION
**Pull request by kt3k**
### Why:

The doc references the GitHub Actions file location as `.workflows`, but the path doesn't seem working as GitHub Actions path.

I tested this in the repo: https://github.com/kt3k/workflows-test

Also when I interacts with users' repos via GitHub APIs, 'Workflows' permission seems required when accessing files under `.github/workflows`, not `.workflows`

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Change workflows file location from `.workflows` to `.github/workflows`.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by kt3k** [comment]
Checked the fix in preview env https://docs-27220-e3016c.preview.ghdocs.com/en/apps/creating-github-apps/registering-a-github-app/choosing-permissions-for-a-github-app#choosing-permissions-for-git-access

Screenshot 2023-08-02 at 13 01 33

**Review by skedwards88 — APPROVED** [review]
Thanks for fixing this! We'll get this merged for you.

**Comment by Miguel736j** [comment]
<details><summary>Details</summary>
<p>

Open 

</p>
</details>

**Comment by Miguel736j** [comment]
Yes

**Pull request merged**
