### PR TITLE
Correctly assign IAM policy bindings

### PR DESCRIPTION
**Pull request by tiwilliam**
### Why:

gcloud projects add-iam-policy-binding only take one role per command. Current docs will only apply the last role specified.

### What's being changed:

Run policy binding as three separate commands instead of one.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@tiwilliam 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by N-Usha** [comment]
@3loka to help review this.

**Comment by kchandra548** [comment]
From the [GCP documentation](https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role), it supports adding only a single role at a time. So the suggested changes are looking good to me.

**Review by kchandra548 — APPROVED** [review]
From [Documentation](https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role)  `add-iam-policy-binding` supports only adding a single role. So this change looks fine.

**Review by ramyaparimi — APPROVED** [review]

**Pull request merged**
