### PR TITLE
Add Bitwarden to the list of TOTP applications

### PR DESCRIPTION
**Pull request by lbjones**
### Why:

Bitwarden has TOTP support and is open source (https://github.com/bitwarden)

### What's being changed:

Adding a link to Bitwarden as a possible TOTP application.
[Bitwarden](https://bitwarden.com/help/article/authenticator-keys/)

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@lbjones Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by ptoomey3** [comment]
Hmm..so, I think we should be quite careful about which apps we add to this list. The bar we had informally set a while back were apps that we trusted (good reputation, good track record, etc) _and_ ones that supported secure backup/restore, since 2FA lockout is one of the biggest risks associated with 2FA. Looking through the list, most look familiar to me and meet this bar. One new one I noticed was Keeper, which I've personally never heard of and don't immediately see a secure backup/restore flow supported. I see that one was added in https://github.com/github/docs/issues/6535, but don't see much of a discussion for how it was decided to be added. With more folks possibly adding things to this list we might want to more formally pin down the requirements for being added, since nearly any TOTP app vendor in the world would love free advertising from us by being added to the list. 

/cc @github/pse-architecture for additional 👀

**Comment by lecoursen** [comment]
👋🏻 @lbjones, after some internal discussion, we decided not to accept updates to these lists via the open-source repo. Thanks for your interest in contributing to the docs!

**Comment by lbjones** [comment]
No prob, thanks for your time!

Thought it could be useful.  BW does support secure backup/restore.   It is one of the best free managers out there https://www.cnet.com/tech/services-and-software/best-password-manager/

**Pull request closed without merging**
