### PR TITLE
Update building-and-testing-python.md

### PR DESCRIPTION
**Pull request by cclauss**
* Bring in Python 3.11 and PyPy 3.9.
* Replace flake8 with ruff to get speed, coverage, and GitHub Annotations

https://devguide.python.org/versions
https://beta.ruff.rs/docs

### Why:

Closes ISSUE

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Review by adhammahdi — COMMENTED** [review]
Have all the procedures been done and withdrawn 
Is there a bank in Ghaith

> 

> 

> 

> ``

**Comment by cmwilson21** [comment]
@cclauss Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by skedwards88 — APPROVED** [review]
Thanks for this PR! We'll get this merged down for you.

**Comment by cclauss** [comment]
@charliermarsh FYI: Live at https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Pull request merged**
