### PR TITLE
Fix #13741 : Self hosted Pull-based scale update

### LINKED ISSUE #13741: Self-hosted runners Pull-based autoscaling precision
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions

### What part(s) of the article would you like to see updated?

For "philips-labs/terraform-aws-github-runner" solution, it is said that "Pull-based autoscaling" is not supported.

This behaviour will change with https://github.com/philips-labs/terraform-aws-github-runner/pull/1577

Change proposal:

___
[Yes](https://github.com/philips-labs/terraform-aws-github-runner#simple-pool) (org-level runners)
___

### Additional information

PR WIP

### PR DESCRIPTION
**Pull request by axel3rd**
### Why:

Closes #13741

### What's being changed:

"philips-labs/terraform-aws-github-runner" (will) supports pull-based autoscaling.

See staging deployment for details.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@axel3rd 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by axel3rd** [comment]
PR set to draft, until decision of https://github.com/philips-labs/terraform-aws-github-runner/issues/1588.
*Pull-based autoscaling* feature could be considered as supported by [philips-labs/terraform-aws-github-runner](https://github.com/philips-labs/terraform-aws-github-runner) in a short term => PR will perhaps be updated.

**Comment by axel3rd** [comment]
PR updated with Pull-based autoscaling support. Will be un-draft when https://github.com/philips-labs/terraform-aws-github-runner/pull/1577 merged.

**Comment by Kokyawminthu** [comment]
axel3rd:axel3rd-self-hosted-pull-based-scale-update

**Comment by axel3rd** [comment]
The [failing](https://github.com/github/docs/runs/4791153698?check_suite_focus=true) *Link Checker: All English* seems not part of this change (`Unhandled error: Error: Input required and not supplied: github-token`).

**Review by ethomson — APPROVED** [review]

**Review by ramyaparimi — APPROVED** [review]

**Comment by axel3rd** [comment]
😘 @ethomson @ramyaparimi @skedwards88 @lucascosti

**Pull request merged**
