### PR TITLE
Fix docs for CodeQL query suites

### PR DESCRIPTION
**Pull request by garysassano**
### Why: Current docs isn't aligned with [MS Learn](https://learn.microsoft.com/en-us/training/modules/code-scanning-with-github-codeql/2-what-is-codeql#default-query-suites) nor with query suites available in CodeQL CLI.

image

Closes: 

### Check off the following:

- [ ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by garysassano** [comment]
The 4 built-in query suites are also visibile in [this Azure DevOps task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-codeql-init-v1?view=azure-pipelines).

**Comment by nguyenalex836** [comment]
@garysassano Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by saritai** [comment]
Hi @garysassano - thanks for your contribution! I'm going to double-check with the relevant team and get back to you on this. From looking at this briefly, I think the [CodeQL query suites](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/codeql-query-suites) article is focused on the query suites available to choose for code scanning default setup in GitHub (only those two options are available) rather than the query suites available in the CodeQL CLI.  If so, this article may need to be updated to clarify that. I do agree that the reusable you updated should contain the full list of query suites available. But I'll get back to you once confirmed! 👍

**Comment by FidelusAleksander** [comment]
This is also very confusing to me as I'm studying for the GitHub Advanced Security exam and one of the items in the study guide is 
`Describe the default CodeQL query suites`
And MSLearn, GitHub Docs and CodeQL CLI have three different/confusing information about this

**Comment by saritai** [comment]
👋 Thanks so much again for bringing this up @garysassano, and thanks also to @FidelusAleksander for your perspective as well! 💛

We've looked into this further, and the availability of query suites in different scenarios is a bit more complex and will require some wider changes in the docs to clarify. We think this would be best addressed internally, so I have opened an internal issue and noted the details brought up in this PR, and will close this PR out. 🙇‍♀️

**Pull request closed without merging**
