### PR TITLE
Fix indentation of groups yaml example

### LINKED ISSUE #27987: DOCS: Examples of `groups` parameter for Dependabot updates has wrong indentation level
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

### What part(s) of the article would you like to see updated?

The docs currently contain an example of using the `groups` parameter. I think it has the wrong level of indentation: the `groups` key should be under `updates`, not at the top level of the YAML config.

Here's the current example, which I think is wrong:
```
# `dependabot.yml` file using the `update-types` option to group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
groups:
  angular:
    patterns:
    - "@angular*"
    update-types:
    - "minor"
    - "patch"
```

This would lead to an error like:

```
The property '#/' contains additional properties ["groups"] outside of the schema when none are allowed
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DenverCoder1**
### Why:

When I saw this example, I assumed this meant you could have `groups` defined outside of `updates` to apply to all package types. Doing so, however, causes the dependabot file check to fail with the following error:

> ## Your .github/dependabot.yml contained invalid details
> 
> Dependabot encountered the following error when parsing your `.github/dependabot.yml`:
> 
> ```
> The property '#/' contains additional properties ["groups"] outside of the schema when none are allowed
> ```
> Please update the config file to conform with Dependabot's specification.

Closes #27987 

### What's being changed (if available, include any code snippets, screenshots, or gifs):

This example shows `groups` at the top level of a dependabot.yml. This PR corrects it to have the groups indented within the npm updates settings since it otherwise fails.

```yaml
# `dependabot.yml` file using the `update-types` option to group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
groups:
  angular:
    patterns:
    - "@angular*"
    update-types:
    - "minor"
    - "patch"
```

```yaml
# `dependabot.yml` file using the `update-types` option to group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
```

Relevent docs links:

- Live - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- Preview deployment - https://docs-28056-0123c9.preview.ghdocs.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@DenverCoder1 Thanks so much for submitting a PR! I'll get this triaged for review :zap:

**Review by jurre — APPROVED** [review]
Thanks, that's totally right! 🙇

**Review by am-stead — APPROVED** [review]
Thanks @DenverCoder1 for creating this PR and fixing this mistake! 🙏 
I'll get this merged. ✨

**Review by ALFA1OMEGA — COMMENTED** [review]
@americanexpress #americanexpress[](https://)linkedin.com/in/americanexpress.com

**Comment by ALFA1OMEGA** [comment]
`ATM.NET`

**Comment by ALFA1OMEGA** [comment]
HOME

**Pull request merged**
