### PR TITLE
Fix typos in search part of contribution guideline

### PR DESCRIPTION
**Pull request by tnir**
### Why:

The less typos, the easier to read.

### What's being changed:

Fix typos in search part of contribution guideline.

### Check off the following:
- [x] All of the tests are passing.
- [n/a] I have reviewed my changes in staging.
- [n/a] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [n/a] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 Thanks for fixing the typos @tnir! Could you either remove the changes you made to the readme or open a new PR without them and close this one? You can add yourself to [the list of contributors](https://github.com/github/docs#contributors-) by creating a new comment in this (or the new, updated) PR using [these instructions](https://allcontributors.org/docs/en/bot/usage#commands). Thanks again! :sparkles:

Using the command helps us to keep track of the changes with all contributors. Thank you!

**Comment by tnir** [comment]
@all-contributors please add @tnir for Maintenance

**Comment by tnir** [comment]
@janiceilene Thanks for your suggestion. Just removed changes from contributors and created #506.

**Review by janiceilene — APPROVED** [review]
Thanks so much @tnir 🎉 I'll update the branch and get this merged once tests are green 🍏

**Pull request merged**
