### PR TITLE
Add additional clarification about the merge queue

### PR DESCRIPTION
**Pull request by ghost**
<!--
Thank you for contributing to this project! You must fill out the information below before we can review this pull request. By explaining why you're making a change (or linking to an issue) and what changes you've made, we can triage your pull request to the best possible team for review.
-->

### Why:
PR adds additional clarification about the Merge Queue
- Merge queue and Pull Requests checks currently are coupled
- Link to the section where these checks are configured is added

It is a follow up of the [How to ensure Github merge queue does not allow failed checks into master #75568](https://github.com/orgs/community/discussions/75568) and probably main discussion - [Pull Request Merge Queue Public Beta Feedback #46757](https://github.com/orgs/community/discussions/46757).

Closes: None

<!-- If there's an existing issue for your change, please link to it above.
If there's _not_ an existing issue, please open one first to make it more likely that this update will be accepted: https://github.com/github/docs/issues/new/choose. -->

### What's being changed (if available, include any code snippets, screenshots, or gifs):

| File                                                                                                                                                                                                                                        | Changes                                 |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------- |
| [managing-a-merge-queue.md](https://github.com/github/docs/blob/3899a1a79e467570fdcf2fb8c36c111a23c5ded6/content/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue.md) | Added additional note about merge queue |

<!-- Let us know what you are changing. Share anything that could provide the most context.
If you made changes to the `content` directory, a table will populate in a comment below with links to the preview and current production articles. -->

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@air3ijai Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by diyaranazarova** [comment]
бу програмда телеграм учун патписчик йигча буладими

**Comment by nguyenalex836** [comment]
@air3ijai Thank you for your patience while our team reviewed your PR! 💛 We made (2) small adjustments to your changes

- Removed "Currently," at the beginning of your addition
- Removed an extra space

I'll update the branch and get this merged once tests are passing 🍏 thank you very much for your contribution! ✨

**Review by nguyenalex836 — APPROVED** [review]

**Comment by air3ijai** [comment]
> "Currently," was added as we all hope that soon these checks will be decoupled :)

Looks good, @nguyenalex836, thank you for the update!

**Pull request merged**
