### PR TITLE
Update adding-outside-collaborators-to-repositories-in-your-organizat…

### PR DESCRIPTION
**Pull request by queenofcorgis**
…ion.md

Adding clarity after a community member question

### Why:

Doc was lacking context and information for free plan users - [Community Discussions being referenced](https://github.com/orgs/community/discussions/46538#discussioncomment-4904157)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Added a sentence to add clarity for free org plan users on inviting outside collaborators to their repo. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @queenofcorgis Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by felicitymay — COMMENTED** [review]
@queenofcorgis - thank you so much for raising this pull request to update the docs so that the question in that discussion is clearly answered 💖 

I had a look to see where we use that "reusable" chunk that you've added the new sentence after. It looks as if we use this in three articles:

- [Adding outside collaborators to repositories in your organization](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization) - this article
- [Converting an organization member to an outside collaborator](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/converting-an-organization-member-to-an-outside-collaborator) -  a related article where the information is also relevant
- [Setting permissions for adding outside collaborators](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/setting-permissions-for-adding-outside-collaborators) - article available for enterprise users only

I recommend that we incorporate your change into the existing reusable with conditions so that it's displayed in the first two articles for users viewing the docs for Free, Pro and Team plans.

I experimented locally, and this is what my suggestion looks like:

image

Do you think that would be clear to users?

**Comment by queenofcorgis** [comment]
@felicitymay love it - concise and to the point - thanks for looking around for other docs that use this language ❤️

**Comment by felicitymay** [comment]
> @felicitymay love it 

So glad you like the suggestion @queenofcorgis. I'll see if I can update the PR accordingly, then you can see it in preview and we can get your update merged.

**Comment by felicitymay** [comment]
Once the preview has [redeployed](https://github.com/github/docs/actions/runs/4176137568/jobs/7232023324), we should be able to see the update:

- [Free, pro, team](https://docs-23788-64e6b9.preview.ghdocs.com/en/organizations/managing-user-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization) - should contain the change
- [GHEC](https://docs-23788-64e6b9.preview.ghdocs.com/en/enterprise-cloud@latest/organizations/managing-user-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization) - and other enterprise versions should be unchanged.

**Comment by felicitymay** [comment]
No obvious reason why that failed. Will update from `main` which will trigger a new deployment.

**Review by felicitymay — APPROVED** [review]

**Pull request merged**
