### PR TITLE
Update content/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform.md to reflect most recent version

### LINKED ISSUE #23934: Update doc to current version of Action: 'google-github-actions/auth'
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform

### What part(s) of the article would you like to see updated?

more recent MAJOR version available.  

* Users likely to copy/paste so important to upgrade
* Also, remove unnecessarily included value when same as default.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brucearctor**
### Why:

Closes [ISSUE](https://github.com/github/docs/issues/23934)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updating doc as noted in https://github.com/github/docs/issues/23934

* the mentioned action is now V1 ( https://github.com/google-github-actions/auth ) so updated accordingly
* removed unneeded attribute, since was same as 'default' value/parameter.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by brucearctor** [comment]
LOL -- the only file I am trying to change is in that list.  That doc is out of date!

**Comment by brucearctor** [comment]
Will leave it to a human to close this [ or perhaps stale bot ] and/or someone to choose to perform same actions/update.  Cheers -

**Comment by cmwilson21** [comment]
@brucearctor Thank you for opening a PR and linking it to your issue! ✨ 

The bot above is to give us a heads up when we are reviewing. Some files we cannot accept changes to, but for this one, we will review it and check with the team before we merge it. It just adds an extra layer of security over certain files 👍 

I'll get this triaged for review! :zap:

**Review by ghost — COMMENTED** [review]
Trash I'm very new to this. Sorry.

**Comment by brucearctor** [comment]
@Patricia1966Wa : is there something I can help you with?

**Comment by brucearctor** [comment]
@cmwilson21 -- anything else needed?  it seems prudent to keep security docs rather up-to-date?

**Comment by cmwilson21** [comment]
@brucearctor - Thanks for checking in on this again. We've checked with the team and this sort of update will need to be made internally. I'm going to go ahead and close this PR and make note for the team to update 💛 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Pull request closed without merging**
