### PR TITLE
Update `repository-branches.md`

### LINKED ISSUE #15614: `repository-branches.md` Uses Incorrect Sidebar Section Name
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Specifically: [Managing a branch protection rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)

Generally: Any article that uses the [`repository-branches.md` reusable](https://github.com/github/docs/blob/main/data/reusables/repositories/repository-branches.md).

### What part(s) of the article would you like to see updated?

**Currently** the [`repository-branches.md` reusable](https://github.com/github/docs/blob/main/data/reusables/repositories/repository-branches.md) instructs the reader to locate the "_Code & operations_" section of the sidebar. However, this instruction is outdated, as the section is now "_Code and automation_" and should read as such.

CleanShot 2022-02-18 at 12 51 26

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jthodge**
### Why:

Closes #15614 

### What's being changed:

**Prior to the changes included in this PR**, the [`repository-branches.md` reusable](https://github.com/github/docs/blob/main/data/reusables/repositories/repository-branches.md) instructs the reader to locate the "_Code & operations_" section of the sidebar:

CleanShot 2022-02-18 at 12 56 29

**Currently, with the changes included in this PR**, the section is appropriately named "_Code and automation_" to reflect the sidebar section in the `Options` menu:
CleanShot 2022-02-18 at 12 51 26

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@jthodge 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

Also, I am very curious to how you highlighted a part of the screenshot 💖  Could you let me know what tool you used for that??

**Comment by jthodge** [comment]
Thanks @ramyaparimi  — appreciate you!
The tool I used for the screenshots is [Cleanshot X](https://cleanshot.com/).
It's likely the best money I've $ / quality of life improvement in software I've used in the last two years — can't recommend it enough!

**Comment by ramyaparimi** [comment]
> The tool I used for the screenshots is [Cleanshot X](https://cleanshot.com/). 

Looks pretty neat!! Thanks for sharing 💖

**Review by felicitymay — DISMISSED** [review]
@jthodge - many thanks for this PR 💖 

It seems as if they changed the name of this section again. Your change is great (see preview: [Managing a branch protection rule](https://docs-preview-15615-77d9e7.eastus.azurecontainer.io/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)) and it was particularly helpful that you included screenshots to explain what you'd changed. 

I notice that we have the same problem in [`sidebar-pages.md`](https://github.com/github/docs/blob/main/data/reusables/pages/sidebar-pages.md). I've updated your PR to fix that as well.

**Review by felicitymay — APPROVED** [review]
Assuming the tests pass, this should be ready to merge.

**Comment by jthodge** [comment]
@felicitymay Thanks for shepherding these changes through to merge! 🎉

**Comment by felicitymay** [comment]
No problem. Thanks for your help 🙂

**Pull request merged**
