### PR TITLE
Removed the fullstop.

### LINKED ISSUE #33161: Remove unnecessary second period from creating-gists#about-gists
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists#about-gists

### What part(s) of the article would you like to see updated?

> After creating a gist, you cannot convert it from public to secret..

Remove unnecessary second period

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lonelyH3b**
### Why:
Remove the second period, i.e, the second full stop from `After creating a gist, you cannot convert it from public to secret..`

Closes: #33161 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@rakinplaban Hello! 👋 Thank you for opening a PR! We noticed this PR has been closed - were you still interested in having this PR merged?

**Comment by rakinplaban** [comment]
Hi @nguyenalex836,

Thank you for reaching out. I closed the pull request because it failed to be deployed. However, I am still interested in having this PR merged eventually.

I'll let you know once I can address the deployment issues.

Best regards,
Rakin

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@rakinplaban It looks like the deployment issue has been resolved! 💛 I'll go ahead and get this merged - thank you very much for your contribution! ✨

**Comment by Rosellyn1990** [comment]
> 
> 
> 
> 
> ### Why:
> 
> Remove the second period, i.e, the second full stop from `After creating a gist, you cannot convert it from public to secret..`
> 
> 
> 
> Closes: #33161 
> 
> 
> 
> 
> 
> 
> 
> ### What's being changed (if available, include any code snippets, screenshots, or gifs):
> 
> 
> 
> 
> 
> 
> 
> ### Check off the following:
> 
> 
> 
> - [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
> 
> 
> 
>   - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
> 
> - [ ] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).
> 
>

**Pull request merged**
