### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by wonda-tea-coffee**
### Why:

because the package name was incorrect.

### What's being changed:

loadash→lodash

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by SMAKSS — APPROVED** [review]

**Comment by janiceilene** [comment]
Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request, then we'll get this up for review!

**Comment by wonda-tea-coffee** [comment]
@janiceilene 
Sorry, corrected 👍

**Comment by janiceilene** [comment]
Thanks so much @wonda-tea-coffee! I'll get this triaged for review 🌟

**Review by hubwriter — APPROVED** [review]
Good spot.
Many thanks @wonda-tea-coffee for correcting this. 👍

**Pull request merged**
