### PR TITLE
Clarify push protection works with secret_scanning.yml

### PR DESCRIPTION
**Pull request by felickz**
### Why:

Clarifies that secret scanning push protection is covered by configuration in secret_scanning.yml

### What's being changed (if available, include any code snippets, screenshots, or gifs):

image
- `", including push protection." `
    -  confirmedadded for GHEC, GHES 3.7 / 3.6 / 3.5 via feature flag `secret-scanning-push-protection`

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @felickz Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by mchammer01** [comment]
I'll take a look at this!

**Review by mchammer01 — COMMENTED** [review]
@felickz 👋🏻 - thanks for fixing this omission ✨ 
I've made a minor suggestion that I'm going to apply. Once this is done, I'll merge your PR asap :shipit:

**Review by mchammer01 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
