### PR TITLE
Documentation about current bug on github

### PR DESCRIPTION
**Pull request by munrocket**
Currently you can't rename yourself back.

Step to reproduce:
1) create an account
2) create a public repo
3) change username and get some automatic redirection
4) try to change it back and get an error
```
Username change was not successful. The repository name `username1/myrepo` has been retired and cannot be reused
```
I have a ticket with this bug in contact support #1180808 but if this is expected behavior, this should be in documentation.

### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@munsocket Thanks so much for opening a PR! Let me know when support gets back to you and what they say, and then I'll triage this PR for review. Their response will help us decide what updates we should consider making 💖

**Comment by munsocket** [comment]
Thanks, at least somebody answered me.

#1167406 closed created 17 days ago
#1180808 open created 7 days ago
I opened two tickets, because I thought the first one is lost somewhere. This process not so easy.

**Comment by janiceilene** [comment]
👋 @munsocket I've chatted with the team about your PR and looked at the support tickets. Your situation is one that most users won't find themselves in (because the repo in question was a prominent one and most people's won't be), so adding to this article would cause more users confusion than it would help. Here's some more information about namespace retirement if you're interested, https://github.blog/2018-04-18-new-tools-for-open-source-maintainers/#popular-repository-namespace-retirement.

Thank you so much for your interest in improving the GitHub docs and I'm glad you got your problem resolved!

**Comment by munrocket** [comment]
Thanks! This bug probably still exist but it was solved manually.

**Pull request closed without merging**
