### PR TITLE
Remove stray space from link

### PR DESCRIPTION
**Pull request by jsoref**
### Why:

The trailing space looks ugly

### What's being changed:

image

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by Makumbindenyasha — COMMENTED** [review]
T

**Review by ramyaparimi — APPROVED** [review]
@jsoref 
Thanks so much for opening a PR with this fix! I'll get this merged once tests are passing 🍏

**Comment by jsoref** [comment]
Fwiw, it looks like an action here failed.

https://github.com/github/docs/runs/4716329992?check_suite_focus=true
https://github.com/github/docs/actions/runs/1658969236/workflow the
https://github.community/t/permissions-nesecary-to-comment-on-a-pr/179047/8

IME, this tends to work:
```
permissions:
  pull-requests: write
```

**Comment by ramyaparimi** [comment]
@jsoref Thanks so much for letting me know 💖  I opened an internal PR with the fix ✨

**Pull request merged**
