### PR TITLE
Update version of setup-dotnet to v3

### PR DESCRIPTION
**Pull request by IvanZosimov**
### Why:

The version of the `setup-dotnet` was recently updated to `v3`. GitHub docs should reflect this change to allow more customers to use the new action version.

Closes [this issue](https://github.com/actions/runner-images-internal/issues/4329)

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Just a minor change in reusable for `setup-dotnet` docs.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @IvanZosimov Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by tazimamatovzeka** [comment]
Ayzat

**Comment by tazimamatovzeka** [comment]
TNHtT2QtKNZsP7FAiQWMyyWH96eLSsMfbn

**Comment by IvanZosimov** [comment]
Hi, @cmwilson21 👋 Are there any updates on this PR?

**Review by lucascosti — APPROVED** [review]
Looks good, thanks @IvanZosimov! I'll get this merged 🚀

**Pull request merged**
