### PR TITLE
repo sync

### PR DESCRIPTION
**Pull request by Octomerger**
This is an automated pull request to sync changes between the public and private repos.

:robot: This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!

### CODE REVIEW

**Comment by FREELANCEGITIT** [comment]
Thank you so muxb




On Thursday, December 3, 2020, 3:50 AM, github-actions[bot] <notifications@github.com> wrote:




@github-actions[bot] approved this pull request.

**Comment by FREELANCEGITIT** [comment]
Now ?




On Thursday, December 3, 2020, 3:52 AM, K. Alene Lister-Simoes <freelance1974@yahoo.com> wrote:

Thank you so muxb




On Thursday, December 3, 2020, 3:50 AM, github-actions[bot] <notifications@github.com> wrote:




@github-actions[bot] approved this pull request.

**Review by mybet002mail — COMMENTED** [review]
https://github.com/github/docs/pull/1769#issue-531713449

**Comment by gid57** [comment]
> This is an automated pull request to sync changes between the public and private repos.
> 
> 🤖 This pull request should be merged (not squashed) to preserve continuity across repos, so please let a bot do the merging!

name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Pull request merged**
