### PR TITLE
Update workflow run limit from 100 to 500

### PR DESCRIPTION
**Pull request by juliobbv**
### Why:

Closes https://github.com/github/c2c-actions-runtime/issues/1308

### What's being changed:

Updates workflow run limit from 100 to 500, to reflect a recent change in product behavior.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

No writer impact.

### CODE REVIEW

**Review by lokesh755 — APPROVED** [review]

**Comment by ramyaparimi** [comment]
@juliobbv Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Mawlamyaigyun** [comment]
Mawlamyaigyun Township Group

**Review by lecoursen — APPROVED** [review]
Thanks! I'll merge now. ⚡

**Comment by 4393445** [comment]
ในวันที่ อา. 25 ก.ค. 2021 02:08 น. Mawjyun ***@***.***>
เขียนว่า:

**Pull request merged**
