### PR TITLE
Add entry to table "create, edit, delete labels"

### LINKED ISSUE #1178: Add row with create/edit/delete labels rights overview to permission level table
### What article on docs.github.com is affected?

The table in the [Repository access for each permission level](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) article.

### What part(s) of the article would you like to see updated?

I would like the table to have a new row called: "Create, edit, delete labels".

Currently the table only lists "Apply labels", but the creating, editing, and deletion of labels requires at least **write** level rights. This is causing confusion for maintainers of a repository who give a collaborator "Triage" rights, and then find out that the "Triage" rights do not include the right to create/edit/delete labels.

This information is mentioned in the  [Creating a label](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-a-label) docs:
> In repositories where you have write access, you can create labels to organize issues and pull requests.

This information should also be visible in the overview table instead of "hidden away" somewhere else.

### Additional information

I'm willing to make the PR to fix this. :smile:

### PR DESCRIPTION
**Pull request by HonkingGoose**
### Why:

Fixes #1178.

### What's being changed:

- Add entry to table "create, edit, delete labels"

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 Thanks for opening a PR @HonkingGoose! I see that this is currently a draft, let me know when it's ready for review and I'll get it triaged 💖

**Comment by HonkingGoose** [comment]
Hi @janiceilene  :wave:

This is ready for triage/review now.

**Comment by janiceilene** [comment]
Thanks @HonkingGoose! I'll get it triaged ⚡

**Review by lashaunda — APPROVED** [review]
[link removed by moderator]

**Comment by HonkingGoose** [comment]
@janiceilene This PR has not been reviewed yet, and now the stale bot is threatening to close the issue... 😄 

Commenting so that the stale bot doesn't close this PR.

**Review by felicitymay — APPROVED** [review]
👋🏻 Hi @HonkingGoose 

Many thanks for your patience with the very slow review. This looks like a great addition to the topic. ✨ 

While reviewing this change, I realized that an associated topic could also do with a minor update and opened: https://github.com/github/docs/issues/1693 for it.

I'll ~update the branch from `main` and~ merge this PR 😄

**Comment by HonkingGoose** [comment]
Cheers, thanks for merging @felicitymay. 😄

**Pull request merged**
