### PR TITLE
Update quickstart.md

### PR DESCRIPTION
**Pull request by Dileepinukurthi**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by MAC-ARTHUR-TRUE** [comment]
Madison chambers or Chamberlin POW MIA Afghanistan IRAC,  impersonated by Pamela mceandry, calling themselves Steve and Mary Female identity change to Paris Pichai or Pichilli Apaguasa. Secured identity with "memory" software accounts of DreamWorks high jacked used against her by known criminals and theives.Stalking of female documented with federal restraining order permanent. Paris 304 663 4110 Sent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  15:53  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent HelpSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/28/22  3:51 PM  (GMT-05:00) To: ***@***.*** Subject: FW: Urgent Data pushesMasked ipPhone info changesAll obsevedSent from my  U.S.Cellular© Smartphone-------- Original message --------From: mc4928184 ***@***.***> Date: 2/24/22  12:07 AM  (GMT-05:00) To: ***@***.*** Subject: Urgent Crime Sent from my  U.S.Cellular© SmartphoneSent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Inukurthi Dileep ***@***.***> Date: 3/4/22  03:28  (GMT-05:00) To: github/docs ***@***.***> Cc: Subscribed ***@***.***> Subject: [github/docs] Update quickstart.md (PR #16047) 
Why:
Closes [issue link]

What's being changed:

Check off the following:

 I have reviewed my changes in staging (look for "Automatically generated comment" and click Modified to view your latest changes).
 For content changes, I have completed the self-review checklist.

Writer impact (This section is for GitHub staff members only):

 This pull request impacts the contribution experience

 I have added the 'writer impact' label
 I have added a description and/or a video demo of the changes below (e.g. a "before and after video")







You can view, comment on, or merge this pull request online at:
  https://github.com/github/docs/pull/16047

Commit Summary

  1585510  Update quickstart.md


File Changes  (1 file)

  
    M
    content/codespaces/getting-started/quickstart.md
    (4)
  


Patch Links:

  https://github.com/github/docs/pull/16047.patch
  https://github.com/github/docs/pull/16047.diff

**Comment by ramyaparimi** [comment]
@Dileepinukurthi 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by mchammer01** [comment]
Hi @Dileepinukurthi - thanks for offering to improve our docs ✨ 
We can't accept these updates because we follow strict content models for our content and also we believe `deep dive` is the correct US spelling.
Thanks for your interest 🙂

**Comment by Heavy8888** [comment]
By n sonic

**Pull request closed without merging**
