### PR TITLE
[actions] remove redundant note from `push` event

### PR DESCRIPTION
**Pull request by kaznovac**
### Why:

Closes n/a

### What's being changed:

there are two notes about combining the `push` event filters;
both the same and they both fit on the same screen (2k, 15");
removed the first one (so both note mentioned filter properties get introduced by doc)

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@kaznovac 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by lucascosti** [comment]
Thanks for this PR, @kaznovac. Because the note is included in subsections that are specific to different situations (workflows when a push to specific branches occurs, vs specific files), users might only read the section relevant to their situation. We need to have the note in both places, because often people won't read the whole `push` section.

**Comment by kaznovac** [comment]
@lucascosti thanks for the review...
than by your reasoning (at least) one note is missing for the middle section https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs

**Comment by lucascosti** [comment]
@kaznovac 🤔 I don't think so, because IIRC, the behavior in the note is specific to only the `branches` and `paths` filters (not `tags`). 🙂

**Comment by kaznovac** [comment]
@lucascosti yes but this restrictions are not specific to the `branches` and `paths` only, those can be combined with `tags`. see here for example https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags

**Comment by lucascosti** [comment]
@kaznovac no, the restriction does not apply to `tags` and `branches`/`paths`. Filters are normally on an `OR` basis, but if you define both `branches` and `paths`, the workflow will only run when both those specific filters are satisfied.

e.g. as per [your link](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags), if you define `branches` and `tags` filters, the workflow will run when either filter is satisfied.

**Comment by kaznovac** [comment]
@lucascosti a bit confusing but makes sense (as both tags and branches are got references), thanks for clarification TIL.

**Pull request closed without merging**
