### PR TITLE
Suggest users to use --force-with-lease instead of --force

### LINKED ISSUE #6804: Use force with lease instead of force
### What article on docs.github.com is affected?

https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

### What part(s) of the article would you like to see updated?

The section that talks about how to push the changes

### PR DESCRIPTION
**Pull request by yeikel**
### Why:

Closes https://github.com/github/docs/issues/6804

### What's being changed:

force overwrites a remote branch with your local branch.

--force-with-lease is a safer option that will not overwrite any work on the remote branch if more commits were added to the remote branch

Read more : https://git-scm.com/docs/git-push

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@yeikel Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Review by jmarlena — APPROVED** [review]
@yeikel Thanks for improving the docs with this PR! 

Once all tests are green, this looks ready to ship. 🚢

**Comment by kenzodadon** [comment]
> Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

**Review by ivan0117 — COMMENTED** [review]
content/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message.md

**Pull request merged**
