### PR TITLE
Update troubleshooting-custom-domains-and-github-pages.md

### PR DESCRIPTION
**Pull request by mark-mxwl**
### Why: 
Custom domain CNAME errors appear to be a common obstacle when deploying to GitHub Pages. While a number of these issues have already been solved, newer users may find more clarity in addressing missing/overwritten CNAME files locally rather than pulling a previous commit from the remote repository.

### What's being changed (if available, include any code snippets, screenshots, or gifs): 
Added one line to the documentation for [Troubleshooting custom domains and GitHub Pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages) that proposes an alternative fix for missing/overwritten CNAME files. By creating the CNAME file manually in the public folder of the user's local repository, the issue is solved in a more direct and accessible manner.

### Check off the following:

- [ X ] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline.

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [ X ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by mark-mxwl** [comment]
@cmwilson21 Np! Thank you!

**Comment by mark-mxwl** [comment]
Hi @cmwilson21 ! Just checking in. Is there anything I can do on my end to better prepare this PR for review?

**Comment by stevecat** [comment]
Hi there @mark-mxwl! Thanks for opening this PR and I'm sorry for the time taken for us to review it.

I can see how the sentence you've added will help people using static site generators that force push changes but the paragraph isn't entirely about those static site generators, instead, it's advising anyone who works on their site locally.

For someone who isn't using a workflow that force-pushes, manually creating their `CNAME` file will cause more problems. Git will still see two diverged commit histories and will be unable to push to the remote or merge without first solving conflicts. The best advice is to instead pull the changes from the remote repository. Even if you've made other commits since, as long as you don't have a CNAME file locally, Git will figure things out and merge it neatly in.

I think it's best leaving this as it is for now but if we see this causing a lot of problems specifically for folks using those static site generators, we could add an entirely new paragraph to clearly share this advice.

Thanks again for spending the time on this! ✨

**Comment by mark-mxwl** [comment]
No prob, @stevecat! I appreciate your insights on the subject!

**Pull request closed without merging**
