### PR TITLE
Remove shell injection in example

### PR DESCRIPTION
**Pull request by soliton-**
### Why:

Avoid shell injection in workflow example.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Workflow example

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@soliton- Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by soliton-** [comment]
@cmwilson21 Just a reminder. This probably got lost over the holidays. Is there anything I need to do?

**Comment by cmwilson21** [comment]
@soliton- Thanks for checking in! It's up on the board waiting for review. Someone will have eyes on it soon. 👀 

We do appreciate your patience as we are catching up after the holidays 💛

**Comment by cmwilson21** [comment]
@soliton- Thanks again for your patience here! I checked with the team and this looks like a great addition to the docs. I'll get this merged down once all the tests have passed ✅ 

Thank you for your interest in improving GitHub Docs! :sparkling_heart:

**Review by cmwilson21 — APPROVED** [review]
LGTM 🚢

**Comment by janl3577** [comment]
Thanks so much

**Comment by hocnali963** [comment]
hi

**Comment by hocnali963** [comment]
hi1000$

**Comment by Je-dev56** [comment]
16qiLPW8gv4nGVMGw7zvdzuThBp8NEH7vX

**Pull request merged**
