### PR TITLE
change blog url for pull_request_target

### LINKED ISSUE #4756: Using correct blog url for `pull_request_target`
### What article on docs.github.com is affected?

[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

### What part(s) of the article would you like to see updated?

url for the blog article does not work

### Additional information

This is the current message:

Bildschirmfoto 2021-03-23 um 12 21 49

### PR DESCRIPTION
**Pull request by flaxel**
### Why:

**Closes [issue link](https://github.com/github/docs/issues/4756)**

### What's being changed:

- change the url of the blog article

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by CuneytMutlu** [comment]
bana kim yardım ediyorsa tanışmak isterim

**Comment by CuneytMutlu** [comment]
suanki hesap github
/
dokümanlar

**Comment by CuneytMutlu** [comment]
ada yoplayalım ben gönlümü verdim aday

**Review by hello-smile6 — APPROVED** [review]

**Review by SMAKSS — COMMENTED** [review]
Hi, thanks for the PR, but the change you made will navigate the end-user to the not found _(404)_ page and the original URL works just fine.

**Comment by flaxel** [comment]
Okay that's funny. Yesterday the link was different and it didn't work for me. With that, I would close this PR and the associated issue.

**Pull request closed without merging**
