### PR TITLE
Correct the example URL

### PR DESCRIPTION
**Pull request by peternewman**
### Why:

- I'll make an issue if I really must, but it's adding four characters!
- Without the .git it's not actually a git repository.

### What's being changed:

See the diff, it's adding four characters! Diff slightly modified as it seems you can't show code markdown within code markdown.
```
diff --git a/content/github/using-git/adding-a-remote.md b/content/github/using-git/adding-a-remote.md
index ce69b353b00..65d792400a5 100644
--- a/content/github/using-git/adding-a-remote.md
+++ b/content/github/using-git/adding-a-remote.md
@@ -37,7 +37,7 @@ You may encounter these errors when trying to add a remote.
 This error means you've tried to add a remote with a name that already exists in your local repository:
 
  ``shell
-$ git remote add origin https://{% data variables.command_line.codeblock %}/octocat/Spoon-Knife
+$ git remote add origin https://{% data variables.command_line.codeblock %}/octocat/Spoon-Knife.git
 > fatal: remote origin already exists.
 ``
```

Without the .git it's not actually a git repository.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@peternewman Thanks for opening a PR 👍 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request to answer **Why** and **What's being changed**, then we'll get this up for review!

**Comment by peternewman** [comment]
> @peternewman Thanks for opening a PR +1 Please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request to answer **Why** and **What's being changed**, then we'll get this up for review!

I've added more why and what's changed detail if someone can re-review please.

Do you actually require me to create a related issue for something so trivial?

**Comment by janiceilene** [comment]
Thanks so much for the additional context @peternewman! I agree that an issue isn't necessary for this particular fix. I'll get this triaged for review ⚡

**Review by shati-patel — APPROVED** [review]
Thank you for the fix, @peternewman! Your help with tidying up our documentation is much appreciated ✨ 

We've briefly paused merging to `main`, but I'll label your PR as "ready". We'll merge it as soon as we can!

**Comment by peternewman** [comment]
Thanks @shati-patel , I assumed you meant a week of delay or something not just a day or two!

**Pull request merged**
