### PR TITLE
Add documentation for actions/setup-node pnpm cache

### PR DESCRIPTION
**Pull request by jacobwgillespie**
### Why:

The `actions/setup-node` action now supports pnpm caching as of [v2.3.0](https://github.com/actions/setup-node/releases/tag/v2.3.0), and @MaksimZhukov [requested a PR to update the docs](https://github.com/actions/setup-node/pull/278#issuecomment-883467375) for that addition.

### What's being changed:

I've added the workflow YAML example from https://github.com/actions/setup-node#caching-packages-dependencies for pnpm underneath the existing npm and yarn examples, matching the order from the action README.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by maxim-lobanov — DISMISSED** [review]

**Review by MaksimZhukov — DISMISSED** [review]
Looks good to me, thank you! Nitpick: I think it make sense to mention the `pnpm` package manager in the [Caching dependencies to speed up workflows](https://github.com/github/docs/blob/main/content/actions/guides/caching-dependencies-to-speed-up-workflows.md#about-caching-workflow-dependencies) guide.

**Comment by jacobwgillespie** [comment]
> I think it make sense to mention the `pnpm` package manager in the [Caching dependencies to speed up workflows](https://github.com/github/docs/blob/main/content/actions/guides/caching-dependencies-to-speed-up-workflows.md#about-caching-workflow-dependencies) guide.

Added! 👍

**Review by MaksimZhukov — DISMISSED** [review]

**Comment by 177771** [comment]
Sent from Yahoo Mail on Android 
 
  On sri, srp 21, 2021 at 9:10, ***@***.***> wrote:   


@MaksimZhukov approved this pull request.

**Comment by ramyaparimi** [comment]
@jacobwgillespie Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Review by ivan0117 — COMMENTED** [review]
n

**Review by ivan0117 — APPROVED** [review]
n

**Review by skedwards88 — COMMENTED** [review]
Thanks for adding this! I'm going to convert the disclaimer to a reusable, then I'll get this merged down for you.

**Review by skedwards88 — APPROVED** [review]

**Pull request merged**
