### PR TITLE
Fixes GHES docs for PAT as SSO not available

### LINKED ISSUE #33696: Fix GHES docs for PAT as SSO not available
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

content/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens.md

### What part(s) of the article would you like to see updated?

Personal access tokens (PATs) screenshot shows "configure SSO" even for GitHub Enterprise Server (GHES), but GHES doesn't have SSO for PATs.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by amarvin**
### Why:

GitHub Enterprise Server (GHES) allows generating personal access tokens (PATs), but unlike GitHub Cloud or GitHub Enterprise Cloud (GHEC) there is no option in GHES to enable SAML SSO for PATs.

Closes: #33696

### What's being changed (if available, include any code snippets, screenshots, or gifs):

- Adds a screenshot from GHES that doesn't show PAT with "configure SSO"
- Updates PAT docs to use new screenshot for GHES

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@amarvin Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by amarvin** [comment]
Thanks, @nguyenalex836!

**Review by luddyinthehouse — COMMENTED** [review]
Gathers interested visible intros to resting ideal number get on informational held with tough ways of not embellishments but distance.

**Comment by stevecat** [comment]
Hi @amarvin, thanks for working on this, it looks like a really good change!

Before we merge this, can I ask you to make one tiny change? Our style guide [asks us not to include liquid conditionals in filenames](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#file-names-for-images), this can cause problems for a few automations we have.

It won't look as neat but could you change this so we have two complete image tags? For example:

`{% ifversion ghes %}Screenshot of the "{% data variables.product.pat_generic_caps_plural %}" page. Next to a blurred-out token, an icon of two overlapping squares is outlined in orange.{% else %}Screenshot of the "{% data variables.product.pat_generic_caps_plural %}" page. Next to a blurred-out token, an icon of two overlapping squares is outlined in orange.{% endif %}`

Let me know once you've made the change so I can review and get this merged! ✨

**Comment by amarvin** [comment]
> Hi @amarvin, thanks for working on this, it looks like a really good change!
> 
> Before we merge this, can I ask you to make one tiny change? Our style guide [asks us not to include liquid conditionals in filenames](https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#file-names-for-images), this can cause problems for a few automations we have.
> 
> It won't look as neat but could you change this so we have two complete image tags? For example:
> 
> `{% ifversion ghes %}Screenshot of the "{% data variables.product.pat_generic_caps_plural %}" page. Next to a blurred-out token, an icon of two overlapping squares is outlined in orange.{% else %}Screenshot of the "{% data variables.product.pat_generic_caps_plural %}" page. Next to a blurred-out token, an icon of two overlapping squares is outlined in orange.{% endif %}`
> 
> Let me know once you've made the change so I can review and get this merged! ✨

Great point and sorry for missing that in the style guide! I've made the change for you to review.

**Comment by amarvin** [comment]
@stevecat, this is ready for your review.

**Comment by amarvin** [comment]
nudge @stevecat

**Comment by nguyenalex836** [comment]
@amarvin Hello! 👋 Thank you very much for your patience - it looks like @stevecat might not be available for a little while. The changes you made as requested look great! I'll go ahead and get this merged 💛 Thank you again for your patience!

**Review by nguyenalex836 — APPROVED** [review]

**Pull request merged**
