### PR TITLE
Fix link to GraphQL "status" documentation

### PR DESCRIPTION
**Pull request by jmezzacappa**
### Why:

The link URL had a typo.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The link URL typo has been corrected.

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by PIYUSH-MISHRA-00 — COMMENTED** [review]
simple grammatical mistake "status" was "statue" but its corrected now

**Comment by jmezzacappa** [comment]
Is there anything else I need to do in this PR? Would this be considered a "content change" and require the self-review checklist?

**Comment by cmwilson21** [comment]
@jmezzacappa Thanks for this PR! It looks like our bot may have gotten a bit wonky here..

I'll get this triaged for review! ⚡

**Review by skedwards88 — APPROVED** [review]
Thanks for this fix! We'll get it merged down for you.

**Review by skedwards88 — APPROVED** [review]
Thanks for this fix! We'll get it merged down for you.

**Comment by jmezzacappa** [comment]
Thanks!

**Pull request merged**
