### PR TITLE
Improved Context about Forks

### LINKED ISSUE #4844: Improve context about forks
### What article on docs.github.com is affected?

"[Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)"

### What part(s) of the article would you like to see updated?

This is a getting started article, and it would be great to share the additional information we have about forks with the new users. Let's link to "[Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)" somewhere within the article.

### Additional information

This issue is for a special project and not currently available for contributors to work on.

### PR DESCRIPTION
**Pull request by codewithdev**
### Why:

Closes #4844

### What's being changed:

- Improved the article [Fork a Repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) and added some additional introductory lines about forks in the header.
- Updated and linked [Working with Forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) to  [Fork a Repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo), which enables the user to directly find the content related to working with forks. 

Screenshot_2

### Check off the following:

- [x] I have reviewed my changes in staging (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by sarahs** [comment]
👋 We did some content restructuring that resulted in a conflict with your PR. It looks like we may not have access to check out your fork. Let us know if you need a hand resolving the conflict!

**Comment by janiceilene** [comment]
🎉 Thanks for opening a PR @codewithdev 🎉 I'll get this triaged for review :zap

**Comment by khalakhras** [comment]
> 👋 We did some content restructuring that resulted in a conflict with your PR. It looks like we may not have access to check out your fork. Let us know if you need a hand resolving the conflict!
> 
> The new location of the file is: `content/github/getting-started-with-github/quickstart/fork-a-repo.md`

 
`Quickstart[Quickstart]() `

**Comment by khalakhras** [comment]
Quick start

**Comment by ethanpalm** [comment]
👋🏼  @codewithdev thanks for opening this PR! Can you check the box next to **Allow edits from maintainers.**? I've got a few suggestions to make on this PR and then we can get it merged ✨

**Comment by codewithdev** [comment]
> 👋🏼 @codewithdev thanks for opening this PR! Can you check the box next to **Allow edits from maintainers.**? I've got a few suggestions to make on this PR and then we can get it merged ✨

@ethanpalm I am not sure there is any option for *Allow edits from maintainers*.

**Comment by codewithdev** [comment]
@ethanpalm  Since the location of the file had been changed in earlier update thus I have updated the file in this PR #6614

**Comment by ethanpalm** [comment]
> @ethanpalm Since the location of the file had been changed in an earlier update thus I have updated the file in this PR 👉 #6614

Thanks for pointing me there. For some reason, review suggestions are not working on this PR so I pushed some changes that are now on that PR. I'll move to #6614 and give it review.

**Comment by codewithdev** [comment]
> > @ethanpalm Since the location of the file had been changed in an earlier update thus I have updated the file in this PR 👉 #6614
> 
> Thanks for pointing me there. For some reason, review suggestions are not working on this PR so I pushed some changes that are now on that PR. I'll move to #6614 and give it review.

Thanks for the review and updation @ethanpalm 😄 I thought to Link the [working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) in the last.

**Comment by ethanpalm** [comment]
Since https://github.com/github/docs/pull/6614 will close https://github.com/github/docs/issues/4844, I'm going to close this PR and we can get everything merged together in #6614.

**Pull request closed without merging**
