### PR TITLE
Fix url in curl examples

### LINKED ISSUE #24424: Two curl examples missing forward slash
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

- https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#generating-an-installation-access-token
- https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation#authenticating-with-an-installation-access-token

### What part(s) of the article would you like to see updated?
Screenshot 2023-03-13 at 11 44 39 PM
Screenshot 2023-03-13 at 11 44 47 PM

Both curl examples missing forward slash after base url

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by emmjohnson**
### Why:
Two curl examples were missing a forward slash.

Closes #24424

### What's being changed (if available, include any code snippets, screenshots, or gifs):
url will now be - --url "https://api.github.com/meta", previously, 
Screenshot 2023-03-13 at 11 44 39 PM

url will now be - --url "https://api.github.com/app/installations/INSTALLATION_ID/access_tokens", previously,
Screenshot 2023-03-13 at 11 44 47 PM

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@emmjohnson Thank you for opening a PR and linking it to your issue! ✨ 

I'll get this triaged for review! :zap:

**Comment by cmwilson21** [comment]
Also, it looks like one of these errors was previously fixed in https://github.com/github/docs/pull/24414. So we'll take a look at the other one involving the `/meta`. Thanks again!

**Review by cmwilson21 — APPROVED** [review]
LGTM! 🚢

**Comment by emmjohnson** [comment]
Thanks @cmwilson21! Do I need to keep updating the branch or you have it from here?

**Comment by cmwilson21** [comment]
@emmjohnson Sorry for the delay! Looks like everything went well and your PR is now merged 🎉

**Pull request merged**
