### PR TITLE
Fix typo in self-hosted runners architecture labels

### PR DESCRIPTION
**Pull request by garysassano**
### Why:

The [main self-hosted runners page](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures) mentions `ARM32` as an architecture, while elsewhere that's referenced simply as `ARM` so it must be wrong in one place.

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@garysassano Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by orhannoguz356** [comment]
İç mimar

**Review by SiaraMist — APPROVED** [review]
Thank you for updating this, @garysassano! ✨  ~I'll go ahead and get it merged.~

Oops, I approved this too soon, apologies. If you go to one of your repositories and add a self-hosted runner, you'll see that when you choose a runner with a Linux operating system, the choices for available architectures are x64, ARM, and ARM64. Whichever architecture you chose would then be added as a label to the runner, which matches what the article you are updating says. If you set the `runs-on` key to `runs-on: [self-hosted, linux, ARM32]`, it would not work because `ARM32` would not be an accurate runner label. In light of that, I'm going to close this pull request. We really appreciate you thinking critically about the docs and making fixes!

**Comment by garysassano** [comment]
@SiaraMist So It was probably [this page](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures) that needed to be aligned for consistency in naming.

**Pull request closed without merging**
