### PR TITLE
Update configuring-github-copilot-in-your-environment.md

### PR DESCRIPTION
**Pull request by regisbsb**
Removing keybinding that does not exist anymore

### Why:

Closes: 

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@regisbsb Thanks so much for opening a PR! I'll get this triaged for review ✨

**Review by Krzysztof135 — COMMENTED** [review]
Ok

**Comment by hubwriter** [comment]
I spun up a Windows VM with Visual Studio 17.10 and confirmed that `Alt + \` does not trigger a Copilot code completion suggestion.

I'll get this merged.

@regisbsb - Thank you for spotting this and updating the docs.

**Review by hubwriter — APPROVED** [review]

**Comment by ayim** [comment]
The replacement for `Alt + \` is the command that triggers next suggestion.
If there is no suggestion, it also triggers a suggestion

**Comment by ayim** [comment]
For downlevel versions of Visual Studio (I believe it's 17.9 or below), Alt + \ still works.

**Review by Annie602942 — COMMENTED** [review]
https://discordapp.page.link/?link=https://discord.gg/xcRH6mN4fa?fingerprint%3D1268419546381946891.vjafjcbHc_c_At4HGnAeUBn40Cg%26attemptId%3D2ccfb545-c28a-497c-bf03-743d667aa5de&apn=com.discord&isi=985746746&ibi=com.hammerandchisel.discord&ifl=https://discord.com/api/download/mobile?invite_code%3DxcRH6mN4fa&sd=Your+place+to+talk+with+communities+and+friends.&utm_source=invite&cid=8040338760412638642&_icp=1

**Pull request merged**
