### PR TITLE
link to git-credential-oauth

### PR DESCRIPTION
**Pull request by hickford**
### Why:

[git-credential-oauth](https://github.com/hickford/git-credential-oauth) is a Git credential helper that supports OAuth authentication to GitHub, similar to Git Credential Manager (GCM). It would be helpful to mention on page  [*Caching your GitHub credentials in Git*](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git) alongside GCM.

This would be particularly helpful for Linux users. Linux distributions such as Debian, Fedora and Ubuntu include git-credential-oauth, making it easy to install and update. GCM is harder to install on Linux and doesn't support Linux arm64 ([detailed comparison](https://github.com/hickford/git-credential-oauth#comparison-with-git-credential-manager)).

GitLab lists both projects in its two-factor authentication documentation https://docs.gitlab.com/ee/user/profile/account/two_factor_authentication.html#oauth-credential-helpers

### Check off the following:

- [x] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nanis94** [comment]
hickford:patch-7

**Comment by cmwilson21** [comment]
@hickford - I noticed this is still a draft. Ping me when it's ready and I'll get it triaged for review! ✨

**Comment by hickford** [comment]
@cmwilson21 ready for review

**Comment by cmwilson21** [comment]
@hickford Thanks for the ping and for opening a PR :+1: Could you please fill out the [pull request template](https://raw.githubusercontent.com/github/docs/main/.github/PULL_REQUEST_TEMPLATE.md) in the top comment in this pull request? This will greatly help us in the review process ✅

**Comment by hickford** [comment]
@cmwilson21 completed template. @github/ecosystem-apps-reviewers could also review.

**Comment by hickford** [comment]
Analogous documentation in GitLab https://docs.gitlab.com/ee/user/profile/account/two_factor_authentication.html#oauth-credential-helpers

**Comment by saritai** [comment]
@hickford 👋 Hello! Thanks for opening a PR! After chatting with the team internally, we are not going to add this link at this time. 💛

Thank you for your interest in improving GitHub Docs! 💖

**Comment by hickford** [comment]
@saritai Can you be more candid? What's the reasoning?

Compared to [saving credentials in plaintext](https://stackoverflow.com/a/35942890/284795), OAuth is a great improvement in security and usability, but Linux users are deterred from using GCM, especially on arm64. This PR would help GitHub users discover an alternative that's easier to install. Please consider reopening.

**Pull request closed without merging**
