### PR TITLE
Update managing-projects-using-jira.md

### PR DESCRIPTION
**Pull request by datanerd**
I suspect UI has changed in GHES since this docs were created, so I've updated them to match the UI in 2.22
Similar with Jira, the DVCS accounts are now under Applications
Lastly, Atlassian has changed "JIRA" to "Jira" a few years ago.

### Check off the following:
- [ ] All of the tests are passing.
- [ ] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [ ] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
👋 @andrekolodochka thanks for opening a PR! This article is for GHES 2.20, 2.21, and 2.22. Do you know when the UI changed, so we can ensure that we're giving users the correct directions for their version?

**Comment by andrekolodochka** [comment]
I'll need to set up GHES 2.20 and 2.21 to check. Can do that next week.

**Review by pes2020kk — APPROVED** [review]

**Review by pes2020kk — DISMISSED** [review]

**Comment by andrekolodochka** [comment]
Installed 2.22.5, 2.21.13 and 2.20.22. None of them have `gear` settings icon. Also the menu items are slightly different in 2.22 vs others. 

I found a way to get a user to the right place which would work the same in all three versions, and possibly in the near future versions as well.

**Comment by janiceilene** [comment]
@andrekolodochka That sounds great! Thanks for the additional information 💖 I've triaged this for writer review.

**Comment by andrekolodochka** [comment]
@janiceilene I can't find the same article for github.com. Do we even have one? I'm happy to create github.com related content, just need guidance on how to create the actual file.
image

**Comment by janiceilene** [comment]
@andrekolodochka This article is in the [`/admin` directory](https://docs.github.com/en/enterprise-server@2.22/admin) which is only intended for GHES administrators. 

It looks like we have a small section on integrating with Jira Cloud in [GitHub extensions and integrations](https://docs.github.com/en/free-pro-team@latest/github/customizing-your-github-workflow/github-extensions-and-integrations#project-management-tools).

Is there more that GHE Cloud customers should know about using Jira?

**Comment by andrekolodochka** [comment]
[GitHub extensions and integrations](https://docs.github.com/en/free-pro-team@latest/github/customizing-your-github-workflow/github-extensions-and-integrations#project-management-tools) page refers to GitHub app for Jira which was developed in collaboration with Atlassian. The app was designed to connect **Github cloud** with **Jira Cloud**. All other combinations should use DVCS connector which this page is about. So:
- GitHub Cloud<->Jira Cloud: can use [GitHub extensions and integrations](https://docs.github.com/en/free-pro-team@latest/github/customizing-your-github-workflow/github-extensions-and-integrations#project-management-tools) page
- GitHub Server<->Jira Server: this page
- GitHub Cloud<->Jira Server: this page with minor changes in step 5 on Jira side
- GitHub Server<->Jira Cloud: this page with minor changes in text and screenshots in steps 2, 4 and 5 in Jira side.

Note, [there are currently discussions with Atlassian](https://github.com/github/business-development/issues/997#issuecomment-737443566) about improving integrations and eventually decommissioning DVCS connector, although no ETA yet.

**Comment by andrekolodochka** [comment]
@janiceilene There are four combinations for Jira and Github integration:
1. GitHub Cloud <-> Jira Cloud - uses the app developed in collaboration with Atlassian and is covered by the [article you mentioned](https://docs.github.com/en/free-pro-team@latest/github/customizing-your-github-workflow/github-extensions-and-integrations#project-management-tools) and handled by 
2. GitHub Server <-> Jira Server - uses DVCS connector and is covered by documentation in this PR
3. GitHub Cloud <-> Jira Server - uses DVCS connector, the majority of content in this PR still applies, but a few minor changes would be required
4. GitHub Server <-> Jira Cloud - uses DVCS connector, the majority of content in this PR still applies, but a few minor changes and a few new screenshots would be required

**Review by carpeqgd83 — APPROVED** [review]

**Comment by saritai** [comment]
@andrekolodochka Thank you for contributing to the docs! I looked over your changes and they look great.

I just made a couple formatting changes:

- The ordered lists had repeated numerals because the images within them weren't indented. Just indented those and now they look good!
- The screenshots you included are very useful! I just made a change in how they are referenced. We generally upload images to a relevant location in  [docs/assets/images](https://github.com/github/docs/tree/main/assets/images) folder of the docs repository and then link to the path, rather than having an external URL. So I just uploaded the images you provided to that location and updated the links in the file!

I'm going to go ahead and approve and merge this PR - thanks again for adding this helpful information!

**Review by saritai — APPROVED** [review]

**Pull request merged**
