### PR TITLE
Align handling-plan-cancellations with billing-customers

### PR DESCRIPTION
**Pull request by danielcompton**
### Why:

https://docs.github.com/en/developers/github-marketplace/selling-your-app-on-github-marketplace/billing-customers#downgrades-and-cancellations has slightly different behaviour specified for cancelling than https://docs.github.com/en/developers/github-marketplace/using-the-github-marketplace-api-in-your-app/handling-plan-cancellations#step-2-deactivating-customer-accounts

This commit aligns the two so they say the same thing. It's possible this should be the other way around.

I opened a ticket at https://support.github.com/ticket/personal/0/1792415 about this too to clarify this.

Closes [issue link]

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Matching the cancellation behaviour between two docs.

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### CODE REVIEW

**Comment by cmwilson21** [comment]
@danielcompton Thanks for submitting a PR! Please keep us updated with your conversation with support.

In the mean time, I'll get this triaged for review!

**Review by seyma-si — COMMENTED** [review]
İlgili alanlar gelistirilmeli

**Comment by danielcompton** [comment]
I got a reply from support last year at https://support.github.com/ticket/1792415:

> Thanks for writing in! I'm sorry for the delayed reply - it's definitely taken us longer to respond than we would have liked.
>
> The steps mentioned in https://docs.github.com/en/developers/github-marketplace/selling-your-app-on-github-marketplace/billing-customers#downgrades-and-cancellations is the correct/expected behavior --when a Marketplace plan is canceled the app is not automatically uninstalled.
>
> Sorry, about the confusion --the documentation is already working on getting that sorted.

**Review by yasirmd — COMMENTED** [review]
Submit feedback approving the changes

**Pull request closed without merging**
