### PR TITLE
Clarify Copilot Chat License Index Limits Are Per Individual

### PR DESCRIPTION
**Pull request by chriscct7**
### Why:

Clarifies that the limits are per person, ie 50 repo index limit for each licensed Copilot Business user not 50 repos for the entire GitHub Organization.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

Updates the title with (Per Individual) to clarify the license limits are individual.

### Important Note

Someone at GitHub should confirm this is true first. I can't test the 50 limits because one of the known limitations around indexing is that there is currently no way to de-index them

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist). (See note above)

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@chriscct7 Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by chriscct7** [comment]
> Our SMEs informed us the repo indexing limits are for the overarching subscription holder, not each individual licensed user (for example, for Copilot Business, the organization or enterprise with the subscription can index a total of 50 repos, rather than each licensed CB user being able to index any 50 repos they choose).

Wanted to double check this because if I'm understanding this correctly, wouldn't that mean that if an Org has 5 or more members it would be better to have people individually buy copilot than using business licensing, particularly as there's no way for a business to pick which repos (or remove/manage repos) are indexed?

**Comment by chriscct7** [comment]
Updated the PR to match that (I think this is the best way of doing it?)

**Comment by nguyenalex836** [comment]
@chriscct7 Apologies for our overzealous bot! Our SME team is giving your latest updates a final review - we'll update as soon as we hear back 💛

**Review by sabrowning1 — COMMENTED** [review]
👋🏼 @chriscct7, thanks again for raising this PR, and sorry for the delayed review! I've left a suggestion below.

> Wanted to double check this because if I'm understanding this correctly, wouldn't that mean that if an Org has 5 or more members it would be better to have people individually buy copilot than using business licensing, particularly as there's no way for a business to pick which repos (or remove/manage repos) are indexed?

Good question! I'd still recommend a Copilot Business subscription for a couple reasons:
* The 50 indexed repos would be available to all Copilot Business users in the organization, while each Copilot Individual user would only have access to a maximum of 5 repos they index themselves.
* The organization would lose out on features like org-level policy management and file exclusion that are available with Copilot Business, but not Copilot Individual.

Once you've had a chance to take a look at my suggestion, feel free to ping me for another review 🙂

**Comment by nguyenalex836** [comment]
@chriscct7 I went ahead and committed the suggestion @sabrowning1 provided 💛 I'll be getting this merged shortly - thank you so much for contributing to GitHub Docs! 🚀 

If you're looking for issues to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@chriscct7 I went ahead and committed @sabrowning1's suggestion 💛 We are currently in a repo freeze, but will get this merged as soon as the freeze ends on November 1st! Thank you so much for contributing to GitHub Docs 🚀 

If you're looking for an issue to pick up, take a look at our [help wanted section](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) to find open issues you can work on ✨

**Pull request closed without merging**
