### PR TITLE
Update about-repository-languages.md

### PR DESCRIPTION
**Pull request by DillonDepeel**
### Why:

Closes [issue link]

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Review by bishal7679 — COMMENTED** [review]
@DillonDepeel it is always recommended to first open an issue & then make the necessary PR for that! (even if its a small one) and **try to make a PR with right changes only.** It should be `repository's` in your changes.
Please follow this approach for your next contributions
I hope you understand :)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Review by bishal7679 — COMMENTED** [review]
Screenshot (142)

**Comment by DillonDepeel** [comment]
> Screenshot (142)

ok, thanks for telling me. I'm still quite new so I appreciate you telling me.

**Comment by janiceilene** [comment]
@DillonDepeel Thanks for opening a PR! We're not going to make the suggested changes to this article, so I'm going to close this PR.

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:

Thanks so much for your interest in improving the GitHub docs 💖

**Review by kbackpeople-jpg — COMMENTED** [review]
R.Me

**Review by kbackpeople-jpg — COMMENTED** [review]
> [](url)_Fixes #41072 _

**Pull request closed without merging**
