### PR TITLE
Updated the environment-variables.md

### LINKED ISSUE #2693: Environment variable docs are inconsistent about GITHUB_ prefix
The [Naming Conventions for Environment Variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#naming-conventions-for-environment-variables) documentation says:

> **Note:** GitHub reserves the `GITHUB_` environment variable prefix for internal use by GitHub. Setting an environment variable or secret with the `GITHUB_` prefix will result in an error.

However, the example in [`jobs.<job_id>.steps[*].env`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv) sets a `GITHUB_TOKEN` environment variable. Which is correct?

### PR DESCRIPTION
**Pull request by Sreelayavuyyuru**
### Why:

**Closes #2693**

### What's being changed:

I have followed the instructions in the issue to fix this. I have corrected the text in the note box to the mentioned paragraph. 
That is, 
"When you set a custom environment variable, you cannot use any of the default environment variable names listed above with the prefix `GITHUB_`. If you attempt to override the value of one of these default environment variables, the assignment is ignored."

I did not remove the **Note:**  (After reviewing the localization checklist) because it was mentioned that the previous one should be change to 'rather a note'. 

I am just getting started with open-source so I am sorry if I have done anything that is incorrect.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by ajsirota — DISMISSED** [review]
Looks great to me! 👍

**Comment by janiceilene** [comment]
👋 @Sreelayavuyyuru Thank you so much for opening a PR with this fix!

> in content/actions/reference/environment-variables.md, change... to a simple paragraph (rather than a note)

From that statement in the issue, I think we do want to remove the `{% note %}` and `{% endnote %}` tags. Since this file is a reusable, it's visible in a few different articles and it looks like `@hubwriter` would prefer it show up in the article as a paragraph, instead of a note. 

Let me know when you've removed the tags and I'll get this up for review ⚡

**Comment by Sreelayavuyyuru** [comment]
Hey @janiceilene, Thank you so much for the instructions!
I have removed the tags, so it looks like a paragraph now like you mentioned 👍🏼

**Review by lecoursen — APPROVED** [review]
Thanks for fixing this! I'll merge it now.

**Pull request merged**
