### PR TITLE
Drop verbose from cp call

### PR DESCRIPTION
**Pull request by WyriHaximus**
### Why:

Having the verbose flag in there is nice for debugging but it logs a ton of mostly information that isn't interesting most of the time. Plus is slows the cp call down having to output it all. It shouldn't be the default recommended way to run it as such.

### What's being changed (if available, include any code snippets, screenshots, or gifs):

The `cp` call in the `init-dind-externals` init container examples.

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by nguyenalex836** [comment]
@WyriHaximus Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by WyriHaximus** [comment]
@nguyenalex836 cool, let me know if I need to provide some numbers or anything else on this 👍.

**Review by subatoi — APPROVED** [review]
Hi @WyriHaximus — I agree with you. Thanks for raising a PR for this change, I'll go ahead and approve and merge it!

**Comment by WyriHaximus** [comment]
@subatoi cheers!

**Pull request merged**
