### PR TITLE
Image Update

### PR DESCRIPTION
**Pull request by Eldrick99**
I Updated the Image nothing else

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/CONTRIBUTING.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

This was my first time sending a pull request ,,

### CODE REVIEW

**Comment by Eldrick99** [comment]
I updated  Sudo  Please Approve I just joined Github First contribution (I didnt do much)

**Comment by ramyaparimi** [comment]
@Eldrick99  I couldn't verify your changes as it didn't show up properly in the deployment. Could you please provide some information on what change you would like to see with the image uploaded?

**Comment by Eldrick99** [comment]
Screenshot_20210809-172638_Chrome
Screenshot_20210809-172925_Samsung Internet

**Comment by Eldrick99** [comment]
.

**Comment by ramyaparimi** [comment]
@Eldrick99 Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo 🐘 🐬  You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions :sparkles:

**Pull request closed without merging**
