### PR TITLE
Add link to issue tracking ACR support

### PR DESCRIPTION
**Pull request by jeffwidman**
Add a link to the issue tracking adding support for ACR.

This way it'll be easier for users to follow if we forget to update this doc when we add support.

And makes it clear (in comments on the linked issue) that this is waiting for something from ACR, not from us.

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for the "Automatically generated comment" and click the links in the "Preview" column to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by cmwilson21** [comment]
👋 @jeffwidman - Thanks for opening a PR! I'll get this triaged for review ⚡

**Comment by jeffwidman** [comment]
Marking as draft for now in favor of @pavera's excellent work in https://github.com/github/dependabot-updates/issues/1903

**Comment by mchammer01** [comment]
@jeffwidman 👋🏻 - can we close this, as I am about to merge https://github.com/github/docs/pull/20651?

**Comment by mchammer01** [comment]
Closing this, feel free to reopen if I misunderstood 😄

**Pull request closed without merging**
