### PR TITLE
Clarify order precedence

### LINKED ISSUE #17058: CODEOWNERS file syntax documentation does not make it explicitly clear that a pattern can only be used once
[maintainer edit]
This issue is reserved for the MLH Fellowship program.

### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### What changes are you suggesting?

The existing documentation for file syntax does not make it explicitly clear that a pattern can only be specified once, and that if >1 instance of a pattern is present, the last instance will take precedence.

For example the following example would only request review from `@doctocat`, `@octocat` would not be included in the reviewers.

```
apps/ @octocat
apps/ @doctocat
```

I would propose that a line be added to the `CODEOWNERS syntax` section indicating that a repeated pattern is not supported.

### Additional information

Additionally, I believe an issue should be raised internally against the validation of codeowners files - the above example will be marked as valid by the CODEOWNERS validation, and will not provide any indication to the end user that only the last instance of the pattern will be used.

### Content plan
Found [here](https://github.com/github/docs/issues/17058#issuecomment-1099307334)

### PR DESCRIPTION
**Pull request by ffalor**
### Why:

Closes #17058

As pointed out by @lecoursen there is already an example about last matching pattern taking precedence, but in the example, it is referring to `*       @global-owner1 @global-owner2` as the preceding matching pattern.

Instead of referring to `*       @global-owner1 @global-owner2` in my PR I put a full example directly under the comments since some readers may see the large block of comments as `breaks` indicating the previous example is irrelevant.

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by janiceilene** [comment]
@ffalor Thanks so much for opening a PR! I'll get this triaged for review ⚡

**Comment by stevecat** [comment]
Hey @ffalor! Thanks for opening this ✨ 

I don't think we should include a broken example, even with the explanation in the comment block above, in "Example of a CODEOWNERS file". I fear folks will miss the comment and try and use it.

Could you fix the example and instead add a new paragraph in "CODEOWNERS syntax" that explains this behaviour? I would suggest adding it under the second paragraph.

Let us know if you have any questions!

**Review by japui — COMMENTED** [review]
Quando alguém abre um pull request que só
# modifica arquivos JS, apenas @js-owner e não o global. Atenção para não 🚱  prejudicar o sistema.

**Comment by janiceilene** [comment]
It doesn't look like any additional commits have been made to update the example described in https://github.com/github/docs/pull/18240#issuecomment-1141878788 💛  I'm going to close this PR, but @ffalor let us know if you want to continue working on this and we can reopen it!

**Pull request closed without merging**
