### PR TITLE
Update understanding-github-actions.md

### PR DESCRIPTION
**Pull request by vladimir-virlan**
on [push] just throws an error:
Error : .github#L1
No event triggers defined in `on`

### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@vladimir-virlan 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by Sandesh333333** [comment]
> on [push] just throws an error: Error : .github#L1 No event triggers defined in `on`
> 
> ### Why:
> Closes [issue link]
> 
> ### What's being changed:
> ### Check off the following:
> * [ ]  I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
> * [ ]  For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).
> 
> ### Writer impact (This section is for GitHub staff members only):
> * [ ]  This pull request impacts the contribution experience
>   
>   * [ ]  I have added the 'writer impact' label
>   * [ ]  I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

**Review by Jarenbeaver — COMMENTED** [review]
on [push] just throws an error:
Error : .github#L1
No event triggers defined in `on`

**Comment by ethomson** [comment]
Hi @vladimir-virlan - thanks for the PR!  However, I think that this change shouldn't be necessary.

> on [push] just throws an error:

If you have `on [push]` that will indeed fail, but `on: [ push ]` (with the colon) should succeed.  This:

```
on: [ push ]
```

should be equivalent to:

```
on:
  push:
```

**Comment by ramyaparimi** [comment]
@vladimir-virlan Since this change is not necessary, I am going to close this PR now 💛. Please see the [PM's comment](https://github.com/github/docs/pull/14240#issuecomment-1021364548) for more explanation. 

Thanks so much for taking out your time in contributing to the GitHub docs 💖

**Pull request closed without merging**
