### PR TITLE
docs(notifications): add missing `member_feature_requested` reason

### LINKED ISSUE #31697: docs: Notifications REST API missing `member_feature_requested` reason
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28

### What part(s) of the article would you like to see updated?

Add the reason `member_feature_requested`

### Additional information

Screenshot 2024-02-17 at 8 47 46 AM

### PR DESCRIPTION
**Pull request by setchy**
### Why:

Closes: #31697

### Check off the following:

- [x] I have reviewed my changes in staging, available via the **View deployment** link in this PR's timeline (this link will be available after opening the PR).

  - For content changes, you will also see an automatically generated comment with links directly to pages you've modified. The comment won't appear if your PR only edits files in the `data` directory.
- [x] For content changes, I have completed the [self-review checklist](https://docs.github.com/en/contributing/collaborating-on-github-docs/self-review-checklist).

### CODE REVIEW

**Comment by setchy** [comment]
I'm not familiar this this notification reason type, so welcome suggestions on an appropriate description.

**Comment by skedwards88** [comment]
(Internal note: Asked for SME assistance for filling in the missing description [here](https://github.slack.com/archives/C1MK6KF5Y/p1708475923970639))

**Comment by setchy** [comment]
Suggestion incorporated

**Comment by nguyenalex836** [comment]
Thanks for incorporating that suggestion, @setchy! I'll update the branch and get this merged once tests are passing 🍏

**Review by nguyenalex836 — APPROVED** [review]

**Comment by nguyenalex836** [comment]
@setchy Thanks for incorporating that suggestion! I'll update the branch and get this merged once tests are passing 🍏

**Pull request merged**
