### PR TITLE
Change id_rsa.pub to id_ed25519.pub

### PR DESCRIPTION
**Pull request by TylerSustare**
### Why:
The https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent tutorial defaults to using `ed25519` via `$ ssh-keygen -t ed25519 -C "your_email@example.com"`however this page still tells the user to copy the content of the `id_rsa.pub` file.

### What's being changed:
Just changing the `pbcopy < ~/.ssh/id_rsa.pub` line to `pbcopy < ~/.ssh/id_25519.pub`

### Check off the following:
- [x] All of the tests are passing.
- [x] I have reviewed my changes in staging.
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by TylerSustare** [comment]
bump

**Comment by janiceilene** [comment]
Sorry about that @TylerSustare! I must have missed this one 💛 I'll get it triaged for review.

**Comment by felicitymay** [comment]
Hi @TylerSustare - apologies for the delay in reviewing.

Many thanks for raising this pull request. It seems as if this was an issue that leapt out at several people and so we had several fixes for these lines. I've just merged a PR that was raised slightly earlier than yours to update the Mac instructions. If you're interested in making the same correction to the Windows (lines 57-8) and Linux instructions (lines 91-2) in the same topic, that would be great. Otherwise I'll close this PR.

**Review by felicitymay — APPROVED** [review]
After discussing with @shati-patel, we agreed that the fairest thing was to merge this PR since your changes were correct.

**Comment by felicitymay** [comment]
> If you're interested in making the same correction to the Windows (lines 57-8) and Linux instructions (lines 91-2) in the same topic, that would be great. 

Actually, as I said, this seems to be a very popular topic at the moment and I can see that someone has already raised a PR to fix those instructions, so please ignore that suggestion. Maybe there's another issue that you're interested in fixing.

**Pull request merged**
