### PR TITLE
Bug - Updated Composite Example Content on Windows

### LINKED ISSUE #11849: composite example does not run in Windows
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

### What part(s) of the article would you like to see updated?

[Creating an action metadata file
](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file) works for ubunut and mac.  For windows, `/` does not work.

suggest the following change:
```
        - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
          shell: bash          
        - run: goodbye.sh
          shell: bash
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

### Why:

Closes https://github.com/github/docs/issues/11849

### What's being changed:

- Updates Composite Example Windows Docs

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@adithyaakrishna 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by pugg11** [comment]
> 

aadithya794@gmail.comhacked

**Comment by pugg11** [comment]
@ @adithyaakrishna @ramyaparimi @pugg11 @bruce @mtodd #
Duplicate of #

**Comment by pugg11** [comment]
[aadithya794@gmail.com](hacked.com) 
: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90

**Comment by adithyaakrishna** [comment]
@ramyaparimi Could you please lmk if there's any update on this PR?

**Comment by ramyaparimi** [comment]
@adithyaakrishna Our small team is working our way through reviewing all of the amazing contributions in the order they were received. One of the writers would be reviewing your PR soon. Thanks so much for your patience 💖

**Review by skedwards88 — APPROVED** [review]
Thanks for this addition! We'll get this merged down for you.

**Pull request merged**
