### PR TITLE
story.txt

### PR DESCRIPTION
**Pull request by NGUYENVANDUONG98ht**
### Why:

Closes [issue link]

### Check off the following:

- [ ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by Nguyenvanduong98ht** [comment]
story.txt

**Comment by Nguyenvanduong98ht** [comment]
Nguyenvanduong98ht@gmail.com

**Comment by Nguyenvanduong98ht** [comment]
writer impact

**Comment by Selena20191** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Samiec0** [comment]
gh pr checkout 15144

**Comment by Samiec0** [comment]
.

**Comment by Samiec0** [comment]
``

**Pull request closed without merging**
