### PR TITLE
Add note for missing sso contributions

### PR DESCRIPTION
**Pull request by SteveDMurphy**
### Why:

Closes internal issue, reference ticket # `1497638`

### What's being changed:

Add a note about why contributions may appear to be missing from the contribution graph when made to a repository requiring sso (when not signed in)

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/github/docs/blob/main/contributing/self-review.md#self-review).

### Writer impact (This section is for GitHub staff members only):

- [ ] This pull request impacts the contribution experience
  - [ ] I have added the 'writer impact' label
  - [ ] I have added a description and/or a video demo of the changes below (e.g. a "before and after video")

### CODE REVIEW

**Comment by ramyaparimi** [comment]
@SteveDMurphy 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

In the meantime, could you please provide link to the issue that's referenced in the OP of this PR?

**Comment by SteveDMurphy** [comment]
Thank you @ramyaparimi !!

This PR actually stemmed from speaking with GitHub support, where I was told they had opened an internal issue around the change I am adding. That # in the OP was the ticket number from that conversation and I wanted to try and help if possible. I can create a public issue as well if that makes sense, thanks again for the help!

**Comment by ramyaparimi** [comment]
> This PR actually stemmed from speaking with GitHub support, where I was told they had opened an internal issue around the change I am adding. That # in the OP was the ticket number from that conversation and I wanted to try and help if possible.

Thanks so much for providing the background information. Thank you for taking your time in making this contribution 💖 

> I can create a public issue as well if that makes sense, thanks again for the help!

Creating PR is just fine. You don't have create a public issue 💖

**Comment by SteveDMurphy** [comment]
Thank you again @ramyaparimi ! Let me know if there is anything else I can do 🙌🏽

**Comment by vgrl** [comment]
@SteveDMurphy Thanks for suggesting these improvements!

Having the change as a note and in that specific section of the article doesn't quite fit in our style guide. However including that info in the "About" section of the article is certainly helpful to other users, so I'll commit a change to that effect and get this PR merged.

**Review by vgrl — APPROVED** [review]
Changes look good in preview: https://docs-preview-15833-3822ba.eastus.azurecontainer.io/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by SteveDMurphy** [comment]
> Having the change as a note and in that specific section of the article doesn't quite fit in our style guide. However including that info in the "About" section of the article is certainly helpful to other users, so I'll commit a change to that effect and get this PR merged.

@vgrl thanks for taking the time for this, love the changes you made - thank you! 🙌🏽

**Pull request merged**
