### PR TITLE
Update and rename duplicating-a-repository.md to Mirror-a-repository.md

### PR DESCRIPTION
**Pull request by I-Cat**
+ Added capitails as required for English grammer.
+ Change duplicating to Mirror because thats what you will be doing by following this guide
+ Added a Windows-10+ x64 refrences
Author: I-Cat
Signedoff by: Brian Coates <the_kat690@hotmail.com>

### Check off the following:
- [ ] All of the tests are passing.
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [ ] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Review by I-Cat — COMMENTED** [review]
reviewing

**Review by I-Cat — COMMENTED** [review]
seen

**Review by SMAKSS — COMMENTED** [review]
Hi there, thanks for the PR.

Well, capitalization is good, but not always, first you need to know why these things are in lower case, maybe there is a reason behind it.

If you really want to contribute to this repo, I guess it is nice to read [the contribution section](https://github.com/github/docs#contributing) carefully to learn about this project and how things going on here.

Unfortunately, most of your current changes will break the page layout and in result, CI would fail.

To make your PR acceptable, please read the documentation carefully, if you ever had any question about it feel free to start a [discussion](https://github.com/github/docs/discussions) or open an [issue](https://github.com/github/docs/issues/new/choose).

**Comment by janiceilene** [comment]
Thanks for opening a PR @I-Cat! We use the word "duplicate" here to clarify exactly what's happening, especially useful if someone doesn't know the word mirror. As @SMAKSS pointed out, the words in the metadata need to be lowercase. I'm going to close this PR 💛  

If you're looking for somewhere to contribute, there are quite a few issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label!

**Pull request closed without merging**
