### PR TITLE
Add caveat about expression syntax

### LINKED ISSUE #3001: Incorrect info about expression syntax for if conditionals
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
### What part(s) of the article would you like to see updated?

There's a reusable (`{% data reusables.github-actions.expression-syntax-if %}`) in this document that contains the info:
> When you use expressions in an if conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the `if` conditional as an expression.

However, I just made a small example run with a job's `if` conditional like:

```yaml
post-build:
     runs-on: ubuntu-latest
     needs: build
     if: !startsWith(needs.build.outputs.sha8, needs.build.outputs.short-sha)
     steps:
        # ...
```
and it failed with a syntax error in the `if` statement: `The workflow is not valid. .github/workflows/release.yml: Unexpected tag '!startsWith(needs.build.outputs.sha8,'` (see [here](https://github.com/jidicula/test-actions/actions/runs/496429121)).

I'd fix this in a PR if I knew where to find the reusable, but it wasn't immediately transparent, so I'm submitting an issue instead. If anyone could point me to where `{% data reusables.github-actions.expression-syntax-if %}` is defined, I'll happily make a PR with the required changes.

### Additional information

- Test run where documentation was false: https://github.com/jidicula/test-actions/actions/runs/496429121
- Permalink to offending if condition: https://github.com/jidicula/test-actions/blob/39946fb7867001386eb671c9f84dfc3a7443dedd/.github/workflows/release.yml#L56

### PR DESCRIPTION
**Pull request by jidicula**
### Why:

For if conditionals, expressions must be explicitly marked for evaluation if they contain any operators.
See github/docs#3001 for context.

### What's being changed:

An inaccuracy in documentation about if conditionals implicitly evaluating expressions without needing to enclose with `${{ }}`.

### Check off the following:
- [x] I have reviewed my changes in staging. (look for the **deploy-to-heroku** link in your pull request, then click **View deployment**)
- [x] For content changes, I have reviewed the [localization checklist](https://github.com/github/docs/blob/main/contributing/localization-checklist.md)
- [x] For content changes, I have reviewed the [Content style guide for GitHub Docs](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by janiceilene** [comment]
@jidicula Thanks so much for opening a PR! I'll get this triaged for review ✨

**Comment by janiceilene** [comment]
It looks like our new action inadvertently closed this 🙃 Sorry about that! Reopening and triaging this for review 💛

**Comment by jidicula** [comment]
@janiceilene oh phew, thanks for reopening! 😅

**Review by hubwriter — APPROVED** [review]
@jidicula - that's a great clarification. Many thanks for taking time to make this improvement to the docs, and for the supporting evidence that you linked to in your issue. Much appreciated - thanks again.

I'll get this merged so that it's live on the docs site very soon.

**Comment by jidicula** [comment]
My pleasure @hubwriter !

**Pull request merged**
